### PR TITLE
Introducing Distinct Color Temperature Selectors: Mireds and Kelvin

### PR DESCRIPTION
**Pull request by schelv**
## Proposed change

Described in https://github.com/home-assistant/core/pull/101990 .

## Type of change

- [ ] Dependency upgrade
- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml
color_temp_mired:

color_temp_kelvin:

```

## Additional information

Also described in https://github.com/home-assistant/core/pull/101990 .

## Checklist

- [x] The code change is tested and works locally.
- [x] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [x] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

**Comment by bramkragten** [comment]
This would be a breaking change, because we remove an existing used selector.

Instead, we should add a `mode` parameter to the existing color temperature selector, this should default to mired, to not be breaking.

**Comment by schelv** [comment]
> This would be a breaking change, because we remove an existing used selector.

The existing selector is still there!
I did remove it from the documentation, and renamed the file and the class, to avoid further usage.

> Instead, we should add a `mode` parameter to the existing color temperature selector, this should default to `mired`, to not be breaking.

This direction was something I considered.
But having `min_mireds`, `max_mireds`, `min`, and `max` configuration variables at the same time? 🤢

**Comment by frenck** [comment]
> But having min_mireds, max_mireds, min, and max configuration variables at the same time? 🤢

We can guard that. keeping `min_mireds` & `max_mireds` in backwards compatible. From the Core end, we can also handle that in the schema to migrate.

**Comment by schelv** [comment]
> We can guard that. keeping `min_mireds` & `max_mireds` in backwards compatible. 

I'm not quite sure what you mean by this.

> From the Core end, we can also handle that in the schema to migrate.

I hadn't considered migration because I'm unsure how it would apply to blueprints. If migration is possible, does that not imply that maintaining backwards compatibility is unnecessary, since everything could be migrated?

**Comment by schelv** [comment]
New attempt to solve the problem in https://github.com/home-assistant/frontend/pull/18627

**Pull request closed without merging**
