### PR TITLE
Exclude import-pages from gallery linting

### PR DESCRIPTION
**Pull request by spacegaier**
## Proposed change

Those two lines cannot statically be linted as those are created dynamically during gallery building. Found that while running `yarn run format` manually.

## Type of change

- [ ] Dependency upgrade
- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [X] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes #
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [ ] The code change is tested and works locally.
- [ ] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

## Summary by CodeRabbit

- **Chores**
  - Added ESLint directives to improve import handling and code quality.

### CODE REVIEW

**Comment by steverep** [comment]
Linting expects those files to exist already (the CI action runs a subset of gulp tasks).  Typescript would also fail without it.

**Review by bramkragten — DISMISSED** [review]

**Comment by bramkragten** [comment]
> Linting expects those files to exist already (the CI action runs a subset of gulp tasks). Typescript would also fail without it.

Yeah, it would also need a `ts-ignore`

**Comment by steverep** [comment]
> Yeah, it would also need a `ts-ignore`

I guess I'm wondering why it's needed at all?  We shouldn't exclude stuff from checks just because a preprocess is needed first; instead just make sure to actually run the preprocess.

**Comment by bramkragten** [comment]
Something like this?
CleanShot 2023-09-26 at 23 40 39

**Comment by steverep** [comment]
Text please... 👨🏻‍🦯

**Comment by bramkragten** [comment]
> Text please... 👨🏻‍🦯

Oops, sorry 😓 sometimes I forget

Basically adding the required gulp action for the linting to pass as a prepare step before the lint and format script

**Comment by steverep** [comment]
> Basically adding the required gulp action for the linting to pass as a prepare step before the lint and format script

Sure.  Is there a way to do it without constantly repeating though?  Would just adding `"prelint"` and `"preformat"` work?

**Comment by bramkragten** [comment]
> Sure. Is there a way to do it without constantly repeating though? Would just adding `"prelint"` and `"preformat"` work?

I looked for that in yarn docs, but doesnt seem to exist, there are only limited lifecycle scripts: <https://yarnpkg.com/advanced/lifecycle-scripts>

**Comment by steverep** [comment]
I think it probably qualifies as part of `postinstall`?

```json
"postinstall": "gulp gen-icons-json build-translations build-locale-data gather-gallery-pages"
```


Sorta kinda makes sense at least for icons and locale data (i.e. if MDI or formatjs gets updated)?

**Pull request closed without merging**
