### PR TITLE
Add extra safeguards on changing temp

### PR DESCRIPTION
**Pull request by sdague**
Further trying to figure out what's going on in bug #6365. This forces
this.value to Number before doing further math, and emits log messages
if we hit thresholds.

### CODE REVIEW

**Review by schotime — APPROVED** [review]

**Review by andrey-git — COMMENTED** [review]
The value is supposed to be typed. Are you sure typing is not working?

In any case I don't think there should be console printout.

**Comment by sdague** [comment]
@andrey-git I don't have a reproduce, I'm going off what people explain in the bug. The console out is there so that if this doesn't work we can at least figure out what values it thought were there.

**Comment by sdague** [comment]
Related bug - https://github.com/home-assistant/home-assistant/issues/6365

**Comment by andrey-git** [comment]
I reproduced this, indeed turns out polymer "type" is not strict.

I don't like the printouts - they are for debugging and shouldn't pollute the console as it can happen in valid case: The temperature is already max and the user clicks "up".

I think this should be fixed at the source - whatever platform is sending a string should send a number instead.

**Comment by schotime** [comment]
I reckon leave the force number in there and the warnings can go.

**Comment by balloob** [comment]
What would be the best way to figure out which platforms are messing up, add a type check to the climate base class?

**Comment by sdague** [comment]
Is the issue this fall through? https://github.com/home-assistant/home-assistant/blob/9b1ed4e79bd1e554d4f6085879722cd335c4ea69/homeassistant/components/climate/__init__.py#L696 

not isinstance(temp, Number)

**Pull request closed without merging**
