### PR TITLE
Initialize boolean properties

### PR DESCRIPTION
**Pull request by steverep**
## Proposed change

Initialize boolean properties to `false` instead of leaving them `undefined`, which never makes sense as an attribute.  When their types include `undefined`, it generally makes it harder to deal with incompatible types.  When they are non-null asserted, it can inadvertently cause bugs.

Specifically, this change searches for the following regex:

```
@property\(\{ type: Boolean(, reflect: true)? \}\)( public)? \w+[!?]: boolean;$
```

And then replaces occurrences with the same thing but `= false`.

As with #19337, the most common properties make up the bulk of the replacements (e.g. `narrow` and `isWide` make up over 70%).

## Type of change

- [ ] Dependency upgrade
- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [x] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes #
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [ ] The code change is tested and works locally.
- [ ] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

**Review by bramkragten — APPROVED** [review]

**Comment by karwosts** [comment]
I'd like to understand this change a little better. I traced a minor break in ha-map to this. 

Previously, it had optional `darkMode` as a boolean input. And if darkmode was not specified as a property, it would defer to the current theme. 

Now darkmode is just set to `false`, so it's rendering the ha-map panel with darkMode = false, even when the theme is dark. (this leads to icons being the wrong color). 

I can easily add the property... but what exactly was wrong with having an optionally defined boolean?

**Comment by thomasloven** [comment]
Woah!

This breaks everything that relies on `whataver !== false` to assume default is `true`.
`state-badge` is one such example.

**Comment by steverep** [comment]
> Woah!
> 
> This breaks some ~everything~stuff that relies on `whataver !== false` to assume default is `true`. `state-badge` is one such example.

I did search quite a bit for such potential issues, but clearly missed a couple things.  I just searched again for various patterns and the `stateColor` property is the only thing I'm finding that doesn't treat the boolean as a binary.  If you know of others, please let me know.

So, for that issue, again it's incredibly confusing to follow (both for developers and users).  AFAICT, the meanings are:
- `true` = color the state
- `false` = don't color the state
- `undefined` = don't color the state unless it's a light

It's confusing enough for developers to follow that, but `state_color` is a documented boolean for several cards (entities, glance, button, etc.).  The light exception when undefined is mentioned nowhere in the docs.  Plus we display this as a switch in the UI editor, which means the off state may give unexpected and varying results (e.g. leaving it alone keeps `undefined` but toggling twice gives `false`?).

I don't really understand the need for the light exception, but it appears to be quite pervasive in the code.  With that in mind, I submitted #19776 for for quick fixes, but this needs a better solution IMO for better UX and cleaner code.

cc: @piitaya, @bramkragten, @matthiasdebaat

**Comment by thomasloven** [comment]
That one was the only one I had ran into.
I actually think that "for historic reasons" it's not the `light` that's the exception, but... everything else.
Light was always supposed to change color, but then the option was added to show color for other things too.
I agree it's not done optimally.

**Pull request merged**
