### PR TITLE
Weather Card: Switch Importance of Name and State

### PR DESCRIPTION
**Pull request by zsarnett**
## Proposed change

image

## Type of change

- [ ] Dependency upgrade
- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes #
- This PR is related to issue:
- Link to documentation pull request:

## Checklist

- [ ] The code change is tested and works locally.
- [ ] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

**Comment by bramkragten** [comment]
Can we align the text sizes in the header? So we only use 2 font sizes

**Comment by zsarnett** [comment]
Because the name is much longer than the temp. I don't think it looks good. Takes away from the temp

**Comment by zsarnett** [comment]
Wondering if the High and low labels are needed if they are both present. Example

`63°F / 54°F`
`High 63°F`
`Low 54°F`

**Comment by bramkragten** [comment]
Would leave them out we also don't have them on the forecast

**Comment by zsarnett** [comment]
I have an Idea for this going to work on it tomorrow. Still can't get my dev env up as HA on Windows is booty. And I cant use docker and dual boot sounds like too much work :)

**Comment by zsarnett** [comment]
Went with the suggestion from Bram. Two Font sizes in the Header

467633f77666348d3c023576df71f80a

**Review by bramkragten — APPROVED** [review]

**Pull request merged**
