### PR TITLE
Add media search

### PR DESCRIPTION
**Pull request by wizmo2**
## Proposed change

This is fontend support for adding a Search function to Media Browser filtering content.  It is particularly targeted for media_player integrations with large media libraries that support search functionality as part of the API

Adds a search button to the Media Browser dialog and Media panel that modifies the search_id to include a wild-card characters, The button visibility is configurable through the integration.  Search functionality can be customized within the integration code.  

The media_player demo integration has been updated to show functionality using 'fnmatch', but  it is recommended that integrations take advantage of the default simplified wildcard search functionality.

back-end [dependacy](https://github.com/home-assistant/core/pull/89934)

image
image
image

## Type of change

- [ ] Dependency upgrade
- [ ] Bugfix (non-breaking change which fixes an issue)
- [X] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```
See media-player demo

## Additional information

- This PR fixes or closes issue: fixes #
- This PR is related to issue or discussion: [Feature Request](https://community.home-assistant.io/t/add-keyword-search-for-media-sources/387288)
- Link to documentation pull request:

## Checklist

- [X] The code change is tested and works locally.
- [X] There is no commented out code in this PR.
- [X] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

Examples have been provided.  The existing developer docs do not go into this much details.

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

**Comment by balloob** [comment]
If this is only searching items in the same folder, we could just filter it in the frontend?

**Comment by wizmo2** [comment]
It'm main purpose is for api searches on big media libraries.  I'm just about to issue a PR for the Logitech Squeeze Players (as an example).  I don't use them, but I would imagine that for online libraries such as spotify, it is essential functionality.

**Comment by bramkragten** [comment]
The search functions should be on the top level I think, and open a dedicated page. This page would have a search bar on top and show results while typing.

**Comment by frenck** [comment]
Closing PR as the parent/Backend PR in Core has been closed.

**Pull request closed without merging**
