### PR TITLE
Capatalize Earth

### PR DESCRIPTION
**Pull request by darthsebulba04**
## Proposed change

Minor grammar fix on the name of our planet.

## Type of change

- [ ] Dependency upgrade
- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes #
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [ ] The code change is tested and works locally.
- [ ] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

**Review by steverep — CHANGES_REQUESTED** [review]
You need to modify `src/translations/en.json` instead.  See the README in the `translations` directory.  Hopefully this will be fixed soon (see #13381).

**Comment by darthsebulba04** [comment]
Ah, sorry.  I missed that.  Do I need to undo the other en.json or should it just overwrite?

**Comment by steverep** [comment]
Please undo so I don't get conflicts in #13724 😉

**Comment by darthsebulba04** [comment]
Couldn't find a way to revert that change.  if that causes conflicts, let me know and I'll trash this PR and start over.

**Review by steverep — APPROVED** [review]

**Comment by steverep** [comment]
Removed the final new line for you after 3 tries.  Apparently GitHub will show you a patch where it's removed, then go ahead and add it back during the commit anyway.  😡

**Pull request merged**
