### PR TITLE
Update frontend to point to Electricity Maps logo instead of CO2 signal

### PR DESCRIPTION
**Pull request by tonypls**
## Type of change

- [ ] Dependency upgrade
- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes #
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [ ] The code change is tested and works locally.
- [ ] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

**Comment by bramkragten** [comment]
I don't think we are going to rename the `co2signal` domain? Shouldn't the Electricity Maps logo be under the `co2signal` domain?

**Comment by tonypls** [comment]
> I don't think we are going to rename the `co2signal` domain? Shouldn't the Electricity Maps logo be under the `co2signal` domain?

Hi Bram, thanks for the quick response!

I believe as we are going to be sunsetting the CO2Signal brand completely and rebranding all CO2Signal assets and services to Electricity Maps that it makes sense to rename the domain as well. 

I believe there will be a few more changes (including into the core repo) but I hope these two PR's capture everything to do with the logo / icon updates.

I've opened a draft brands PR [here](https://github.com/home-assistant/brands/pull/4521)

@madsnedergaard What do you think?

**Comment by bramkragten** [comment]
@tonypls as long as the domain in the core repo is not updated (which we should not IMHO), you should not removed the brand icon for `co2signal`. It is used on the integration and device pages.

If you would rename the domain from `co2signal` to `electricity_maps` there are likely breaking changes or at least a lot more work to do migrations and stuff.

I would suggest to only update the icon, logo, and name of the integration and leave the domain as is. The user will not really see the domain anyway, it is mostly a technical thing.

**Comment by tonypls** [comment]
Closing this in favour of keeping the co2signal domain 👍

**Pull request closed without merging**
