### PR TITLE
Polymer 1.7

### LINKED ISSUE #112: Upgrade to Polymer 1.7
Polymer 1.7 was released 4 days ago: https://github.com/Polymer/polymer/releases/tag/v1.7.0

This release includes future compatibility with Polymer 2.0 which will follow the ShadowDOM v1 spec.

We should:
 - Upgrade bower.json to install Polymer 1.7
 - Verify all things still work
 - Migrate our uses of `<content>` to use `<slot>` (see release notes for instructions)
 - Migrate away from using `:root` in custom CSS. (see release notes for instructions)

### PR DESCRIPTION
**Pull request by justweb1**
Update to Polymer 1.7

Fixes #112

### CODE REVIEW

**Comment by balloob** [comment]
https://github.com/home-assistant/home-assistant-polymer/issues/112 -> did you also migrate away from using `:root` in Custom CSS ?

**Comment by justweb1** [comment]
I did not. I must've missed it.

**Comment by justweb1** [comment]
@balloob Looks like we are good.

**Comment by balloob** [comment]
🐬 🎉

**Pull request merged**
