### PR TITLE
Entity card: Added power off button.

### PR DESCRIPTION
**Pull request by multiholle**
A power off button for group cards instead of a toggle button. Displays the current group power status and allows to turn off all elements of a group. This button can't turn on the group elements.

Can be activated by using `control: power_off` in groups.

image

Modification of group component: home-assistant/home-assistant#8926

### CODE REVIEW

**Comment by homeassistant** [comment]
Hello @multiholle,

When attempting to inspect the commits of your pull request for CLA signature status among all authors we encountered commit(s) which were not linked to a GitHub account, thus not allowing us to determine their status(es).

The commits that are missing a linked GitHub account are the following:

- [`5dfe2b2b37a817ff9dd449ecf9b72474111a7385`](https:&#x2F;&#x2F;github.com&#x2F;home-assistant&#x2F;home-assistant-polymer&#x2F;pull&#x2F;383&#x2F;commits&#x2F;5dfe2b2b37a817ff9dd449ecf9b72474111a7385) - This commit has something that looks like an email address (marcel.holle@comdirect.de). Maybe try linking that to GitHub?.

Unfortunately, **we are unable to accept this pull request until this situation is corrected.**

Here are your options:

1. If you had an email address set for the commit that simply wasn't linked to your GitHub account you can link that email now and it will retroactively apply to your commits. The simplest way to do this is to click the link to one of the above commits and look for a blue question mark in a blue circle in the top left. Hovering over that bubble will show you what email address you used. Clicking on that button will take you to your email address settings on GitHub. Just add the email address on that page and you're all set. GitHub has more information about this option [in their help center](https://help.github.com/articles/setting-your-email-in-git/#commits-on-github-arent-linking-to-my-account).

2. If you didn't use an email address at all, it was an invalid email, or it's one you can't link to your GitHub, you will need to change the authorship information of the commit and your global Git settings so this doesn't happen again going forward. GitHub provides some great instructions on how to change your authorship information [in their help center](https://help.github.com/articles/setting-your-email-in-git/).
   * If you only made a single commit you should be able to run
      ```
      git commit --amend --author="Author Name <email@address.com>"
      ```
      (substituting Author Name and email@address.com for your actual information) to set the authorship information.
   * If you made more than one commit and the commit with the missing authorship information is not the most recent one you have two options:
       1. You can re-create all commits missing authorship information. This is going to be the easiest solution for developers that aren't extremely confident in their Git and command line skills.
       2. You can use [this script](https://help.github.com/articles/changing-author-info/) that GitHub provides to rewrite history. **Please note:** this should be used only if you are very confident in your abilities and understand its impacts.
   * Whichever method you choose, I will come by to re-check the pull request once you push the fixes to this branch.

We apologize for this inconvenience, especially since it usually bites new contributors to Home Assistant. We hope you understand the need for us to protect ourselves and the great community we all have built legally. The best thing to come out of this is that you only need to fix this once and it benefits the entire Home Assistant and GitHub community.

Thanks, I look forward to checking this PR again soon! :heart:

**Comment by homeassistant** [comment]
Hi @multiholle, 

It seems you haven't yet signed a CLA. Please do so [here](https://home-assistant.io/developers/cla_sign_start/?pr=home-assistant&#x2F;home-assistant-polymer#383).

Once you do that we will be able to review and accept this pull request.

Thanks!

**Comment by balloob** [comment]
I don't want to add this. People can already use the toggle button to turn the group off. I don't want to add configuration options like this.

**Comment by multiholle** [comment]
@balloob If you don't want to add configuration options to the ui, how are the users supposed to optimize the ui to their needs?

In my case I would like to add a power off switch to all of my groups representing a room. This will kill everything when I leave the room. On the other hand I don't want to have a power_on switch wich will turn on my receiver, chrome cast and all of my lights when I enter the room. This wouldn't be a valid scenario. Instead I add actions to trigger scenarios like "basic lights", "watching tv", "mood lights".

It's ok to me, if you don't want a power off button. But I would like to have an alternative to achieve this behaviour. I really liked the possibilities to configure ha to my needs so far.

**Comment by balloob** [comment]
- Make a script that turns off the group when activated
- Hack something together with [custom UI](https://home-assistant.io/developers/frontend_creating_custom_ui/)

**Pull request closed without merging**
