### PR TITLE
Expose entities for Google/Alexa

### PR DESCRIPTION
**Pull request by balloob**
This ports the [entity filter function from Home Assistant](https://github.com/home-assistant/home-assistant/blob/dev/homeassistant/helpers/entityfilter.py#L30) from Python to JavaScript. We will be able to use this function to power a user interface for exposing entities for Google Assistant, Emulated Hue, Alexa (as per #679)

Implemented function on the cloud dashboard.

Requires: https://github.com/home-assistant/home-assistant/pull/18216

### CODE REVIEW

**Comment by andrey-git** [comment]
I think each new function should have at least one (non test) use

**Comment by andrey-git** [comment]
Is the lint change specific for hound or is it relevant for local eslint too?

**Comment by balloob** [comment]
I agree that we need non-test use. Waiting for #674 and #675 to land 👍 .

Eslint changes are relevant for local too.

**Comment by balloob** [comment]
extracted eslint stuff.

**Comment by ciotlosm** [comment]
I assume this is no longer relevant?

**Comment by balloob** [comment]
It is relevant but need to build UI that uses it. It is for Alexa and Google Assistant to decide what to expose.

**Comment by balloob** [comment]
image

**Comment by balloob** [comment]
Blocked by converting tests to TS first.

**Pull request merged**
