### PR TITLE
Add lovelace template extension points

### PR DESCRIPTION
**Pull request by cdce8p**
Reintroduce/Extend `Template Extension points` first added with #1230, after the move to `lit-elements`. Additionally I created some functions for dependencies, so custom ui authors could use them within their templates as well (e.g. for `computeStateName`).

As with the original PR, this could remain unofficial or I could add the example below together with a small explanation in the dev documentation.

## Example

Add a `position` value for covers.

Screen Shot 2019-08-04 at 20 04 24

```js
const HuiGenericEntityRow = customElements.get('hui-generic-entity-row');
const HuiCoverEntityRow = customElements.get('hui-cover-entity-row');
const html = HuiGenericEntityRow.prototype.html;


class MyHuiGenericEntityRow extends HuiGenericEntityRow {

  infoTemplate(stateObj) {
    return html`
      ${this._computeName(stateObj)}
      <div class="secondary">
        Position: ${this.position}
      </div>
    `;
  }
}
customElements.define('my-hui-generic-entity-row', MyHuiGenericEntityRow)


class MyHuiCoverEntityRow extends HuiCoverEntityRow {

  template(stateObj) {
    return html`
      <my-hui-generic-entity-row
        .hass="${this.hass}"
        .config="${this._config}"
        .position="${this._computeStatePosition(stateObj)}"
      >
        ${this.coverControlTemplate(stateObj)}
      </my-hui-generic-entity-row>
    `;
  }

  _computeStatePosition(stateObj) {
    return stateObj.attributes.current_position;
  }
}
customElements.define('my-hui-cover', MyHuiCoverEntityRow);
```

### CODE REVIEW

**Comment by balloob** [comment]
Previous PR: https://github.com/home-assistant/home-assistant-polymer/pull/2132

**Comment by cdce8p** [comment]
I'm sorry, I brought this up again. Completely missed that I had already.

**Comment by balloob** [comment]
Haha, all good 👍 

I think that our custom elements don't change enough to make these things worthwhile. 

Something that might change in the future is that we will start loading more custom elements on demand . Right now loading Lovelace loads all the elements that could ever be rendered by Lovelace. That is inefficient. So relying on extending built-in elements might not be a good plan in the long run either.

**Comment by cdce8p** [comment]
In that case, I was wondering if it's possible to import / use frontend functions within custom components (e.g. [computeStateName](https://github.com/cdce8p/home-assistant-polymer/blob/1fb8d7cc6d3ced6be8c7f05c8b9c1a4a3a93c35e/src/panels/lovelace/components/hui-generic-entity-row.ts#L1)). So far I didn't managed to do, except for copying the functions itself. Below is the full example of what I'm currently doing.

```js
const HuiGenericEntityRow = customElements.get('hui-generic-entity-row');
const HuiCoverEntityRow = customElements.get('hui-cover-entity-row');

const html = HuiGenericEntityRow.prototype.html;
const css = HuiGenericEntityRow.prototype.css;


function computeObjectId(entityId) {
  return entityId.substr(entityId.indexOf(".") + 1);
}

function computeStateName(stateObj) {
  stateObj.attributes.friendly_name === undefined
    ? computeObjectId(stateObj.entity_id).replace(/_/g, " ")
    : stateObj.attributes.friendly_name || "";
  return stateObj.attributes.friendly_name;
}



// ###### Cover ######
// ###################

class MyHuiGenericEntityRow extends HuiGenericEntityRow {
  render() {
    if (!this.hass || !this.config) return html``;
    const stateObj = this.config.entity
      ? this.hass.states[this.config.entity]
      : undefined;
    if (!stateObj) return html``;

    return html`
      <state-badge
        .hass=${this.hass}
        .stateObj=${stateObj}
        .overrideIcon=${this.config.icon}
      ></state-badge>
      <div class="flex">
        <div class="info">
          ${this.config.name || computeStateName(stateObj)}
          <div class="secondary">
            Position: ${this.position}
          </div>
        </div>

        <slot></slot>
      </div>
    `;
  }
}
customElements.define('my-hui-generic-entity-row', MyHuiGenericEntityRow)


class MyHuiCoverEntityRow extends HuiCoverEntityRow {
  render() {
    if (!this._config || !this.hass) return html``;
    const stateObj = this.hass.states[this._config.entity];
    if (!stateObj) return html``;

    return html`
      <my-hui-generic-entity-row
        .hass=${this.hass}
        .config=${this._config}
        .position=${stateObj.attributes.current_position}
      >
        <ha-cover-controls
          .hass=${this.hass}
          .stateObj=${stateObj}
        ></ha-cover-controls>
      </hui-generic-entity-row>
    `;
  }
}
customElements.define('my-hui-cover', MyHuiCoverEntityRow);
```

**Comment by iantrich** [comment]
Many helper functions have been extracted here: https://github.com/custom-cards/custom-card-helpers
computeStateName has not been yet, but would be great if you added it.

**Pull request closed without merging**
