### PR TITLE
Change all keys for "Open"/"Closed" to cover-keys

### PR DESCRIPTION
**Pull request by c727**

### CODE REVIEW

**Review by andrey-git — APPROVED** [review]

**Comment by c727** [comment]
@andrey-git @armills the keys are not updated https://lokalise.co/project/3420425759f6d6d241f598.13594006/?k=6884521

**Comment by andrey-git** [comment]
Maybe we need to push the change? I don't have lokalise push permissions.

**Comment by armills** [comment]
Looks like the build got canceled: https://travis-ci.org/home-assistant/home-assistant-polymer/builds/323540930?utm_source=github_status&utm_medium=notification
> This job was cancelled because the "Auto Cancellation" feature is currently enabled, and a more recent build (#2747) for branch master came in while this job was waiting to be processed.

We should probably turn that feature off for master. I've restarted the build.

**Comment by armills** [comment]
We could also set it up to upload with every build, so it'll eventually sync up even if we miss one.

**Pull request merged**
