### PR TITLE
Alarmui

### PR DESCRIPTION
**Pull request by persandstrom**
UI for alarm control panel.

### CODE REVIEW

**Comment by balloob** [comment]
Merged it. You did however introduce some linting errors:

screen shot 2015-09-16 at 9 00 56

**Comment by balloob** [comment]
Which I fixed btw.

**Comment by persandstrom** [comment]
Ah, i'll fix that later

**Comment by persandstrom** [comment]
OK. Thanks

**Comment by lindstromhenrik** [comment]
What was the reason behind removing the keypad completely from the UI? It would be great to have that as an option when using the UI with a touch screen.

**Comment by persandstrom** [comment]
@lindstromhenrik The idea was that the build in numeric keypad should be displayed on touch screen if the active text input only accepts numbers. That didn't really work out though, at least not on Android. I do not have the answer on how to solve it, but I think it should be possible.

**Comment by lindstromhenrik** [comment]
What about having the alarm component set the code_format to '\d+' if the code only contains digits and then check for this in the UI and set something like keypadVisible=true that in turn toggles the keypad visibility?
I'll be happy to submit a PR if you think it is a good way to go?

**Comment by persandstrom** [comment]
Take a look at this: http://stackoverflow.com/questions/6178556/phone-numeric-keyboard-for-text-input
That is how this is supposed to work, and that would be a good solution for you as well, right? 
Also, start a new issue, or PR if you are submitting code, that way it will be more visible that you are working on it.

**Comment by lindstromhenrik** [comment]
No, my use case is not with an iPhone or Android phone (using the touch display with the raspberry pi). I created a PR where I reverted your removal of the UI keypad and added a check to show it if the codeFormat is 'only digits'.

**Pull request merged**
