### PR TITLE
Move styles from the chip used in targets to ha-chip

### PR DESCRIPTION
**Pull request by ludeeus**
## Proposed change

Gallery demo: <https://618242f677081d00071a7b30--home-assistant-gallery.netlify.app/#demo-ha-chip>

## Type of change

- [ ] Dependency upgrade
- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [x] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes #
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [x] The code change is tested and works locally.
- [ ] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

**Comment by Misiu** [comment]
The version with the leading icon has some glitches:
ha_chips

when you change from standard to outline the width change and when you activate the chip it moves to the left a bit (only in the outline version)

Not sure if the size of the leading icon follows the material design spec (https://material.io/components/chips#action-chips), but maybe that was a conscious decision.

**Comment by ludeeus** [comment]
Let's not waste more time on this.
Better to wait for `mwc-chip` <https://github.com/material-components/material-web#components>

**Comment by Misiu** [comment]
@ludeeus the chips you created looks really great. I think this should be added because the implementation of `mwc-chips` didn't even start. In the first roadmap, they were expected in Q3 2020, but a year has passed and there is only a prototype that was created in Jan 2020 (https://github.com/material-components/material-web/tree/chip-prototype)

We won't change the style from standard to outline dynamically right? So the only issue is when we activate the chips.

**Comment by ludeeus** [comment]
Sure, but what we already have "works"

**Pull request closed without merging**
