### PR TITLE
Add condition row colouring

### PR DESCRIPTION
**Pull request by spacegaier**
## Proposed change

As proposed in https://github.com/home-assistant/frontend/discussions/7415 this adds colors so that one can more easily see the layout.
Coloring is applied to `LogicalCondition` = "and", "or" and "not" since I think only those result in nested layouts.

**Question**: What is the best way to determine colors? Currently I only looked at the light theme so far. I use two lighter colors derived from the theme's primary color. 

**Default colors:**
grafik

**Primary color changed in theme:**
grafik

## Type of change

- [ ] Dependency upgrade
- [ ] Bugfix (non-breaking change which fixes an issue)
- [X] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes https://github.com/home-assistant/frontend/discussions/7415
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [X] The code change is tested and works locally.
- [X] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

**Comment by mrand** [comment]
Rather than re-using --light-primary-color, did you try --secondary-background-color?

If that didn't look right, I'd vote for making another new variable.  I am concerned that re-using --light-primary-color as a background (which is used lots of other places) will make it difficult to get reasonable contrast with the text in some cases while still have it usable in other cases.  I'm finishing up a monochrome theme and have run into this conflict in a couple of situations.

**Comment by spacegaier** [comment]
@mrand No I did not check that one. I first focused on getting an initial pilot implementation done tog et some feedback if that is a direction we want to go in at all. The initial feedback in Discord was not too positive: https://discord.com/channels/330944238910963714/351047592588869643/779865024218792037

Note to self: I could imagine something similar also for the card editor (stack and grid cards).

**Comment by zsarnett** [comment]
Note to self: Please don't let Phillip do this 😄 

The Stack and Grid Cards have a different future and so do these automation pages.

I do not think we should do this and focus on the better future of these pages. Bandaid just make more changes that make the UX worse.

**Comment by spacegaier** [comment]
Are the plans for the automation pages mocked up somewhere? Quite curios what the better solution for the nested conditions is. Some sort of visual tree structure?

**Comment by zsarnett** [comment]
The plan would be to nest them and if you want to edit them you would click into it. We should have never done it this way. Cards in Cards is actually against Material Design. The nesting would show the text of the conditions inside and to edit a nest condition you would need to open that up. Its not mocked out completely but either way we should not code a temp solution that will just be overwritten later

**Pull request closed without merging**
