### PR TITLE
fix alignment of switches positioned absolutely

### LINKED ISSUE #3810: Switches gone bad
image

It's caused by inline style `position: relative` being set

image

It's unclear to me where this happens.

### PR DESCRIPTION
**Pull request by iantrich**
closes https://github.com/home-assistant/home-assistant-polymer/issues/3810

### CODE REVIEW

**Comment by balloob** [comment]
Although this fixes it, I rather have us figure out how `position: relative` is set as an inline style.

**Comment by iantrich** [comment]
I couldn't figure that out

**Comment by bramkragten** [comment]
It is the ripple directive:
https://github.com/material-components/material-components-web-components/blob/b1d1640c9c3b27ec0f3c9054c1b2a158f23a891a/packages/ripple/src/ripple-directive.ts#L79

You can prevent it by putting the position inline, saves an override with `!important`

**Comment by bramkragten** [comment]
Seems like the google and alexa entities pages are also affected with some styling issues

**Comment by balloob** [comment]
I think the easier trick is to just wrap the switches in a div, position absolute the div. Overriding the position means the ripple will not work.

**Comment by bramkragten** [comment]
I tried it, and the ripple seemed to work fine, this behavior has changed in a recent update of `mwc-switch`, not sure if it is intended or not, seems a bit weird

**Comment by balloob** [comment]
I still prefer to wrap it, if ripple expects `position: relative`, we should not mess with it.

**Comment by iantrich** [comment]
So I would make my own render with the outside div and pass all properties to the inner mwc-switch?

**Comment by bramkragten** [comment]
No, you just add a div to the switches that are absolute positioned now:
```html
<div class="position-absolute-class">
    <ha-switch></ha-switch>
</div>
```

**Review by bramkragten — APPROVED** [review]

**Comment by bramkragten** [comment]
We also have to look at the google and alexa entities pages:

image

**Comment by iantrich** [comment]
I think that's present anywhere there is text after the switch, like editors as well...

**Comment by bramkragten** [comment]
OK, so it does have a slot, but no styling? I guess we have to add some styling to the slot.

**Pull request merged**
