### PR TITLE
Add Bengali language

### LINKED ISSUE #8008: Please add বাংলা Language
English Name: Bengali (Bangla)
Native Name: বাংলা

### PR DESCRIPTION
**Pull request by spacegaier**
## Type of change

- [ ] Dependency upgrade
- [ ] Bugfix (non-breaking change which fixes an issue)
- [X] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes https://github.com/home-assistant/frontend/issues/8008
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [ ] The code change is tested and works locally.
- [ ] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

**Comment by bramkragten** [comment]
I have to add this to Lokalise

**Comment by DrHaque** [comment]
Please let me know if I can be any help adding it. I have been waiting for a while. Thank you.

**Review by bramkragten — APPROVED** [review]

**Comment by bramkragten** [comment]
I added the language to Lokalise, and gave @DrHaque access to it! Happy translating!

**Comment by DrHaque** [comment]
Thanks a lot.

**Pull request merged**
