### PR TITLE
Fix hidden conditional card in editor preview

### PR DESCRIPTION
**Pull request by piitaya**
## Type of change

- [ ] Dependency upgrade
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes #
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [ ] The code change is tested and works locally.
- [ ] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

## Summary by CodeRabbit

- **Bug Fixes**
  - Corrected the handling of the `preview` mode in the Lovelace UI cards to ensure proper Boolean type recognition. This enhances stability and consistency when toggling the preview attribute.

### CODE REVIEW

**Comment by piitaya** [comment]
@coderabbitai pause

**Review by bramkragten — APPROVED** [review]

**Comment by ncodee** [comment]
@piitaya Issue still persists in 2024.7.2.

**Comment by piitaya** [comment]
Yeah, it was not included in 2024.7.2, the patch was done before.

**Comment by ncodee** [comment]
> Yeah, it was not included in 2024.7.2, the patch was done before.

Oh okay, the mushroom card release notes mentioned 2024.7.2. I'd imagine it will be pushed to 7.3 release?

**Comment by piitaya** [comment]
@ncodee I just checked and it seems to be fixed in `2024.7.2`. Be sure to have Mushroom `3.6.4` and HA `2024.7.2`.

**Comment by ncodee** [comment]
> @ncodee I just checked and it seems to be fixed in `2024.7.2`. Be sure to have Mushroom `3.6.4` and HA `2024.7.2`.

Yup, it working now after clear cache, thank you!

**Pull request merged**
