### PR TITLE
Minify logos

### PR DESCRIPTION
**Pull request by KTibow**
## Proposed change
The SVG logo is surprisingly unminified. This PR minifies it in most places.

## Type of change
Bugfix

*No configuration, issues, discussions, or pull requests is relevant*

## Checklist

- [ ] The code change is tested and works locally.
- [x] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

### CODE REVIEW

**Review by steverep — COMMENTED** [review]
All of these are minified in production builds.  Are you looking at the dev build perhaps?

**Comment by KTibow** [comment]
By "minify" I mean doing optimizations like using arcs that aren't auto-performed

**Comment by bramkragten** [comment]
The mask icon is changed, it is not the same (space on the bottom) is this intentional?

**Comment by KTibow** [comment]
It was semi-intentional, as I thought it would make more sense to replace the logo than minify it given that the current one has some not-so-smooth corners:
image
Should I edit the new one so it has no padding?

**Comment by bramkragten** [comment]
> Should I edit the new one so it has no padding?

Yes please

**Review by bramkragten — APPROVED** [review]

**Pull request merged**
