### PR TITLE
Move fire dialog to state-cards

### PR DESCRIPTION
**Pull request by c727**
... + a bit clean up

### CODE REVIEW

**Comment by andrey-git** [comment]
Now code that was in one place is repeated in every state card. What's the benefit?

**Comment by c727** [comment]
The code belongs to the state-card, for badge(s) and ha-cards we also have the code in each cards.

Main reason: I want to be able to show and custom dialog, independent from entity_id or domain, later

**Comment by andrey-git** [comment]
Also, what happens if state card is shown in other environment (more-info, configurator or something else)? It probably shouldn't fire the event.

**Comment by c727** [comment]
I will filter inDialog

**Comment by andrey-git** [comment]
Still, components should be reusable. The statecard itself is not supposed to fire more-info as that functionality only makes sense in the cards ui and not in other places.

Who would show that future custom dialog?

**Comment by c727** [comment]
is showing state-card in more-info still suitable as we show the entity name already in the toolbar?

Atm I use the state-cards also as full-cards

**Comment by balloob** [comment]
I agree with @andrey-git, firing the events does not belong in the state cards.

**Comment by c727** [comment]
it does not belong to state-cards but ha-cards use it? same as ha-cards not all state-cards have more-info now.
if you don't want to change it we can close this PR

**Pull request closed without merging**
