### PR TITLE
Move RGBW and RGBWW white control to new UI slider

### PR DESCRIPTION
**Pull request by PaoloTK**
## Proposed change
The UI for light control has recently been updated for brightness and white temperature controls, but not for the white component of RGBW and RGBWW lights. I've done so with the goal of better UX, especially on mobile.

chrome_lt40KdcYl7
chrome_PX2MitzNv2

 

## Type of change

- [ ] Dependency upgrade
- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information
The old style white brightness control sliders under the RGB color picker for RGBW and RGBWW lights have been removed. They have been replaced with a dedicated tab for each component: white for RGBW lights and warm white and cold white for RGBWW lights. Unlike the brightness slider, the white sliders can go down to 0% to fully disable the channel.
Since RGBW and RGBWW lights, unlike RGB+W or RGB+CCT lights, can have the white channel(s) on at the same time as the color channels, switching between tabs does not disable the other channels.
Since RGBW and RGBWW lights don't have separate modes, the change color dialog will always open on the color tab.
It's my understanding that a color temperature cannot be specified for the white channel(s) of RGBW and RGBWW lights. Because of this I had to pick arbitrary colors for the new sliders.
For the RGBW white brightness slider color I chose the amber-color variable. I experimented with trying to use a neutral white color but found contrast to be an issue on the light theme.
For the RGBWW white brightness sliders, I used the colors the CCT gradient is built with.
I kept the original color brightness slider, which is not in line with the new UI. I don't think it makes sense to have a separate tab for separate brightness. I think the best solution is to update the design to a slider like the ones provided by the tile card.

## Checklist

- [x] The code change is tested and works locally.
- [x] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

**Comment by bramkragten** [comment]
Do I understand correctly that the values of the three tabs (color, warm and cold white) are active all at the same time?

**Comment by PaoloTK** [comment]
> Do I understand correctly that the values of the three tabs (color, warm and cold white) are active all at the same time?

Yes

**Comment by bramkragten** [comment]
I don't think that is what we want, the tab should show the current options, and I don't think those options should be spread out over multiple tabs...

@matthiasdebaat, can you take a look?

**Comment by piitaya** [comment]
Hello 👋
Each tab correspond to a mode ([color mode documentation](https://developers.home-assistant.io/docs/core/entity/light/#color-modes)) : 
- first one : `RGB`, `RGBW`, `RGBWW`, `XY` or `HS` modes depending of light mode support
- second one : `COLOR_TEMP` if light support it.

`WHITE` is a special mode without variable so it doesn't have dedicated tab but only a toggle icon in the main view
`ONOFF` and `BRIGHTNESS` modes are for light that doesn't support color so all control are in the main view.

white, cold white and warn white are not mode, it's a variable for RGBW and RGBWW so it must stay with the color wheel.

**Pull request closed without merging**
