### PR TITLE
Adjust password manager polyfill for form injections

### PR DESCRIPTION
**Pull request by steverep**
## Proposed change

This makes some changes to make the polyfill more forgiving of password managers that inject elements directly into the hidden form (e.g. LastPass):

- Plays a CSS trick to move the `form` container off screen, then just move any children back
- Adds labels and a fake form action so the polyfill looks more real
- Hide only the input and label elements
- Better align the real and polyfill input fields
- Ancillary change to submit button style (width and height of 0 behaves like `display: none`, which may mean password managers don't even see it, similar to a screen reader)
- Work around several LastPass restrictions - see https://github.com/home-assistant/frontend/pull/17830#issuecomment-1714329110 below

@gjohansson-ST could you please test this with LastPass?

I did test with 1Password in Firefox and found that, for some reason, it does help their menu/button show up, but you need to tab past the Login button to get it.  Their menu seems to mainly be triggered by focusing in a field, but simply doesn't even attempt to do so if the field is in a shadow tree.

## Type of change

- [ ] Dependency upgrade
- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes #
- This PR is related to issue or discussion: #10274 
- Link to documentation pull request:

## Checklist

- [x] The code change is tested and works locally.
- [x] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

**Comment by gjohansson-ST** [comment]
Thanks @steverep will test it tomorrow

**Comment by steverep** [comment]
You can still auto fill using the browser extension manually, right?

**Comment by gjohansson-ST** [comment]
Nope, no autofill, nothing.
Only thing is LP obviously recognize I'm in the right place/site so I can do copy/paste but that's it.

**Comment by steverep** [comment]
I broke down and tried the LastPass Firefox extension for myself.  It doesn't help at all that the extension behaves differently for `http://localhost:8124` than it does for my production site (i.e. no context menu ever).  Makes it pretty difficult to test any changes... 😞

**Comment by steverep** [comment]
@gjohansson-ST I'm utterly baffled.  No matter what I do, I cannot get LastPass to recognize the polyfill form, and that includes completely unhiding it and making it virtually identical to GitHub (in fact much simpler).

**Comment by gjohansson-ST** [comment]
This will allow autofill to work but my skills on css is too bad so I can't manage to get the LP icons to appear in front.
```git
diff --git a/src/auth/ha-password-manager-polyfill.ts b/src/auth/ha-password-manager-polyfill.ts
index 415230c9c..4d013b666 100644
--- a/src/auth/ha-password-manager-polyfill.ts
+++ b/src/auth/ha-password-manager-polyfill.ts
@@ -51,7 +51,7 @@ export class HaPasswordManagerPolyfill extends LitElement {
         height: 62px;
         padding: 0;
         border: 0;
-        opacity: 0;
+        opacity: 1;
         z-index: -1;
       }
       /* Button position is not important, but size should not be zero */
@@ -122,7 +122,7 @@ export class HaPasswordManagerPolyfill extends LitElement {
         .value=${this.stepData[schema.name] || ""}
         .autocomplete=${schema.autocomplete}
         class="underlay"
-        aria-hidden="true"
+        data-hidden="true"
         @input=${this._valueChanged}
         @change=${this._valueChanged}
       />
```

**Comment by gjohansson-ST** [comment]
With this both autofill and the icons works. Not sure how it possibly will affect other pwd managers?
```diff
diff --git a/src/auth/ha-password-manager-polyfill.ts b/src/auth/ha-password-manager-polyfill.ts
index 415230c9c..4654bcbca 100644
--- a/src/auth/ha-password-manager-polyfill.ts
+++ b/src/auth/ha-password-manager-polyfill.ts
@@ -51,9 +51,13 @@ export class HaPasswordManagerPolyfill extends LitElement {
         height: 62px;
         padding: 0;
         border: 0;
-        opacity: 0;
+        opacity: 1;
         z-index: -1;
       }
+      /* Overlapping on injecting password managers */
+      .password-manager-polyfill > div {
+        z-index: 99 !important;
+      }
       /* Button position is not important, but size should not be zero */
       .password-manager-polyfill > input.underlay[type="submit"] {
         width: 1px;
@@ -122,7 +126,8 @@ export class HaPasswordManagerPolyfill extends LitElement {
         .value=${this.stepData[schema.name] || ""}
         .autocomplete=${schema.autocomplete}
         class="underlay"
-        aria-hidden="true"
+        data-hidden="true"
+        inert
         @input=${this._valueChanged}
         @change=${this._valueChanged}
       />
```

**Comment by steverep** [comment]
🤣 I was just about to comment that I figured out by accident it doesn't like 0 opacity (0.01 is fine, but not 0).  Why it is bothering to check the opacity value is kind of ridiculous, but that can be worked around.

It does not seem to care about `aria-hidden`, so that change is unnecessary.  It would be a show-stopper too, so that's good at least.

I am adding some other stuff like labels and fake form attributes to make the polyfill look as real as possible.  Since most of these paid ones don't tell you what their rules are for detecting the fields, they could easily make a change to break the whole thing.

**Comment by steverep** [comment]
Spoke too soon on adding back `aria-hidden`.... it doesn't like that on the `input`, but is fine with it on a parent )which makes zero sense BTW).  Problem is I cannot seem to just play a trick on it to make the injected icons accessible because it injects them to the same parent as the `input` (as opposed to the `form`).

Basically, it is trapping the polyfill into either making the login inaccessible, because assistive technology will see the form, or making all injected content inaccessible.

FYI on your diffs:
- `data-hidden` should do nothing
- `inert` is not a good idea as per spec it should make the `input`s unfillable

**Comment by steverep** [comment]
> With this both autofill and the icons works. Not sure how it possibly will affect other pwd managers?

What browser/OS are you using?  I'm having trouble reproducing.

**Comment by steverep** [comment]
Okay I now know way too much about the quirks of the LastPass extensions.  I've pushed something that works around several of them so that autofill works in both Firefox and Chrome per my testing.  Here's a summary:

| LastPass fails if field has... | Work around by... |
|:--- |:--- |
| `opacity : 0;` style | Anything > 0 is fine (e.g. 1%) |
| `aria-hidden="true"` attribute | Adding a `div` wrapper and hiding that instead |
| `tabindex="-1"` attribute | Use any other negative integer other than -1 |

As for the icons on the input fields, I cannot get them to work without breaking something else.  For whatever weird reason in their calculation, LastPass is positioning them correctly vertically, but horizontally just off the screen to the left (`left: -487px` on my screen relative to the left edge of the form).  I've only been able to get them to position correctly horizontally by:

1. Putting the polyfill form on top, which we obviously can't do
2. Adding the `inert` attribute as @gjohansson-ST discovered, but putting it on the `input` makes autofill stop working in Firefox, and putting it on the wrapper will just cause the icon to be there but not clickable which would be pointless and confusing

...and they have no chance of being accessible via keyboard either since the wrapper is hidden and LP doesn't have any ARIA on their SVG.

So, minus the icons, I'm calling this a win.  It recognizes the fields and autofill works now.

**Review by bramkragten — APPROVED** [review]

**Pull request merged**
