### PR TITLE
Fix text color for hass-tabs-subpage with narrow

### LINKED ISSUE #9592: Mobile header text color for hass-tabs-subpage panel in narrow darkmode unreadable
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

The text as per example is too dark and I can't seem to find a theme variable to change it as it's on mobile not desktop. Desktop is unaffected.
image

### Describe the behavior you expected

Default colour should be more visible.

### Steps to reproduce the issue

1. use a dark theme with iOS
2.
3.
...

### What version of Home Assistant Core has the issue?

2021.7.4

### What was the last working version of Home Assistant Core?

unknown. it's been an issue for a while

### In which browser are you experiencing the issue with?

iOS App

### Which operating system are you using to run this browser?

iOS

### State of relevant entities

_No response_

### Problem-relevant frontend configuration

_No response_

### Javascript errors shown in your browser console/inspector

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by ludeeus**
## Type of change

- [ ] Dependency upgrade
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes #9592
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [ ] The code change is tested and works locally.
- [ ] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

**Review by balloob — APPROVED** [review]

**Comment by DavidFW1960** [comment]
This hasn't fixed the issue. It still looks the same to me

**Comment by ludeeus** [comment]
It has not been released

**Comment by DavidFW1960** [comment]
It looked like it was merged in 20210802.0 which I thought was in the beta release notes?

**Comment by ludeeus** [comment]
Supervisor UI follows Supervisor releases, so for your specific problem, you have to wait.
All other places it's in b8

**Comment by DavidFW1960** [comment]
Cool. I thought it was frontend. Didn't realise it was a supervisor issue

**Comment by ludeeus** [comment]
It's a frontend issue.
Both core and supervisor uses the same elements, but they do not share a release schedule

**Pull request merged**
