### PR TITLE
Add particles to onboarding

### PR DESCRIPTION
**Pull request by balloob**
## Proposed change

Put onboarding content in a card and animate the background.

https://user-images.githubusercontent.com/1444314/110275646-50085280-7f86-11eb-9b55-47e9d5ee03b0.mp4

## Type of change

- [ ] Dependency upgrade
- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes #
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [ ] The code change is tested and works locally.
- [ ] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

**Comment by spacegaier** [comment]
Any risk of performance impacts on the lowest tier hardware that we see being used for HA dashboards? Not sure if we have any insight into that at all though.

**Comment by balloob** [comment]
This is rendered client side.

**Comment by spacegaier** [comment]
> 
> 
> This is rendered client side.

I know, I was asking about the performance impact on the client, for people using old phones / tablets. No idea how lightweight that particle rendering is.

**Comment by balloob** [comment]
I've updated the screenshot with the lates tweaks, also showing both light + dark mode.

**Comment by SNoof85** [comment]
Don't know if it's the same particles i'm used to see on Prism (web interface for Nutanix hypervisor console) but on client side it can be heavy !
By the way, onboarding will looks like i'm connecting to work backend systems ! 👎 🤣

**Comment by balloob** [comment]
So it's not loaded on mobile. Only if the space is there will we show it.

**Review by bramkragten — APPROVED** [review]

**Pull request merged**
