### PR TITLE
Don't load mdi icons with JS - it doesn't do anything.

### PR DESCRIPTION
**Pull request by andrey-git**
Don't load mdi icons with JS - it doesn't do anything.

### CODE REVIEW

**Comment by balloob** [comment]
We load the icons async. HTML imports are only resolved once. By importing it in JS again, we can make sure that we don't show the UI before icons are loaded. This would not be necessary if icon sets can be loaded async and iron-icons would update (but that seemed to be broken)

**Comment by andrey-git** [comment]
What's the thing we are trying to prevent? That UI appears without icons and the icons appear later? I think it is better to show the UI as soon as possible

**Comment by balloob** [comment]
From my tests I was unable to get the UI to show and the icons show later. That would be the preferred way of doing it.

**Comment by andrey-git** [comment]
Are you testing with this patch? What browser are you using?

**Comment by balloob** [comment]
I wasn't. I did that test like 6 months ago.

**Review by balloob — APPROVED** [review]

**Comment by andrey-git** [comment]
I propose to wait until after this week's release and then submit.

**Pull request merged**
