### PR TITLE
HA Cloud overflow wrap 

### LINKED ISSUE #2982: HA Cloud Remote URL and Certificate Fingerprint extend outside of card width
**Home Assistant release with the issue:**
0.90b7

**UI (States or Lovelace UI?):**
Lovelace

**Browser and Operating System:**
iOS app

**Description of problem:**
Home Assistant Cloud page - the Nabu Casa URL and Certificate fingerprint both extend out of the card on mobile devices, or at least the iOS app. It does not prevent them from being used so it's just a visual thing.

image

### PR DESCRIPTION
**Pull request by JensVanhooydonck**
Overflow wrap for Remote URL and Certificate Fingerprint.
Closes #2982

### CODE REVIEW

**Comment by homeassistant** [comment]
Hi @JensVanhooydonck, 

It seems you haven't yet signed a CLA. Please do so [here](https://home-assistant.io/developers/cla_sign_start/?pr=home-assistant&#x2F;home-assistant-polymer#3905).

Once you do that we will be able to review and accept this pull request.

Thanks!

**Comment by bramkragten** [comment]
Thanks!

Can we create a class with `overflow-wrap: break-word` instead of targeting all `p` and `a` tags only apply it where it is needed?

**Comment by JensVanhooydonck** [comment]
I have altered the styling to create a class and applied the class where needed.

**Review by bramkragten — APPROVED** [review]
Thanks! 🦁

**Pull request merged**
