### PR TITLE
Allow groups in data table to be collapsed

### PR DESCRIPTION
**Pull request by bramkragten**
## Proposed change

CleanShot 2024-04-22 at 12 52 22

## Type of change

- [ ] Dependency upgrade
- [ ] Bugfix (non-breaking change which fixes an issue)
- [X] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes #
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [ ] The code change is tested and works locally.
- [ ] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

**Comment by matthiasdebaat** [comment]
Could you indent the rows of the group? For example like this.
image

**Comment by bramkragten** [comment]
> Could you indent the rows of the group? For example like this.

That means there is a lot less room for the name when you group the table, I don't think we have that space at the moment

**Comment by matthiasdebaat** [comment]
> That means there is a lot less room for the name when you group the table, I don't think we have that space at the moment

48px or so isn't a lot IMO. Especially compared to the extra benefit of making the hierarchy clearer.

**Comment by bramkragten** [comment]
I don't think it is that easy, let's make some designs and work on it afterwards.

**Review by piitaya — APPROVED** [review]
Should we save `collapsedGroups` in the local storage? I can be in another PR.

**Pull request merged**
