### PR TITLE
[On Hold] Generate Brotli files

### PR DESCRIPTION
**Pull request by andrey-git**
Generate Brotli files

### CODE REVIEW

**Comment by balloob** [comment]
From [the Brotli PR](https://github.com/aio-libs/aiohttp/pull/2312) it seems like they only supported receiving requests using brotli. It doesn't seem like they will sent brotli generated files.

To add that, we should add similar code as [this gzip PR for aiohttp](https://github.com/aio-libs/aiohttp/pull/1426).

**Comment by armills** [comment]
Ran some numbers out of curiosity:

image

**Comment by balloob** [comment]
Note that when it comes to compressing for the web, besides the final size, the CPU needed for decompression matters too.

**Comment by balloob** [comment]
Can we close this PR?

 - We're waiting for aiohttp support for serving Brotli files
 - We're using WebPack now and thus this PR would need to be redone using [brotli-webpack-plugin](https://github.com/mynameiswhm/brotli-webpack-plugin)

**Pull request closed without merging**
