### PR TITLE
Add clearing of checked items to shopping-list-card

### PR DESCRIPTION
**Pull request by iantrich**
I debated with making the icon color the same as the section label color. Thoughts?

shopping-list

### CODE REVIEW

**Comment by zsarnett** [comment]
Checked Items is not showing on the demo page

**Comment by iantrich** [comment]
> Checked Items title is not showing on the demo page

@zsarnett the translation is available in the dev gallery, it looks like. I seem to recall @balloob mentioning this before. Perhaps the `script/develop_gallery` is missing something?

**Comment by balloob** [comment]
It requires a round trip -> merged to master -> uploaded to lokalise -> downloaded from lokalise and merged into master.

**Comment by balloob** [comment]
Oh, I guess someone should update our script to run based off dev, not master: #2037

**Review by balloob — APPROVED** [review]

**Comment by heitjer** [comment]
Is there any way to disable the "clear all" button?

**Comment by bramkragten** [comment]
Please don't comment on old closed PR's or issues

**Pull request merged**
