### PR TITLE
Add password field support to ha-form

### PR DESCRIPTION
**Pull request by awarecan**

### CODE REVIEW

**Review by balloob — APPROVED** [review]

**Comment by balloob** [comment]
What is WIP about it? I agree that this is not a proper permanent solution but it will work for now. The real solution would be to allow tagging certain fields as passwords.

**Comment by awarecan** [comment]
WIP is because I still cannot display the icon!

**Review by balloob — APPROVED** [review]

**Comment by balloob** [comment]
The iconset web component was never imported so the icons never registered.

Adding this fixed it:

```js
import '../components/ha-iconset-svg.js';
```

**Comment by balloob** [comment]
image

**Pull request merged**
