### PR TITLE
Polymer 3 modulize

### PR DESCRIPTION
**Pull request by balloob**
It's not that bad 😉 

PR to get frontend working again in dev mode. I consider frontend frozen until this PR is merged. Here is the to do:

 - [x] Code split panels (`partial-panel-resolver.js`) (requires backend change) #1165
 - [x] Code split charts (`ha-chart-base.js`) #1164
 - [x] Code split ha-markdown (`ha-markdown.js`) #1155
 - [x] Load web animations polyfill (in `home-assistant.js`) #1163
 - [x] Load the config panel JS #1166
 - [x] Roboto fonts #1162
 - [x] ES5 build #1168
 - [x] load mdi.html (we can postpone this if we just load HTML import polyfill) #1160
 - [x] Handle extra HTML urls (we can postpone this if we just load HTML import polyfill) #1160
 - [x] Localization needs to work again #1161
 - [x] Expose Polymer.Element and Polymer on window for custom UI and custom panels. #1167
 - [x] Migrate from `paper-material` to `paper-styles` ([info](https://www.npmjs.com/package/@polymer/paper-material)) #1170
 - [x] History/logbook panel passes a custom date object to formatDate resulting in `dateObj.toLocaleDateString` failing. (probably vaadin date picker change related) #1171
 - [x] Fork [`app-storage-behavior`](https://unpkg.com/@polymer/app-storage@3.0.0-pre.19/app-localstorage/app-localstorage-document.js) and remove reference to `import.meta`. Breaks webpack build. Used in `dev-mqtt` and `dev-service` #1172
 - [x] input_datetime more info should work without paper-time-input #1173
 - [x] Icon parsing fails, patch iron-iconset-svg #1175

## Running locally

- Backend: checkout https://github.com/home-assistant/home-assistant/pull/14456
- Frontend: run `yarn` to install the latest packages, after that you can run `webpack --watch` and it will generate the bundle and keep it up to date as you change files.

## Post Polymer 3

There is a ton of cleanup that we can do that we will not do in this PR. Moved them to #1176

### CODE REVIEW

**Comment by andrey-git** [comment]
Is there any way to do things incrementally, if the Fe is frozen anyway?

**Comment by balloob** [comment]
We should open pull requests into this branch.

**Comment by balloob** [comment]
Going to turn off hound for the Polymer repo temporary

**Comment by fanthos** [comment]
Found this:
https://www.npmjs.com/package/@fooloomanzoo/datetime-picker
Not sure it working or not.

**Comment by balloob** [comment]
@fanthos looks like that one is also still published as HTML https://unpkg.com/@fooloomanzoo/datetime-picker@2.9.1/

I think for now I'll just make it a normal input

**Comment by balloob** [comment]
The tests are currently failing because:
 - `state-card-dispay-test.html` depends on `state-summary/state-card-display.js`
 - which depends on `js/common/entity/compute_state_display.js`
 - which depend on `js/common/datetime/format_*`
 - which then depend on `fecha`

And `fecha` doesn't build with Rollup.

**Comment by balloob** [comment]
I've set the fecha dependency temporarily to my ES module fork of fecha.

Problem with the web component tester is that it uses Rollup under the hood which is slightly stricter than Webpack with certain things.

**Pull request merged**
