### PR TITLE
Use ha-card for dev tool "Services" + visual tweaks

### PR DESCRIPTION
**Pull request by spacegaier**
## Proposed change

**A few UI cleanup / improvements:**
1. Use `<ha-card>` to display the description and parameters for a service call. This provides some more visual structure for that page.
2. Small tweaks to the page, such as a header line after the table header for additional visual structure.
3. Service parameter table now gets hidden if no parameter info is found.
4. Dark theme: Made secondary background color a bit brighter, so that there is a better visual separation from the regular background.
5. Removed the `<h3>` from the state dev tools since it looked weird as this font size was only slightly larger than the rest of the page, but not enough to look "on purpose". 

**Before:**
image

**After:**
image

image

## Type of change

- [X] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes #
- This PR is related to issue:
- Link to documentation pull request:

## Checklist

- [X] The code change is tested and works locally.
- [X] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

**Comment by bramkragten** [comment]
Can you add screenshots of the light theme and the code editor in other places, like lovelace?

**Comment by spacegaier** [comment]
> 
> 
> Can you add screenshots of the light theme and the code editor in other places, like lovelace?

@bramkragten Screenshots added on top.

**Comment by bramkragten** [comment]
I don't like the code editor in the light theme, and in the dark theme the difference is minimal

**Comment by spacegaier** [comment]
Dark: I would be happy to make it even lighter.
Light: What would you prefer instead? I went with this color since we already used it as secondary background.

**Comment by bramkragten** [comment]
I think it is too dark, the text on it doesn't work well

**Comment by spacegaier** [comment]
I removed the styling changes for the code editor again as discussed and will look into those in a separate PR. Screenshots are updated.

**Review by bramkragten — APPROVED** [review]

**Pull request merged**
