### PR TITLE
Fix time format in charts

### PR DESCRIPTION
**Pull request by bramkragten**
## Proposed change

Uses the language of the user settings to format the time in the charts

## Type of change

- [ ] Dependency upgrade
- [X] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes #
- This PR is related to issue:
- Link to documentation pull request:

## Checklist

- [ ] The code change is tested and works locally.
- [ ] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

**Review by ludeeus — APPROVED** [review]
Nice! :globe_with_meridians:

**Comment by fancygaphtrn** [comment]
FWIW, I had a custom card that displays weather forecast data as a chart.   May be my problem in development but this change broke it.   Leaving this here for someone else that may have run into the problem.

I previously used this in the html.
          <ha-chart-base data="[[ChartData]]"></ha-chart-base>

Had to change to include the hass object to this.
          <ha-chart-base hass="[[_hass]]" data="[[ChartData]]"></ha-chart-base>

Card example
image

**Comment by kbrohkahn** [comment]
Thanks @fancygaphtrn! Found a few others with the same issue for that custom card.

**Comment by SiliconAvatar** [comment]
I believe that this should have been tagged as a breaking change, since it seems that previous usages of `ha-chart-base` in custom cards breaks now, when not supplied with the new `hass` parameter.
Or is the "Breaking Change" tag only applied if it breaks built-in cards?

**Pull request merged**
