### PR TITLE
Fix updating history card + only update when entity changed

### LINKED ISSUE #5129: History Graph Card (history-graph) not updating until the page is manually refreshed
## Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

## The problem
I have multiple history-graph cards in my dashboard. All worked well until 0.106.5 when these graphs stopped updating. I tried changing refresh_interval, changed browsers even tried clean installation with no luck. I need to refresh the page to see new data on the graph. All graphs ale stuck in time of last page refresh.

## Expected behavior

Graphs should be refreshing according to refresh_interval parameter.

## Steps to reproduce

1. Add history-graph to Lovelace
2. Add any sensor, that changes state reasonably often to graph.
3. Save and let it show in the browser for a few minutes

## Environment

Home Assistant release with the issue: 0.106.6
Last working Home Assistant release (if known): 0.106.4
Browser and browser version: Android Chromium, Safari
Operating system: iOS, iPadOS, Android

## Problem-relevant configuration

        - type: history-graph
          hours_to_show: 8
          refresh_interval: 30
          title: 'Teplota a vlhkosť'
          entities:
            - entity: sensor.bedroom_temperature
              name: 'Spálňa'
            - entity: sensor.kids_room_temperature
              name: 'Detská izba'
            - entity: sensor.paincave_temperature
              name: 'Pracovňa'
            - entity: sensor.dining_room_temperature
              name: 'Obývačka'
            - entity: sensor.master_bathroom_temperature
              name: 'Kúpelňa'
            - entity: sensor.guest_bathroom_temperature
              name: 'Hosťovská kúpelňa'
            - entity: sensor.bedroom_humidity
              name: 'Spálňa'
            - entity: sensor.kids_room_humidity
              name: 'Detská izba'
            - entity: sensor.paincave_humidity
              name: 'Pracovňa'
            - entity: sensor.dining_room_humidity
              name: 'Obývačka'
            - entity: sensor.master_bathroom_humidity
              name: 'Kúpelňa'
            - entity: sensor.guest_bathroom_humidity
              name: 'Hosťovská kúpelňa'

## Javascript errors shown in your browser console/inspector

```txt

```

### PR DESCRIPTION
**Pull request by bramkragten**
## Proposed change

Fixes https://github.com/home-assistant/frontend/issues/5129

And only fetch history when the state of a shown entity is changed

## Type of change

- [ ] Dependency upgrade
- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes #
- This PR is related to issue:
- Link to documentation pull request:

## Checklist

- [ ] The code change is tested and works locally.
- [ ] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

**Review by ludeeus — APPROVED** [review]
:chart_with_upwards_trend:

**Comment by manutoky** [comment]
Any chance that 0.115.2 reverted this fix? My history cards are not updating anymore after the HA update.

**Comment by Leapo** [comment]
> Any chance that 0.115.2 reverted this fix? My history cards are not updating anymore after the HA update.

Seeing the same behavior here

**Comment by zsarnett** [comment]
Please do not comment on old PRs. PLease create a new issue

**Pull request merged**
