### PR TITLE
Fix material resolving

### PR DESCRIPTION
**Pull request by balloob**
## Proposed change

Got these warnings when yarn installing:

```
warning Resolution field "@material/animation@8.0.0-canary.096a7a066.0" is incompatible with requested version "@material/animation@8.0.0-canary.a78ceb112.0"
warning Resolution field "@material/base@8.0.0-canary.096a7a066.0" is incompatible with requested version "@material/base@8.0.0-canary.a78ceb112.0"
warning Resolution field "@material/feature-targeting@8.0.0-canary.096a7a066.0" is incompatible with requested version "@material/feature-targeting@8.0.0-canary.a78ceb112.0"
warning Resolution field "@material/theme@8.0.0-canary.096a7a066.0" is incompatible with requested version "@material/theme@8.0.0-canary.a78ceb112.0"
```

This PR solves it, but I haven't checked if circular progress still works 😬 

## Type of change

- [ ] Dependency upgrade
- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes #
- This PR is related to issue:
- Link to documentation pull request:

## Checklist

- [ ] The code change is tested and works locally.
- [ ] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

**Comment by balloob** [comment]
Tested. Seems to work.

**Comment by bramkragten** [comment]
Can't work?

**Comment by bramkragten** [comment]
https://github.com/material-components/material-components-web/pull/6203

**Comment by bramkragten** [comment]
https://github.com/home-assistant/frontend/pull/6517

**Pull request closed without merging**
