### PR TITLE
Input Select form: Add "Copy options"

### PR DESCRIPTION
**Pull request by kubawolanin**
## Proposed change

Dropdown helper currently has no possibility to select/copy created options to clipboard.
This PR adds "Copy options" feature:
copy-options

## Type of change

- [ ] Dependency upgrade
- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes #
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [ ] The code change is tested and works locally.
- [ ] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

**Comment by kubawolanin** [comment]
Marking as draft since there's a bug I couldn't fix - clicking "Copy options" or closing the three dot menu results in closing the dialog window completely. Experimented with `ev.preventDefault` as well as `stopPropagation` inside `_handleAction` but with no luck so far.

**Comment by zsarnett** [comment]
What is the use case for this?

**Comment by kubawolanin** [comment]
Hey Zack.
Had 10+ options in the input_select entity that I've added with UI.
Needed them in a yaml based automation.
Then I realized that none of the options on the UI are selectable 😱
Having "Copy options" would have saved me quite some time of extracting them from DevTools ;-)

**Comment by kubawolanin** [comment]
This three dot menu would allow us to add "Reorder items" feature in the future, which also would be nice to have there.

**Comment by matthiasdebaat** [comment]
> This three dot menu would allow us to add "Reorder items" feature in the future, which also would be nice to have there.

We had a solution about that in this issue https://github.com/home-assistant/frontend/issues/10107#issuecomment-948968460, that I prefer. Unfortunately that hasn't been pushed.

> Having "Copy options" would have saved me quite some time of extracting them from DevTools ;-)

This sound like an edge case for a small group of users. Don't know if we should add extra UI components to the screen for everyone.

**Comment by kubawolanin** [comment]
Hey @matthiasdebaat 
> We had a solution about that in this issue https://github.com/home-assistant/frontend/issues/10107#issuecomment-948968460, that I prefer. Unfortunately that hasn't been pushed.

Wow, I like it too! Any chance to push it further? It even allows to select the text, which resolves my initial issue.

**Comment by kubawolanin** [comment]
@ChrisBit do you plan to resurrect #10361? It would be perfect 🎉

**Pull request closed without merging**
