### PR TITLE
Allow moving card to specific position

### PR DESCRIPTION
**Pull request by ktnrg45**
## Proposed change

Allows moving a card to a specific position/index directly. Currently we have to repeatedly click on the up/down arrows until the card reaches the desired position.

- Adds a move button next to up/down arrows for each card in config view

- When clicking the move button on the card to be moved, the card is selected to be moved.
If the next click is another cards move button, the selected card will take the second cards position.

## Type of change

- [ ] Dependency upgrade
- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

Tested on Chrome Desktop, Android Chrome + Samsung Browser
- This PR fixes or closes issue: fixes #
- This PR is related to issue: 
- Link to documentation pull request: 

## Checklist

- [x] The code change is tested and works locally.
- [x] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

**Comment by zsarnett** [comment]
I don't think this is a very good User Experience for this feature.

**Comment by bramkragten** [comment]
Can you add some screenshots/screen capture of how this would look/work.

**Comment by zsarnett** [comment]
We should also talk about if we plan to use the drag and drop system. Are we going to allow users to use the old methods as well? (Move card up/down) if not then this isn't something we should add as it's just more to remove later after a short time of releasing it

**Comment by ktnrg45** [comment]
Sure. Below is a demo. I do feel that the feature of positioning cards specifically itself, if not my implementation of it, would be useful for scalability reasons ie. (100+ Cards in a view).

demo

**Comment by timmo001** [comment]
Perhaps instead of clicking the same icon again on another card, there should be a colored section added in between each card that is clickable. Clicking the same icon looks like you are swapping positions instead of moving the position imo.


_Really wish there was a nice drag and drop library out there. Only one I've been able to find is muuri, but I've had a terrible experience with it before_

**Comment by zsarnett** [comment]
We have a PR out for the Muuri Library Integration. I agree this isn't the best UX for moving cards. I think we should focus on the Drag and Drop implementation that should be coming in the next few releases. Its a big PR and will take time but we will get there.

**Comment by zsarnett** [comment]
https://github.com/home-assistant/frontend/pull/4804

**Comment by timmo001** [comment]
Aha yes. Thought I'd saw it. Good luck getting that to work :smile: 

I think this solution is good for the interim though. Depends how close we are to completion in #4804

**Comment by zsarnett** [comment]
I don't think adding a new feature and then removing the feature a release later is a good idea. We should choose one-way move cards and go with it. It will only confuse users if we give them features and immediately take it away or give them multiple different ways to move a card which only makes maintaining harder and code base more complicated

**Comment by ktnrg45** [comment]
Ah I didn't see that there was a drag and drop PR open. I agree that DND would be more user friendly and definitely the better option.
@zsarnett Would the DND be compatible/feasible for mobile browsers as well? The reason I ask is because if DND it isn't feasible on mobile, a button-like interface may be an appropriate alternative for it.

**Pull request closed without merging**
