### PR TITLE
Add advanced mode

### LINKED ISSUE #3277: Customization in Home Assistant 0.93+ does not work
*@ricmik commented on Jun 14, 2019, 8:34 PM UTC:*

**Home Assistant release with the issue:**

0.93, 0.94.3

**Last working Home Assistant release (if known):**
This install was done directly on 0.93

**Operating environment (Hass.io/Docker/Windows/etc.):**

Hass.io on Raspberry Pi

**Component/platform:**

Customization

**Description of problem:**
After a new install of Home Assistant 0.93 I'm unable to do any customizations via the customization page of the web interface.

Error message in web interface:
It seems that your configuration.yaml doesn't properly include customize.yaml Changes made here won't affect your configuration.

The customizations worked in the beginning until a reboot of Hass.io

Sometimes the web interface let me customize the entities, and other times I get the message: The following attributes are already set in customize.yaml

**Problem-relevant `configuration.yaml` entries and (fill out even if it seems unimportant):**

**Complete configuration.yaml**

```yaml
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123

# Auto discovery
discovery:

# Sensors
sensor:
  # Weather prediction
  - platform: yr

# Text to speech
tts:
  - platform: google_translate

logger:
  default: info

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml

recorder:
  purge_keep_days: 3

device_tracker:

weather:
  - platform: met

homekit:
  filter:
    include_domains:
      - light
      - media_player
    exclude_entities:
      - light.stue
      - light.balkong
      - light.kjokken
      - light.soverom
      - light.innelys
      - light.utelys

  entity_config:
    media_player.stue:
      name: Sonos Stue
      feature_list:
        - feature: play_pause
    media_player.bad:
      name: Sonos Bad
      feature_list:
        - feature: play_pause
    media_player.kjkken:
      name: Sonos Kjøkken
      feature_list:
        - feature: play_pause
    media_player.soverom:
      name: Sonos Soverom
      feature_list:
        - feature: play_pause

input_boolean:
  guest_mode:
    name: Gjestemodus
    icon: mdi:seat-individual-suite
  vacation_mode:
    name: Feriemodus
    icon: mdi:beach
  christmas_mode:
    name: Julemodus
    icon: mdi:ornament
  wakeup_routine:
    name: Morgenstemning
    icon: mdi:weather-sunset-up
  wakeup_weekends:
    name: Aktivert i helg
    icon: mdi:calendar-range
input_datetime:
  wakeup_time:
    name: Stå opp
    has_date: false
    has_time: true

light:
- platform: switch
  name: Balkonglys
  entity_id: switch.balkonglys
- platform: group
  name: Balkong
  entities:
    - light.balkonglys
- platform: group
  name: Stue
  entities:
    - light.leselys_sofahjorne
    - light.taklampe
- platform: group
  name: Kjøkken
  entities:
    - light.kjokkenbord
- platform: group
  name: Soverom
  entities:
    - light.nattbord_1
    - light.nattbord_2
    - light.vindu_soverom
- platform: group
  name: Innelys
  entities:
    - light.stue
    - light.kjokken
    - light.soverom
- platform: group
  name: Utelys
  entities:
    - light.balkong
media_player:
- platform: yamaha
  source_ignore:
    - "AUDIO1"
    - "AUDIO2"
    - "JUKE"
    - "MusicCast Link"
    - "NET RADIO"
    - "Napster"
    - "PHONO"
    - "SERVER"
    - "Spotify"
    - "TUNER"
    - "USB"
    - "V-AUX"
    - "iPod (USB)"
    - "Bluetooth"
    - "AV1"
    - "AV2"
    - "AV3"
    - "AV6"
    - "HDMI4"
    - "HDMI5"
  source_names:
    AV4: "TV"
    AV5: "Sonos"
    HDMI1: "PS4"
    HDMI2: "HTPC"
    HDMI3: "AppleTV"
  zone_ignore:
    - "Zone_2" 
```

**Traceback (if applicable):**

Not sure if these log messages are relevant, but they seem to happen when I try customization.

```
2019-06-14 20:31:44 ERROR (MainThread) [frontend.js.latest.201906040] http://hassio.local:8123/frontend_latest/app.29ef27ad.js:2:59869 Uncaught TypeError: Cannot convert undefined or null to object
2019-06-14 20:31:44 ERROR (MainThread) [frontend.js.latest.201906040] http://hassio.local:8123/frontend_latest/app.29ef27ad.js:2:59869 Uncaught TypeError: Cannot convert undefined or null to object
2019-06-14 20:31:51 ERROR (MainThread) [frontend.js.latest.201906040] http://hassio.local:8123/frontend_latest/app.29ef27ad.js:2:59869 Uncaught TypeError: Cannot convert undefined or null to object
2019-06-14 20:31:51 ERROR (MainThread) [frontend.js.latest.201906040] http://hassio.local:8123/frontend_latest/app.29ef27ad.js:2:59869 Uncaught TypeError: Cannot convert undefined or null to object

```

**Additional information:**

**customize.yaml**

```yaml
binary_sensor.soveromsvindu_hoyre:
  device_class: window
binary_sensor.soveromsvindu_venstre:
  device_class: window
binary_sensor.kjokkenvindu_hoyre:
  device_class: window
binary_sensor.balkongdor:
  device_class: door
binary_sensor.inngangsdor:
  device_class: door
```

*This issue was moved by [OttoWinter](https://github.com/OttoWinter) from [home-assistant/home-assistant#24538](https://github.com/home-assistant/home-assistant/issues/24538).*

### PR DESCRIPTION
**Pull request by balloob**
Allow users to enable advanced mode in their profile page.

image

The bottom of the config dashboard will have a link to point people at advanced mode.

image

Thanks to @SeanPM5 for the input.

---

Hide the following sections unless advanced mode is enabled:
 - Customize page
 - From general page:
   - config validation
   - config reloading

Fixes #3277

### CODE REVIEW

**Comment by aidbish** [comment]
Would it be possible to hide the delete/update buttons of the entity registry unless advanced mode in enabled as a future part of this?

**Comment by balloob** [comment]
@aidbish what do you mean with the update button? We should still allow users to rename names and entity IDs. Delete I can see how it should be hidden.

What do you mean with both the YAML and the UI options?

**Comment by aidbish** [comment]
Hi @balloob 
Understand and point1

for yaml/ui. In your original opening comment you said its a yaml config item but would probably become a UI. my comment was simply asking if both options could be possible

**Comment by balloob** [comment]
Oh right. So advanced mode is going to only impact what is visible in the UI. Because of that, we are going to make it a UI only feature to show advanced features in the UI.

And no, we're not dropping YAML.

**Comment by aidbish** [comment]
No Problemo
Was more concerned of the possible complaints by the YAML fans when there is not a corresponding yaml config item for something

**Comment by balloob** [comment]
All YAML things will be part of advanced mode. The YAML tools that are now part of general and only shown in advanced mode (validate config, reload config), will be moved to a new config option.

**Pull request merged**
