### PR TITLE
Improve state and name display on state-card-display

### PR DESCRIPTION
**Pull request by piitaya**
## Proposed change

https://github.com/home-assistant/frontend/pull/17649 PR introduced multiline support. This PR improves the display by setting `min-width` to name and state to avoid multiline text for small state like version number.

**Short name, long state**

CleanShot 2023-10-13 at 10 20 58

**Short name, short state**

CleanShot 2023-10-13 at 10 20 42

**Long name, short state**

CleanShot 2023-10-13 at 10 20 28

**Long name, long state**

CleanShot 2023-10-13 at 10 20 17

## Type of change

- [ ] Dependency upgrade
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes #
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [ ] The code change is tested and works locally.
- [ ] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

**Review by bramkragten — APPROVED** [review]

**Comment by ildar170975** [comment]
@piitaya 
1. W/o these additions I see this:
Short name, long state
изображение

Short name, short state
изображение

Long name, short state
изображение

Long name, long state
изображение

In your examples a name may be "shortened" by ellipsis. This a LOOSING of information.

2. In my PR (https://github.com/home-assistant/frontend/pull/17649) I made a mistake - forgot to add this line for ".state" (was added locally in my tets setup, I just forgot to add to PR... my fault...):
```
justify-content: flex-end;
```

**Comment by piitaya** [comment]
The bug was this one because there was no min-width for the state 

image

Do you think it's better to have the state on 6 lines if the name is very long? We should not encourage user to use very long name like this.

**Comment by ildar170975** [comment]
@piitaya 
The problem is that I do not see what you see...
изображение
The picture you posted shows a wrapped version - which looks bad, absolutely agree.
But I cannot reproduce it.
In my tests I tried to achieve "do not use ellipsis" (info should be 100% displayed).

**Comment by piitaya** [comment]
The very long name is not long enough in your example to reproduce the issue.

**Comment by ildar170975** [comment]
Now I see it. Agree, looks very bad.
Can we show names w/o ellipsis?

**Pull request merged**
