### PR TITLE
Added schedule panel

### PR DESCRIPTION
**Pull request by alex-torregrosa**
Adds a custom panel for home-assistant/home-assistant/pull/22037

### CODE REVIEW

**Comment by iantrich** [comment]
We'll want to write this as a LitElement, not PolymerElement as that is the way we're moving the repo.
Can you also provide some screens of what this looks like?

**Comment by alex-torregrosa** [comment]
Ok, I'll rewrite it using LitElement.

It currently looks like this:

screenshot

**Comment by yosilevy** [comment]
Cool!! I currently use google calendar for schedule but this would make it redundant. Great.

Alex - please check that it looks good when you switch to RTL (right to left). You can do this by selecting this in the language drop down:
image

Thanks

**Comment by Misiu** [comment]
@alex-torregrosa I was searching for a schedule option for Home Assistant and I found this PR.
This looks awesome 🎉🎉🎉
I really don't understand why this got closed.
I need a scheduler for couple of generic thermostats and about ten roller shutters.
Your solution would work perfectly for me.
I've checked the architecture issue and there are a lot of comments, but not even a single proposed solution.
Home Assistant is missing a Scheduler option, I hope it will get one some day.

**Pull request closed without merging**
