### PR TITLE
Add icon for manual mode

### PR DESCRIPTION
**Pull request by TomMini**
Added an icon for manual operation mode to the lovelace thermostat card.

### CODE REVIEW

**Comment by balloob** [comment]
How does the icon look? And how does that look together with the other ones?

**Comment by TomMini** [comment]
It's the hand cursor cursor-pointer, used for thermostats that support a manual-mode. If a thermostat has this operation in it's current operationlist it's not rendered/controllable in the lovelace-ui at all.

**Comment by zsarnett** [comment]
Can we get screen shots of the whole thermostat with manual mode being apart of it? Also, you will need to add Manual to the translations.

**Comment by TomMini** [comment]
Here's the screen shot with manual mode enabled. Also made the color blue when in manual operation
image

**Review by zsarnett — APPROVED** [review]

**Review by iantrich — APPROVED** [review]

**Pull request merged**
