### PR TITLE
Merge ha-paper-slider into ha-slider

### PR DESCRIPTION
**Pull request by thomasloven**
## Proposed change

Merge `ha-paper-slider` (which modifies some styles of `paper-slider`) into `ha-slider` (which fixes a rounding problem with `paper-slider`).

I don't understand why there were two of them anyway.

## Type of change

- [ ] Dependency upgrade
- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [x] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes #
- This PR is related to issue:
- Link to documentation pull request:

## Checklist

- [ ] The code change is tested and works locally.
- [ ] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

**Comment by bramkragten** [comment]
This could be breaking for custom card developers

**Review by bramkragten — APPROVED** [review]

**Comment by thomasloven** [comment]
`ha-paper-slider` is already "broken" by lazy-loading more-info dialogs.
Of the two sliders `ha-paper-slider` looked better but was lazy-loaded since 0.115, and `ha-slider` behaved better and was not lazy-loaded.
The new `ha-slider` is (currently) immediately loaded and now has the good looks of `ha-paper-slider`.

**Comment by bramkragten** [comment]
What is loading `ha-slider`?

**Comment by thomasloven** [comment]
The more-info controls for `light` entities. Through `ha-labeled-slider`.

**Comment by bramkragten** [comment]
But the more info controls are(where) lazy loaded?

**Comment by thomasloven** [comment]
You're right. I assumed some were not loaded, and that's why it worked.
But I found it:
https://github.com/home-assistant/frontend/blob/d9f42712e41d13325a33383bf6779dd2c84943e9/src/dialogs/more-info/ha-more-info-dialog.ts#L32
https://github.com/home-assistant/frontend/blob/d9f42712e41d13325a33383bf6779dd2c84943e9/src/state-summary/state-card-content.js#L9
https://github.com/home-assistant/frontend/blob/d9f42712e41d13325a33383bf6779dd2c84943e9/src/state-summary/state-card-input_number.js#L9

**Comment by bramkragten** [comment]
I wonder if we should replace the `state-card-content` with the lovelace entity row

**Pull request merged**
