### PR TITLE
Bump @fullcalendar to version 6.1.1

### PR DESCRIPTION
**Pull request by steverep**
## Proposed change

This is meant to replace #14914 from dependabot.  After skimming dependabot issues, it seems this is failing because dependabot cannot yet handle a jump from no peer dependencies to having them.  As a result, it seems to miss the fact that `@fullcalendar/*` plugins now all have `@fullcalendar/core` as a peer dependency.  So the whole scope needs to update to v6 at once, plus the following:
- According to the [v6 release notes](https://fullcalendar.io/docs/upgrading-from-v5), manual style imports are no longer needed and CSS is injected via the JS, so I removed those occurences
- Removed the internal `@fullcalendar/common` package (no v6)
- Changed a couple occurrences of importing `memoize` to use `memoize-one` package instead (if these were purposely needed from `fullcalendar`, then they need to come from `@fullcalendar/core/internal` now)

Functionality seems fine but I admittedly did not even try to inspect for style differences. 😉 🦯 

## Type of change

- [x] Dependency upgrade
- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes #
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [x] The code change is tested and works locally.
- [x] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

**Comment by bramkragten** [comment]
Checked the styling, and that is not quite there yet... Will look into it

CleanShot 2023-01-02 at 17 20 17

**Comment by bramkragten** [comment]
Ugh...

https://github.com/fullcalendar/fullcalendar/blob/main/packages/core/src/styleUtils.ts

They should let you provide an element to apply the styles to...

**Comment by bramkragten** [comment]
https://github.com/fullcalendar/fullcalendar/issues/7118

**Comment by steverep** [comment]
Yeah, I was afraid of that… Should be a simple fix if they respond quickly though.

There's also a new Web component package from them, which I didn't look into yet. It may, or may not be useful to us.

**Comment by bramkragten** [comment]
Their webcomponent doesn't use shadow DOM...

**Comment by steverep** [comment]
Upgraded to get their fix in 6.1, but again I'll defer to you on reviewing the style.

**Comment by bramkragten** [comment]
Looks good!

**Review by bramkragten — APPROVED** [review]

**Pull request merged**
