### PR TITLE
Insteon device configuration panel

### PR DESCRIPTION
**Pull request by teharris1**
## Proposed change

Add a control panel to allow Insteon devices to be configured using the frontend.

This is related to core PR https://github.com/home-assistant/core/pull/49785

## Type of change

- [ ] Dependency upgrade
- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes #
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [x] The code change is tested and works locally.
- [x] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

**Comment by homeassistant** [comment]
Hi @GitHub-Action, 

It seems you haven't yet signed a CLA. Please do so [here](https://home-assistant.io/developers/cla_sign_start/?pr=home-assistant&#x2F;frontend#9010).

Once you do that we will be able to review and accept this pull request.

Thanks!

**Comment by teharris1** [comment]
@bramkragten The backend has been merged into dev. Is there an expectation on when this PR could get reviewed? I have users very excited about this feature. :)

**Comment by teharris1** [comment]
FYI, these commits were only to rebase to the current version since lit-element is no longer being used and some items have been retyped.

**Comment by teharris1** [comment]
@balloob Sorry to bother you but I am concerned that this PR has sat for so long. The backend is merged. I am happy to help in any way to move this forward but I am not sure what the process is. This is my first front-end PR. if you are not aware, there are two very common Insteon solutions in the market that are currently experiencing problems. THis PR closes a big gap in the ability to manage the Insteon nextwork directly in HA and closes some of the gap of competing products.  I am hopeful this will lure other Insteon users to try HA as their solution.

**Comment by bramkragten** [comment]
Hey @teharris1, sorry for not responding sooner, I was a bit busy.

This is very big PR, we should definitely split it up into multiple smaller ones.

Having said that, we should probably make a decision if we want this Insteon panel in Home Assistant core, did we discuss this before? 

You should open an architecture discussion for that.

**Comment by teharris1** [comment]
Any thoughts on this?

**Comment by teharris1** [comment]
> we should probably make a decision if we want this Insteon panel in Home Assistant core,


@bramkragten any decision on the question above? Before I break this up into multiple PRs I want to make sure I am not wasting my time. This work has been going on for almost a year so you can imagine I am concerned about spending more time on something that may not move forward.

**Comment by bramkragten** [comment]
I'm on vacation atm, will get back to you when I'm back.

**Comment by balloob** [comment]
I think that it's better to not move forward with the insteon panel. Insteon is used by 0.2% of the users, https://analytics.home-assistant.io/#integrations, and it's not an official integration or open home automation standard.

This code can still be made available to users via a custom integration registering a custom panel, similar to how the Supervisor panel works.

**Pull request closed without merging**
