### PR TITLE
Pass device ID to logbook if available

### PR DESCRIPTION
**Pull request by balloob**
## Proposed change
Pass device ID to logbook if available.

## Type of change

- [ ] Dependency upgrade
- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes #
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [ ] The code change is tested and works locally.
- [ ] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

**Comment by bdraco** [comment]
Needs a guard for empty entities

Screen Shot 2022-05-18 at 19 35 47
Screen Shot 2022-05-18 at 19 35 41

**Comment by bdraco** [comment]
Logbook cards are no longer filtering entities. 
Screen Shot 2022-05-18 at 22 36 31

**Comment by bdraco** [comment]
I fixed the missing devices here https://github.com/home-assistant/core/pull/72122

**Comment by bdraco** [comment]
Area cards have the logbook oldest first instead of newest first.  The devices are coming through now! w/ https://github.com/home-assistant/core/pull/72122

`Nick Office Pico` .. `release stop` is from a device
Screen Shot 2022-05-18 at 22 51 44

**Comment by balloob** [comment]
Pushed fixes.

**Comment by bdraco** [comment]
Retesting now

**Comment by bdraco** [comment]
Out of scope, but the logbook card doesn't support selecting a device or entity (only entities)

**Comment by bdraco** [comment]
Order is reversed in areas.  Oldest events are shown first
Screen Shot 2022-05-19 at 12 31 24

**Comment by balloob** [comment]
I want to do the device picker for logbook card in another PR because it will require making some decisions. Would you expect to pick a device, and then have it automatically select all entities too? And if we do that, should we even still show the entity picker? And should there be a toggle if the device should only show logbook entries for primary entities or also config/diagnostic?

**Comment by bdraco** [comment]
> I want to do the device picker for logbook card in another PR because it will require making some decisions. 

I agree 100%. Was only mentioning it for testing completeness.

> Would you expect to pick a device, and then have it automatically select all entities too? 

Sadly since not all entities have devices or come from config entries, I think we have to select both otherwise the user is likely missing out on a lot of entities they probably want to track.

> And if we do that, should we even still show the entity picker? 

Previous answer applies

> And should there be a toggle if the device should only show logbook entries for primary entities or also config/diagnostic?

Previous answer applies

**Comment by bdraco** [comment]
Devices with only diagnostic entities get the full logbook

Screen Shot 2022-05-19 at 12 37 01

**Comment by bdraco** [comment]
Contexts and user ids are still fetched for empty areas
Screen Shot 2022-05-19 at 12 43 47

**Comment by bdraco** [comment]
Screen_Shot_2022-05-19_at_12_47_36

Logbook and history have a disagreement on times.  May be a backend bug though.  Will investigate

**Comment by bdraco** [comment]
> Screen_Shot_2022-05-19_at_12_47_36
> 
> Logbook and history have a disagreement on times. May be a backend bug though. Will investigate

This is actually a long standing bug in history.  If we collapse duplicate states we don't take the first time
```
2800520|sensor.master_zone_status|Damper Open||||2022-05-19 13:52:09.065517|2799952|187|0|01G3E9E3V996EF30564QSFRDYY||
2807628|sensor.master_zone_status|Damper Open||||2022-05-19 15:04:28.430579||187|0|01G3EDJHGEN87YDMWN7AYKDDYP||
2818789|sensor.master_zone_status|Damper Open||||2022-05-19 16:45:57.022715||187|0|01G3EKCBCY3F3XE4MPEDAYX1G4||
2825119|sensor.master_zone_status|Damper Open||||2022-05-19 17:23:22.836699||187|0|01G3ENGWJMJB6SPM3AMAJHG5T9||
```

**Comment by bdraco** [comment]
There is a bug with minimal responses with the last state that is the cause of https://github.com/home-assistant/frontend/pull/12728#issuecomment-1132009267

We replace it with a full state for the frontend but we get the wrong one if we have skipped all the states at the end of the list.

Opened https://github.com/home-assistant/frontend/pull/12732 to get the attributes from first state instead of the last.   I'm going to remove the code that replaces the last state on the backend with a full state instead of a minimal state so we don't have that complexity as it was only doing so to make the frontend happy

**Comment by bdraco** [comment]
Ok back to testing this.

**Comment by bdraco** [comment]
```diff
diff --git a/src/panels/config/devices/ha-config-device-page.ts b/src/panels/config/devices/ha-config-device-page.ts
index 3c0477573..372334048 100644
--- a/src/panels/config/devices/ha-config-device-page.ts
+++ b/src/panels/config/devices/ha-config-device-page.ts
@@ -594,8 +598,8 @@ export class HaConfigDevicePage extends LitElement {
                       <ha-logbook
                         .hass=${this.hass}
                         .time=${this._logbookTime}
-                        .entityId=${this._entityIds(entities)}
-                        .deviceId=${this._deviceIdInList(this.deviceId)}
+                        .entityIds=${this._entityIds(entities)}
+                        .deviceIds=${this._deviceIdInList(this.deviceId)}
                         virtualize
                         narrow
                         no-icon
```

**Comment by bdraco** [comment]
✅ Logbook cards
✅ Logbook from left bar
✅ Areas
Devices ...testing in progress https://github.com/home-assistant/frontend/pull/12728#issuecomment-1132118619

**Comment by bdraco** [comment]
Finished testing.  Looks like just the missing `s`s and this is GTG 👍

**Review by bdraco — DISMISSED** [review]

**Review by bdraco — APPROVED** [review]

**Comment by bdraco** [comment]
✅ Logbook cards
✅ Logbook from left bar
✅ Areas
✅  Devices  ~~https://github.com/home-assistant/frontend/pull/12728#issuecomment-1132118619~~
✅ More Info

**Comment by bdraco** [comment]
This one is really so cool to see in action.  👍

**Pull request merged**
