### PR TITLE
Added NL nl.json

### PR DESCRIPTION
**Pull request by passie**

### CODE REVIEW

**Comment by TopdRob** [comment]
++ good translation

**Comment by mariniertje** [comment]
Status is not a proper translation for State. The English word for Status is also Status (plural: statuses).

However, I also recommended using another word than "States" in #484 , since you're likely to run into the same problem in other languages. And if the source word is not specific and clear enough, it will result in messy and free translations of words, which can result in them losing their original meaning/intent. I've ran into this many times before with translation projects, and therefore recommend (and prefer) to stick with the correct/literal translations of the source word and not translations of individual interpretations of the source word.

**Comment by balloob** [comment]
I agree, we should not go for "Status". For English we're talking about using "Overview". I think that for Dutch we can go for "Overzicht"

**Comment by balloob** [comment]
I've also updated Historie -> Geschiedenis. That's more aligned with the terminology in browsers.

**Comment by balloob** [comment]
Thanks!

**Pull request merged**
