### PR TITLE
Clean up users table

### PR DESCRIPTION
**Pull request by balloob**
## Proposed change

We tend to introduce columns to represent single data points of an object. The problem with that is that the table headers take up a lot of space and so don't translate to mobile.

This PR is a proposal for a new approach on how to show information on mobile. Also shortens headers on desktop.

Before:
image

After:
image

Each icon will show a tooltip when hovering.

Mobile view:

image

An alternative approach I can think of is using [chips](https://design.home-assistant.io/#components/ha-chips) but I'm afraid that using text will take up a lot of space.

Also includes a bug fix: we will no longer show "Unnamed User" for users that have no username. 

## Type of change

- [ ] Dependency upgrade
- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes #
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [ ] The code change is tested and works locally.
- [ ] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

**Comment by balloob** [comment]
Marking as draft because I want to get rid of paper tooltip

**Comment by mdegat01** [comment]
While it does take up less space I feel like its kind of a usability loss, the page is now a lot harder to grasp at a glance in my opinion. As it is now I can glance at that table and immediately know what's going on, no explanation required. The proposal requires either a legend or tooltips to understand what I'm seeing since the meaning behind the icons isn't readily apparent. The disabled icon is very familiar so I can associate that with inactive user easily enough but the others I'd have to look up their meaning. Chips is better from that perspective but as you point out it may not save any space.

Also I would just note that tooltips with essential info in them (like explanations for icons) is considered bad practice for accessibility ([this article](https://sarahmhigley.com/writing/tooltips-in-wcag-21/) explains why pretty well). Not sure if HA is actually usable on a screenreader so maybe that's a non-issue but the issue does also come up on touch devices like phones since you can't hover.

**Comment by balloob** [comment]
Got rid of paper tooltip and updated icons too:

image

**Comment by balloob** [comment]
@mdegat01 I guess you're right that there is enough space so now only applied the change to the mobile view. It's still taking up a lot of space requiring at least 1350 pixels screen real estate to avoid horizontal scrolling bars.

**Comment by balloob** [comment]
This is how it can look with chips. They would all be put in a single column

image

**Comment by spacegaier** [comment]
I second what @mdegat01 wrote. Only having the icons feels like a UX downgrade.

The benefit of having individual table columns is that you can sort by them. I personally do not have that many accounts in my instances, so not that important to me, but might be to others?

Is there perhaps a way to have the table headers be multi line, so "System\ngenerated" and "Local\nonly"?

**Comment by balloob** [comment]
@spacegaier I already updated it to be just for mobile. The mobile view for users is currently unusable because the names are cut off.

**Comment by zsarnett** [comment]
@matthiasdebaat Any viewpoints?

**Comment by spacegaier** [comment]
> @spacegaier I already updated it to be just for mobile. The mobile view for users is currently unusable because the names are cut off.

Yes, I saw that. Should have been clearer in my last comment: That was meant in regards to non-mobile.

**Comment by matthiasdebaat** [comment]
I like that this improves the table on mobile. I would recommend avoiding icons that need explanation. In that case it is better to show the label with an optional icon. In this case I think we have two options:

1. Flip the table like this:

2. Hide less important columns, for example `system generated` and `group`.

Personally I like option 1 the best. It's also a pattern we can use for other tables.

**Comment by balloob** [comment]
I've updated the headers to be "System" and "Local". Updated screenshots in PR description.

**Comment by balloob** [comment]
Pushed an update to show the icons + labels in the user detail dialog (when you tap on a user):

image

**Comment by balloob** [comment]
One extra idea I have is that for system generared, we could show "System" in the "Group" column.

**Comment by balloob** [comment]
Discussed with Matthias. Hiding the system icon on mobile, rest can stay as-is.

**Pull request merged**
