### PR TITLE
Custom more info

### PR DESCRIPTION
**Pull request by exxamalte**
This allows for defining a custom more info dialog, similar to the custom state card.

Pull request in developers.home-assistant with documentation: https://github.com/home-assistant/developers.home-assistant/pull/1

### CODE REVIEW

**Comment by c727** [comment]
purely out of interest, do you already have some custom more info cards that you want to use?

**Comment by exxamalte** [comment]
@c727: The idea for this extension came when I was just developing a new component that generates binary sensors and for which I wanted to show additional information on the frontend. In particular I am retrieving events from a GeoRSS feed; if there is one or more events in the vicinity of the HA instance, the binary sensor turns on and I would like to show a map with the events in the more info dialog.
When checking out the existing capabilities to add a more info dialog I realised that this can currently only be added per domain, so for _all_ binary sensors or _all_ sensors, but not just for those binary sensors that my new component generates and provides some additional attributes for.
I thought that this custom more info capability could be a stop gap measure in the meantime.

**Comment by c727** [comment]
```javascript
window.hassUtil.dynamicContentUpdater(
  this,
  stateObj && stateObj.attributes && stateObj.attributes.custom_ui_more_info
    || `more-info-${window.hassUtil.stateMoreInfoType(stateObj)}`,
  { hass, stateObj }
);
```

**Comment by exxamalte** [comment]
@c727: Happy to include your suggestion for improvement. However, could you please have a look at the `toUpperCase()` part that I carried over from the original code? I am unsure if there are any side effects when removing that.

**Comment by andrey-git** [comment]
toUpperCase is required for non chrome, where element.tagName is uppercase.

**Comment by exxamalte** [comment]
Thanks @andrey-git. Well in that case I propose to keep the original code for readability and simplicity instead of trying to reduce the code any further.

**Review by balloob — APPROVED** [review]

**Pull request merged**
