### PR TITLE
Build hassio panel

### PR DESCRIPTION
**Pull request by balloob**
Organize Hass.io panel stuff as own separate project with own build scripts. Adds these new scripts to be run from the `/hassio` folder:

 - `script/build_hassio` to build the panel into `/hassio/build-es5`
 - `script/develop` to start the development server so that changes are automatically rebuild

This will require a few changes on the Hass.io supervisor side:
 - Run `hassio/script/build_hassio` to build the frontend
 - It should embed all files in the `hassio/build-es5` folder. All these files should be accessible. This is needed to make code splitting work.

Also adds the `script/develop` script for normal repo.

CC @pvizeli @c727 - I don't have Hass.io running locally. So I know it builds, just don't know if it works 🤔

### CODE REVIEW

**Comment by pvizeli** [comment]
The new files work with old one? So we need no migration path?

**Comment by balloob** [comment]
No they don't. The new files expect the whole dir to be available for the files. But also @c727 already reported another issue that I need to fix.

**Comment by pvizeli** [comment]
Okay, I wait a bit until you give the go

**Comment by balloob** [comment]
The issue has been fixed. 

For building:

```
hassio/script/build_hassio
```

Then make sure we serve the resulting folder `/hassio/build_es5/` from `/api/hassio/app-es5/` from Home Assistant.

**Pull request merged**
