### PR TITLE
Translated developer tools template page

### PR DESCRIPTION
**Pull request by springstan**
Issue affected: #3429

Description:
- added developer tools template page translations to src/translations/en.json
- updated developer-tools-template.js accordingly

Result:
grafik

### CODE REVIEW

**Comment by springstan** [comment]
I was not sure whether or not to translate the code in the template editor.
Would that be a good idea? Since jinja itself is more or less plain English.

**Comment by bramkragten** [comment]
Let's not do that for now, will go wrong in translating probably many times.

**Review by bramkragten — APPROVED** [review]
Great thanks! 🦁

**Comment by springstan** [comment]
Yeah that was also something I was considering, it is probably better to leave it like that, at least for now.

**Pull request merged**
