### PR TITLE
Update Lovelace Thermostat Card to include all supported thermostat m…

### PR DESCRIPTION
**Pull request by callifo**
Add support to Thermostat Card to include other thermostat operation modes,

  on
  fan_only
  eco
  dry
  idle
  electric
  performance
  high_demand
  heat_pump
  gas

### CODE REVIEW

**Comment by homeassistant** [comment]
Hi @callifo, 

It seems you haven't yet signed a CLA. Please do so [here](https://home-assistant.io/developers/cla_sign_start/?pr=home-assistant&#x2F;home-assistant-polymer#2039).

Once you do that we will be able to review and accept this pull request.

Thanks!

**Comment by zsarnett** [comment]
How do these icons look when on the thermostat? Have you tested all of them?

**Comment by iantrich** [comment]
I haven't went through this code, but would think this would look bad if a thermostat supported all of these modes

**Comment by balloob** [comment]
We should only support buttons for official operation modes. This list is not it.

**Comment by balloob** [comment]
Also include a screenshot how this would look.

**Comment by callifo** [comment]
I'll change it to those and get back to you. I took the list above from the Entity definition so assumed that was the official list.

I have tested what mine supports, dry and fan (plus cool/heat), and I can probably use a demo thermostat to mock the rest of them up. I can't see a case where all of these would ever be supported on one card, so the number of elements and width wont be an issue.

**Comment by callifo** [comment]
Here are the mockups. Open to suggestions for colours... the manual, dry and idle would have no strip colour as they dont allow temperature control?

**Modes: Off, Auto, Manual, Eco**
off-auto-manual-eco-off
off-auto-manual-eco-auto_on
off-auto-manual-eco-manual_on
off-auto-manual-eco-eco_on

**Modes: Off, Heat, Cool, Fan, Dry**
off-heat-cool-fan-dry-off
off-heat-cool-fan-dry-fan_on
off-heat-cool-fan-dry-dry_on

**Comment by zsarnett** [comment]
Remove Manual from the PR and I think it will be good to go. We currently have a PR for the Manual Mode addition

**Comment by callifo** [comment]
Ok sweet, will do tonight

**Comment by zsarnett** [comment]
I think that dry does need a color because it will be able to set a temperature. Its just like Cool but reduces the Humidity as well. Maybe Like #efbd07 Yellow or something. Really up to you as long as its not totally random haha

**Review by zsarnett — APPROVED** [review]
Once Color for dry is added. Good to Merge

**Comment by callifo** [comment]
Done, updated to #efbd07

**Comment by zsarnett** [comment]
Looks Good! 👍

**Comment by jncanches** [comment]
This is a great evolution, but for HVAC (MQTT HVAC for example), eco mode cannot be used because it behaves more like an addition to the mode than a full mode itself. It's a full mode for a simple air conditionner that can only make frost. But for a reversible (frost and heat) system, eco means heat less when i'm on heat mode and frost less when i'm in cold mode. 
Do you see what I mean ?
With my MQTT HVAC, I must have a switch below my card to display the eco functionnality. It would be great to have a thermostat card that can turn this "eco mode" into an "eco switch" that can be turned on and off without deselecting the heat or cold mode.
Could be displayed on a second line of icon...

However, great work, as usual !

**Pull request merged**
