### PR TITLE
Align+fix date time entity rows

### PR DESCRIPTION
**Pull request by bramkragten**
## Proposed change

Fix date entity row, show labels

## Type of change

- [ ] Dependency upgrade
- [X] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes #
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [ ] The code change is tested and works locally.
- [ ] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

**Review by piitaya — CHANGES_REQUESTED** [review]
There is a side effect on other entity rows (light, switch) : 

### Before
CleanShot 2023-06-05 at 14 43 41

### Afte
CleanShot 2023-06-05 at 14 44 07

**Comment by piitaya** [comment]
Do we need to change the hui generic layout? 
Now number and cover entity are broken 

CleanShot 2023-06-05 at 15 08 58

CleanShot 2023-06-05 at 15 07 59

**Comment by bramkragten** [comment]
Uuuuuh HOW? They don't hide the name?

I think it makes sense to do this in the generic row, as all controls are right aligned, expect the case I try to fix now.

**Comment by piitaya** [comment]
Adding additional `div` breaks some style for some entity row. Also, some custom cards use `hui-generic-entity-row` (see  https://github.com/search?q=%3Chui-generic-entity-row&type=code&l=JavaScript). We shouldn't do this layout change one day before release. We can do this for the next beta and find another fix for date entity row.

**Comment by piitaya** [comment]
We can just add the needed `div` in `hui-date-time-entity-row` like we did for input number.

```js
<hui-generic-entity-row .hass=${this.hass} .config=${this._config}>
        ${stateObj.attributes.mode === "slider"
          ? html`
              <div class="flex">
                <ha-slider
```

**Comment by bramkragten** [comment]
IMHO `hui-generic-entity-row` should handle this.

**Comment by piitaya** [comment]
> IMHO `hui-generic-entity-row` should handle this.

I agree but we should update all other entity rows that handle it manually. We should let a least 1 beta week to custom card developer to update their own card.

**Review by piitaya — APPROVED** [review]

**Pull request merged**
