### PR TITLE
Improvements for zwave group config

### PR DESCRIPTION
**Pull request by andrey-git**
Improvements for zwave group config
* Show group-selector first
* Show info about the group, including node names and instance numbers - without requiring to select target node.
* Only show 'remove' button if target node is in the list.

Missing features: 
* Allow adding / removing instances to the group.
* Show instance label instead of just instance number.

### CODE REVIEW

**Comment by balloob** [comment]
Do you think that we should migrate this config editor to use the `<ha-config-section>` component like the rest of the config panel uses?

**Comment by andrey-git** [comment]
I have applied ha-config-section for zwave.

**Comment by andrey-git** [comment]
Kind ping :)

**Review by balloob — APPROVED** [review]

**Comment by balloob** [comment]
Sorry, missed this one :(

**Pull request merged**
