### PR TITLE
Automation dialog: add localization, fix CSS

### PR DESCRIPTION
**Pull request by c727**
auto

### CODE REVIEW

**Comment by c727** [comment]
new:
new

**Comment by balloob** [comment]
I would expect slightly more padding at the bottom of the button https://material.io/design/components/dialogs.html#specs

**Comment by c727** [comment]
Added 8px for all:
margin

**Comment by balloob** [comment]
I don't think that's correct, how does the camera and the graph card look ?

**Comment by c727** [comment]
history had double margin and camera still looks like this
cam


ok new version:
nn

**Pull request merged**
