### PR TITLE
Fix activate scene button + allow removing icon

### LINKED ISSUE #7877: Error removing custom icon in scene editor
## Checklist

- [x ] I have updated to the latest available Home Assistant version.
- [ x] I have cleared the cache of my browser.
- [x ] I have tried a different browser to see if it is related to my browser.

## The problem
If you set a custom icon for a scene, using the scene editor it works fine, but if you remove the icon by deleting the text in the field you get the error "Message malformed: Icons should be specified in the form "prefix:name" for dictionary value @ data['states'][0]['icon']".
The only way to remove the icon is to edit scene.yaml

## Expected behavior
Should be able to remove a custom icon in the scene editor.

## Steps to reproduce

1. Set a custom icon for the scene, i.e. hass:home
2. Save the scene
3. Edit the scene again
4. Remove the custom icon by deleting the text in the icon field
5. Save
6. You get the error "Message malformed: Icons should be specified in the form "prefix:name" for dictionary value @ data['states'][0]['icon']"

## Environment
 0.118.4

- Home Assistant release with the issue:
- Last working Home Assistant release (if known):
- Browser and browser version:
- Operating system:

## State of relevant entities

```yaml

```

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

### LINKED ISSUE #8907: Unable to trigger scenes using 'play' icon in Configuration → Scenes
### Checklist

I have updated to the latest available Home Assistant version.
I have cleared the cache of my browser.
I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When trying to trigger a scene from the Configuration section using the 'play' icon, nothing happens in the UI and an error appears in the console. Scenes can still be triggered by automations and pressing the info icon on the right, then "Activate" in the modal that appears, also works successfully.

The last working version that I can recall was prior to the `2021.4` update.

### Describe the behavior you expected

The scene should activate.

### Steps to reproduce the issue

1. Navigate to Configuration → Scenes
2. Click the 'play' icon on the left
3. Open console in dev tools to see the error

### What version of Home Assistant Core has the issue?

core-2021.4.4

### What was the last working version of Home Assistant Core?

core-2021.3.*

### In which browser are you experiencing the issue with?

Microsoft Edge Version 89.0.774.45, Firefox 87.0 (64-bit)

### Which operating system are you using to run this browser?

_No response_

### State of relevant entities

n/a

### Problem-relevant frontend configuration

n/a

### Javascript errors shown in your browser console/inspector

```txt
13:22:39.248 chunk.26875b781ede613ebabf.js:1786 Uncaught (in promise) TypeError: Cannot read property 'entity_id' of undefined
    at HTMLElement.value (chunk.26875b781ede613ebabf.js:1786)
    at HTMLElement.<anonymous> (chunk.26875b781ede613ebabf.js:1685)
    at g.handleEvent (app.ebe75b7a.js:12795)
    at HTMLElement.__boundHandleEvent (app.ebe75b7a.js:12795)
13:22:42.271 chunk.26875b781ede613ebabf.js:1786 Uncaught (in promise) TypeError: Cannot read property 'entity_id' of undefined
    at HTMLElement.value (chunk.26875b781ede613ebabf.js:1786)
    at HTMLElement.<anonymous> (chunk.26875b781ede613ebabf.js:1685)
    at g.handleEvent (app.ebe75b7a.js:12795)
    at HTMLElement.__boundHandleEvent (app.ebe75b7a.js:12795)
13:22:44.080 chunk.26875b781ede613ebabf.js:1786 Uncaught (in promise) TypeError: Cannot read property 'entity_id' of undefined
    at HTMLElement.value (chunk.26875b781ede613ebabf.js:1786)
    at HTMLElement.<anonymous> (chunk.26875b781ede613ebabf.js:1685)
    at g.handleEvent (app.ebe75b7a.js:12795)
    at HTMLElement.__boundHandleEvent (app.ebe75b7a.js:12795)
```

### PR DESCRIPTION
**Pull request by bramkragten**
Fixes #8907
Fixes #7877

## Type of change

- [ ] Dependency upgrade
- [X] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes #
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [ ] The code change is tested and works locally.
- [ ] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

**Review by spacegaier — CHANGES_REQUESTED** [review]
The scene play fix works for me. But the coding for the icon saving does not. It now allows to press the save button when you empty the icon field (the `delete` statement does its job), but the previous icon stays nonetheless (if you go back to the overview it is there and when you go into scene editing again, it is filled again).

Once we have a solution for that, the same fix also needs to be copied to `ha-script-editor` I think.

**Comment by bramkragten** [comment]
Mmm that sounds like a backend issue then...

**Comment by bramkragten** [comment]
https://github.com/home-assistant/core/pull/49248

**Comment by spacegaier** [comment]
> 
> 
> [home-assistant/core#49248](https://github.com/home-assistant/core/pull/49248)

Fixes the issue for scenes, but issue still remains for scripts (I copied over the frontend fix and then the frontend allows saving, but the backend still seems to retain the old value).

**Comment by bramkragten** [comment]
Well this issue / pr is for scenes, scripts can be a separate one :-)

**Review by spacegaier — APPROVED** [review]

**Pull request merged**
