### PR TITLE
[WIP] Display devices present in configured zones

### PR DESCRIPTION
**Pull request by kamaradclimber**
Devices present in a zone are displayed on a circle around the center of the zone.
Circle is taken to be the radius of the zone itself.
We only take care of devices having exact same location as the zone itself since those are the one located explicitely in a zone (ping device tracking for instance).

Reference: https://stackoverflow.com/a/1253545/277527

2017-11-12-184853_909x554_scrot

### CODE REVIEW

**Comment by homeassistant** [comment]
Hi @kamaradclimber, 

It seems you haven't yet signed a CLA. Please do so [here](https://home-assistant.io/developers/cla_sign_start/?pr=home-assistant&#x2F;home-assistant-polymer#621).

Once you do that we will be able to review and accept this pull request.

Thanks!

**Comment by kamaradclimber** [comment]
I'd really like feedback regarding javascript style or code organization. Suggestions regarding testing would also be welcomed!

**Comment by andrey-git** [comment]
I didn't read into the code, so a general remark:
Use ES6 style code (let/const instead of var, arrow functions, etc.)

I don't know if that is feasible, but I think it is best to calculate the smallest circle possible and put icons on it.
I.e. if there is a single icon - put it in the center of the zone. Two icons - touching zone center with their edges. 3 icons - all touching each other.

**Comment by kamaradclimber** [comment]
Thanks @andrey-git for the feedback.

There is a discussion on discord about what this feature should look like. I'm putting the PR to WIP until I have a better implementation.

**Comment by c727** [comment]
Any progress for this PR? :)

**Comment by kamaradclimber** [comment]
@c727 unfortunately feedback got on discord requires changes that are beyond my current skills (and the time necessary for me to level up).

**Pull request closed without merging**
