### PR TITLE
Add rpi_gpio to the list of reloadables

### PR DESCRIPTION
**Pull request by Misiu**
## Proposed change

Backend PR: https://github.com/home-assistant/core/pull/39548
I've also organized imports and filled missing properties attributes (VS Code was showing warnings for them)

## Type of change

- [ ] Dependency upgrade
- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes #
- This PR is related to issue:
- Link to documentation pull request:

## Checklist

- [ ] The code change is tested and works locally.
- [ ] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

**Comment by Misiu** [comment]
Backend PR is merged.

**Comment by bramkragten** [comment]
https://github.com/home-assistant/frontend/pull/6773

**Comment by Misiu** [comment]
@bramkragten awesome! Should I close this one then?

**Comment by bramkragten** [comment]
If it works and is approved yes.

**Pull request closed without merging**
