### PR TITLE
Allow for state_image and camera_image in picture card

### PR DESCRIPTION
**Pull request by iantrich**

### CODE REVIEW

**Comment by balloob** [comment]
I'm not deep enough into the code right now to make a good decision. 

We have these in what cards already?

And which was the picture card again ? I can't find it in the demo.

**Comment by iantrich** [comment]
@balloob hui-picture-elements-card, hui-picture-glance-card and hui-picture-entity-card all support camera and state images. hui-picture-card is the odd one out, currently.

**Comment by iantrich** [comment]
I would like to follow this up with addressing the gaps mentioned here for our picture-cards https://github.com/home-assistant/ui-schema/issues/189 from @thomasloven

**Comment by balloob** [comment]
I think that picture card should not get these options because then it would be literally the same as picture-entity ? And then we might as well just delete the card instead.

**Comment by iantrich** [comment]
If we're considering that, I would propose we retire `picture-entity` and move all logic to `picture` as it is more robust and make `entity` optional.

**Comment by balloob** [comment]
What do you mean with more robust? 

To retire picture-entity, we would have to add things like the name/state overlay to picture.

I think that we should instead just leave it as is, and call it a day?

**Comment by iantrich** [comment]
I meant we would rename `picture-entity` to `picture` and make `entity` optional. Then all the functionality of the two would be in `picture`, I believe, unless I"m missing something obvious.

**Comment by balloob** [comment]
How would a picture-entity look with an optional entity? I wonder if that won't just make the config overly complex.

**Comment by balloob** [comment]
Remember we need to build UIs for this.

**Comment by balloob** [comment]
I suggest we close this PR.

If we would merge the cards, it would be so much different of this card anyway.

**Pull request closed without merging**
