### PR TITLE
Change minimum width to show numbers in EntityRow to 300px

### PR DESCRIPTION
**Pull request by andrist**
## Proposed change

Remove hard-coded check on column width of 350px to hide certain elements.

DISCLAIMER: I'm new to hass.io and am not aware of the all the implications this change will have. Therefore I'm filing the PR to get such input -> please advise.

At the moment, the only effect of this code I'm aware of is the buggy behavior described below.

## Additional information

- This PR is related to the discussion at: [https://community.home-assistant.io/t/input-number-slider-not-showing-number/118241/12](https://community.home-assistant.io/t/input-number-slider-not-showing-number/118241/12) (numbers on sliders being hidden depending on browser width):

Summary: Depending on the screen or browser width during initial load, the values next to sliders are shown or hidden.
- This behavior toggles multiple times accross different browser widths (because the arrangement changes from 2 to 3 columns and the check is done on column width).
- It kicks in at different widths than column arrangement changes (which feel arbitrary)
- As far as I can tell, the space where the number should be is still there, so nothing is gained by hiding the number.
- The hiding persists, even if the browser width (or mobile device orientation) is changed subsequently.
- There is no way to disable this random hiding mechanism

The proposed change removes the check during load, which effectively always renders the numbers. This is the behavior I personally want (as well as others in the discussion linked above), but might not be the best solution for everyone (or have other side effects?).

Other solutions could include:
- providing a configuration option to disable this hiding mechanism (easy workaround for users)
- changing the check to coincide with the width at which column layout changes (would feel less random)
- adapting the hiding mechanism when the browser width changes (would feel less random)

## Checklist

- [ ] The code change is tested.
- [X] The code change works locally.
- [X] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

### CODE REVIEW

**Comment by homeassistant** [comment]
Hi @andrist, 

It seems you haven't yet signed a CLA. Please do so [here](https://home-assistant.io/developers/cla_sign_start/?pr=home-assistant&#x2F;frontend#8050).

Once you do that we will be able to review and accept this pull request.

Thanks!

**Comment by andrist** [comment]
Done, thanks.

**Comment by emufan** [comment]
I socond this. Would be great to have this merged. Did this locally for now as well. I see no benefit from a UI perspective for this 350 pixel check. Esp. as there is enough space below 350 px as well. If this is really to be declined to merge (hopefully not), perhaps a pixel customizing yaml attribute could be introduced (with 350 px default).

**Comment by andrist** [comment]
I think this might also fix issue #2905, which looks like it's dealing with the same behavior.

**Comment by bramkragten** [comment]
It would at least need a resize observer it needs to be hidden.

**Comment by andrist** [comment]
thanks @bramkragten . Is there anything I need to do for this PR to move forward?

**Comment by emufan** [comment]
> It would at least need a resize observer if it needs to be hidden.

Such a resize observer is not there at the moment either. If you open below 350 and then resize above 350 it is still not shown. And the other way if Ou open above 350 it is still shown below 350. 

There is enough space below 350 as well, as far as I see, all the time. Therefore I second to remove this 350 check completely. The state is to important to not show ist.

**Comment by andrist** [comment]
@bramkragten . Is there anything I need to do for this PR to move forward?

**Comment by bramkragten** [comment]
Can you please add an example to the gallery and show the before/after in multiple screen sizes here?

**Comment by emufan** [comment]
> Can you please add an example to the gallery and show the before/after in multiple screen sizes here?

Start with 350: no state
image

resize to above 350, e.g. 550: still no state:
image

start with 550: state
image

resize to 350: still state:
image

resize even smaller: still state and still enough space, e.g. 275:
image

My suggestion: Either
- remove this hide completely
- introduce a yaml-paramter where the user can set a wanted value, e.g. 250, with default value as is 350
- introduce a "hide_state: false - Always show the state, even when the card is too narrow" paramater as done in Thomas' card: https://github.com/thomasloven/lovelace-slider-entity-ro

**Comment by bramkragten** [comment]
I meant I wanted to see how your new proposed code would look like on the different screen sizes.

As you show in your 275px screenshot, the slider is almost not useable. That is why this code is there, that we don't update when you make the screen bigger is a bug, and could be fixed with a `resizeObserver`.

**Comment by andrist** [comment]
it would always look like images 4-6.

- Can you point me to an example of resizeObserver in use; i'll try to implement it.
- "just resize to see the missing number" isn't really a  solution on mobile; I still think an option to turn off this behavior would be preferable

**Comment by bramkragten** [comment]
You can click it to get the number? If there is no space, we can't show both. I'm also ok with showing an input box instead of the slider if we don't have space.

For examples for resizeObservers, we have a lot: https://github.com/home-assistant/frontend/search?q=resizeobserver

Check the media player row or weather card for example.

**Comment by sVnsation** [comment]
+1 on this. resizeObserver won't help on the Apps, there is a fixed size.

**Comment by emufan** [comment]
But why not introducing the "hide_state: false - Always show the state, even when the card is too narrow" paramater as done in Thomas' card: https://github.com/thomasloven/lovelace-slider-entity-ro? Or introduce a yaml-paramter where the user can set a wanted value, e.g. 250, with default value as is 350?

A lot of people have something below the current 350, where both (slider and number) is possbile, but because of the hardcoded 350, the value is not shown.

> As you show in your 275px screenshot, the slider is (almost) not useable.

Yes and no. Here the left margin from the value is too big, but anyway (in my case) better a smaler slider, than no value. I completely understand, that there are other needs, but every need could be solved, with either the pixel-marameter or the "always show" parameter.

**Comment by bramkragten** [comment]
We will not add options for this, wouldn't an input box be a solution when there is no room for a slider?

**Comment by emufan** [comment]
> We will not add options for this,

Any reason for this?

**Comment by bramkragten** [comment]
> > We will not add options for this,
> 
> Any reason for this? With such oiptions, everyone can pick, what he want and exeryone, who will not set an option has the current state?

Every option we add, adds complexity and increases the maintenance burden. That's why we try to have as few options as possible.

**Comment by emufan** [comment]
> > > We will not add options for this,
> > 
> > 
> > Any reason for this? With such oiptions, everyone can pick, what he want and exeryone, who will not set an option has the current state?
> 
> Every option we add, adds complexity and increases the maintenance burden. That's why we try to have as few options as possible.

But asd much as needed would be great. ;-)

Anyway: My ultimate proposal: Set the filter value to 300 instead of 350. he problem with 350 is, that it is most of the time to big and the state

**Comment by bramkragten** [comment]
Sounds good.

**Review by emufan — CHANGES_REQUESTED** [review]
@andrist Can you add the lines again and only change the 350 to 300 (compare the discussion in PR)?

**Comment by emufan** [comment]
@bramkragten What is needed, that someone approves/merges the discussed and afterwards created and linked PR from @sVnsation above?

**Comment by bramkragten** [comment]
Would need screenshots from multiple situations, long titles, short titles, wide and small screen. But ideally also the resize observer discussed.

**Comment by mikemcduffie** [comment]
Not sure if this related, but I came chasing an issue where value/unit labels were not shown on slider entities. In my case some sliders show value/units and some don't even on the same card and where there is no significant difference in the input_numbers. 

Attached is an example. Units for all sliders is "min" and ranges are similar or identical but label is not shown despite card width being wide enough. All number input sliders are 5-20 or 15-20 with step 5, so long sliders are not necessary. One of the sliders is the same range/step as the manual timer input (which reliably displays label) so I don't think number of steps/current value digits is the issue.

Screenshot is from Electron web app on MacOS, but I get the same results on latest versions of iOS and Mac Companion apps. Currently on Hass Version core-2021.4.6 on pi4, but I've had this issue for a long time. 

I was specifically searching for a "hide_state:" field as it should solve my issue. 

Screen Shot 2021-05-20 at 10 13 14 AM

**Comment by simbesh** [comment]
7 months and this simple label bug is still unresolved 🙄

for anyone else looking for a fix use this custom card:
https://github.com/thomasloven/lovelace-slider-entity-row

**Comment by andrist** [comment]
Thanks Thomas

Agreed -- It's a weird thing to not fix. Beyond providing a PR, there's not
much I can do... no signs of interest in merging it. Will switch to the
custom card.

Cheers,

Ruben

**Comment by bramkragten** [comment]
There is a post above that explains what needs to be done to get this merged...

**Comment by andrist** [comment]
don., @bramkragten please let me know if this works for you and start the workflows when you get a chance.

**Comment by bramkragten** [comment]
#8310

**Pull request closed without merging**
