### PR TITLE
Only show header toggle for entities card if title

### PR DESCRIPTION
**Pull request by balloob**
## Proposed change

We should not show a header toggle as default config if no title is configured.

Before: 

image

After:

image

## Type of change

- [ ] Dependency upgrade
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes #
- This PR is related to issue:
- Link to documentation pull request:

## Checklist

- [ ] The code change is tested and works locally.
- [ ] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

**Review by zsarnett — COMMENTED** [review]
We should make this better in the editor as well. Its weird to toggle options and nothing to happen on the card

**Review by bramkragten — APPROVED** [review]

**Comment by zsarnett** [comment]
I am not sure I follow. Current the editor needs updated because I can toggle the show Header Toggle and it doesn't show. And there is no way of knowing why unless I read docs. Toggle the dialog and nothing happening is weird

If I don't have a title and then I toggle the show header toggle and it doesn't show then that is also weird

**Comment by bramkragten** [comment]
Thats not what this code does. Only when there is not show toggle config, it will try to check if we should or should not show the toggle.

**Comment by balloob** [comment]
The default if the setting is `undefined` is to derive if we should toggle it from the entities in the card. That default will now only consider toggleable entities if there is a header shown (because it has a title)

**Pull request merged**
