### PR TITLE
Add password confirmation to snapshot creation

### PR DESCRIPTION
**Pull request by ludeeus**
## Proposed change

Add a field to confirm the password when creating a snapshot
image

## Type of change

- [ ] Dependency upgrade
- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes #
- This PR is related to issue or discussion: https://community.home-assistant.io/t/snapshot-add-password-confirmation-for-saving-protected-snapshots/252698
- Link to documentation pull request:

## Checklist

- [x] The code change is tested and works locally.
- [ ] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

**Comment by bramkragten** [comment]
Can we give the `Password protection` checkbox a little more margin at the top, and align it with the radio controls above?

**Review by bramkragten — APPROVED** [review]

**Comment by ludeeus** [comment]
Will that not look strange when doing partial?
image

**Comment by bramkragten** [comment]
No? That should also still align

**Comment by ludeeus** [comment]
If that's moved it looks like it's part of the add-ons instead of a new section

**Review by ludeeus — COMMENTED** [review]
:heavy_check_mark:

**Pull request merged**
