### PR TITLE
Move light effects above color picker

### PR DESCRIPTION
**Pull request by spacegaier**
## Proposed change

image

## Type of change

- [ ] Dependency upgrade
- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [X] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes https://github.com/home-assistant/frontend/discussions/7379
- This PR is related to issue or discussion: https://github.com/home-assistant/frontend/issues/7736
- Link to documentation pull request:

## Checklist

- [X] The code change is tested and works locally.
- [X] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

**Comment by bramkragten** [comment]
I don't think we should use a less-used feature up the UI for these reasons

**Comment by spacegaier** [comment]
> 
> 
> I don't think we should move a less-used feature up in the UI for these reasons

I do get your point. In the end it's matter of how we weigh the pro/cons for the move:

Pro:
- Better discoverability of the effects option (might be outside the screen on smaller devices)
- Better usability on smaller screens since now the effects dropdown has enough space to show more than only one or two rows before hitting the bottom screen border, see screenshot in linked discussion (the color palette doesn't care about its position in that regard)

Cons:
- Lesser used element (probably?) now further up (but at least does not hurt the discoverability of the color palette)

If a light does not have defined effects, then of course the dropdown will not be rendered at all.

**Comment by SNoof85** [comment]
If I can add a pro : 
When the list of effects is so big (like for WLED lights) the effects dropdown goes too far outside the view on mobile. The you can see only 4 lines of effects. With the effect select up to the color picker you'll be able to see more effects !

**Comment by bramkragten** [comment]
Can we look into a different dropdown menu instead? Like `mwc-select`?

**Comment by spacegaier** [comment]
> 
> 
> Can we look into a different dropdown menu instead? Like `mwc-select`?

For which goal? How does that impact the position of the dropdown in the dialog?

**Comment by bramkragten** [comment]
My understanding is that the problem is that the current dropdown always goes down, even if there is no room down and it should actually go up?

I think they solved that in `mwc-select`

**Comment by spacegaier** [comment]
That would solve part of the issue, but not the "detectability" / discovery in the UI overall.

**Comment by bramkragten** [comment]
We moved most controls below the color picker now, like white value, etc. It would be weird to move effects up now, as I still think it is way less used...

**Pull request closed without merging**
