### PR TITLE
Include backend translations in Lokalise download

### PR DESCRIPTION
**Pull request by steverep**
## Proposed change

Modifies the script to download translations from Lokalise to also include the backend project.  This way the nightly artifact contains all current translations.  I also modified things to download in the desired directories rather than requiring a copy/delete afterwards.

This change is needed by #13724 

## Type of change

- [ ] Dependency upgrade
- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [x] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes #
- This PR is related to issue or discussion: #13381 
- Link to documentation pull request:

## Checklist

- [x] The code change is tested and works locally.
- [x] There is no commented out code in this PR.
- [x] Tests have been added to verify that the new code works.

### CODE REVIEW

**Comment by steverep** [comment]
Note the [current test run](https://github.com/home-assistant/frontend/actions/runs/3177619972/jobs/5178262546) fails because it finds HTML in some of the backend translations 😞

**Comment by bramkragten** [comment]
The reason we did the check first and then move them, is that we would never have wrong/dirty translations in the product. Now if the checks fail, we have already overwritten the old translations with new wrong ones?

It doesn't matter much for a build, as that will get discarded anyway, but does when doing it locally for example.

**Comment by bramkragten** [comment]
> How do you want to handle the failed checks on the backend translations? They are stemming from strings that allow markdown. Should we just check the frontend only for now?

Seems like it isn't even real html, ideally we would fix them, in this case it needs to be escaped, not sure how much we will find though 😨

**Comment by steverep** [comment]
One of the 3 errors in the log was not real HTML, but the other two I think had converted \*\* to `<b>`.

**Comment by steverep** [comment]
I did a search in the core repository and here are the stats:
- The `owntracks` integration is the only one with a problem stemming from the original `strings.json`.  It needs escaping or reformatting as you said.
- 56 errors show up in the translations to various other languages, where the translator either converted markdown to HTML, screwed up escaping, etc.

**Comment by steverep** [comment]
I don't think it makes sense to hold up this PR to fix those 57 issues.  I've removed the check on the backend translations for now, which is essentially the status quo, and I'll open an issue on core.

But, the [new test run](https://github.com/home-assistant/frontend/actions/runs/3192479638/jobs/5210002726) is now failing complaining about bad key references which I don't understand because those references don't exist in the current `en.json`.  Is this some sort of issue where there's a big delay on the Lokalise side?

**Review by bramkragten — APPROVED** [review]

**Pull request merged**
