### PR TITLE
Device attributes

### PR DESCRIPTION
**Pull request by elupus**
Display device attributes for water_heater and climate

### CODE REVIEW

**Comment by balloob** [comment]
What device attributes are going to be shown ? 

Generally the more info should already contain all the things that climate/water heater represents

**Comment by elupus** [comment]
Integrations present more things not supported by the default model. It could be for a water heater multiple temperature sensors, for climate why the auto state is currently heating (some type of external override like floor heating mode). We have this for sensors already. So imho it should be same for the other entities.

**Comment by balloob** [comment]
Sensors are special in that they are currently being abused by most integrations. There are really two groups: sensors that have a unit of measurement, and all others that just dump random text/data in the entity. The latter shows the attributes, but that's because we can't standardize it.

**Comment by elupus** [comment]
Lights have them too.

**Comment by iantrich** [comment]
I think your specific scenarios should be addressed in the more-info rather than just dumping everything on cards that already have a lot going on in them.

**Comment by elupus** [comment]
More info?

**Comment by elupus** [comment]
What I meant is. This is on what I consider the more info card/dialog.

**Comment by iantrich** [comment]
What I'm getting at is that these have known attributes so doing the dump just isn't as clean as integrating them nicely into the dialog. For sensors it makes sense as you never know what attributes will be there.

**Comment by elupus** [comment]
Same goes here thou. A climate entity for example represent a quite complex system. Much more so than say a temperature sensor. So I'd say it makes more sense on climate to be able display additional metadata.

IMHO it should at least be consistent

**Comment by iantrich** [comment]
I suppose that could be true. I'm fine with it after a rebase; I think in a future PR I would like to have attributes in a collapsible section inside the dialog to make it a little cleaner.

**Comment by bramkragten** [comment]
This PR has gone stale so closing it.

**Pull request closed without merging**
