### PR TITLE
feat: add ipv6 addr gen mode selection

### LINKED ISSUE #1687: IPv6 Addr-gen-mode should be EUI64 and not stable-privacy
### Describe the issue you are experiencing

Home-Assistant IMHO is a server system and server system shouldn't change their IP address from time to time.

The default settings for NetworkManager under Home Assistant OS is `ipv6.addr-gen-mode=stable-privacy`. This settings helps to hide the mac-adress of the user. But it also prevents to configure the router firewall to access Home-Assistant over IPv6 from the Internet. 

To full support IPv6 remote access from the Internet a stable IPv6 address is needed, that doesn't change unpredictable. 

I updated the Network-Manager configuration with `ha login` and changed `addr-gen-mode` to `eui64`. With this change the public IPv6 address uses the same suffix as the link local and it's possible to configure the router firewall.

You can validate this in your router. Mine shows 10 different IPv6 addresses after some month.

### What operating system image do you use?

generic-x86-64 (Generic UEFI capable x86-64 systems)

### What version of Home Assistant Operating System is installed?

7

### Did you upgrade the Operating System.

No

### Steps to reproduce the issue

1. Setup IPv6
2. Check the Suffix of the registered IP-Addresses

They will differ between public and link-local addresses and their lifetime will be limited.

### Anything in the Supervisor logs that might be useful for us?

```txt
Not needed
```

### Anything in the Host logs that might be useful for us?

```txt
Not needed
```

### System Health information

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by novag**
## Proposed change

This change introduces support for selecting the IPv6 address generation mode of NetworkManager when the configuration method is set to "auto". By default the "addr-gen-mode" is set to "stable-privacy" which is not suitable for home users with dynamic IPv6 prefixes. In "stable-privacy" mode the interface ID is only guaranteed to be stable per prefix/subnet as per [RFC7217](https://datatracker.ietf.org/doc/html/rfc7217).

## Type of change

- [ ] Dependency upgrade
- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

image

- This PR fixes or closes issue: fixes https://github.com/home-assistant/operating-system/issues/1687
- This PR is related to issue or discussion: https://github.com/home-assistant/operating-system/issues/1687
- Link to documentation pull request:
- Link to supervisor pull request: https://github.com/home-assistant/supervisor/pull/4510

## Checklist

- [x] The code change is tested and works locally.
- [x] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

**Comment by piitaya** [comment]
Can we have labels "Method" and "Address generation mode" for each group of radio buttons?

**Comment by mdegat01** [comment]
This should default to `Stable Privacy`, it shouldn't ever show up without an option selected like the screenshot above.

Is there some way to make this clearly an advanced option? To my understanding a vast majority of users will not have to change this. And its also extremely technical, a tiny percentage of users will know what that means. This should be one of those options like "if you don't know what this is and you haven't been specifically directed to change it by something, don't change this."

**Comment by novag** [comment]
> This should default to `Stable Privacy`, it shouldn't ever show up without an option selected like the screenshot above.#

That was a mistake. When I made the screenshot with the new section title, I was not running the supervisor changes, which is why it was blank. When running the correct supervisor version it cannot be blank.

> Is there some way to make this clearly an advanced option? To my understanding a vast majority of users will not have to change this. And its also extremely technical, a tiny percentage of users will know what that means. This should be one of those options like "if you don't know what this is and you haven't been specifically directed to change it by something or someone, don't change this."
> 
> Honestly I'm tempted to say we should leave it as a CLI only option for advanced users. If we think it needs to be in the UI I guess that's ok but either their needs to be more info for the 99% of users that will not have a clue what that's saying or it needs to be hidden more and actively discourage changing it.

I am still convinced that every user behind a DS-Lite connection ([RFC 6333](https://datatracker.ietf.org/doc/html/rfc6333), at least in Germany this is the vast majority of home internet connections) who wants to forward ports to Home Assistant has to make this change.

As already mentioned, in "stable-privacy" mode the interface ID is only guaranteed to be stable per prefix/subnet as per [RFC7217](https://datatracker.ietf.org/doc/html/rfc7217). This is by design, and why it is called "stable-privacy". If it were stable accross prefixes/subents, it would not be much better than using the interface EUI. The UUID only identifies the interface and is part of the resulting random stable identifier:
> RID = F(Prefix, Net_Iface, Network_ID, DAD_Counter, secret_key)

**Comment by ianmtaylor1** [comment]
Thank you all for your work on this. I just want to add support for this change from a user.

> I am still convinced that every user behind a DS-Lite connection with dynamic prefixes ([RFC 6333](https://datatracker.ietf.org/doc/html/rfc6333), at least in Germany this is the vast majority of home internet connections) who wants to forward ports to Home Assistant has to make this change.

Dynamic prefixes are also common in the USA. My past two ISPs have used 6rd ([RFC5969](https://datatracker.ietf.org/doc/html/rfc5969)) where the prefix will change every time the external IPv4 address changes, or DHCPv6-PD, where the assigned prefix changes less often but is also not guaranteed to stay the same. Static host parts on servers are necessary to allow external access in the router firewall when the assigned prefix is changing.

**Comment by bramkragten** [comment]
Supervisor PR was closed.

**Comment by Jatoxo** [comment]
Why was this closed? 
> I am still convinced that every user behind a DS-Lite connection with dynamic prefixes ([RFC 6333](https://datatracker.ietf.org/doc/html/rfc6333), at least in Germany this is the vast majority of home internet connections) who wants to forward ports to Home Assistant has to make this change.
This is exactly my setup. I still don't know how to change the adress generation through CLI. These options were the first place I looked. 

The folders described in https://github.com/home-assistant/operating-system/blob/dev/Documentation/configuration.md don't exist for me.

**Comment by ianmtaylor1** [comment]
@Jatoxo It looks like there were unresolved issues in the code that would have implemented this, and the issue was automatically closed after some time.

In the mean time, here is how I was able to do this on my HAOS. (Please note, I am just a *user*, unaffiliated with Home Assistant, and while this worked for me it is not official and has no guarantee of working for you.)

1. Get terminal access to the base operating system. You can do this either 
    a. with a physically attached monitor and keyboard, typing 'login' at the default home assistant console.
    b. with the [advanced SSH and terminal](https://github.com/hassio-addons/addon-ssh) community add-on.
2. Run `nmcli con show` to list Network Manager connections, noting the name of the one that is connected. Mine was called "Supervisor end0".
3. Run `nmcli con mod '<your connection name>' ipv6.addr-gen-mode eui64`. The single quotes are required. In my case I literally ran `nmcli con mod 'Supervisor end0' ipv6.addr-gen-mode eui64`.
4. Run `nmcli con down '<your connection name>'` and `nmcli con up '<your connection name>'` to restart the connection with the new address. This will disconnect your HAOS server from the network, so don't do this over SSH or the web terminal :-). Rebooting the server accomplishes the same thing.

So far for me this configuration has persisted through reboots and upgrades, but I don't know if it will continue to in the future.

As a bonus, you can enable a [IPv6 address token](https://man7.org/linux/man-pages/man8/ip-token.8.html) by also running `nmcli con mod '<your connection name>' ipv6.token ::123`, replacing `::123` with your desired address token.

**Comment by Jatoxo** [comment]
> @Jatoxo It looks like there were unresolved issues in the code that would have implemented this, and the issue was automatically closed after some time.
> 
> In the mean time, here is how I was able to do this on my HAOS. (Please note, I am just a _user_, unaffiliated with Home Assistant, and while this worked for me it is not official and has no guarantee of working for you.)
> 
> 1. Get terminal access to the base operating system. You can do this either
>    a. with a physically attached monitor and keyboard, typing 'login' at the default home assistant console.
>    b. with the [advanced SSH and terminal](https://github.com/hassio-addons/addon-ssh) community add-on.
> 2. Run `nmcli con show` to list Network Manager connections, noting the name of the one that is connected. Mine was called "Supervisor end0".
> 3. Run `nmcli con mod '<your connection name>' ipv6.addr-gen-mode eui64`. The single quotes are required. In my case I literally ran `nmcli con mod 'Supervisor end0' ipv6.addr-gen-mode eui64`.
> 4. Run `nmcli con down '<your connection name>'` and `nmcli con up '<your connection name>'` to restart the connection with the new address. This will disconnect your HAOS server from the network, so don't do this over SSH or the web terminal :-). Rebooting the server accomplishes the same thing.
> 
> So far for me this configuration has persisted through reboots and upgrades, but I don't know if it will continue to in the future.
> 
> As a bonus, you can enable a [IPv6 address token](https://man7.org/linux/man-pages/man8/ip-token.8.html) by also running `nmcli con mod '<your connection name>' ipv6.token ::123`, replacing `::123` with your desired address token.

I appreciate the guide, however "nmcli" isn't recognized (command not found). Is the network manager not used anymore?

**Comment by ianmtaylor1** [comment]
How are you accessing the terminal? If physical keyboard/monitor, make sure to exit the `ha` prompt by typing "login". If through add-on, note that the official Home Assistant Terminal&SSH add-on doesn't provide access to Network Manager commands, I needed to use the [Advanced SSH & Web Terminal](https://github.com/hassio-addons/addon-ssh) community add-on to be able to use nmcli.

**Comment by dfriday** [comment]
> @Jatoxo It looks like there were unresolved issues in the code that would have implemented this, and the issue was automatically closed after some time.
> 
> In the mean time, here is how I was able to do this on my HAOS. (Please note, I am just a _user_, unaffiliated with Home Assistant, and while this worked for me it is not official and has no guarantee of working for you.)
> 
> 1. Get terminal access to the base operating system. You can do this either
>    a. with a physically attached monitor and keyboard, typing 'login' at the default home assistant console.
>    b. with the [advanced SSH and terminal](https://github.com/hassio-addons/addon-ssh) community add-on.
> 2. Run `nmcli con show` to list Network Manager connections, noting the name of the one that is connected. Mine was called "Supervisor end0".
> 3. Run `nmcli con mod '<your connection name>' ipv6.addr-gen-mode eui64`. The single quotes are required. In my case I literally ran `nmcli con mod 'Supervisor end0' ipv6.addr-gen-mode eui64`.
> 4. Run `nmcli con down '<your connection name>'` and `nmcli con up '<your connection name>'` to restart the connection with the new address. This will disconnect your HAOS server from the network, so don't do this over SSH or the web terminal :-). Rebooting the server accomplishes the same thing.
> 
> So far for me this configuration has persisted through reboots and upgrades, but I don't know if it will continue to in the future.
> 
> As a bonus, you can enable a [IPv6 address token](https://man7.org/linux/man-pages/man8/ip-token.8.html) by also running `nmcli con mod '<your connection name>' ipv6.token ::123`, replacing `::123` with your desired address token.

Sadly this does no longer work. `nmcli con show` returns `Warning: nmcli (1.46.0) and NetworkManager (1.44.2) versions don't match. ` and `nmcli con mod 'Supervisor end0' ipv6.addr-gen-mode eui64` fails.

Downgrading networkmanager-cli  in [advanced SSH and terminal](https://github.com/hassio-addons/addon-ssh) to 1.44.4-r0 by 
1. unistalling the current version `apk del networkmanager` and
2.  installing an older version `apk add  --no-cache --repository http://dl-cdn.alpinelinux.org/alpine/v3.19/community/ networkmanager-cli=1.44.4-r0` 

worked for me.

**Pull request closed without merging**
