### PR TITLE
Add support for country based languages

### PR DESCRIPTION
**Pull request by ljmerza**
In reference to #2676

### CODE REVIEW

**Comment by ljmerza** [comment]
Others had similar issues of home assistant not seeing the country based languages so it set the wrong language.  I'm not sure what their configuration was but this is what chrome set by default. Seems to effect a small number of users but they shouldn't really have to go through the trouble of figuring this out like I did.

**Comment by c727** [comment]
well and now you kill the logic for users with a "correct" order x)

**Comment by c727** [comment]
it will break if the first code includes a script tag like `zh-hans-tw` or if you have somethink like `zh-MY, zh-CN, ...` as Simplified Chinese user. (These examples are not Chinese exclusiv)

**Comment by balloob** [comment]
@c727 has a good point. 

Before we can change this, please link to an authoritative resource that specifies how browser languages should be mapped to a translation backend. Can we map en-US to en? Or should we keep the mappings 1-on-1? Or maybe something completely different.

Just because some users are impacted now, doesn't mean that your change would impact an even bigger amount of users.

**Comment by ljmerza** [comment]
Reading through the [w3 notes](https://www.w3.org/International/questions/qa-choosing-language-tags) on this issue, I see it says 

> golden rule is to keep your language tag as short as possible. Only add further subtags to your language tag if they are needed to distinguish the language from something else in the context where your content is used.

Following this, I'll throw in  the towel on this. Thanks for the discussion :+1:

**Comment by c727** [comment]
My Chinese examples are bad as they fail in the `if` all in all. So imo it was a bad desicion to use script tags for Chinese in HA... Also the browsers seem to prefer language tag and optional country tag as code.

In my local takeaway are working only foreigners from asien countries. They all speak the same language but some of them are from a different country with a different script. So they can talk to each other in the same language but for notes they use German cause they can't read the others script. So it's sometimes important to use correct country tags for an language.

The language detection was implemented before HA got multi user support. Maybe now it's better if the user can select a language on first login and we store this in backend (maybe suggest some languages based on detected language and country tags)

**Comment by ljmerza** [comment]
Yeah that would make sense to have language selection on login. On my first time using home assistant I had real trouble finding where the language settings were without being able to read anything,

**Pull request closed without merging**
