### PR TITLE
Fix line charts not being displayed

### PR DESCRIPTION
**Pull request by bdraco**
## Proposed change

```
compute_rtl.ts?286b:5 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'language')
    at computeRTL (compute_rtl.ts?286b:5:1)
    at HaChartBase.render (ha-chart-base.ts?c6b5:137:1)
    at HaChartBase.update (lit-element.ts?0c87:132:1)
    at HaChartBase.performUpdate (reactive-element.ts?9d98:1216:1)
    at HaChartBase.scheduleUpdate (reactive-element.ts?9d98:1149:1)
    at HaChartBase.__enqueueUpdate (reactive-element.ts?9d98:1121:1)
```

## Type of change

- [ ] Dependency upgrade
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes #
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [x] The code change is tested and works locally.
- [ ] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

**Comment by karwosts** [comment]
Can you check that this is not just a caching issue? I saw this once, but it went away after clearing the caches. Can we really render without a hass object?

In my dev tree I don't see any problems loading any more-info charts.

**Comment by bdraco** [comment]
> Can you check that this is not just a caching issue? I saw this once, but it went away after clearing the caches. Can we really render without a hass object? Prior to this change hass was not passed to this object, but now it is, so I wonder if a cached version of the file is not providing it.
> 
> In my dev tree I don't see any problems loading any more-info charts.

Not a cache issue.  I can replicate it in dev mode as well, thats how I got the trace

**Comment by karwosts** [comment]
> > Can you check that this is not just a caching issue? I saw this once, but it went away after clearing the caches. Can we really render without a hass object? Prior to this change hass was not passed to this object, but now it is, so I wonder if a cached version of the file is not providing it.
> > In my dev tree I don't see any problems loading any more-info charts.
> 
> Not a cache issue. I can replicate it in dev mode as well, thats how I got the trace

Ok. I still don't see how this could occur, and I don't see it in my env, but I guess the change is safe, so that's fine.

**Comment by bdraco** [comment]
Its only the more-info line charts without logbook and no statistics AFAICT

**Comment by bdraco** [comment]
Looks like its also the statistics graph cards

**Comment by bdraco** [comment]
This also fixes the graphs on the energy panel

**Review by steverep — CHANGES_REQUESTED** [review]
We definitely shouldn't have style be controlled by the existence of `hass`.  The problem is that #14919 introduced the `hass` property, but did not make sure it was then defined for all instances of `<ha-chart-base>`.

If the padding is appropriate for all occurrences, then just search the code for `"<ha-chart-base"` and pass the property where it's missing.

If not, then #14919  should be refactored.

**Comment by bdraco** [comment]
> If the padding is appropriate for all occurrences, then just search the code for `"<ha-chart-base"` and pass the property where it's missing.

Unfortunately I can't answer that as I don't know if it is.  I'm going to close this PR as I don't have enough historical knowledge to know if thats a safe change or not.

**Comment by steverep** [comment]
I would think it's fine because the `paddingYAxis` property is defaulted to 0, which is the default if the padding wasn't provided in CSS.  @bramkragten can better confirm on the other instances.

For reference, here are the missing instances:

8 results - 7 files

src/components/chart/statistics-chart.ts:
  135:       <ha-chart-base

src/panels/config/hardware/ha-config-hardware.ts:
  412:                     <ha-chart-base
  443:                     <ha-chart-base

src/panels/lovelace/cards/energy/hui-energy-devices-graph-card.ts:
  89:           <ha-chart-base

src/panels/lovelace/cards/energy/hui-energy-gas-graph-card.ts:
  108:           <ha-chart-base

src/panels/lovelace/cards/energy/hui-energy-solar-graph-card.ts:
  107:           <ha-chart-base

src/panels/lovelace/cards/energy/hui-energy-usage-graph-card.ts:
  101:           <ha-chart-base

src/panels/lovelace/cards/energy/hui-energy-water-graph-card.ts:
  108:           <ha-chart-base

**Comment by karwosts** [comment]
Yeah I guess I agree this change would have been fine. `paddingYAxis` was added in the recent PR, and only set by `state-history-chart-line` and `state-history-chart-timeline`, so for other classes that also instance ha-chart-base, it would always be 0, in which case whether or not there is a hass object, padding left and padding right would both always be 0 regardless. 

So whether the change from this PR is submitted, or whether hass object is added to all those other instances, I think the end result would be the same?

**Comment by steverep** [comment]
Correct, but that still leaves `ha-chart-base` with an error-prone dependency IMO.  The `hass` property was typed with a non-null assertion which is what led to the error.

**Comment by steverep** [comment]
@bramkragten this PR asks larger questions about passing the `hass` object around which I cannot answer.  I'm re-opening until you can chime in.  There is quite a mix of preference in the code:

- **Non-Null (`hass!:`):** 491 occurrences in the code
- **Possibly undefined (`hass?:`):** 144 occurrences in the code

Clearly there's a tendency to make sure it's always defined when it's a property, but there's no test for it.

**Comment by piitaya** [comment]
I opened a PR to add missing `hass` for chart to fix the bug during the beta : https://github.com/home-assistant/frontend/pull/15218
I agree with steve, we must define a rules for `hass` injection in components.

I wonder if we can use contexts to get `hass` everywhere we want.

**Comment by steverep** [comment]
Could it still function as a reactive property that way?  Closing and maybe we can open an issue to discuss there.

**Pull request closed without merging**
