### PR TITLE
Fix volume slider of assumed_state media player in entity row

### PR DESCRIPTION
**Pull request by Drafteed**
## Proposed change
This small PR fixes cramped volume slider of `assumed_state` media player in entity row by hiding the stop button.

Before:

image

After:

image

## Type of change

- [ ] Dependency upgrade
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes #
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [x] The code change is tested and works locally.
- [x] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

**Comment by matthiasdebaat** [comment]
Thanks for this fix! It's still a bit cramped though. Might be better to move the mute and slider as a separate row below the buttons.

**Comment by Drafteed** [comment]
> Thanks for this fix! It's still a bit cramped though. Might be better to move the mute and slider as a separate row below the buttons.

I think it will look weird and massive visually.

**Comment by Drafteed** [comment]
> It's still a bit cramped though

We can also hide the next track button:

image

The "Stop" and "Next" buttons will remain available in the dialog box:

image

**Comment by matthiasdebaat** [comment]
> The "Stop" and "Next" buttons will remain available in the dialog box:

Yeah, I agree. Let's continue with your original idea by hiding the `stop` button. Hiding the `next` button shouldn't impact entities that doesn't have the cramped space problem, for example ones without a volume slider.

CleanShot 2023-01-11 at 13 40 08@2x

**Comment by Drafteed** [comment]
@matthiasdebaat I've made changes. The stop/next buttons is hidden only when has the volume slider and `assumed_state`.

**Review by bramkragten — APPROVED** [review]

**Pull request merged**
