### PR TITLE
add title option to stack cards

### LINKED ISSUE #3804: Name/title for horizontal- and vertical stack
*@Smiggel commented on Apr 28, 2019, 4:22 PM UTC:*

I would like to be able to add an title to a horizontal and vertical stack. Now I am not able to do this and get items like in the the attachment:

[Schermafbeelding 2019-04-28 om 17 39 44](https://user-images.githubusercontent.com/1825953/56867169-86680480-69e2-11e9-8884-191a9a1cec9f.png)

I would be nice to be able to have a header above the cards.

*This issue was moved by [iantrich](https://github.com/iantrich) from [home-assistant/ui-schema#264](https://github.com/home-assistant/ui-schema/issues/264).*

### PR DESCRIPTION
**Pull request by iantrich**
Closes https://github.com/home-assistant/home-assistant-polymer/issues/3804

Docs: https://github.com/home-assistant/home-assistant.io/pull/10512

### CODE REVIEW

**Comment by bramkragten** [comment]
I think it looks a bit weird to have a header outside of a card...

**Comment by iantrich** [comment]
Yeah, as do I, but I know people want it 🤷‍♀️

**Comment by bramkragten** [comment]
We shouldn't just do anything people want, it will get a mess, let's think of a better way to do this. Isn't there a custom card that allows stacks in a card? Can't you add a title there?

**Comment by iantrich** [comment]
I didn't mean to imply I didn't see it value in it; I meant I didn't see myself using it. I think it is a fine addition and something we should add.

**Pull request merged**
