### PR TITLE
Add button to request an update

### PR DESCRIPTION
**Pull request by bdraco**
## Proposed change

Unless I've missed it, there isn't an obvious way to request an entity update in the UI besides the developer tools.  This change adds a button to the more-info card to request one.  I'm not sure this is the best place, but it sure made testing polling entities easier.

Jun-09-2022 13-55-00

## Type of change

- [ ] Dependency upgrade
- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes #
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [ ] The code change is tested and works locally.
- [ ] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

**Comment by bdraco** [comment]
Ideally this would only appear on polling entities but since we don't know for entities not in the registry it seemed better to be consistent

**Comment by bdraco** [comment]
Maybe this should only appear in advanced mode?

**Comment by bdraco** [comment]
I feel like I don't have a handle on whether this is incredibly useful for the average user or incredibly useless for the average user, or somewhere in between.  For testing polling integration it's invaluable, but I'm not the user here.

**Comment by noxhirsch** [comment]
For me this would be incredibly useful (I already wanted to request exactly that feature). I often use the update entity service either for testing or for example things like REST sensors with (deliberately) long update intervals. In my optinion it would be best to only show it in advanced mode.

**Comment by matthiasdebaat** [comment]
For advanced users who want to test polling entities, this button can be useful. For all other users it is an extra, perhaps even unclear button. Unless we can make it more specific, I don't recommend adding this button to all info dialogs for (advanced) users.

For confirmation I would recommend the following: click icon-button > icon-button changes to circular progress indicator > when reloaded it's replaced with an check icon > after 2 seconds the original icon-button is shown again.

**Comment by bdraco** [comment]
> Unless we can make it more specific, I don't recommend adding this button to all info dialogs for (advanced) users.

I'm afraid this one is going to be confusing on the more info dialog.  Maybe there is a better place we can add it?  I'm kinda tempted to close this PR since I can't think of one.  We can always revive it later if we come up with the right place in the future.

**Comment by noxhirsch** [comment]
Maybe an implementation as a "hidden" advanced feature could be an alternative? Something like (long) press on the state in more-info? 
That would be similar to the hidden "fullscreen" feature when you click on the title of the more-info dialog.

**Comment by matthiasdebaat** [comment]
> Maybe there is a better place we can add it? I'm kinda tempted to close this PR since I can't think of one.

Me neither. We want to improve the more-info dialog, I will keep this option in mind when working on some designs.

**Comment by ludeeus** [comment]
How useful would this even be? (as opposed to how much confusion it will cause)
It only works on polling entities.
Which excludes all push integrations, and integrations with an update coordinator.
In some cases where it is a polling entity, there are additional limitations added to the update frequency.
IMO with all the cases where this does not work (or does not work how the user expects it to work) Id say that using the service under developer-tools is the perfect place for it.

**Comment by bdraco** [comment]
While it's an interesting idea and very useful for a subset of cases, I think it will cause more confusion than its worth as designed.   I'm going to close this for now and keep it in mind if I find the perfect place for it that makes more sense or we come up with a way to know if an entity is polling even without being in the registry.

Thanks for the feedback.

**Pull request closed without merging**
