### PR TITLE
Revise grid neutrality energy dashboard card, modify energy dashboard presentation to match

### PR DESCRIPTION
**Pull request by wtadler**
## Proposed change
- Eliminate the (unreferenced and arbitrary) yellow range of the gauge per conversation in the Discord and #9976
- Change red/green ranges to blue/purple for consistency
- Lighten blue/purple throughout the energy dashboard
- Make bar chart opacity consistent through the energy dashboard

> (Moved this to PR #10326 but preserving here because of the discussion.)
> - Correct and revise the tooltip per #9976 
> ### Before
> ```
> This card represents your energy dependency.
> 
> If it's green, it means you produced more energy than that you
> consumed from the grid. If it's in the red, it means that you
> relied on the grid for part of your home's energy consumption.
> ```
> ### After
> ```
> This card indicates your net energy usage.
> 
> If the needle is in the green, you returned
> more energy to the grid than you consumed from it.
> If it's in the red, you consumed more energy than you returned. 
> ```

## Type of change

- [ ] Dependency upgrade
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: 
- This PR is related to issue or discussion: partly addresses suggestions in #9976 
- Link to documentation pull request:

## Checklist

- [ ] The code change is tested and works locally.
- [x] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

**Comment by bramkragten** [comment]
I agree with the text update, not sure about the yellow 🤷‍♂️

**Comment by wtadler** [comment]
Thanks, @bramkragten. We've been messaging on the Discord, but I'll sum up here. Basically, the yellow range is completely arbitrary. In fact, even a hard boundary at 0 for net positive or net negative is not particularly relevant for a user. Users should not care whether they are at net -0.1 kwH or +0.1 kWh.

Accordingly, you put together this mockup, which I think is an improvement:
image

But I would take this a step further and go from red/green to blue/purple, because:
- Red/green implies bad/good, which is not necessarily true—someone might not have the goal of returning lots of energy to the grid. Users in areas without net metering, for instance, get no benefit from returning to the grid and if they are not altruistic, they might want to instead find a way to store excess production, as explained by the [tooltip on the solar-consumed energy dashboard card](https://github.com/home-assistant/frontend/pull/10052).
- The red/green zones here represent exactly the same thing as blue/purple do on three other energy dashboard cards: grid energy consumption/return.

This is my mockup for how this could look:
image

This uses, as the endpoints, the existing colors `energy-grid-consumption-color` and `energy-grid-return-color` in [ha-style.ts](https://github.com/home-assistant/frontend/blob/dev/src/resources/ha-style.ts). (Though the difference between blue and purple becomes more apparent if you raise overall lightness a bit.) The 50% point is halfway between the two colors, with lightness increased.

**Comment by bramkragten** [comment]
@matthiasdebaat do you have an opinion about this?

**Comment by matthiasdebaat** [comment]
> This is my mockup for how this could look: 
image

This is a difficult one. I think using purple and blue is correct, but it is not appealing to the eye. They aren't contrasting colors and we don't use gradients in our interface. Without gradients it would look like this
graph

For now I don't have a better solution. What do you think?

**Review by bramkragten — APPROVED** [review]
Waiting for @matthiasdebaat to approve the colors

**Pull request merged**
