### PR TITLE
Update climate state card and more info dialog

### PR DESCRIPTION
**Pull request by justweb1**
This update will change the standard temperature slider to a range slider. This will allow the user to specify the low_temp and high_temp versus having it automatically set for them based on a target_temp.

This will allow for better granularity as well as working more similarly to their actual thermostat.

**I do not have a thermostat for testing so please review and test the code before putting it into production.**

### CODE REVIEW

**Comment by justweb1** [comment]
image

**Comment by balloob** [comment]
Each component has a demo platform so that you're able to test the frontend without actually interacting with a device. Add this to your config:

```yaml
climate:
  platform: demo
```

**Comment by justweb1** [comment]
Thanks. I'll  take a look.

**Comment by justweb1** [comment]
@balloob Can I run something like `pip3 install --upgrade git+git://github.com/home-assistant/home-assistant.git@dev' to automatically install the pull?

**Comment by balloob** [comment]
Yeah, see the development instructions on the site

**Comment by justweb1** [comment]
I'm having trouble the this repository and my dev env. Would it make more sense to close this pull request, refork, and submit a new pull request after testing?

**Comment by justweb1** [comment]
Close pull request to rebuild and test.

**Pull request closed without merging**
