### PR TITLE
Update cast launch screen colors

### PR DESCRIPTION
**Pull request by jeremynoesen**
## Proposed change

Change the background color and the text color of the cast launch screen to match that of the Home Assistant branding. The first image is what the screen looks like now (background white, text black), and the second image is what this PR will make it look like (background f2f4f9, text 1d2126). This will also fix the fact that the "white" in the Home Assistant logo is different from the white background, which also fills in the Nabu Casa logo.

Screenshot 2024-02-09 at 1 46 56 PM
Screenshot 2024-02-09 at 1 46 31 PM

## Type of change

- [ ] Dependency upgrade
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes #
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [x] The code change is tested and works locally.
- [x] There is no commented out code in this PR.
- [NA] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [NA] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

**Comment by jeremynoesen** [comment]
If #19748 happens to get merged, and this also gets merged, there might be some conflicts, since the mentioned PR deletes the .status css block, while this one uses it.

**Comment by jeremynoesen** [comment]
I think the CI / Build supervisor (pull_request) check got stuck.

**Comment by jeremynoesen** [comment]
I would appreciate if someone could take a look at this. It is a subtle change, but it makes the launch screen look more polished.

**Comment by bramkragten** [comment]
@jeremynoesen I'll merge this for now, the reason it was not merged yet is because there is a complete new design for the launch screen that will be implemented soon.

**Review by bramkragten — APPROVED** [review]

**Comment by jeremynoesen** [comment]
> @jeremynoesen I'll merge this for now, the reason it was not merged yet is because there is a complete new design for the launch screen that will be implemented soon.

I'm looking forward to it! Sorry to seem pushy with this PR, I had no clue that was in the works 😅

**Pull request merged**
