### PR TITLE
Keep targets when switching services

### PR DESCRIPTION
**Pull request by bdraco**
## Proposed change

It is a common workflow to clone an automation and service call from off from on, or open to close.

Right now when you do that the targets get cleared which makes it much more difficult.

Before:
switch_open_close

After:
keep_entity

## Type of change

- [ ] Dependency upgrade
- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes #
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [x] The code change is tested and works locally.
- [ ] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

**Comment by zsarnett** [comment]
What happens if you have a light as a target with the service of Turn On and then change the service to Cover Close

**Comment by bdraco** [comment]
> What happens if you have a light as a target with the service of Turn On and then change the service to Cover Close

The entities are not cleared in this case.  Should we remove all entities that don't match the same domain?  I was thinking they could change it again if they hit the wrong one first

**Comment by zsarnett** [comment]
Yea I think we should remove any that don't work with the service. So on load, if there are values we can remove them if not accepted.

**Comment by bdraco** [comment]
Just realized what is acceptable is defined by the yaml file.  Will need to dig in a bit to figure out how to use that as a filter / modularize the existing code if it can't be

**Comment by bdraco** [comment]
Looks like the code needs to be broken out so its reusable here 
https://github.com/home-assistant/frontend/blob/dev/src/components/ha-selector/ha-selector-target.ts

**Pull request closed without merging**
