### PR TITLE
Add Swedish translation

### PR DESCRIPTION
**Pull request by joch**
There could possibly be a better word for "states".

### CODE REVIEW

**Comment by homeassistant** [comment]
Hi @joch, 

It seems you haven't yet signed a CLA. Please do so [here](https://home-assistant.io/developers/cla_sign_start/?pr=home-assistant&#x2F;home-assistant-polymer#490).

Once you do that we will be able to review and accept this pull request.

Thanks!

**Comment by ggravlingen** [comment]
@joch isn't "States" in Home assistant more of a main menu/"Huvudmeny"?

**Comment by joch** [comment]
@ggravlingen I agree, but I don't think "Huvudmeny" conveys the meaning of "states" properly. Maybe "Översikt"?

**Comment by ggravlingen** [comment]
@joch "Översikt" is a lot better! My belief is that it will be more helpful to new users to relate to going back to "Översikt". In my view, "States" is more of a technical term.

**Comment by balloob** [comment]
We're planning to converge to Overview in every language so this is a good change 👍

**Comment by balloob** [comment]
Thanks! 🇸🇪

**Pull request merged**
