### PR TITLE
Upgrade MDI icons to 4.2.95

### PR DESCRIPTION
**Pull request by bonanitech**

### CODE REVIEW

**Comment by balloob** [comment]
This pull request contained breaking changes. 

Please for future PRs include the changelog, including breaking changes, and map those against icons that are in use in the backend.

**Comment by bonanitech** [comment]
🤦🏼‍♂️😳

**Comment by bonanitech** [comment]
BTW, what was the breaking change?

**Comment by balloob** [comment]
partlycloudy -> partly-cloudy

**Comment by bonanitech** [comment]
But that is not in the changelog of this version. 🤔

**Comment by bonanitech** [comment]
Found it, that was on version 3.9.97. I didn't raise a PR for that version.

**Pull request merged**
