### PR TITLE
Update codemirror

### PR DESCRIPTION
**Pull request by bramkragten**
## Proposed change

https://codemirror.net/6/docs/changelog/

## Type of change

- [X] Dependency upgrade
- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes #
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [ ] The code change is tested and works locally.
- [ ] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

**Review by spacegaier — APPROVED** [review]
PR itself looks good to me, but I did not actually test it. Given that most current reported issues are with CM6 + iOS/macOS anyway, checking out the PR would not yield anything anyway in my env 😆.

**Comment by bramkragten** [comment]
I tested it, but doesnt seem to solve the issues.

**Comment by spacegaier** [comment]
> 
> 
> I tested it, but doesnt seem to solve the issues.

That's unfortunate. But even then merging makes sense to benefit of all other bug fixes for issues we did not face yet :) .

Are you quite sure that it is not HA specific? Then perhaps raising it with [CM6](https://github.com/codemirror/codemirror.next/issues) makes sense?

**Comment by bramkragten** [comment]
We created issues, I just need to create a simple repo for the issue.

**Pull request merged**
