### PR TITLE
Fix white spaces and line breaks in template editor

### PR DESCRIPTION
**Pull request by justweb1**
Fix white spaces and line breaks in template editor.

**Related Issue**
https://github.com/home-assistant/home-assistant-polymer/issues/122

### CODE REVIEW

**Comment by justweb1** [comment]
@kellerza will you test this in Firefox. I am having trouble getting it installed on my dev machine.

**Comment by balloob** [comment]
This fix will not work once we switch over to use ShadowDOM for web components (Polymer 2) because we are not allowed to style inside of it.

Also, a `paper-textarea` is [quite complex](https://github.com/PolymerElements/paper-input/blob/master/paper-textarea.html#L37-L83) so just making all white-space `pre-wrap` can cause more harm.

**Comment by justweb1** [comment]
I realized that and fixed it in the second commit

**Comment by justweb1** [comment]
@balloob I used an id and the mixin to tighten up the scope to the textarea box.

**Comment by justweb1** [comment]
I did inspect the element and it showed it looked fine but I couldn't rest in Firefox. I'll get Firefox working tonight and fix this.

**Comment by kellerza** [comment]
@justweb1 the patch worked, but when I tried a modification & revert it still worked.

As you mentioned on gitter, Firefox 49.0.1 (it auto-updates) most likely this, even my production 0.30.1 HASS started working after a page refresh, so we can safely close this issue. Thanks for the effort!

**Comment by balloob** [comment]
Closing this as this issue has magically resolved itself…

**Pull request closed without merging**
