### PR TITLE
change System Health icon

### PR DESCRIPTION
**Pull request by Mariusthvdb**
from Heart, which is widely (and dominantly?) used for Favorites in apps
to Stethoscope, which seems way more identifiable for a Health checker purpose

## Type of change

- [ ] Dependency upgrade
- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes #
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [ ] The code change is tested and works locally.
- [ ] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

**Comment by ildar170975** [comment]
I do not recognize this as a stethoscope:
image

I propose `mdi-heart-pulse` instead:
image

**Comment by Mariusthvdb** [comment]
Tbh, it’s a fine stethoscope, looks exactly like the one I am holding .

heart-pulse is used already in Ha core, for z-wave node-status entities.

**Comment by frenck** [comment]
I agree with @ildar170975.

Please note, that this also needs an update to our `brands` repository to match this frontend change.

**Comment by ildar170975** [comment]
> heart-pulse is used already in Ha core, for z-wave node-status entities.

Same repeated icon may be not a problem if these icons are on different pages.

The idea is to make a picture intuitively clear.
May be this stethoscope icon will not be clear...

The "heart" icon may be used even w/o a "pulse" - i.e. may be kept as it is now.
As for "favourites" - a Chrome, for example, is using a "star" icon...

**Comment by Mariusthvdb** [comment]
ok, thx.

one could argue the hospital family to be even more of a universal health indicator:

Schermafbeelding 2022-07-26 om 10 01 17

personally, I would change the heart for heart-pulse.

if we could agree on the hospital-box-outline I could continue with that, otherwise will close.

**Comment by matthiasdebaat** [comment]
System Health is more about the status of your system than a place to fix it. Therefore I agree with @ildar170975 that `mdi-heart-pulse` is a better fit, as a pulse represents the status.

**Comment by Mariusthvdb** [comment]
btw @frenck you mean this https://github.com/home-assistant/brands/blob/master/core_integrations/system_health/icon.txt?

it already is stethoscope ;-)

**Comment by frenck** [comment]
@Mariusthvdb Yeah, hence me mentioning it to get it into sync.

**Comment by Mariusthvdb** [comment]
so now I am confused. 
Apparently it was deemed appropriate to have system health use `stethoscope`, but somehow the `heart` came into play? And that was no longer in sync from that time?

I am still somewhat reluctant to feel the objection to the nr1 system health checker device being `stethoscope`. Having just returned from the hospital (I kid you not), and having seen a few Health checkers myself, the first thing was: "ok, let's listen to that"...

So checking the status of the system (which turned out to be ok ;-) ) as Matthias illustrated it. Stethoscope doesn't fix anything....

Even the Brand says a `stethoscope` is the tool of choice...

**Comment by frenck** [comment]
3 org members already responded to go with `mdi-heart-pulse`, I'm not sure what is left to be confused about?

**Comment by Mariusthvdb** [comment]
also: https://github.com/home-assistant/brands/pull/3558

**Comment by zsarnett** [comment]
https://github.com/home-assistant/frontend/pull/13281

We are removing the system health option

**Comment by frenck** [comment]
@zsarnett This is the icon for the System health integration, which remains in both documentation & core backend (e.g., shown in loaded integrations). Shouldn't that be adjusted?

I'm not sure how #13281 relates to this PR?

**Comment by zsarnett** [comment]
I think you meant to have this on the brands repo which in that case yes. That one can stay opened

**Comment by frenck** [comment]
> I think you meant to have this on the brands repo which in that case yes.



Yup. Sorry!

**Pull request closed without merging**
