### PR TITLE
Add user confirmation to update installation

### PR DESCRIPTION
**Pull request by spacegaier**
## Proposed change

image

## Type of change

- [ ] Dependency upgrade
- [ ] Bugfix (non-breaking change which fixes an issue)
- [X] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes #
- This PR is related to issue or discussion: https://github.com/home-assistant/frontend/discussions/12333
- Link to documentation pull request:

## Checklist

- [X] The code change is tested and works locally.
- [X] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

**Review by ludeeus — COMMENTED** [review]
I do not believe that this is something that is up to the frontend to decide.
If this is needed it should be done with a supported feature flag on the entity and then the frontend can show something like this for entities that need it.

**Comment by spacegaier** [comment]
> I do not believe that this is something that is up to the frontend to decide. If this is needed it should be done with a supported feature flag on the entity and then the frontend can show something like this for entities that need it.

I disagree. I don't feel that this is something that the backend needs to be involved with. Before actually triggering something critical as an update, the user should confirm that, especially since the "Skip" button that a user actually might have wanted to click on is right next to it.

Having this popup appear for some updates, but not for others (based on some flag that the backend might set or not set) feels inconsistent from a UX perspective

**Comment by ludeeus** [comment]
If that is your concern, add more space between them instead

**Comment by spacegaier** [comment]
> If that is your concern, add more space between them instead

From my POV does still not invalidate having this safeguard in place (e.g. to protect user from "auto-pilot clicking").

**Comment by frenck** [comment]
> (e.g. to protect user from "auto-pilot clicking").

Always asking for confirmation induces the same issue.

**Comment by spacegaier** [comment]
> > (e.g. to protect user from "auto-pilot clicking").
> 
> Always asking for confirmation induces the same issue.

I think it reduces the risk nonetheless, since an extra click has to be made and any dialog with a warning icon should hopefully give a user a pause for a second to then purposefully trigger the action.

Might this be a topic where perhaps we should ask for some community feedback in the forums?

**Comment by frenck** [comment]
> Might this be a topic where perhaps we should ask for some community feedback in the forums?

IMHO it adds a lot of clicks that are unneeded and will result in 1 thing: More people automating to do updates automatically (which IMHO is even worse).

I rather see smart logic (which needs to be provided by the backend) that indicates the update  risk (for example). E.g., allowing the integration to warn for breaking updates and not to ask on e.g., patches. Such a thing would prevent brain training as well.

Anyways, I personally would not accept and be highly annoyed if this change was merged.

**Comment by zsarnett** [comment]
Let's just move the buttons further from each other for now.

We can create a discussion to find out if the community would rather have this. I do think it would be nice to have a backend flag to determine if we should make sure they want to upgrade.

**Comment by matthiasdebaat** [comment]
> Let's just move the buttons further from each other for now.

Yes, I agree. Let's do this for now.

About the confirmation dialogs, Nielsen Norman group has a nice [article](https://www.nngroup.com/articles/confirmation-dialog/) about them. We should use them before committing actions with serious consequences, but not for routine actions. People will stop paying attention to the question and the confirmation dialog will lose its power to prevent errors. Exactly what the discussion above is about. When it's a repetitive task with the severity of different outcomes we should only show confirmation dialogs when the risk is significantly high. That is for us to decide. 

Personally I think we should only show a confirmation dialog when there are breaking changes, because this kind of update might stop your system. It would be great if we show what kind of breaking changes affect him.

_P.S. I would also drop the icon in front of the title._

**Pull request closed without merging**
