### PR TITLE
add dominos panel

### PR DESCRIPTION
**Pull request by craigjmidwinter**
Panel for Dominos pizza component

### CODE REVIEW

**Comment by c727** [comment]
Regarding your contacts to hotUKdeals and mydealz, will our users get some coupon codes if we merge this? 😋

**Comment by wardcraigj** [comment]
@c727 I wish I had a sweet hookup for pizza coupons like that! 😀 Actually, the client library for this does support the ability to add coupon codes, I just haven't had a chance to implement it yet

**Comment by balloob** [comment]
We should not merge this. With this approach we're going to ship like a 1000 panels.

**Comment by wardcraigj** [comment]
Hey @balloob,

Sorry to bug you, I know you are super busy--

I'm just wondering what the preferred approach for presenting this information to the user is? Initially I just included an option to dump this in the log and then refactored to present it in this panel.  Just want to make sure I've got the right approach before I start refactoring this--

My instinct would be to generalize this panel so that it could be used for all menus/product-lists in the future if someone implements another component for food or product ordering information

**Pull request closed without merging**
