### PR TITLE
Add name attribute to autocomplete fields

### PR DESCRIPTION
**Pull request by steverep**
## Proposed change

Follow recommendations on MDN and elsewhere to appease password managers and autofill features by naming fields and wrapping in `form` elements.

## Type of change

- [ ] Dependency upgrade
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: #10274 
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [x] The code change is tested and works locally.
- [x] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

### CODE REVIEW

**Comment by steverep** [comment]
I just realized I forgot to add it to the password manager Polyfill… I can do it tomorrow or whoever is reading this can be generous

**Review by piitaya — COMMENTED** [review]
We can't do that because `ha-form` can be inside `ha-form` when using the `grid` or `expendable` selector. We should handle this case with nested forms.

**Comment by steverep** [comment]
Ah... forgot about that.

**Comment by piitaya** [comment]
The name of the `ha-form` is confusing. May be we should rename it to `ha-fields` or `ha-field-group`.
HTML have an input/button for submit but we can't add this with this component.

I think we can add the naming to this component because it's its responsability to manage fields. The `form` element is already in the DOM for login component. Only the field names were missing.

**Comment by steverep** [comment]
Again, good catch.  I reverted that part of the change and just made the PR about adding the `name` attribute everywhere there is `autocomplete`.

**Comment by steverep** [comment]
I think I got everything and fixed a previous mistake I made too.  Is this too late for 2022.11?

**Review by bramkragten — APPROVED** [review]

**Pull request merged**
