### PR TITLE
Make sure slider type updates with changes to temperatures

### LINKED ISSUE #3373: hui-thermostat-card decide on slider type based on available temperature once on load
**Home Assistant release with the issue:**
0.96.0.dev0

**Last working Home Assistant release (if known):**

**UI (States or Lovelace UI?):**
Lovelace

**Browser and Operating System:**
Chrome

**Description of problem:**
Slider type for climate thermostat is decided on page load, and won't update as state changes. It is based on availability of temperature_min/max on page load. If these are temporarily unavailable when page is loaded. Wrong slider will be present until page is re-loaded. Offending code here:  https://github.com/home-assistant/home-assistant-polymer/blob/dev/src/panels/lovelace/cards/hui-thermostat-card.ts#L253-L271

**Javascript errors shown in the web inspector (if applicable):**

**Additional information:**

Sequence done, Heat, Heat/Cool, Refresh, Heat. In Heat only temperature attribute is available, in Heat/Cool temperature_min/max is available.

Correct in Heat mode
image

Incorrect in Heat/Cool
image

Correct in Heat/Cool (difference is currently 0 between min/max)
image

Incorrect in Heat mode
image

### PR DESCRIPTION
**Pull request by elupus**
Fixes #3373

### CODE REVIEW

**Comment by iantrich** [comment]
LGTM

**Review by balloob — APPROVED** [review]

**Comment by balloob** [comment]
Good catch !

**Comment by elupus** [comment]
I just noted that there still some remnant things not updating. The slider type now properly changes, but for some reason the value:s doesn't fully end up correct. i'm unable to figure out why.

I can't reproduce it here: https://jsfiddle.net/kxqr43p7/3/

I wonder if it might have been fixed in the next roundSlider version. Not really sure yet how one update it.

**Comment by elupus** [comment]
Okey, we need to change order, setting sliderType first in the attribute.

**Pull request merged**
