### PR TITLE
Update ha-switch (Material 3)

### PR DESCRIPTION
**Pull request by KTibow**
## Proposed change

Updates ha-switch to use `@material/web` (Material 3) for the switch instead of `@material/mwc-switch`.

## Type of change

- [ ] Dependency upgrade
- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Additional information

image
image
This does change the shape of the switch and the theming variables.

- This PR fixes or closes issue: fixes #
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [x] The code change is tested and works locally.
- [x] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

**Comment by bramkragten** [comment]
You know there is a material 3 style switch element? `md-switch` https://github.com/material-components/material-web/tree/master/switch

**Comment by KTibow** [comment]
i was going to reply that `@material/web` is still in beta and not used but i just checked and saw that we're using it
oh well i'll make it use that one instead

**Comment by KTibow** [comment]
Blocked by no M3 global theme (see #16035)

**Comment by KTibow** [comment]
Stale.

**Pull request closed without merging**
