### PR TITLE
Render target picker combo-box in overlaying menu surface

### PR DESCRIPTION
**Pull request by bramkragten**
## Proposed change

https://user-images.githubusercontent.com/5662298/210346581-7a6ce13e-6175-4d1d-b11d-ccb2849fd0af.mp4

## Type of change

- [ ] Dependency upgrade
- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [X] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes #
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [ ] The code change is tested and works locally.
- [ ] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

**Comment by karwosts** [comment]
IMO this seems like it still has some issues. Between screen widths 900-1200px, the box starts to shrink, until you hit screen width 900 and you only get a couple characters. 

image

Some of my changes in #14938 tried to address this case, the picker I think instead should move down to the next line instead of compressing on the right edge.

**Comment by bramkragten** [comment]
Yes, we should move to the narrow layout sooner here

**Comment by karwosts** [comment]
"Narrow" is when the sidebar is removed, correct?

Yes changing to narrow earlier could work, though I don't know if you really need to lose the sidebar to fix this. Seems like the picker just needs to be able to wrap under the date selector, and then you can comfortably display the sidebar and the content between 900-1200px.

**Comment by balloob** [comment]
I think that we should consider not matching the width of the buttons element but picking a widt (like 400px) and aligning the menu as good as possible around the buttons element.

**Comment by piitaya** [comment]
Can we fix the layout issue between 900px and 1200px and merge it ? It can be nice to have it for the next release 🙂

**Review by piitaya — APPROVED** [review]

**Comment by ildar170975** [comment]
Was it merged?
Still the list may be narrow:

изображение

**Pull request merged**
