### PR TITLE
Standardize config menu grammar

### PR DESCRIPTION
**Pull request by meichthys**
- Remove periods from menu item descriptions
- Change `Create and edit` to `Manage` to match other menu item descriptions

## Type of change

- [ ] Dependency upgrade
- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests
- [X] Minor grammatical fixes

## Checklist

- [X] The code change is tested and works locally.
- [X] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

**Review by zsarnett — APPROVED** [review]

**Comment by zsarnett** [comment]
You need to rebase to the dev branch and retarget your PR. We don't merge directly to the master branch

**Comment by meichthys** [comment]
@bramkragten Do i still need to rebase to dev, or did you take care of that for me?

**Comment by zsarnett** [comment]
Need to rebase

**Comment by meichthys** [comment]
@zsarnett Does that look better?

**Comment by zsarnett** [comment]
You shouldnt see any of brams commits

**Comment by meichthys** [comment]
@zsarnett I'm not sure how to rebase :/ 
I've reverted brams commit but i'm not sure if that's sufficient.

**Comment by zsarnett** [comment]
git reset HEAD~15
Then revert any file changes that you didn't want then
git push -f

**Pull request closed without merging**
