### PR TITLE
Correct "read-only" which was translated as "disabled"

### PR DESCRIPTION
**Pull request by wsw70**
There are two identical entries in the entities filter, despite pointing to two different views (read-only and disabled)

## Breaking change

No, just a visual change.

## Proposed change

There are two identical lines in the entities filter - I thought that it was a bug but ends up just being a copy/paste of the previous line in the translation JSON.

## Type of change

- [ ] Dependency upgrade
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

"Bug" is a big word - it is a fix in the translation.

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes #
- This PR is related to issue:
- Link to documentation pull request:

## Checklist

- [ ] The code change is tested and works locally.
- [ ] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

**Comment by Misiu** [comment]
This should be changed in lokalise project, not here.
https://app.lokalise.com/project/3420425759f6d6d241f598.13594006/?view=multi

**Comment by wsw70** [comment]
@Misiu thanks. Is there a place where this is documented? (I just forked/PR the JSON and nothing in the process complained).

Also - after registering I do not have access to the project (`Sorry, you do not have permission to access this resource:
https://app.lokalise.com/project/3420425759f6d6d241f598.13594006/?view=multi`). And this seems to be a trial.

**Comment by Misiu** [comment]
@wsw70 actually it is well documented: https://developers.home-assistant.io/docs/translations/
You don't need to start new project, just join existing one

**Comment by wsw70** [comment]
> @wsw70 actually it is well documented: https://developers.home-assistant.io/docs/translations/
> You don't need to start new project, just join existing one

Super, thanks. Besides correcting the translation, should I do anything else to have it pushed? Or is the process automatic?

**Comment by Misiu** [comment]
@wsw70 this is full automatic :)

**Pull request closed without merging**
