### PR TITLE
Add exclude attributes support to attribute selector

### PR DESCRIPTION
**Pull request by frenck**
## Proposed change

Adds the possibility to exclude attributes from the attribute selector.

Applied this to 4 places in the automations/script that use this selector currently.

The goal is to clean up the attributes shown in the automation editor. Sometimes you get a lot. However, most are not useful or do not apply.

For example: "Friendly name" is pretty useless in the number condition, so is having "device_class" in your state triggers.

This PR excludes a bunch of well-known (built-in) attributes depending on the situation.

CleanShot 2022-08-20 at 11 13 36

Note: The excludes lists look similar in some places, but they are different depending on the use case.

## Type of change

- [ ] Dependency upgrade
- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes #
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [ ] The code change is tested and works locally.
- [ ] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

**Comment by frenck** [comment]
I'm not sure why the types fail, or how to solve it. Some hints/help with that would be appreciated 👍

**Comment by zsarnett** [comment]
Seems like because it was a const (done in a previous pr) the new code was unable to change a read-only return type. I honestly don't know why you were getting this but maybe @steverep does as he added the const originally

**Comment by frenck** [comment]
Rebased to deal with the merge conflict

**Comment by steverep** [comment]
`as const` needs to be there so the schema is a literal type.  This is to enforce that `localize` is only passed keys that exist.  What is the error?  If you add it back I can help fix whatever the error is.

**Comment by zsarnett** [comment]
You can pull his branch down to your local machine and test if you get time. I'm out for the weekend or I would look at it further

**Comment by frenck** [comment]
@steverep One of the error is currently visible

**Comment by steverep** [comment]
They are only "fixed" because the changes to type check the localize key are not complete.  So they are passing a temporary exception instead of actually conforming.  Please add them back. 😢

**Comment by frenck** [comment]
> Please add them back. 😢

Will do.

**Comment by frenck** [comment]
@steverep Reverted, but that brings me back to the original issue :)

**Comment by steverep** [comment]
Ok give me a little time to review

**Comment by frenck** [comment]
Feel free to push onto the branch 👍

**Comment by frenck** [comment]
Thanks @steverep 👍

**Comment by steverep** [comment]
Should be good now.  All you had to do was add `readonly` to the `exclude_attributes` property (the errors were simply complaining you can't take something that's typed as literal/const/readonly and assign it to something that isn't).

I think there is also an error in the schema function because `entity_id` can be `string | string[]` but the method doesn't handle this.  It's not caught because it's not typed.  That's somebody else's fault though 😉

**Comment by frenck** [comment]
looks good to me 👍 
Can't prove my own PR thought 😄

**Comment by steverep** [comment]
As a general comment, is the list of excluded attributes going to be difficult to maintain?

**Comment by frenck** [comment]
Yes, but we don't use attributes in general anymore (unless we change models), so maintenance should be low.

This is more or less meant as a way to reduce noise on the user end (they can still use these attributes if they want, the selector accepts manual custom input).

**Comment by steverep** [comment]
i'm not necessarily against it, but it just seems to go against the rest of the front end code. Everywhere a domain or an attribute is used, it's just typed as a string that we know nothing about. And that's the type coming from the web socket as well. @bramkragten  might have some thoughts on this.

**Comment by frenck** [comment]
> but it just seems to go against the rest of the front end code.

Unfortunately, it isn't.

**Comment by frenck** [comment]
To illustrate what is shown now (like everything in the sink)

CleanShot 2022-08-20 at 20 47 43

Lots of stuff isn't usable here (as it won't change, thus won't trigger), or are confusing (e.g., "Preset modes" vs "Preset mode", only the latter is usable in these cases).

**Review by steverep — APPROVED** [review]

**Comment by steverep** [comment]
Alright you convinced this newbie.  If I get blamed I'll just say you bullied me. 😛 

PS - I'm legally blind, so screenshots are only slightly above useless to me 😎

**Comment by frenck** [comment]
> If I get blamed I'll just say you bullied me. 

Haha, don't worry! Everything can be reverted, fixed, or improved on in the future 👍 

And these changes I've made the past day, yeah, they can be improved on for sure. In the end, they are quick wins for the end-user experience. 

>  I'm legally blind, so screenshots are only slightly above useless to me

Right! I forgot about that for a moment, sorry about that!

**Pull request merged**
