### PR TITLE
Fix target_temperature_step

### LINKED ISSUE #3384: Undefined on termostat card
**Home Assistant release with the issue:** 0.96.0

**Last working Home Assistant release (if known):**

**UI (States or Lovelace UI?):**

**Browser and Operating System:** Mac, Chrome

**Description of problem:**

If no SUPPORT_TARGET_TEMPERATURE in climate component, there is `Undefined` temperature on climate card.
Also affected climate.mqtt component if no `temperature_command_topic` set.

**Javascript errors shown in the web inspector (if applicable):**
```

```

**Additional information:**

### PR DESCRIPTION
**Pull request by Anonym-tsk**
Fixes #3384 and fixes https://github.com/home-assistant/home-assistant/issues/25252

### CODE REVIEW

**Comment by balloob** [comment]
🙈 oh my. Thanks for that fix. I am embarrassed.

**Comment by balloob** [comment]
Oh your PR targeted master…

**Comment by Anonym-tsk** [comment]
@balloob yes, master. I think, it's minor fix, for 0.96.2(3)

**Comment by balloob** [comment]
it's in 0.96.2

**Comment by balloob** [comment]
Everything always go to dev. We don't decide with PR target in what release something is included.

**Pull request merged**
