### PR TITLE
Create no.json

### PR DESCRIPTION
**Pull request by hwikene**

### CODE REVIEW

**Comment by homeassistant** [comment]
Hi @hwikene, 

It seems you haven't yet signed a CLA. Please do so [here](https://home-assistant.io/developers/cla_sign_start/?pr=home-assistant&#x2F;home-assistant-polymer#486).

Once you do that we will be able to review and accept this pull request.

Thanks!

**Comment by Danielhiversen** [comment]
Maybe add
` "states": "Tilstander",
`
Or do have a better suggestion for `states` ?

**Comment by hwikene** [comment]
I was struggeling to find a good suggeston for "states" 
But "states": "Tilstander", will work. 
Thanks!

**Comment by balloob** [comment]
We're planning to use the translation of "Overview" in every language. So Oversikt?

**Comment by Danielhiversen** [comment]
Oversikt is fine

**Comment by balloob** [comment]
Done! 🐬  🇳🇴

**Comment by hwikene** [comment]
Great! :)

**Pull request merged**
