### PR TITLE
Minor change to thermostat card to reflect step_temp on set-temperature

### PR DESCRIPTION
**Pull request by bannhead**
A simple change to display the temperature set in a manner consistent with the step parameter

### CODE REVIEW

**Comment by bannhead** [comment]
Pre-commit changes indentation

**Comment by thomasloven** [comment]
This conflicts with #4172. Would you mind adding the same change to the `new-round-slider` branch too?

https://github.com/home-assistant/home-assistant-polymer/blob/new-round-slider/src/panels/lovelace/cards/hui-thermostat-card.ts#L155-L156

**Comment by bannhead** [comment]
I did a PR to that branch, but I don't know how to solve conflits

**Comment by bannhead** [comment]
Messed up things, made a new PR

**Pull request closed without merging**
