### PR TITLE
Fixing thermostat bugs (scrolling and state) #758 and #763

### LINKED ISSUE #763: Front-end doesn't allow state for thermostats
Currently `state-card-climate.html` uses `[[stateObj.attributes.operation_mode]]` to show thermostat state. This is not useful as operation_mode should represent the static type of operation supported by the thermostat, not the actual state. 

Showing "idle" or "heating" when in "auto" mode should be allowed while still maintaining correct operation_mode to display Operation dropdown selection.

### PR DESCRIPTION
**Pull request by ciotlosm**
Fixing bug more-info-climate card interface scroll bug #758
Also fixes #763

### CODE REVIEW

**Comment by homeassistant** [comment]
Hi @ciotlosm, 

It seems you haven't yet signed a CLA. Please do so [here](https://home-assistant.io/developers/cla_sign_start/?pr=home-assistant&#x2F;home-assistant-polymer#759).

Once you do that we will be able to review and accept this pull request.

Thanks!

**Review by andrey-git — APPROVED** [review]
Code looks fine. Please sign the CLA.

**Comment by ciotlosm** [comment]
The state modification is backwards compatible with most thermostats except https://github.com/home-assistant/home-assistant/blob/dev/homeassistant/components/climate/netatmo.py#L83 which seems to define "state" differently. 
Looking at the implementation, the block does not seem to be used so I propose to remove that block and allow the parent (in __init__) to be used which would work.

**Comment by tinloaf** [comment]
You said this is necessary for https://github.com/home-assistant/home-assistant/pull/11325 - why did you close this PR?

**Comment by ciotlosm** [comment]
I messed up branches on my machine and I ended up with more commits that should not have been there. In my messy attempt to clean branches and pick commits I ended up with an empty commit list for the above PR and it closed by itself. 

I have opened a new PR with the correct commits here https://github.com/home-assistant/home-assistant-polymer/pull/766

**Pull request closed without merging**
