### PR TITLE
Convert remaining elements to ES6 classes

### PR DESCRIPTION
**Pull request by emlove**
Monster PR, but I used vim macros to take care of most of the heavy lifting, so we be done with this. I've tested it where I can with demo platforms. This was focused mostly just on the minimal conversion, not the style changes such as collapsing properties or other optional ES6 changes.

Feel free to push commits to this PR as well.

### CODE REVIEW

**Comment by andrey-git** [comment]
Did you handle `this.fire` automatically?
There is also `this.debounce`

In general I think such a huge PR is too dangerous.

**Comment by armills** [comment]
`this.fire` was just a manual fix. Grepped for the usages and updated appropriatel. We could pick files off of this branch and merge them in smaller chunks as well, but the goal here is to create less busy-work. Understandably a ton to go through though.

**Comment by balloob** [comment]
So I agree with the sentiment by @andrey-git that huge PRs are dangerous, especially since we have pretty much no tests for the frontend.

However, I also believe that our resources are limited. So I suggest we do a quick smoke test clicking around with Home Assistant in demo mode, and if it all works, let's go ahead and merge it and publish a new release to HASS. We have a week to find more bugs before release.

**Comment by balloob** [comment]
I reviewed the PR and looked for common pitfalls (like not calling `super.ready()` but it seems to be all taken care off.

**Comment by armills** [comment]
I could also break this up in to several separate PRs if we want to have smaller sets of diffs to sign-off on, but basically having taken the pitfalls we've learned from other conversions, and doing it all systematically at once seems to have covered our bases. I'm OK with either solution.

**Comment by andrey-git** [comment]
Polymer2 doesn't have `debounce`. This should have triggered many JS exceptions. If it didn't - it means this type of testing is not good.

**Review by andrey-git — APPROVED** [review]

**Comment by balloob** [comment]
Fixed 2 missed async conversions in 33eb417

**Pull request merged**
