### PR TITLE
Allow changing direction of slider in cover position tile feature

### PR DESCRIPTION
**Pull request by Misiu**
## Proposed change
This change will allow the user to change the direction of the slider in the cover position tile feature:

image

image

image

It still follows the rule that we should use the active zone from more info (in this case the active zone shows the close percentage), but it allows us to have 0% on the left.

Ideally, this should be the default behavior, because it uses the close percentage as an active zone and it allows consistent UI/UX - 0% is on the left as in all other tile features.

## Type of change

- [ ] Dependency upgrade
- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes #
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [x] The code change is tested and works locally.
- [x] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

**Comment by piitaya** [comment]
This change was already proposed in the original PR : https://github.com/home-assistant/frontend/pull/16110#issuecomment-1683638924. 

I discussed with the UX team and we prefer to keep the current behavior for now rather to add option.

**Comment by frenck** [comment]
Thanks for the contribution, as per above, we decided not to do this.

Nevertheless, thanks for being willing to contribute.

../Frenck

**Comment by Misiu** [comment]
No worries :)
I plan to release this as a custom tile feature.
Sorry for not closing this before.

**Comment by jonferreira** [comment]
> Thanks for the contribution, as per above, we decided not to do this.
> 
> Nevertheless, thanks for being willing to contribute.
> 
> ../Frenck

While I can understand the decision to keep the same default behaviour, I don't understand why an option to invert the slider is not allowed?

IMHO the slider on a 100% opened cover should be represented the same way as a 100% dimmable light, i.e. slider fully to the right. Again, I understand everyone has their opinion and this may not make sense to some people but I'd love to have an option to "invert" the slider bahviour.

**Comment by piitaya** [comment]
@jonferreira We didn't add the option because we don't want to multiply the number of option for each card or card features.
However, it's totally possible to create a custom feature for this behavior (see [documentation](https://developers.home-assistant.io/docs/frontend/custom-ui/custom-card/#tile-features)).

**Comment by jhemak** [comment]
I think this would be a great feature. I also find it confusing to have 100% on the left.

**Pull request closed without merging**
