### PR TITLE
Add lock features for tile card

### PR DESCRIPTION
**Pull request by marcgeurts**
## Proposed change

Added lock features for the tile card.

Screenshot 2024-04-17 at 14 28 34

Screenshot 2024-04-17 at 14 28 08

image

Screenshot 2024-04-17 at 14 25 39

## Type of change

- [ ] Dependency upgrade
- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml
type: tile
entity: lock.front_door
features:
  - type: lock-commands
  - type: lock-open-door
```

## Checklist

- [x] The code change is tested and works locally.
- [x] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

**Comment by silamon** [comment]
For clearness: This is a continuation of #19880 with the UX feedback applied in https://github.com/home-assistant/frontend/pull/19880#issuecomment-1972828926.

**Comment by marcgeurts** [comment]
> For clearness: This is a continuation of #19880 with the UX feedback applied in [#19880 (comment)](https://github.com/home-assistant/frontend/pull/19880#issuecomment-1972828926).

Thank you @silamon, that's correct, I forget to mention it.

**Comment by marcgeurts** [comment]
Once https://github.com/home-assistant/frontend/pull/19944 is merged, I will add a pulsating effect on the closing action too.

**Comment by piitaya** [comment]
Thank you for the contribution @marcgeurts! 
Can be have the success message as a label instead of a button to keep consistency with the lock more info?
CleanShot 2024-04-22 at 11 19 15

**Comment by marcgeurts** [comment]
Thanks for your review @piitaya , I did consider this before, but wasn't sure because labels weren't used yet with tile cards.

image

I changed it to a label now.

**Review by silamon — APPROVED** [review]

**Pull request merged**
