### PR TITLE
Add created/modified to registry tables

### PR DESCRIPTION
**Pull request by bramkragten**
## Proposed change

- Adds 2 by default hidden columns to devices/entities/labels tables.
- Changes the logic of sizing columns
- Allows table to scroll horizontally if it doesn't fit

## Type of change

- [ ] Dependency upgrade
- [ ] Bugfix (non-breaking change which fixes an issue)
- [X] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes #
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [ ] The code change is tested and works locally.
- [ ] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

## Summary by CodeRabbit

- **New Features**
	- Added `created_at` and `modified_at` properties to various configuration entities, enhancing tracking of creation and modification timestamps.
	- Introduced new columns for `created_at` and `modified_at` in data tables across different components.

- **Bug Fixes**
	- Removed fixed `width` properties for certain UI elements, improving responsiveness and layout flexibility.

- **Documentation**
	- Updated translation files to include new terms for `created_at` and `modified_at`.

### CODE REVIEW

**Comment by silamon** [comment]
Let use the "—" again instead of "-", it looks nicer. 

image

**Review by silamon — DISMISSED** [review]
I'm not sure if the year should also be displayed in the created/modified dates. 
We do have an open issue for last triggered in automations: https://github.com/home-assistant/frontend/issues/20392
For created/modified, it may not change as much as last triggered, making this issue more visible on these columns.

**Comment by silamon** [comment]
To fix the CI: Update your prettier to the last version (yarn install) and rerun prettier. It's the removal of ( ) in the ha-data-table that causes it to fail.

**Review by frenck — APPROVED** [review]

**Comment by ildar170975** [comment]
> I'm not sure if the year should also be displayed in the created/modified dates.

Since these values can be from past years - displaying a year will avoid confusions.
https://github.com/home-assistant/frontend/issues/21640

**Pull request merged**
