### PR TITLE
Update energy dashboard to include gas in Total Energy & CO2 calculations

### LINKED ISSUE #10207: Gas in kWh does not report correctly values
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

- Energy coming from grid and coming from gas in kWh are not added in the Total

 - « non fossil » is only the one for grid ( so is wrong as gas is 100% fossil) and calculation should consider « non fossil »/« Total »
- Even with an unit price, gas price stays equal to 0

### Describe the behavior you expected

- Energy coming from grid and coming from gas in kWh should be added in the Total (Home)

 - « non fossil »  calculation should consider « non fossil »/« Home » values
 
- There should be Gas cost calculation

### Steps to reproduce the issue

no step necessary; situation after several hours

### What version of Home Assistant Core has the issue?

Home Assistant Container

### What was the last working version of Home Assistant Core?

 	core-2021.10.1

### In which browser are you experiencing the issue with?

All (Fiefox, Chrome, + Ipad Safari

### Which operating system are you using to run this browser?

Windows 11

### State of relevant entities

_No response_

### Problem-relevant frontend configuration

_No response_

### Javascript errors shown in your browser console/inspector

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by ColinRobbins**
## Proposed change

The Energy distribution and CO2 cards in the Energy dashboard only take into account Electricity.
When the Gas consumption is available as kWh, the Total energy use in the Home, and the C02 consumption totals should include Gas.
This change adds gas into those calculations

## Type of change

- [ ] Dependency upgrade
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

The energy dashboard should be configured to use a gas sensor in kWh for this change to have an effect.

## Additional information

- This PR fixes or closes issue: fixes https://github.com/home-assistant/frontend/issues/10207#issuecomment-955655634
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [x] The code change is tested and works locally.
- [x] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

**Comment by zsarnett** [comment]
Can you add an image to show the changes made?

**Comment by ColinRobbins** [comment]
> Can you add an image to show the changes made?

gas

**Comment by bramkragten** [comment]
If we would do this, the circle of the home should also include gas

**Comment by bramkragten** [comment]
I'm not sure about this, the behavior is now different based on the unit of the gas entity...

**Comment by ColinRobbins** [comment]
> I'm not sure about this, the behavior is now different based on the unit of the gas entity...

But without it, it is clearly wrong.
You have gas and grid feeding kWh into home, but the numbers do not add up.
There is a lot of support for the request on the issues page.

There is a remedy for users - create a template sensor to convert m3 to to kWh.

If we agree it is the right thing to do, I can take a look at the ‘circle’ comment.

**Comment by pbranly** [comment]
Hi
What is missing to push that very interesting PR?

**Comment by ColinRobbins** [comment]
@bramkragten,  by way of contrast, here is a screen shot without this PR.
In my view (and the comments in the associated issue) this does not make sense, as the gas value links to home, which only shows the electric kWh value.
 CA544484-1DEB-4F7A-81F5-5BFE1B3CE74E.
Hence the PR to resolve the issue.

**Comment by pbranly** [comment]
I fully agree with your PR that is definitively what I want as well.
How can I help if possible to push this PR ?
It seems that it is waiting a reviewer .
Thanks
Phil

**Comment by bramkragten** [comment]
> @bramkragten, by way of contrast, here is a screen shot without this PR. In my view (and the comments in the associated issue) this does not make sense, as the gas value links to home, which only shows the electric kWh value. CA544484-1DEB-4F7A-81F5-5BFE1B3CE74E. Hence the PR to resolve the issue.

I agree with that, but we have take other parts and maintainability into account too.

It would be weird that a gas meter with m3 would behave differently and hard to explain, that's mainly my issue. Now we have to decide if we want to support converting m3 to kWh to support this for m3 too... making things extra complicated again.

**Comment by pbranly** [comment]
@bramkragten ,

Hi I fully agree that in the option gas/m3, it is not possible to add carrots and navets so as it is our demand is only when both electricity and gas energy are in kWh.

But in the option gas/kWh, this should be a huge improvement fully in line with the major concern that everybody has or should have with energy, climatic issues, carbon increase, COB21, etc …..
It should be major to have a screen that shows to users that use electricity only, how much their country contribute or not to carbon reduction ( this already works perfectly)
It should be major to have a screen that show to users (as I am) that use both gas and electricity how much is their total consumption in kWh ( with gas the current home value is nearly marginal as it shows only electricity ) and the final result in term of carbon result ( I live in France where because or thanks to nuclear electricity we have a very good carbon value but my central heating is from gas ….)
For me the PR from @ColinRobbins is perfect and should be implemented as far as your general development plan allows it.

Sorry for several English errors … I am French !


And finally for long term development I already wrote some proposals I would be very happy to discuss 

https://github.com/home-assistant/frontend/issues/10208

Regards
Philippe

**Comment by ColinRobbins** [comment]
> m3 to kWh

Please be aware (I assume you are, but want to make sure), that converting m3 to kWh is non trivial, as it has both geographic and time sensitive variables.

**Comment by pbranly** [comment]
Hi Awesome Home assistant team.
Any news about this topic ?
Is it at least in the road map ?
Any date ?
Thanks per advance 
Phil

**Comment by balloob** [comment]
We've decided to not do this right now. We don't want to include gas until we have a proper plan how gas can work in energy management regardless of the unit.

**Pull request closed without merging**
