### PR TITLE
Handle mouse events on touchscreens. Fix #2085

### PR DESCRIPTION
**Pull request by thomasloven**
I think this does it.

Before merging I would want someone to test on:

- [X] Chrome for Android
- [X] Windows 10 pc with touchscreen (mouse)
- [X] Windows 10 pc with touchscreen (touch)
- [X] Safari on iphone

### CODE REVIEW

**Comment by zsarnett** [comment]
Chrome on Android ✔️

**Comment by zsarnett** [comment]
```
long-press-directive.ts:85 [Intervention] Ignored attempt to cancel a touchstart event with cancelable=false, for example because scrolling is in progress and cannot be interrupted.
clickStart @ long-press-directive.ts:85
long-press-directive.ts:107 [Intervention] Ignored attempt to cancel a touchend event with cancelable=false, for example because scrolling is in progress and cannot be interrupted.
clickEnd @ long-press-directive.ts:107
```

RIP ❌ Android Chrome

**Comment by thomasloven** [comment]
Trying again. Resetting the test list.

**Comment by iantrich** [comment]
No on Win10/Touch for Mouse, Touch still works

**Comment by zsarnett** [comment]
Not working on Android Chrome

**Comment by thomasloven** [comment]
Let's try something else. New round!

**Review by balloob — APPROVED** [review]

**Pull request merged**
