### PR TITLE
Add entity_picture capability to plant card

### PR DESCRIPTION
**Pull request by PeteBa**
Adds the ability to set a background image to the plant card:

image

Can specify via customising the entity_picture:
```
  customize:
    plant.miflora_3:
      friendly_name: Ponytail Palm (Bedroom)
      entity_picture: /local/ponytail_palm.jpg
```
Appreciate any feedback on layout.

@c727 , let me know any coding improvements
@ChristianKuehnel, let me know your thoughts

### CODE REVIEW

**Comment by c727** [comment]
Imo this design does not fit with our other cards

**Comment by PeteBa** [comment]
Thanks for the feedback. I get what you mean and below is an alternative (shown against the media player card for a style comparison). It does take up a significantly more height but may be more aligned.

image

Having said that, the original layout was derived from the camera card so I guess there is no established norm for "image" centric cards! Appreciate all thoughts.

**Comment by c727** [comment]
Much better. You can also check the original paper-card, it has properties for header image and text. Also check out camera card. Both have the text on the bottom of the image.

Still someone else should give his ok to add a static image to this card that

**Comment by PeteBa** [comment]
The Material Design [site](https://material.io/) is a great resource! I have tried to adopt the standards to a revised card layout. Looks to fit well alongside the Media Player card and retains the current layout if no `entity_picture` has been set. I think the height of the plant image could come down a bit but I stuck with the 16x9 pattern. I will wait for feedback before posting any updated code.

image

@c727, one style question I have is the sensor value parts (numeric and uom) are treated differently i.e. value numerics are in `primary-text-color` but value uoms are using `secondary-text-color`. This feels a bit odd and couldnt reference that from material.io. Any insight?

**Comment by c727** [comment]
I thought the secondary text color looks nice but feel free to change it

**Comment by PeteBa** [comment]
Rebased PR to align with recent move to javascript and removed WIP as card now reflects layout below (with and without entity_picture).

image

Appreciate any feedback as I go off to water and feed the plants...

**Comment by balloob** [comment]
Can you align the font size of the name ("Peace Lily (Living Room)" in your example) the same as the font size for Camera and Media Player?

**Comment by PeteBa** [comment]
OK, so the entity name is 16px in Camera Card and 14px in Media Player Card (compared with 24px in Entity Card). I have gone with the larger 16px as the media player card supports multiple lines and hence, I assume, the slightly small font size.

By way of comparison with the previous version:
image

**Review by balloob — APPROVED** [review]

**Pull request merged**
