### PR TITLE
Display path to configuration.yaml

### PR DESCRIPTION
**Pull request by justweb1**
Displays configuration.yaml path on the dev-info screen.

Related Issue:
https://github.com/home-assistant/home-assistant/issues/3556

Related PR's:
https://github.com/home-assistant/home-assistant/pull/3660
https://github.com/home-assistant/home-assistant-js/pull/23

### CODE REVIEW

**Comment by justweb1** [comment]
Ready to merge with https://github.com/home-assistant/home-assistant/pull/3660

**Comment by justweb1** [comment]
@balloob @robbiet480, Just needs a review before I merge.

**Review by balloob — COMMENTED** [review]
This time, can you include the updated home Assistant js repo, but only after I merge your commit and whole you're on the master branch with latest changes pulled

**Comment by justweb1** [comment]
@balloob Did I update that correctly?

**Pull request merged**
