### PR TITLE
Fix Polish translation on energy panel

### PR DESCRIPTION
**Pull request by pepsonEL**
## Type of change

- [ ] Dependency upgrade
- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes #
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [ ] The code change is tested and works locally.
- [ ] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

**Comment by homeassistant** [comment]
Hi @pepsonEL, 

It seems you haven't yet signed a CLA. Please do so [here](https://home-assistant.io/developers/cla_sign_start/?pr=home-assistant&#x2F;frontend#10517).

Once you do that we will be able to review and accept this pull request.

Thanks!

**Review by xcybplx — APPROVED** [review]
That's correct PL translation.

**Comment by Misiu** [comment]
@pepsonEL you should fix translations on lokalise, not here.
Translations are automatically downloaded, so your changes will be overridden.
This is the link to the place where you should fix this: https://app.lokalise.com/project/3420425759f6d6d241f598.13594006

**Comment by ludeeus** [comment]
Closing as this needs to be done on lokalise, thanks anyway :+1:

**Comment by pepsonEL** [comment]
But i dont see this translation on this peage lokalise. I search where is "Siatka" and not found it in polish language.....

**Comment by ludeeus** [comment]
<https://app.lokalise.com/project/3420425759f6d6d241f598.13594006/?view=single&reference_lang_id=640&single_lang_id=748&search=energy_distribution>

**Comment by Misiu** [comment]
image
it is there.
Just clear the filters first

**Pull request closed without merging**
