### PR TITLE
💄 save login dialog

### LINKED ISSUE #4138: Move save login prompt as it overlaps certain UI features such as add integration
**Checklist:**

- [x] I updated to the latest version available
- [x] I cleared the cache of my browser

**Home Assistant release with the issue:**
Been around for a while but I only really notice this in my dev instance, probably started when new auth system was put in place?

**Last working Home Assistant release (if known):**
Before new auth as the prompt did not exist
**UI (States or Lovelace UI?):**
Neither, Configuration -> Integrations

**Browser and Operating System:**

Chrome on Desktop and also mobile, probably impacts all devices and browsers as both buttons are in the same location
**Description of problem:**
When a user navigates to Configuration and selects Integration without saving the login prompt or dismissing it the Add Integration icon is hidden behind it.  

image

image

**Javascript errors shown in the web inspector (if applicable):**

```
n/a
```

**Additional information:**
We should probably move this or allow the button to be above if its shown, either way not good to have it hidden.  Maybe a better location is in the header since its completely out of the way?

### PR DESCRIPTION
**Pull request by iantrich**
fixes https://github.com/home-assistant/home-assistant-polymer/issues/4138

### CODE REVIEW

**Comment by bramkragten** [comment]
It should be a dialog if we place it in the middle of the screen, having a card float around in the middle is weird I think.

But not sure it should be that prominent anyway. Why isn't it a toast?

**Comment by iantrich** [comment]
> Why isn't it a toast?

Yeah, that would probably be best. I'll make the change.

**Comment by iantrich** [comment]
Not sure why, but localize is not returning any results for me when used in here :man_shrugging: anyone have any idea why?

**Comment by balloob** [comment]
We should not merge this. It's totally fine on its place. That issue is dumb, the user can just press either button ?

**Comment by balloob** [comment]
Blocking all interaction with the page for a login prompt is a bad experience too. I am going to close this.

**Pull request closed without merging**
