### PR TITLE
Add UI for reload resources service

### PR DESCRIPTION
**Pull request by bramkragten**
## Proposed change

UI for https://github.com/home-assistant/core/pull/32865

## Type of change

- [ ] Dependency upgrade
- [ ] Bugfix (non-breaking change which fixes an issue)
- [X] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes #
- This PR is related to issue: 
- Link to documentation pull request: 

## Checklist

- [ ] The code change is tested and works locally.
- [ ] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

**Comment by Misiu** [comment]
@bramkragten does this mean that I can add a sensor, switch or integration to configuration.yaml and after reloading they will be added/updated? What about `recorder` or `logger`? Will they also reconfigure?

**Comment by frenck** [comment]
@Misiu These changes are for reloading Lovelace resources defined in YAML...

So not related to anything in your comment.

**Comment by Misiu** [comment]
@frenck I'm still new here. Isn't a switch a Lovelace resource?
So it will only reload themes and dashboards?

**Comment by pvizeli** [comment]
@Misiu you get a ban now for 2 day until you learn that you don't should comment on PR

**Pull request merged**
