### PR TITLE
Use newspaper icon for change log button

### PR DESCRIPTION
**Pull request by felipecrs**
## Type of change

- [ ] Dependency upgrade
- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [x] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes #
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [x] The code change is tested and works locally.
- [x] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

**Comment by felipecrs** [comment]
I think it fits a little better than the current icon. What do you guys think?

**Comment by bramkragten** [comment]
Agree, or maybe `note-edit` or something

**Comment by felipecrs** [comment]
Existing:

image

Newspaper:
image

Note-edit:
image

I'm fine with either one, except the first lol.

**Comment by felipecrs** [comment]
image

As we are discussing alternatives, there is also this one.

**Comment by piitaya** [comment]
I like the newspaper one 🙂

**Comment by matthiasdebaat** [comment]
Yeah, let's use Newspaper

**Review by bramkragten — APPROVED** [review]

**Pull request merged**
