### PR TITLE
Fix add application credential keyboard handling

### LINKED ISSUE #21202: Application Credentials: new credential dialog discards changes when done via keyboard
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

While testing a different bug and adding fake data, I noticed that if you try to add a credential and save by pressing enter/return key on keyboard, the dialog gets closed/discarded instead. You can only save by pressing the Add button in dialog.

 Screen Shot 2024-06-28 at 2 44 28 AM

### Describe the behavior you expected

allow saving by pressing return/enter key

### Steps to reproduce the issue

[Open your Home Assistant instance and Manage your application credentials.](https://my.home-assistant.io/redirect/application_credentials/)

1. Go to Application Credentials
2. Click button to add new credential
3. Enter fake name/client id/secret, try to save by pressing enter/return on keyboard. Everything you entered will be lost.
4. Now repeat but press "Add" button in dialog, your changes will be saved

### What version of Home Assistant Core has the issue?

2024.7.0b3

### What was the last working version of Home Assistant Core?

_No response_

### In which browser are you experiencing the issue with?

_No response_

### Which operating system are you using to run this browser?

_No response_

### State of relevant entities

_No response_

### Problem-relevant frontend configuration

_No response_

### Javascript errors shown in your browser console/inspector

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by silamon**
## Type of change

- [ ] Dependency upgrade
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes #21202
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [x] The code change is tested and works locally.
- [x] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

## Summary by CodeRabbit

- **Enhancements**
	- Updated `DialogAddApplicationCredential` component to use Home Assistant (HA) buttons instead of Material Web Components (MWC) buttons for a more integrated user experience.

### CODE REVIEW

**Comment by silamon** [comment]
@coderabbitai pause

**Comment by silamon** [comment]
@coderabbitai Can you find all occurrences in the codebase where the the cancelbutton is a primaryAction in the dialog?

**Comment by silamon** [comment]
@coderabbitai, give it another try. We have multiple ha-dialog components that have a ha-button or mwc-button slot="primaryAction" and their text is "${this.hass.localize("ui.common.cancel")}".

**Comment by silamon** [comment]
@coderabbitai, look at the changed files in this PR for an example. What it originally was, is what we're looking for in the codebase.

**Review by piitaya — APPROVED** [review]
Thank you @silamon

**Pull request merged**
