### PR TITLE
Create nl.json

### PR DESCRIPTION
**Pull request by mariniertje**
Created nl.json to provide Dutch (NL) translations for Home-Assistant

### CODE REVIEW

**Comment by homeassistant** [comment]
Hi @mariniertje, 

It seems you haven't yet signed a CLA. Please do so [here](https://home-assistant.io/developers/cla_sign_start/?pr=home-assistant&#x2F;home-assistant-polymer#484).

Once you do that we will be able to review and accept this pull request.

Thanks!

**Comment by mariniertje** [comment]
Please be aware that the word "States" doesn't result in the best possible translations in other languages. 
The word "Status(es)" might lead to better translations, that are more used in daily language.

**Comment by TopdRob** [comment]
Duplicate of #483

**Comment by passie** [comment]
although i'm not a translator myself as a profession, these seem inaccurate

**Comment by balloob** [comment]
I've merged the first PR that added the Dutch language. Please open a PR against the current translation with improvements.

**Pull request closed without merging**
