### PR TITLE
Add presence device_class for binary_sensor

### PR DESCRIPTION
**Pull request by arsaboo**
Parent PR: https://github.com/home-assistant/home-assistant/pull/10705

Adds presence device_class

### CODE REVIEW

**Comment by andrey-git** [comment]
Also add states and translations

**Comment by arsaboo** [comment]
@andrey-git Not sure about the states....can you please guide me where exactly..thanks!

**Comment by arsaboo** [comment]
Let me know if anything else is required...thanks!

**Review by andrey-git — APPROVED** [review]

**Comment by andrey-git** [comment]
Waiting till backend PR is submitted

**Pull request merged**
