### PR TITLE
Improve zones UI

### LINKED ISSUE #4565: Zone panel looks weird when empty
Current dev:

image

I think that we should also include non-editable zones and mark them as non-editable.

### LINKED ISSUE #4573: Creating Zone: Any change to data (including dragging zone) centers zone
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

On dev. 

Any data entry in the new zone editor resets the map, including dragging and dropping the zone. 

If the map is to reset, it should make sure that the full radius of the zone is included.

## Expected behavior
Map to stay where it is unless I am manually editing the lat/long.

## Steps to reproduce
config -> zones -> create new zone.

Zoom out, drag icon on map. See how it resets the map.

## Environment

- Home Assistant release with the issue: 
- Last working Home Assistant release (if known): 
- UI Type (States or Lovelace): 
- Browser and browser version: 
- Operating system: 

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

### LINKED ISSUE #4574: New zone form polishing
## The problem

Few things about the new zone form:
- let's put latitude/longitude on a single line. Do we even have to show it as a row or can we put it somehow on the map in the top right, but a lot smaller ?
- If no icon is given, don't default it to a home. Use no icon instead (like on maps panel)
- Clicking on the "passive" text label of the toggle doesn't change the toggle (but does ripple it!)
- Let's not default the new zone to our home location. Maybe put it like 500 meters away from it?
- After creating first zone, maybe make sure it's selected/seen on the map. 
- Show the non-editable zones too, but indicate that they can't be edited. (This way we also show home zone)
- In the zones list, we show an information icon, but clicking on it brings us to an edit screen. Let's make it pencils. 
- In the zones list, center the icon inside the `contentIcon` space. According to the CSS it should, not sure why it isn't.

### PR DESCRIPTION
**Pull request by bramkragten**
closes #4574 
fixes #4565 
fixes #4573

### CODE REVIEW

**Comment by balloob** [comment]
- Wondering if we need to hide the config sidebar to give more space to the map?
- Clicking on a zone on the right will not fit it to the map. We should fit it in the map + some space around it (or it's a full orange page)
- Map still resets when I'm editing in the edit dialog
- Can we add a tooltip when hovering the disabled flow rows with why it won't work.

**Comment by balloob** [comment]
Can we text-align: center the zone name.

image

**Comment by balloob** [comment]
Tapping the home zone name shouldn't show an alert. Just the edit icon.

**Comment by bramkragten** [comment]
> Map still resets when I'm editing in the edit dialog
Not seeing this? When do you get that?

**Comment by bramkragten** [comment]
> Wondering if we need to hide the config sidebar to give more space to the map?

I don't know... let's keep that for another PR (or another nav 😄 )

**Review by balloob — APPROVED** [review]

**Pull request merged**
