### PR TITLE
Fixes: #1902 - Thermostat/Light Background

### PR DESCRIPTION
**Pull request by zsarnett**
image

image

### CODE REVIEW

**Comment by zsarnett** [comment]
Fixes: https://github.com/home-assistant/home-assistant-polymer/issues/1902

**Review by balloob — APPROVED** [review]

**Comment by balloob** [comment]
NIce!

**Comment by balloob** [comment]
Removed from 0.81.3 because you included changes for light card, which don't exist for master.

**Comment by matisaul** [comment]
Is it include in HA 0,81.6 ? I still have this issue.

**Comment by zsarnett** [comment]
This will be in 0.82

**Comment by matisaul** [comment]
Perfect, thanks!

**Comment by thecesco** [comment]
hi, i still have the issue in 0.99.2

**Comment by frenck** [comment]
@thecesco Please do not use old PR's to report issues on. There is no way to keep track.
Please open a separate issue with all the details. Thanks 👍

**Pull request merged**
