### PR TITLE
Update hui-entity-badge.ts

### PR DESCRIPTION
**Pull request by dhoeben**
## Proposed change

Added option to increase badge size with CSS variables, as this was possible with the old badges as well. Also removed two variables, which are bad practise to use. They are already defined and if changed in themes.yaml (e.g. when opacity set to 0), the current situation will still show the ripple. 

## Type of change

- [X] Dependency upgrade
- [ ] Bugfix (non-breaking change which fixes an issue)
- [X] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml
themes:
  ha-badge-size: 60px
  ha-badge-icon-size:  18px

  #if you want the ripple to show as before
  ha-ripple-hover-opacity: 0.04
  ha-ripple-pressed-opacity: 0.12
```

## Additional information

- This PR fixes or closes issue: fixes #
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [X] The code change is tested and works locally.
- [X] There is no commented out code in this PR.
- [X] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

## Summary by CodeRabbit

- **New Features**
	- Improved styling flexibility of the badge component through the use of CSS custom properties, enhancing adaptability to different themes and sizes.
- **Bug Fixes**
	- Resolved issues related to fixed dimensions, ensuring better responsiveness in various display contexts.

### CODE REVIEW

**Review by frenck — CHANGES_REQUESTED** [review]
What is the impact on this change?

Also, the it seems to be driven from a theme perspective? But these aren't support theme variables, see:

<https://www.home-assistant.io/integrations/frontend/#supported-theme-variables>

../Frenck

**Comment by dhoeben** [comment]
> What is the impact on this change?
> 
> 
> 
> Also, the it seems to be driven from a theme perspective? But these aren't support theme variables, see:
> 
> 
> 
> <https://www.home-assistant.io/integrations/frontend/#supported-theme-variables>
> 
> 
> 
> ../Frenck

The purpose of home assistant is to be customisable. When you are using variables to define the opacity of the ripple, you must not hardcode this in the style. Now, when the user defines the variable in theme.yaml, e.g. to set the opacity of the ripple to 0, this will not have impact on the ripple in the tile card. This is exactly NOT how variables work. Hense, I removed the variable. As it is defined already in the hui-ripple.

Regards,

Douwe

**Comment by dhoeben** [comment]
Also in regard to the variables to be used in themes, the badge size used to be there with the previous badges. As these are now changed, I changed the variable name as well.

**Review by dhoeben — COMMENTED** [review]
.

**Pull request closed without merging**
