### PR TITLE
Replaced Roboto with variable for primary font family

### LINKED ISSUE #21569: Data tables don't use font-family CSS-variable
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

When you override the font-family in your theme/config, there is currently no way to override/adjust the way the text is presented inside the newly introduced data tables. The Roboto font seems to be hard coded, instead of the introduction of a new CSS variable, or relying on the main CSS font variable.

### Describe the behavior you expected

Another CSS variable, which could be overridden/adjusted where it's default value fallback to the main font-family variable.
It would also be nice, to get these (newly created) CSS variables documented somewhere..

### Steps to reproduce the issue

1. Change the font
2. See the data tables inside Settings
4.
...

### What version of Home Assistant Core has the issue?

2024.7.4

### What was the last working version of Home Assistant Core?

_No response_

### In which browser are you experiencing the issue with?

Safari/IE/Chrome/Firefox on MacOS, and the Companion app on iOS

### Which operating system are you using to run this browser?

MacOS/iOS

### State of relevant entities

_No response_

### Problem-relevant frontend configuration

_No response_

### Javascript errors shown in your browser console/inspector

_No response_

### Additional information

_No response_

### LINKED ISSUE #21691: Lovelace has font 'Roboto' hard-coded in certain cards.
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

Roboto is hard coded in some cards for lovelace, whilst others respect the theme. This leads to scenarios where a theme with a particular font does not mesh well agaisnt the default Roboto. 

As an example, in the recently added entity-badge Roboto is hard coded for the font family [hui-entity-badge.ts](https://github.com/home-assistant/frontend/blob/6754b8893b7e025ec622a2ce7cb1acbbccc60deb/src/panels/lovelace/badges/hui-entity-badge.ts#L242):
```
.badge {
    ...
    text-align: center;
    font-family: Roboto;
}
```

In the case of a card that does respect the font (e.g. hui-button-card), it simply does not mention the tag font-family.

Cards that do not respect the font that I know of at the moment are the entity badges, as well as some entity details, logbook, history.
FontDifference
FontDifference2
FontDifference

### Describe the behavior you expected

All cards should respect the theme.

### Steps to reproduce the issue

N/A

### What version of Home Assistant Core has the issue?

2024.8.1

### What was the last working version of Home Assistant Core?

2024.8.1

### In which browser are you experiencing the issue with?

Brave v 1.68.137

### Which operating system are you using to run this browser?

Windows 11

### State of relevant entities

_No response_

### Problem-relevant frontend configuration

_No response_

### Javascript errors shown in your browser console/inspector

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by JuliaSoriaSmith**
## Proposed change

Some cards in home assistant lovelace do not respect the font, e.g. the recently added badges.
I replaced certain instances of the default Roboto being harded coded with the --primary-font-family variable.
badge_after
badge_before

## Type of change

- [ ] Dependency upgrade
- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [X] Code quality improvements to existing code or addition of tests

## Example configuration

Example theme.yaml that changes the font

```yaml

test:

  font-variant-numeric: "Kode Mono"

```

## Additional information

- This PR fixes or closes issue: fixes #21691 fixes #21569
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [X] The code change is tested and works locally.
- [X] There is no commented out code in this PR.
- [X] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

## Summary by CodeRabbit

- **New Features**
	- Updated font management across multiple components by utilizing a dynamic CSS variable for font-family, enhancing flexibility and consistency in styling.

- **Bug Fixes**
	- No bug fixes were included in this release.

- **Documentation**
	- No documentation changes were made.

- **Refactor**
	- Streamlined font styling in various components to improve maintainability and theming capabilities.

- **Chores**
	- No additional chores were performed in this release.

### CODE REVIEW

**Review by silamon — COMMENTED** [review]
Thank you for your contribution! :+1:

From where does the '--primary-font-family' come from? Is that a newly introduced css variable? 
For easiness on usage, it would be better if the css is like: 
`font-family: var(--primary-font-family);` where `--primary-font-family` is set to `"Roboto", "Noto", sans-serif`.

**Comment by JuliaSoriaSmith** [comment]
My mistake I used --primary-font-family oblivious to the paper form system. 
I used paper-font-body1_-_font-family opposed to --primary-font-family. As I understand it paper-font-body1_-_font-family is the common CSS variable for frontend

**Comment by silamon** [comment]
Normally, we're moving away from polymer, but it seems like the css vars are still sticking to the polymer css variables. So yes, that should be correct.

**Comment by nagtegaal** [comment]
Simple, but great patch for more consistency across Home Assistant! Love it...

The add-on page (http://homeassistant.local:8123/hassio/dashboard) and the notification-section (just above your user profile page) also uses the hardcoded Roboto-font, or do not respect the use of the primary_font_family CSS variable.

(Also HACS 2.0 doesn't seem to respect the font-family CSS variable.)

**Comment by nagtegaal** [comment]
> Normally, we're moving away from polymer, but it seems like the css vars are still sticking to the polymer css variables. So yes, that should be correct.

How do you mean we are moving away from polymer? Where is that stated? And what should be the final solution? Is that documented somewhere?

**Review by silamon — CHANGES_REQUESTED** [review]
I'm going to let this be marked as draft until the neccessary changes have been made. If there's anything unclear, feel free to ask.

**Comment by silamon** [comment]
> > Normally, we're moving away from polymer, but it seems like the css vars are still sticking to the polymer css variables. So yes, that should be correct.
> 
> How do you mean we are moving away from polymer? Where is that stated? And what should be the final solution? Is that documented somewhere?

* https://developers.home-assistant.io/blog/2019/05/22/internet-of-things-and-the-modern-web/
* https://developers.home-assistant.io/blog/2023/04/04/deprecating_polymer/

**Comment by nagtegaal** [comment]
> I'm going to let this be marked as draft until the neccessary changes have been made. If there's anything unclear, feel free to ask.

What has to be done to get this included in core? I'm a newbee when it come to using Github for patches, but I would love to get this patch applied to core to things will become a bit better...

**Comment by JuliaSoriaSmith** [comment]
I will change it to use the different font families, but i also want to focus and just change the HA chip card

**Comment by nagtegaal** [comment]
Inside the "notifications"-section, and the subheaders/repairs on the "configuration" page custom font will be ignored:
image

On the voice-assistants page (the uppermost respects the custom font, the other underneath not:
image

All (data)-tables, their select options and buttons are ignoring custom fonts:
image

The HASSIO backups page:
image

The repairs page:
image

The (developer-tools) modal popups:
image

And the (Add-on) iframe pages:
image

image

**Comment by nagtegaal** [comment]
Inside the "notifications"-section, and the subheaders/repairs on the "configuration" page custom font will be ignored:
image

On the voice-assistants page (the uppermost respects the custom font, the other underneath not:
image

All (data)-tables, their select options and buttons are ignoring custom fonts:
image

The HASSIO backups page:
image

The repairs page:
image

The (developer-tools) modal popups:
image

And the (Add-on) iframe pages:
image

image

**Pull request closed without merging**
