### PR TITLE
Add filters to dev-state page

### PR DESCRIPTION
**Pull request by UnrealKazu**
One of the features I've been wanting to add for some time now is the ability to filter on entities on the states page in the developer tools, and I'm not the [only](https://community.home-assistant.io/t/filter-and-sort-entity-ids-in-ha/6647) [one](https://community.home-assistant.io/t/searchable-entities-in-states-tab-of-developer-tools/30683).

I've added three input fields, one for each column in the states table. The entities and states filter work by using simple string comparison. The attributes filter is more complex in code, due to the nature of the attributes object in an entity. If the user enters a string for an attribute, as long as no colon ( : ) has been typed, the string will be matched against all keys and values, and if any of those give a hit, the entity is returned. Once the user has entered a colon, the key must always be matched, and the value is again matched based on string comparison.

All string comparisons work based on simple `.includes()` operations. So part of a key or value is enough to be matched. This to keep the filter flexible and lean, where any user would be able to quickly filter on what the user wants to see.

I've included a gif showing all three filters:

dev_state_filter

This is my first contribution to this project. I've tried to stick as much as possible to the conventions I could see in the rest of the code. Working with Polymer is new for me, so any constructive criticism about that is more than welcome. There was already a nice foundation of the `_entities` object being sorted and mapped, so an `filter()` call was quite easily added.

Regarding translations: because translations are a new thing in HASS, I've left it out for now. Should it be necessary for this PR I will gladly add them.

### CODE REVIEW

**Comment by homeassistant** [comment]
Hi @UnrealKazu, 

It seems you haven't yet signed a CLA. Please do so [here](https://home-assistant.io/developers/cla_sign_start/?pr=home-assistant&#x2F;home-assistant-polymer#595).

Once you do that we will be able to review and accept this pull request.

Thanks!

**Comment by c727** [comment]
Cool feature. Do you know about this: https://jcrowther.io/2015/06/09/polymer-dom-repeat-filtering-and-sorting/

**Comment by UnrealKazu** [comment]
@c727 I looked into some Polymer features that could possibly aid me for this feature. But in the original code I saw `map()` and `sort()` already being used on the `_entities` object, and thus I thought I could just as easily extend on those using `filter()`. I have to admit that the code got bigger than I originally foresaw due to the complexity of the attributes object.

But thanks for the tip, I will look into that!

**Comment by andrey-git** [comment]
@UnrealKazu welcome to Home Assistant frontend!

Please run `yarn test` locally to see eslint errors.

Instead of special-casing Arrays just turn attribute into string via `JSON.stringify` and search in the result.

**Comment by UnrealKazu** [comment]
@andrey-git Thanks, I was completely unaware that my eslint was not running... I'm already on it for fixing those linting problems.

**Comment by balloob** [comment]
Thanks! 🐬  🌮 

And like Andrey said, welcome to frontend dev 👍

**Pull request merged**
