### PR TITLE
Convert tile button into more generic button

### PR DESCRIPTION
**Pull request by piitaya**
## Proposed change

- Convert tile button into more generic button so we can use this button outside tile card (more info dialog for example)
- Add `ha-bar-button-group` component to manage space between buttons and orientation
- Add gallery documentation

Question : Should we rename `ha-bar-slider`, `ha-bar-switch` and `ha-bar-button` to `hui-slider`, `hui-switch` and `hui-button` ? or `ha-control-slider`? or other name ?

## Type of change

- [ ] Dependency upgrade
- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [x] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes #
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [ ] The code change is tested and works locally.
- [ ] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

**Comment by bramkragten** [comment]
> Question : Should we rename ha-bar-slider, ha-bar-switch and ha-bar-button to hui-slider, hui-switch and hui-button ? or ha-control-slider? or other name ?

Why would we rename it? Will it be just for dashboards?

**Comment by piitaya** [comment]
For more info and tile card features. Do you think we can keep `ha-bar-button-group` and `ha-bar-button` ?
image

**Comment by bramkragten** [comment]
Yes, just not sure about the `bar` in the name

**Review by bramkragten — APPROVED** [review]

**Comment by piitaya** [comment]
Yes, I don't like it either 😅

**Pull request merged**
