### PR TITLE
add static colors for waterfurnace states

### PR DESCRIPTION
**Pull request by sdague**
In order to keep these colors stable for state, add all the furnance
states from waterfurnace. These colors from their web UI, but should
be appropriate to other platforms as well.

### CODE REVIEW

**Comment by sdague** [comment]
fyi, is there case folding already, or am I going to have to change states to all be low case?

**Comment by balloob** [comment]
There is no case folding.

I am a bit hesitant to add sensor values to this list, as that can and will grow endless. I think that for now we should limit it to the known states of the entity components (climate, media_player, light)

**Comment by sdague** [comment]
I could map down to the climate states in most cases.... except there is only one HEAT and one COOL state in climate. The furnace has 3 heating modes (heating 1, heating 2, aux heat) and 2 cooling. Which are distinct.

I don't really have a preference on the path to getting those to stable colors, but I'd really like to.

**Comment by balloob** [comment]
I don't like mapping to climate states because then we will have to add new climate states to support a sensor. That's unnecessary coupling.

The color generator could be made deterministic: https://github.com/home-assistant/home-assistant-polymer/blob/master/src/components/entity/ha-chart-base.html#L493

**Comment by c727** [comment]
0.64.1 has a set of colors defined, is this PR still required?

**Comment by balloob** [comment]
This PR seems to have gone stale. Closing it. You can reopen it when you're ready to finish it.

**Pull request closed without merging**
