### PR TITLE
Updated picture-elements demo card

### PR DESCRIPTION
**Pull request by arsaboo**
Updated to add padding, use different elements, and demo entities.

### CODE REVIEW

**Comment by c727** [comment]
I don't like PRs that are obviously untested. Also this is for functional testing so configs should be minimalistic

**Comment by balloob** [comment]
We need all types of elements with various options, which is what I see here?

**Comment by arsaboo** [comment]
@c727 I tested the config locally before posting it here. Let me know if there is anything missing or anything you would like to be modified. 

I won't feel bad if you want to close the PR, if it does not fit the requirements :)

**Comment by arsaboo** [comment]
Ok....I tested the netlify build and the elements all show up (the bedlight toggle does not work, not sure why). 

I won't feel bad if you want to close the PR if it does not fit the requirements :)

**Review by balloob — APPROVED** [review]

**Comment by balloob** [comment]
The light will be fixed when I update how we provide the fake states

**Pull request merged**
