### PR TITLE
Sort automation triggers with drag and drop

### PR DESCRIPTION
**Pull request by piitaya**
## Proposed change
This PR allows triggers sorting with drag and drop gesture. (PR for conditions and actions will follow)

https://user-images.githubusercontent.com/5878303/186643958-70b1a756-dca9-4b2b-8f6b-0c3b6fd7850c.mp4

## Type of change

- [ ] Dependency upgrade
- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

Inspired from `hui-entities-card-row-editor`. There is a lot of technical stuff to make it work (`_attached` and `_renderEmptySortable`). I'm wondering if it is possible de simplify all this stuff.

- This PR fixes or closes issue: fixes #
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [x] The code change is tested and works locally.
- [x] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

**Comment by bramkragten** [comment]
> Inspired from hui-entities-card-row-editor. There is a lot of technical stuff to make it work (_attached and _renderEmptySortable). I'm wondering if it is possible de simplify all this stuff.

I think it should be possible to create an element to handle the drag and drop stuff, that has a slot for the content, that would make it way easier to reuse drag and drop stuff

**Comment by piitaya** [comment]
There is just a little issue, reordering close all expanded blocks 😕

**Comment by bramkragten** [comment]
> There is just a little issue, reordering close all expanded blocks 😕 because the re-render is forced with `_renderEmptySortable` boolean.

I guess we can store which are open, and restore it?

**Comment by piitaya** [comment]
> > There is just a little issue, reordering close all expanded blocks 😕 because the re-render is forced with `_renderEmptySortable` boolean.
> 
> I guess we can store which are open, and restore it?

It breaks that one too : https://github.com/home-assistant/frontend/pull/13407. Drag and drop on that feature is not a easy one 😅

**Comment by balloob** [comment]
Maybe we just want to add a re-order menu item to the "trigger" section (next to the help icon). It would enable a trigger mode in which everything is just titles. No expansion going on.

**Comment by piitaya** [comment]
I would have prefer re-order them without a dedicated mode 😕 But it can simplify the UI. The chevron can be replaced by the drag icon to save space.

**Comment by piitaya** [comment]
I fixed the issue. No dedicated mode is needed.

https://user-images.githubusercontent.com/5878303/186764365-4d1fe5bc-5925-4bd7-bdb1-fa9bbeaeb813.mp4

**Comment by frenck** [comment]
How about we remove the handle (to save space, especially on mobile) and instead, make the whole header draggable (except for, of course, the chevron and overflow menu).

Show the move mouse pointer when hovering over the header.

**Comment by balloob** [comment]
Re-ordering is not a common use case, so I wonder if it is something that we always would want to take up screen real estate.

**Comment by steverep** [comment]
Throwing my 2 cents in...

I wouldn't make this change until there is also a keyboard only way of accomplishing the reorder.  In the initial redesign, @balloob added move up/down buttons for actions, so that feature could be replicated here for triggers.

With that in mind, I would suggest considering if it would create user confusion as to when order matters and when it doesn't, especially if the same mechanism exists for actions as does for triggers and conditions.

At least for actions, the drag icon should be located with the move up/down buttons IMO.

> How about we remove the handle (to save space, especially on mobile) and instead, make the whole header draggable (except for, of course, the chevron and overflow menu).
 
The whole header is the expand/collapse button, not just the chevron.

**Comment by piitaya** [comment]
The up and down arrow can be confusing because there is a chevron now.

Maybe we can group up and down button in a menu like @frenck suggested (or in the dot menu but there already are lot of actions)

image

**Comment by matthiasdebaat** [comment]
Maybe [this article](https://medium.com/salesforce-ux/4-major-patterns-for-accessible-drag-and-drop-1d43f64ebf09) can help in making drag & drop accessible without adding arrows or an overflow menu?

**Comment by steverep** [comment]
@matthiasdebaat that's a good article, especially in noting the need for `aria-live` messages during the operation.  The drag icon could be used also as a toggle button to put an item in and out of reorder mode.

My big criticism of that article in particular would be that it doesn't explain how it's made accessible on mobile.  It's certainly possible though.  The most prominent example that comes to mind is rearranging apps on iOS home screens, although that's much more complicated than just a 1-dimensional reorder.

**Comment by piitaya** [comment]
For a first version, I added the up and down arrows so we can order triggers in the same way as the actions.

**Comment by balloob** [comment]
I also still think that re-ordering  is nice, but it takes up a lot of screen real estate for a feature that is occasionally needed. I think I lean to a dedicated re-order mode.

**Comment by piitaya** [comment]
The firefox issue already exist on entities card editor, I pushed a fix too : https://github.com/home-assistant/frontend/pull/13518

**Pull request closed without merging**
