### PR TITLE
Move Editing of Dashboard to config page

### PR DESCRIPTION
**Pull request by zsarnett**
## Proposed change

CleanShot 2022-05-10 at 10 36 55

## Type of change

- [ ] Dependency upgrade
- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes #
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [ ] The code change is tested and works locally.
- [ ] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

**Comment by frenck** [comment]
I feel like this is a bit inconsistent.

CleanShot 2022-05-11 at 08 11 34

We use the pencil icon

CleanShot 2022-05-11 at 08 12 13@2x

in Automations, Scenes, Scripts & Zones; and could not find any other occurrence using an edit button in the data table.

Is there a specific reason this one is different?

**Comment by spacegaier** [comment]
I agree with Frank. We should be consistent and use the pencil icon here.

**Comment by matthiasdebaat** [comment]
How about this on [desktop prototype](https://www.figma.com/proto/FxvBgKik8oqwnjMx8PWQmc/Tables?page-id=0%3A1&node-id=1%3A99&viewport=1206%2C664%2C0.62&scaling=min-zoom&starting-point-node-id=1%3A99&show-proto-sidebar=1). On desktop we show the buttons on hover. I've also changed the button to `View`, because with the different options added to the table you can open different kind of things.
CleanShot 2022-05-12 at 14 32 10@2x


And this on [mobile prototype](https://www.figma.com/proto/FxvBgKik8oqwnjMx8PWQmc/Tables?page-id=0%3A1&node-id=1%3A259&viewport=1206%2C664%2C0.62&scaling=min-zoom&starting-point-node-id=1%3A259&show-proto-sidebar=1). On smaller devices in an overflow menu.
CleanShot 2022-05-12 at 14 34 23@2x

**Comment by spacegaier** [comment]
Why only show on hover? For the other tables (automations, scripts, ...) we always show the icons. Overflow for narrow screens is a good idea.

**Comment by zsarnett** [comment]
Why should we only do what we have already done? :) Showing on hover is a good way to clean up a dashboard on load. Less Busy.

Just need to make sure it's accessible

**Comment by frenck** [comment]
> Why should we only do what we have already done?

If you want my vote, please don't go the route of big textual buttons in data tables, I might be acceptable in the English language, but especially with translations that can become too large to be friendly (and grow unexpectedly in size). I would prefer the icon in those cases instead.

However, that is a different discussion, not sure if that should be solved in this PR.

**Comment by frenck** [comment]
> I do agree with using the icons for edit instead.

Aah ok, my misunderstanding / bad. 👍

**Comment by spacegaier** [comment]
@zsarnett Do you plan on moving that forward with the pencil icon for the edit mode?

**Comment by frenck** [comment]
We'll close this PR for now. This should originate from out of UX.

../Frenck

**Pull request closed without merging**
