### PR TITLE
Add fan speed control for tile card

### PR DESCRIPTION
**Pull request by piitaya**
## Proposed change

Add fan speed control for tile card if fan supports it.
I also improved the fan entity type.

CleanShot 2022-11-29 at 11 07 02

## Type of change

- [ ] Dependency upgrade
- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes #
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [ ] The code change is tested and works locally.
- [ ] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

**Comment by matthiasdebaat** [comment]
Same as for light brightness, can we show the percentage instead of `on`?

**Comment by piitaya** [comment]
Yes, I will make a PR for that ! For cover too?

**Comment by bramkragten** [comment]
I think we need better support for `step` in the bar slider. While sliding your will not see what value it will snap to, you only see it when release it, and then the value will be set already.

**Comment by matthiasdebaat** [comment]
> I think we need better support for `step` in the bar slider. While sliding your will not see what value it will snap to, you only see it when release it, and then the value will be set already.

Does that mean the device will change value after release? Would expect on drag.

**Comment by piitaya** [comment]
I put the PR in draft because slider is not appropriate when the fan has a few number of steps.

**Pull request closed without merging**
