### PR TITLE
Adds Name and Icon as options on Entities

### PR DESCRIPTION
**Pull request by zsarnett**
image

Small PR to get this started. Later PR to add other options per configType (glance options vs entities options, etc)

### CODE REVIEW

**Comment by iantrich** [comment]
I think these configuration panels would be perfect use cases for [Steppers](https://material.io/archive/guidelines/components/steppers.html) in a future PR

**Comment by balloob** [comment]
The problem we're facing is that not each config element that wants to edit entities has the same options. So we should make it possible to pass in a tag to render the options.

**Comment by zsarnett** [comment]
Right that's what I was saying under the picture. I think I am going to close this PR and re structure. 

Do you think creating an element for each is the best option. Since they are all inputs or somewhat similar we could have a options object array where you pass in the name (name, icon) and the type of input. Also I have looked through every possiblity but if they end up being all input text fields then that makes itmuch easier

**Comment by balloob** [comment]
lol, that's the same discussion as when we talked about card config UI implementation. Let's stick with elements for now. We can either pass the custom element class or the HTML tag as the element to use to the entities editor.

**Pull request closed without merging**
