### PR TITLE
WIP: Ha-card for plant component

### PR DESCRIPTION
**Pull request by PeteBa**
This introduces an ha-card for the Plant component (written by @ChristianKuehnel) that makes visible the plant's state and highlights the cause of any problems (i.e. needs water/fertilzer).

image

This is a work-in-progress and dependent on design decisions progressing in the backend Plant PR (https://github.com/home-assistant/home-assistant/pull/9534) but raising for visibility/comment.

### CODE REVIEW

**Comment by andrey-git** [comment]
What is shown in `more-info`?

Do all of those need to be visible all the time?
Maybe this UI can go into 'more-info' and a state-card will show OK / Problem.

**Comment by PeteBa** [comment]
@andrey-git, exactly the conversation that is going on in the backend thread.

Currently, `more-info` is just the default card with history/attributes of the plant. But request was to allow the user to tap any of the 5 icons of the `ha-card` to bring up a history graph corresponding to the associated underlying sensor.

**Comment by ChristianKuehnel** [comment]
@PeteBa sorry, maybe a stupid question: how can I test your new state-card?
just adding it to the customize and frontend sections of the config file as your last version does not work.

**Comment by c727** [comment]
@ChristianKuehnel you need development environment for the frontend to test this; https://home-assistant.io/developers/frontend/

**Comment by PeteBa** [comment]
@andrey-git, based on your comments in the backend thread, I thought I had better check if the following was a valid approach. Basically, I want one entity's `ha-card` to bring up another entity's `more-info` card, i.e. :

1) The plant entity provides the underlying sensor entity_ids as state attributes

2) An "on-tap" listener is registered on each of the icons in the plant `ha-card`:
```html
  <paper-icon-button
    sensor='[[item]]'
    disabled$='[[computeDisabled(stateObj, item)]]'
    icon='[[computeIcon(stateObj, item)]]'
    on-tap='showSensorHistory'>
  </paper-icon-button>

```
3) The event handler redirects a "hass-more-info" event to associated sensor:
```javescript
  showSensorHistory(ev) {
    ev.stopPropagation();
    var sensor_id = this.stateObj.attributes[ev.target.sensor + '_id'];
    this.fire('hass-more-info', { entityId: sensor_id });
  }
```

I haven't committed/pushed this yet given the conversation is on-going but, please, let me know if you think its a non-starter.

**Comment by c727** [comment]
```
<style>
  .content {
    display: grid;
    grid-template-columns: repeat(5, 1fr);
    width: 100%;
  }
</style>
...
<div class="content">
  <template is='dom-repeat' items='[[config]]'>
    <paper-icon-button
      sensor='[[item]]'
      disabled$='[[computeDisabled(stateObj, item)]]'
      icon='[[computeIcon(stateObj, item)]]'
      on-tap='showSensorHistory'>
    </paper-icon-button>
    </template>
</div>
...
 var _CONFIG = {
    temperature: { sensor: 'temperature', icon: 'mdi:thermometer', uom: '°C' },
    moisture: { sensor: 'moisture', icon: 'mdi:water', uom: '%' },
    brightness: { sensor: 'brightness', icon: 'mdi:white-balance-sunny', uom: 'lx' },
    conductivity: { sensor: 'conductivity', icon: 'mdi:emoticon-poop', uom: 'µS/cm' },
    battery: { sensor: 'battery', icon: 'mdi:battery', uom: '%' }
  }
...
showSensorHistory(ev) {
    ev.stopPropagation();
    var sensor_id = ev.model.item.sensor;
    this.fire('hass-more-info', { entityId: sensor_id });
  }
```

**Comment by PeteBa** [comment]
@c727, that's some great feedback. The new grid css really simplifies a lot. I wish the sensor entity_ids were as straightforward as "temperature" ... but they are more like "sensor.miflora_1_temperature" hence the need to index into this.stateObj attributes. Let me work in your feedback and I'll push the revision. Thanks again.

**Comment by c727** [comment]
@PeteBa I did some corrections... I havn't tested the code but maybe some parts are useful for you

**Comment by c727** [comment]
have you noticed my updates?

**Comment by PeteBa** [comment]
@c727, yes, and thanks again. I have taken on-board the grid css and the fireMoreInfo() simplification. These are great and help reduce line count. I have left the others for the moment as they require agreement with the Plant component author once way forward has been agreed.

**Comment by andrey-git** [comment]
Sorryvto chime in late. Grid is only supported on modern browsers. Don't use it.

**Comment by PeteBa** [comment]
@andrey-git, no problem, thanks for the heads-up.

**Review by balloob — APPROVED** [review]

**Comment by balloob** [comment]
This looks great. Maybe in the future we can start decorating the whole card with a photo of the plant and have the icons be placed on an overlay on it. Kind of like our media player.

**Pull request merged**
