### PR TITLE
Auto remove empty items from shopping list

### LINKED ISSUE #14480: Empty items not dropped from shopping list
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When an item name is left empty in shopping list, it is not dropped/removed. 

This is a bug in the design of the integration.

- This behaviour is inconsistent with the rest of HA, e.g. lists of entities in dashboard
- dropping empty items from lists is intuitive behaviour also outside of HA
- removing individual items is a feature missing from the shopping list integration anyway; this would be a simple clutter-less way of implementing it

### Describe the behavior you expected

Empty labels should drop from the list, as is the case in a lot of homeassistant's UI

### Steps to reproduce the issue

1. add an item to shopping list
2. move keyboard focus away from item
3. item now exists
4. edit item and remove all text in label
5. move keyboard focus away from item
6. item still listed, albeit with empty description
7. repeat as desired and observe many empty shopping list items 

### What version of Home Assistant Core has the issue?

2022.11.2

### What was the last working version of Home Assistant Core?

none

### In which browser are you experiencing the issue with?

latest chrome, firefox, safari, iOS app

### Which operating system are you using to run this browser?

Windows 10, iOS 16, latest macOS

### State of relevant entities

_No response_

### Problem-relevant frontend configuration

```yaml
default integration, working as designed. the bug is in the design as documented, not the implementation.
```

### Javascript errors shown in your browser console/inspector

_No response_

### Additional information

The majority of the items in my list are frequently used items that I re-use all the time, like daily necessities that rarely change. And then there are some rare occasions when I get something special (say, a rug or a pot) 

It doesn't make sense to have to remove _all_ my items and having to re-create the majority to get rid of a minority of them.

Yes, I am aware that I can re-label these, but this issue goes beyond finding additional items to buy, just so I can fill in the blank items in my list.

### PR DESCRIPTION
**Pull request by spacegaier**
## Proposed change
Automatically remove empty shopping list items. Requires https://github.com/home-assistant/core/pull/82992 that adds support for item removal in general.

## Type of change

- [ ] Dependency upgrade
- [ ] Bugfix (non-breaking change which fixes an issue)
- [X] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes #14480
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [X] The code change is tested and works locally.
- [X] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

**Review by Quentame — APPROVED** [review]
LGTM, thanks !

**Comment by spacegaier** [comment]
> Maybe for a new PR, but adding a trash button to remove one item would be awesome. 😉

I had quickly thought about that, but I am not sure if that is really needed. I personally do not use the shopping list feature, but I would assume that normally if you added entries to the list you remove them by completing and then clearing the completed items. Directly removing an item is probably more a niche occurrence and by clearing the name you can now remove them, although that is of course not visually hinted at for the user with is a drawback.

**Comment by spacegaier** [comment]
@matthiasdebaat What do you think about a deletion button? Where would we place that? Having it continuously shown (e.g. next to the existing drag handle) would block quite some space plus next to the drag handle feels a bit risky in terms of accidental clicks (can be mitigated by a confirmation popup which probably would be required regardless of button position).

**Review by bramkragten — APPROVED** [review]

**Comment by richardwonka** [comment]
> … I personally do not use the shopping list feature, but I would assume that normally if you added entries to the list you remove them by completing and then clearing the completed items. …

in our household it’s used extensively. 

There are a lot items that we know will be needed ever so often. Think milk, bread, coffee,… 

These items no one wants to type every time, so we keep ticked items in the list while they’re in stock and untick them when we know we need more. 

Other items are not that frequent (christmas tree, e.g.) and keeping those in the list would clutter the list of daily groceries.

**Comment by spacegaier** [comment]
> 
> Other items are not that frequent (christmas tree, e.g.) and keeping those in the list would clutter the list of daily groceries.

Then for those the new approach to clear the text label would be the way to go.

**Pull request merged**
