### PR TITLE
Revert "Automation/Script editor border-radius fix (#23267)"

### LINKED ISSUE #23486: Tag selector dropdown broken
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

The dropdown for NFC Tags selector seems broken, it's displaying inside of the card / off-screen. On desktop I can only see like two or three items from the dropdown and there's no way of scrolling using your mouse wheel, only way is to navigate the dropdown using keyboard. 

Screen Shot 2024-12-27 at 5 16 05 PM

And on mobile/iPhone, you can only see one item and no way of scrolling the dropdown to select any other tag:

Screenshot 2024-12-27 at 5 29 05 PM

### Describe the behavior you expected

Tag selector dropdown to function normally

### Steps to reproduce the issue

1. Create a few (4) NFC tags in Settings → Tags
2. Go to Automation/Script editor and add a "Tag" trigger
3. See the dropdown is messed up

### What version of Home Assistant Core has the issue?

2025.1.0b2

### What was the last working version of Home Assistant Core?

_No response_

### In which browser are you experiencing the issue with?

_No response_

### Which operating system are you using to run this browser?

_No response_

### State of relevant entities

_No response_

### Problem-relevant frontend configuration

_No response_

### Javascript errors shown in your browser console/inspector

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by MindFreeze**
## Proposed change

The `overflow: hidden` part hides some options when there is a select in the trigger/action so I reverted the PR and added default values for the border radius instead.
Don't squash this PR, pls

## Type of change

- [ ] Dependency upgrade
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes https://github.com/home-assistant/frontend/issues/23486
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [ ] The code change is tested and works locally.
- [ ] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

**Comment by ildar170975** [comment]
> added default values for the border radius instead.

I considered this option in my PR - but is caused this imperfection:
image

Although it is better than clipped options in "select".

**Review by silamon — APPROVED** [review]
I only have the squash available. I'll leave this one unmerged.

**Comment by ildar170975** [comment]
@MindFreeze can you provide clarifications for [this](https://github.com/home-assistant/frontend/pull/23475#issuecomment-2563696072)?
I honestly cannot see how it is possible to use a "select" for a disabled element.

**Comment by MindFreeze** [comment]
@ildar170975 Try the second select in a device trigger

Hmm, actually now it looks like the options are still accessible because the list is scrollable. It's just not obvious because there is no scrollbar and it looks cut off at the top and bottom. This can be considered an issue with the select I guess, but it is still not great that the list area is limited to the height of the trigger card.

Another solution is to add `overflow: hidden` only when it is disabled

**Comment by ildar170975** [comment]
> Try the second select in a device trigger

Yes, see it now. Strange it is not observed with a "state trigger".
OK, will think how to fix that [graphical imperfection](https://github.com/home-assistant/frontend/pull/23475#issuecomment-2563696072) then.

**Comment by MindFreeze** [comment]
`margin: -1px -1px 0` kind of fixes it but it overlaps the disabled background and the border
image

**Comment by ildar170975** [comment]
> margin: -1px -1px 0

Not cool. I will try to find a way.

**Pull request merged**
