### PR TITLE
Style fixes

### PR DESCRIPTION
**Pull request by yosilevy**
## Proposed change

Style cleanup - inline

## Type of change

- [ ] Dependency upgrade
- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [X] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes #
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [X] The code change is tested and works locally.
- [X] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

**Comment by silamon** [comment]
Some older browsers still don't support the CSS logical properties (like margin-inline-start and margin-inline-end) and fallback to the margin-left and margin-right properties. Removing those will probably take away the margin completely if support is missing, but I'm not entirely sure.

**Comment by yosilevy** [comment]
@silamon @bramkragten some devs on the team started entering only the logical properties so I followed suite. We can decide not to do it yet although I don't think users need this. This is common spread by now.

**Comment by bramkragten** [comment]
For the legacy build I want to add a css converter that handles this, let's wait for that

**Comment by yosilevy** [comment]
@bramkragten  Should we delete this PR?

**Comment by piitaya** [comment]
I'm closing the PR as we don't have css converter for that for now. We will remove the unused property when it will have it.

**Pull request closed without merging**
