### PR TITLE
do not hide the logbook in more-info for sensor-entities having a non numeric value

### PR DESCRIPTION
**Pull request by LiBe-net**
## Proposed change

A sensor having a non-numeric value hides the logbook if you click on it opening "more-Info"
For CONTINUOUS_DOMAINS: counter, proximity, sensor, zone the logbook is hidden resulting in custom Sensors representing a text do not show the logbook. For example i have some Template-Sensors which writes some text as State: they belong to the domain "sensor" and therefor the logbook is hidden. More-Info then only shows the color bar chart which is very hard to read.

This Commit additionally only hides the logbook if the CONTINUOUS_DOMAINS entity has a numeric-state. This is releated to: @https://github.com/home-assistant/frontend/issues/18847

and 
@https://github.com/home-assistant/frontend/pull/22724
Suggestion from @karwosts in 22724 was to use history.ts and isNumeric: I have not found where the real state is checked for   numeric: so please correct me if i missed something here or if this issue can be resolved in a better way ...

## Type of change

- [ ] Dependency upgrade
- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes #
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [ ] The code change is tested and works locally.
- [ ] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

image

### CODE REVIEW

**Comment by karwosts** [comment]
Fully checking for a numeric sensor would involve a few things, more than just checking the current state. For example a numeric sensor may be temporarily `Unavailable`. In which case we still want to show the numeric graph. This is done by a few checks:

- Does sensor have a `unit_of_measurement` or `state_class`? (if yes, the numeric)
- Is the device class one of the "numeric device classes" returned in the list from `getSensorNumericDeviceClasses` ? (if yes, then numeric)

If a sensor is technically a number, but has no state class, no UoM, and not one of the numeric device classes, then we typically have treated that as a text sensor instead of a number, because we don't know what else may be in the history.

**Comment by boern99** [comment]
@karwosts 
thank you:  I have not removed the check for unit_of_measurement:  
I tested the code using a sensor which gets unavailable: if unit_of_measurement is available and the state is numeric: the is-numeric check would not jump in: but not sure if it fits all scenarios ..
For now without this commit the none numeric sensor i tested has no state_class or device_class and its value is a text: the logbook would not be loaded. 
Maybe a better solution would be an addition DeviceClass or State class for Non Numeric - Values which could be used for Sensors containing a text? Would add the possibility to enable the logbook for text sensors.

**Comment by boern99** [comment]
thank you. Solved it by using binary-Sensors for my usecases. Feel free to finish working on this or to close this Pull Request ..

**Comment by karwosts** [comment]
Closing as OP does not intend to continue. We can reopen if you decide to come back to it.

**Comment by ildar170975** [comment]
@boern99 
> Solved it by using binary-Sensors for my usecases

There are many users who are using non-numerical sensors & would be happy if you continue this important work.
Ofc not forcing you...

**Pull request closed without merging**
