### PR TITLE
Add demo

### PR DESCRIPTION
**Pull request by balloob**
This adds a build target that builds a demo that will show Lovelace.

 - Powered by `provideHass` from the gallery, so interacting with some domains will update the entity 
 - Navigation to other panels is not working yet
 - Currently using auto-generated Lovelace config, we should convert this to a real Lovelace config

### CODE REVIEW

**Comment by frenck** [comment]
Maybe a bit out of scope, but getting this running on a different location with automated deployments would be really great (e.g., `demo.home-assistant.io`).

That allows us to easily update the demo on release and remove the bit from the web/doc repo as well.

**Review by bramkragten — APPROVED** [review]
I had a quick look, didn't had time to go deep in all 2274 lines...

**Comment by bramkragten** [comment]
@frenck that is the idea :-)

**Comment by bramkragten** [comment]
Running script/develop_demo:
- It builds es5?
- bunch of missing WS Commands (probably known?)
- bunch of missing API Mocks (probably known?) 
- Missing `KeyframeEffect`?
- favicon
- Translations / text missing?
image
image

image

**Comment by bramkragten** [comment]
And this should be filtered from raw config I guess?
image

**Comment by bramkragten** [comment]
Missing text was solved after a refresh

**Comment by balloob** [comment]
We build ES5 in development because prod build is just ES5 to keep deployment simple.

I'll add the missing keyframe. It's a polyfill.

**Pull request merged**
