### PR TITLE
Tell mobile app to scan for Improv devices when 'Add Integration' tap

### PR DESCRIPTION
**Pull request by bgoncal**
## Proposed change

Add event to call the mobile app and ask to start scanning for Improv BLE devices.

ref: https://github.com/home-assistant/iOS/pull/2855

## Type of change

- [ ] Dependency upgrade
- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes #
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [ ] The code change is tested and works locally.
- [ ] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

## Summary by CodeRabbit

- **New Features**
  - Introduced new action based on configuration state that triggers "improv/scan" messages.
  - Added support for detecting if setup improv is possible with the new `canSetupImprov` indicator.

### CODE REVIEW

**Comment by bramkragten** [comment]
Should we do this when you click add integration, or when the integration page is loaded? We scan for USB devices for example when the page is opened.

https://github.com/home-assistant/frontend/blob/dev/src/panels/config/integrations/ha-config-integrations-dashboard.ts#L238

**Comment by bgoncal** [comment]
> Should we do this when you click add integration, or when the integration page is loaded? We scan for USB devices for example when the page is opened.
> 
> 
> 
> https://github.com/home-assistant/frontend/blob/dev/src/panels/config/integrations/ha-config-integrations-dashboard.ts#L238

My ideas was to trigger it as soon as the user taps "add integration" so it knows it is in a "Add device context" and then the mobile app can ask for Bluetooth usage permission etc.
What do you think?

**Comment by bramkragten** [comment]
Since it is discovered I would expect as a user not to have to press on the add device button for it to show up.

The permission is just a one time thing right?

**Comment by bgoncal** [comment]
> Since it is discovered I would expect as a user not to have to press on the add device button for it to show up.
> 
> 
> 
> The permission is just a one time thing right?

Indeed but on top of that I wanted to avoid unecessary usage of Bluetooth, devices & integrations is a page where (at least myself) go through it many times. But we can experiment having it on page load too.

**Comment by bramkragten** [comment]
I can't judge how expensive the scanning is, so I leave that judgement to you, could be a good reason not to do it on page load indeed.

**Comment by bgoncal** [comment]
> I can't judge how expensive the scanning is, so I leave that judgement to you, could be a good reason not to do it on page load indeed.

Sounds good, I'll merge it like this for now until I evaluate the impact and then update it if makes sense

**Review by bramkragten — APPROVED** [review]

**Pull request merged**
