### PR TITLE
Update hassio-host-info.html

### PR DESCRIPTION
**Pull request by pvizeli**
Update info view for next Hass.io release. Actual we support only OTA updates, after the Hass.io OS is out and we can add the support on UI back:
https://github.com/home-assistant/hassio/blob/dev/API.md#host

### CODE REVIEW

**Comment by balloob** [comment]
Looks fine for me. @c727 ?

**Comment by c727** [comment]
`deployment` is normal|beta|dev - I'm not sure if a user needs a 2nd beta option

`hostname` is changeable, is this an additional hostname for `hassio` or does this replace hassio?

maybe we should move host/hardware to a new view...

**Comment by pvizeli** [comment]
@c727,

`hostname` can be everthing and is changeable by user. `deployment` is needed because the update circle is not same as on supervisor and they can be a stable supervisor on a beta OS.

But Yes, in future we should have a new view but for the moment and for the release, I use this to move forward and I'm happy if you do a better version if you have time :)

**Comment by c727** [comment]
For me this was not ready to merge:
- beta mode should also be only visible if activated
- why should we show the hostname there?
- what is `deployment` ist the user runs hassio custom installation?

**Comment by pvizeli** [comment]
@c727 I need this now for the release and I can't wait. There are too many parts they wait of this. Feel free to make better version for next release

**Pull request merged**
