### PR TITLE
Lovelace: Add a label entity row

### PR DESCRIPTION
**Pull request by thomasloven**
This just adds a special row to the entities card in lovelace.

It's a label.
It does nothing but display an icon and a text with slightly larger size (--paper-font-subhead).

label row

## Documentation:
home-assistant/home-assistant.io#6849

### CODE REVIEW

**Comment by balloob** [comment]
It doesn't look nice. It's also too easily confused with interactive elements. Please browse the material design guidelines for an example of headers in lists..

**Comment by thomasloven** [comment]
Yeah... I really should have thought of doing that from the start...
Sorry for wasting peoples time.

more whitespace

**Comment by balloob** [comment]
I like section.

**Review by balloob — APPROVED** [review]

**Comment by balloob** [comment]
Next time a Lit Element? 😉

**Pull request merged**
