### PR TITLE
Add drag and drop to area dashboard

### PR DESCRIPTION
**Pull request by bramkragten**
## Proposed change
Allows areas to be dragged from 1 floor to another.

## Type of change

- [ ] Dependency upgrade
- [ ] Bugfix (non-breaking change which fixes an issue)
- [X] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes #
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [ ] The code change is tested and works locally.
- [ ] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

**Comment by frenck** [comment]
Tested it. If I unassign an area (by dragging it back into the unassigned group), it disappears from the list.

The floor ID gets messed up:

CleanShot 2024-03-30 at 19 54 17@2x

**Comment by piitaya** [comment]
We should disable drag and drop on mobile because that would make the page unscrollable.

**Comment by bramkragten** [comment]
Or should we add a delay?

**Comment by frenck** [comment]
Seems to work well now, just noticed the difference in size of assigned vs unassigned cards:

image

**Comment by bramkragten** [comment]
Fixed

**Comment by piitaya** [comment]
As we can scroll when dragging in mobile, I think it makes more sense to remove the DnD feature on mobile. WDYT?
We can add a nested md-menu to assign floor using an overflow menu per area card on mobile.

**Comment by bramkragten** [comment]
> As we can scroll when dragging in mobile, I think it makes more sense to remove the DnD feature on mobile. WDYT? We can add a nested md-menu to assign floor using an overflow menu per area card on mobile.

I like that is now targeted pure based on if the event was touch, and not just on the screensize...

**Review by piitaya — APPROVED** [review]

**Pull request merged**
