### PR TITLE
add arm_custom_bypass

### PR DESCRIPTION
**Pull request by zsarnett**

### CODE REVIEW

**Comment by c727** [comment]
this is not correct, also no need for this: https://github.com/home-assistant/home-assistant-polymer/blob/dev/src/panels/lovelace/cards/hui-alarm-panel-card.js#L224

**Comment by zsarnett** [comment]
Can you explain why this is not correct and provide a solution? @c727

**Comment by balloob** [comment]
I think one is that we shouldn't add this under the `ui` key, All translations can use the state key. 

We should have a fallback localize key either. The first one should just work.

**Comment by c727** [comment]
I guess you want to add a key for the mode/service `arm_custom_bypass` instead, it "works" cause it uses the state translation instead which can be similar/same. You should separate the localization of states and modes/services to avoid this. `states[]` is also a bad name for the service definition, maybe you should change it.

For static keys like clear_code you can use [[localize('ui.card.alarm_control_panel.clear_code')]].

**Pull request merged**
