### PR TITLE
Move user settings to profile page

### PR DESCRIPTION
**Pull request by balloob**
With the user system, we're planning to lock the configuration page for just owners. So I have moved the browser specific settings to the profile page.

image

### CODE REVIEW

**Comment by awarecan** [comment]
Should it say "You are the owner.", not "an owner." 😄

**Comment by MartinHjelmare** [comment]
Is owner limited to one account?

**Comment by balloob** [comment]
@martin for now yes.

**Comment by awarecan** [comment]
Wrong tagging 😄 

@MartinHjelmare

**Comment by balloob** [comment]
Updating and making the text at beginning of the card translatable will be done in another PR.

**Pull request merged**
