### PR TITLE
Make valid attributes a table instead of raw JSON

### PR DESCRIPTION
**Pull request by robbiet480**

### CODE REVIEW

**Comment by balloob** [comment]
You'll want to remove the margin of the pre used for parameter name.
screen shot 2016-10-30 at 21 32 19

Show a message when no description is available. Differentiate between services known to HA and ones that are not known (known services can still have no description).
screen shot 2016-10-30 at 21 33 07

Show a message that the user has to pick a service/domain when none selected.
screen shot 2016-10-30 at 21 34 29


Soo, in the future maybe we should allow people to fill in values directly next to the description 👍

**Comment by robbiet480** [comment]
@balloob should be good to go

**Comment by balloob** [comment]
One final change: when selecting a new domain, can we auto select the first available service?

**Comment by balloob** [comment]
Ok to merge when comment addressed 🐬

**Comment by robbiet480** [comment]
will most likely do that change tomorrow as well as adding the right side list back thx

**Pull request merged**
