### PR TITLE
Consistent blank before "%"

### PR DESCRIPTION
**Pull request by spacegaier**
## Proposed change

Percent is basically a "unit", so we should consistently have a blank in front of it. In some areas we already do, in other not. With this PR it should now be (more) consistent.

## Type of change

- [ ] Dependency upgrade
- [X] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes #
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [X] The code change is tested and works locally.
- [X] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

**Comment by bramkragten** [comment]
This is going to be another argument :smile:

> English style guides prescribe writing the percent sign following the number without any space between (e.g. 50%). However, the International System of Units and ISO 31-0 standard prescribe a space between the number and percent sign, in line with the general practice of using a non-breaking space between a numerical value and its corresponding unit of measurement.

**Comment by spacegaier** [comment]
My opinion is that we should be consistent. Since we treat "%" as a unit in some places, we should do it everywhere (and that way be consistent with ISO rather that "just" one language even if it is EN). E.g. in the sensor card we have separation as we consider it the unit:
grafik

We do the same already for some/many entity rows:
grafik

Currently this leads to those inconsistencies:
grafik

grafik

**Comment by bramkragten** [comment]
I'm ok with adding the space, was just mentioning that it could lead to another round of arguments :-)

**Comment by spacegaier** [comment]
> 
> 
> I'm ok with adding the space, was just mentioning that it could lead to another round of arguments :-)

I am fine with arguing for consistency, so point them to me :) .

I resolved the merge conflicts. Let me know if everything looks good.

**Review by bramkragten — APPROVED** [review]

**Pull request merged**
