### PR TITLE
Hass.io panel localization - dashboard

### PR DESCRIPTION
**Pull request by ludeeus**
## Proposed change

- Adds localization to the "dashboard" section of the Hass.io panel.
- For the part where there were no installed addons, I changed the inline href to an action button instead (was not sure how that would have been handled with localizations).

image

### Not translated:

- "Add-ons" (Title over the installed addons)
- Home Assistant Core (Title in update card)
- Supervisor(Title in update card)

## Type of change

- [ ] Dependency upgrade
- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Additional information

- This PR fixes or closes issue: fixes #
- This PR is related to issue: 
- Link to documentation pull request: 

## Checklist

- [x] The code change is tested and works locally.
- [x] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io
_more to come_

### CODE REVIEW

**Comment by ludeeus** [comment]
I'll hold off the rest of the panel until we get this in, in case I did something wrong, and that way I do not need to play whack-a-mole with merge conflicts 🙈

**Comment by ludeeus** [comment]
Note to self, keys need adjustment after panel rename

**Comment by bramkragten** [comment]
This is tricky, as the releases of the supervisor and home assistant core are not aligned, the translations for the supervisor could not be available in home assistant core. So the supervisor probably needs its own translation file.

**Comment by balloob** [comment]
Yeah, we need to break out the hassio translations for this to work.

**Comment by balloob** [comment]
Going to close this since it won't work with the current approach. We need translation plumbing to get this to work.

**Pull request closed without merging**
