### PR TITLE
Add custom selectUnit, use in relativeTime function

### LINKED ISSUE #11130: Timestamp sensor shows "last year" while only 10 days ago
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Timestamp sensors like "last boot" from the systemmonitor integration or "Up time" from Brother Printer integration now show the text "last year" which is not very helpful.
The timestamp has only been like 10 days ago (2021-12-29T15:45:18+00:00)

### Describe the behavior you expected

Display a text representing a shorter duration. 
It showed texts like "last week" before.

### Steps to reproduce the issue

1. Get a timestamp sensor entity with timestamp in last year
2. Look at entity in an entities card or in the device screen and see "last year"

### What version of Home Assistant Core has the issue?

core-2021.12.8

### What was the last working version of Home Assistant Core?

_No response_

### In which browser are you experiencing the issue with?

Version 96.0.4664.110 (Official Build) (64-bit) and 95.0.2 (64-bit)

### Which operating system are you using to run this browser?

Windows 10

### State of relevant entities

```txt
entity:
sensor.last_boot
Last boot

state:
2021-12-29T15:45:18+00:00	

attributes:
device_class: timestamp
friendly_name: Last boot

and

entity:
sensor.hl_3140cw_uptime
HL-3140CW Uptime

state:
2021-12-05T14:46:53+00:00

attributes:
device_class: timestamp
friendly_name: HL-3140CW Uptime
```

### Problem-relevant frontend configuration

```yaml
entities:
  - entity: sensor.processor_use
  - entity: sensor.load_1m
  - entity: sensor.load_5m
  - entity: sensor.load_15m
  - entity: sensor.network_throughput_out_eth0
  - entity: sensor.network_throughput_in_eth0
  - entity: sensor.disk_free
  - entity: sensor.last_boot
show_header_toggle: false
title: Home Assistant status
type: entities
```

### Javascript errors shown in your browser console/inspector

```txt
no errors in console
```

### Additional information

image

Since it just started happening recently I guess it is due to the timestamp being in the previous year.

### PR DESCRIPTION
**Pull request by mvarrieur**
## Proposed change

Use custom implementation of `selectUnit` which prioritizes shorter timespans over longer ones.

## Type of change

- [ ] Dependency upgrade
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes #11130
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [x] The code change is tested and works locally. 
- [x] There is no commented out code in this PR. (I put a link to the original MIT license code that this was using before in a comment, if you don't want that let me know and I can remove it)
- [x] Tests have been added to verify that the new code works.

Note: I had an issue with testing this, I don't think the current tests for this file are even running. I added an intentionally failing test and couldn't get the test suite to fail. I did add a test for moving from one year to the next, but I really do not think it is actually running, unless CI operates differently than local.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

**Comment by homeassistant** [comment]
Hello @mvarrieur,

When attempting to inspect the commits of your pull request for CLA signature status among all authors we encountered commit(s) which were not linked to a GitHub account, thus not allowing us to determine their status(es).

The commits that are missing a linked GitHub account are the following:


- [`c71e0544dca4c537fdf429e8266b7954adc7ddcf`](https://github.com/home-assistant/frontend/pull/14008/commits/c71e0544dca4c537fdf429e8266b7954adc7ddcf) - This commit has something that looks like an email address (mike.varrieur@gmail.com). Maybe try linking that to GitHub?.


Unfortunately, **we are unable to accept this pull request until this situation is corrected.**

Here are your options:

1. If you had an email address set for the commit that simply wasn't linked to your GitHub account you can link that email now and it will retroactively apply to your commits. The simplest way to do this is to click the link to one of the above commits and look for a blue question mark in a blue circle in the top left. Hovering over that bubble will show you what email address you used. Clicking on that button will take you to your email address settings on GitHub. Just add the email address on that page and you're all set. GitHub has more information about this option [in their help center](https://help.github.com/articles/setting-your-email-in-git/#commits-on-github-arent-linking-to-my-account).

2. If you didn't use an email address at all, it was an invalid email, or it's one you can't link to your GitHub, you will need to change the authorship information of the commit and your global Git settings so this doesn't happen again going forward. GitHub provides some great instructions on how to change your authorship information [in their help center](https://help.github.com/articles/setting-your-email-in-git/).
   * If you only made a single commit you should be able to run
      ```
      git commit --amend --author="Author Name <email@address.com>"
      ```
      (substituting "Author Name" and "`email@address.com`" for your actual information) to set the authorship information.
   * If you made more than one commit and the commit with the missing authorship information is not the most recent one you have two options:
       1. You can re-create all commits missing authorship information. This is going to be the easiest solution for developers that aren't extremely confident in their Git and command line skills.
       2. You can use [this script](https://help.github.com/articles/changing-author-info/) that GitHub provides to rewrite history. **Please note:** this should be used only if you are very confident in your abilities and understand its impacts.
   * Whichever method you choose, I will come by to re-check the pull request once you push the fixes to this branch.

We apologize for this inconvenience, especially since it usually bites new contributors to Home Assistant. We hope you understand the need for us to protect ourselves and the great community we all have built legally. The best thing to come out of this is that you only need to fix this once and it benefits the entire Home Assistant and GitHub community.

Thanks, I look forward to checking this PR again soon! :heart:

**Comment by mvarrieur** [comment]
Just wanted to make sure this part was surfaced: Note: I had an issue with testing this, I don't think the current tests for this file are even running. I added an intentionally failing test and couldn't get the test suite to fail

**Comment by homeassistant** [comment]
Hi mvarrieur

It seems you haven't yet signed a CLA. Please do so [here](https://home-assistant.io/developers/cla_sign_start/?pr=home-assistant/frontend#14008).

Once you do that we will be able to review and accept this pull request.

Thanks!

**Comment by homeassistant** [comment]
Hi mvarrieur

It seems you haven't yet signed a CLA. Please do so [here](https://home-assistant.io/developers/cla_sign_start/?pr=home-assistant/frontend#14008).

Once you do that we will be able to review and accept this pull request.

Thanks!

**Review by bramkragten — APPROVED** [review]
Thanks!

**Pull request merged**
