### PR TITLE
Add a way to use a value of an attribute in conditional card

### PR DESCRIPTION
**Pull request by PiotrMachowski**
## Proposed change
Added a new optional field: `attribute` to card's configuration. When an attribute is provided, a value of given attribute is used instead of entity's state to calculate card's visibility.

## Type of change

- [ ] Dependency upgrade
- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

Lovelace:
```yaml
type: conditional
conditions:
  - entity: binary_sensor.example_sensor
    state: value_1
    attribute: example_attribute
card:
  type: entities
  entities:
    - entity: sun.sun
```
Configuration.yaml:
```yaml
input_boolean:
  helper:
    name: Helper
template:
  - binary_sensor:
      - name: Example sensor
        state: "{{ is_state('input_boolean.helper', 'on') }}"
        attributes:
          example_attribute: >
            {% if is_state('input_boolean.helper', 'on') %}
              value_1
            {% else %}
              value_2
            {% endif %}
```

## Additional information

- ~~This PR fixes or closes issue: fixes #~~
- ~~This PR is related to issue or discussion:~~
- Link to documentation pull request: https://github.com/home-assistant/home-assistant.io/pull/21151

## Checklist

- [x] The code change is tested and works locally.
- [x] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [x] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

**Comment by PiotrMachowski** [comment]
I made it in a similar way to `entity` card

**Comment by spacegaier** [comment]
@bramkragten So your proposal would be to leave it out of the editor, but in general support using the attribute via the YAML mode?

I think that would then be consistent with the Entities card where I think attribute rows are also only supported via YAML.

**Comment by bramkragten** [comment]
Yes

**Comment by PiotrMachowski** [comment]
👍 I will adjust my PR

**Comment by spacegaier** [comment]
@PiotrMachowski Tomorrow is beta cutting day. So if this change should still make it, the adjustment needs to happen soon, if it should still get in.

**Comment by PiotrMachowski** [comment]
@zsarnett sorry, I was busy with vacuum map card, I will try to adjust this PR today

**Review by zsarnett — APPROVED** [review]

**Comment by zsarnett** [comment]
Nice. Now just need a quick Doc PR if you can

**Comment by PiotrMachowski** [comment]
Documentation PR added: https://github.com/home-assistant/home-assistant.io/pull/21151

**Comment by zsarnett** [comment]
Nice!. Github action is broken so Ill run that again

**Comment by zsarnett** [comment]
Thinking about this, I believe the condition card and picture elements card only update their rendering if the state of the entity changes. Therefore, if using attribute we may not update when the attribute changes but only when the attribute changes and the state changes

**Comment by zsarnett** [comment]
After discussing this with Bram and Paulus, because entities should be moving their attributes to more entities this will become less and less of a feature that is needed. Along with the experience of an attr changing but the conditional not because we only look at state changes is another issue.

We shouldn't do this for those reasons...

**Pull request closed without merging**
