### PR TITLE
Fix state_color for button

### PR DESCRIPTION
**Pull request by iantrich**
## Type of change

- [ ] Dependency upgrade
- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes #
- This PR is related to issue: 
- Link to documentation pull request: 

## Checklist

- [ ] The code change is tested and works locally.
- [ ] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

**Review by bramkragten — APPROVED** [review]

**Comment by sblantipodi** [comment]
@iantrich @bramkragten 
just updated to 0.106.1, issue is not fixed. problem still there exactly as before.

**Comment by iantrich** [comment]
Doesn't look like a frontend build got tagged

**Comment by sblantipodi** [comment]
@iantrich this means that they don't released your fix?

**Comment by bramkragten** [comment]
It is in 0.106.2

**Pull request merged**
