### PR TITLE
Show if a custom integration overwrites a core integration

### PR DESCRIPTION
**Pull request by MindFreeze**
## Proposed change

Sometimes users override a core integration, without them knowing they do. This often results in unexpected behavior.
While it is part of the design of core to allow for overriding core integration, we should make the user more aware they actually are override a core integration.

~~I do need some input on the design. Ideally I would've replaced the custom component icon with the same + an exclamation mark, but there isn't such an icon in Material icons. So the options I see are:~~
- ~~Add a new icon. This is the current implementation in this PR~~
- ~~Change the icon from `package-variant` to something else but what?~~
- ~~Change the color of the icon to something more prominent. The icons in the selector for a new integrations don't have color though~~

The design decision was to change the color and tooltip
image

## Type of change

- [ ] Dependency upgrade
- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes #
- This PR is related to issue or discussion:
- Link to documentation pull request:
- Link to backend PR: https://github.com/home-assistant/core/pull/127937

## Checklist

- [x] The code change is tested and works locally.
- [x] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

**Comment by MindFreeze** [comment]
I would really prefer to change the custom integration icon somehow, rather than add a new one because they become redundant. If it overwrites core, than it must be custom.

**Comment by silamon** [comment]
I couldn't find a better icon so it could be combined. In the end you want this to stand out to let the user know that they have overridden the core integration. 

I'm not sure if "overwrites" is the correct term that explains it all, you've used overridden and my first thought would be to replace a core integration.

**Review by piitaya — APPROVED** [review]

**Comment by frenck** [comment]
backend has been merged.

**Comment by marcinbauer85** [comment]
The design used to implement changes: https://www.figma.com/design/zSpQQiJb0AEc6jRaKIkL5l/HA-03?node-id=2001-646&node-type=section&t=3EL1cUmDRXaQVVcV-11

**Pull request merged**
