### PR TITLE
Remove redundant text in Cloud panel #3824

### LINKED ISSUE #3824: Remove redundant text in Cloud panel
**Home Assistant release with the issue:**
0.99.3

**Description of problem:**
The Alexa and Google Assistant cards in Cloud panel contain some redundant text (red rectangles in pic below). You can see where the arrows are pointing that this information is already mentioned above.

cloud-panel

The italicized text in the red rectangles should be removed to clean up the cards a little, unless there are any objections? This would be an easy one for Hacktoberfest.

### PR DESCRIPTION
**Pull request by shmooey**
This fixes #3824 

image

### CODE REVIEW

**Comment by homeassistant** [comment]
Hi @shmooey, 

It seems you haven't yet signed a CLA. Please do so [here](https://home-assistant.io/developers/cla_sign_start/?pr=home-assistant&#x2F;home-assistant-polymer#3967).

Once you do that we will be able to review and accept this pull request.

Thanks!

**Review by iantrich — APPROVED** [review]

**Comment by bramkragten** [comment]
Should we remove this or rephrase, I think it can be helpful for people to know what kind of devices are Alexa/Google Assistant-enabled?

**Comment by SeanPM5** [comment]
My line of thinking was:

* These cards are getting a little bit crowded/cluttered now and this text seems entirely unnecessary
* The text on the first line ("via any Alexa-enabled device") should already make it clear that all devices are supported. It's hard to misinterpret "any Alexa-enabled device" but once you start listing specific devices under that, I feel like that muddies the water a bit.
* If we start listing specific models, then people are just going to get confused when their model isn't listed. "It says Echo Dot, but I have an Echo Show, am I unsupported? What about this Echo Studio they just announced? Echo Flex?" 

I think removing it cleans up the card a little and also reduces any possibility for confusion.

**Review by bramkragten — APPROVED** [review]
OK, sounds reasonable

**Pull request merged**
