### PR TITLE
Change to thermostat card to reflect step_temp on set-temperature

### PR DESCRIPTION
**Pull request by bannhead**
Reference https://github.com/home-assistant/home-assistant-polymer/pull/4219

This is my proposal to change the graphic aspect of the set temperature when the thermostat works with whole temperature steps.

### CODE REVIEW

**Comment by Molodax** [comment]
I don't think that is is a good idea to show a decimal for current temperature when it is equal to 0 just for sake of "consistency".

**Comment by bannhead** [comment]
My code changes impact only set temperature. Thermostat card set current temperature to whole if F and to halves if C, but give priority over this to target_temperature_step

My code only impacts set temperature.  The thermostat card shows the current temperature step in whole if F and in halves if C, but gives priority to target_temperature_step if supplied by the thermostat.

My only change is to reflect the same to the other parameter, set temperature.

**Comment by bramkragten** [comment]
Please rebase this PR

**Comment by bramkragten** [comment]
Your PR targets the branch `new-round-slider` this should be `dev`

**Review by bramkragten — APPROVED** [review]

**Pull request merged**
