### PR TITLE
Fix script config editor

### LINKED ISSUE #13663: New scripts are called 'New Script' regardless how I name them (v2022.9.0)
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When creating a new script, I put a name in the 'Name' field but when hitting 'Save', Home Assistant stores it as 'New Script' regardless of the name I entered

### Describe the behavior you expected

The script should be saved with the name I gave it

### Steps to reproduce the issue

1. create new script
2. name script
3. add actions @ sequence
4. save script
...

### What version of Home Assistant Core has the issue?

2022.9.0

### What was the last working version of Home Assistant Core?

2022.8.7

### In which browser are you experiencing the issue with?

Chrome 104.0.5112.102, Firefox 104.0.1 (64-bits)

### Which operating system are you using to run this browser?

Windows 11 Pro

### State of relevant entities

_No response_

### Problem-relevant frontend configuration

_No response_

### Javascript errors shown in your browser console/inspector

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by piitaya**
## Proposed change

Script editor config form was broken

## Type of change

- [ ] Dependency upgrade
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes #13663
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [ ] The code change is tested and works locally.
- [ ] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

**Comment by piitaya** [comment]
@zsarnett I'm not sure about the change. Why is there return instead of break for 2 cases? Is this wanted?

**Comment by zsarnett** [comment]
The code after doesnt need to run right? The id changed function updates the values therefore the code looking at changing the config isn't needed. 

At least that was what I thought. I think. I don't remember

**Comment by piitaya** [comment]
I tested and the first key to iterate is always "mode". The "return" keyword exits the `for` loop, so the other keys are not checked.

**Comment by zsarnett** [comment]
Ah gotcha.

**Review by zsarnett — APPROVED** [review]

**Comment by piitaya** [comment]
I don't understand how this can work during past months 😅

**Pull request merged**
