### PR TITLE
add favicon.svg to public/icons

### PR DESCRIPTION
**Pull request by NovapaX**
see home-assistant PR to add it to template head.
https://github.com/home-assistant/home-assistant/pull/10290

### CODE REVIEW

**Comment by balloob** [comment]
This one is black. Our current favicon is blue.

**Comment by balloob** [comment]
Ah read up on it, it's for Apple stuff.

**Comment by balloob** [comment]
Can you remove `home-assistant-icon.svg` as it's no longer used? (why is that one so big anyway, that's horrible)

**Comment by NovapaX** [comment]
Yes, its only for macOS Safari (pinned tabs) currently.
The color of the icon is styled in the <link> tag in the head of the html.

That old `home-assistant-icon.svg` is so big because it's has quite a lot of raster/png data embedded (shadow and gradient)
I will make a PR on home-assistant-assets later to add some nice vector only svg files. I think assets/icons should include some basic artwork even if its not used and only if its not too big?

**Comment by balloob** [comment]
No, the frontend should only contain assets related to the frontend. Extra graphics can go to the `home-assistant-assets` repo. 

Can you also rename the file from favicon to mask-icon ? That way it's clear what it is used for.

**Pull request merged**
