### PR TITLE
replace ToggleSwitch with new LightSwitch

### PR DESCRIPTION
**Pull request by Mariusthvdb**
now that has become the new default for switch, might be better to use that too in the device_class on/off states
and make it mimic a physical switch even better.

## Proposed change

Apr-04-2022 16-44-34

current:

Apr-06-2022 10-16-38

## Type of change

- [ ] Dependency upgrade
- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes #
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [ ] The code change is tested and works locally.
- [ ] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

**Comment by matthiasdebaat** [comment]
I would prefer `mdi-toggle-switch-variant` and `mdi-toggle-switch-variant-off`. It got less details that works better for a small icon.

**Comment by Mariusthvdb** [comment]
and for the default keep mdiLightSwitch ? Or also change to mdiToggleSwitchVariant

**Comment by matthiasdebaat** [comment]
> and for the default keep mdiLightSwitch ? Or also change to mdiToggleSwitchVariant

We should keep it consistent and go for `mdiToggleSwitchVariant`

**Comment by Mariusthvdb** [comment]
really odd, my VSC prettier checker says no problems in this workspace..?

**Review by zsarnett — APPROVED** [review]

**Pull request merged**
