### PR TITLE
Add logic to find best device domain match + show correct brand logo

### LINKED ISSUE #14620: Brand Icons for entities from multiple integrations
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

I have some Shelly 1PM (and other models) devices I setup with the same exact steps. Those devices are provided to HA from two integrations Shelly and Unifi Network. The thing is that they are not represented the same in HA especially in regards to Brand Logo!

Attached some screenshots.

### Describe the behavior you expected

Device brand icons to be represented according to their manufacturer.

### Steps to reproduce the issue

1. No specific steps!!
01 Multiple Integration Entities
02 Device ONE
03 Device TWO

### What version of Home Assistant Core has the issue?

Home Assistant 2022.11.0

### What was the last working version of Home Assistant Core?

_No response_

### In which browser are you experiencing the issue with?

Version 108.0.5359.95 (Official Build) (64-bit)

### Which operating system are you using to run this browser?

HA is installed on Intel NUC

### State of relevant entities

_No response_

### Problem-relevant frontend configuration

_No response_

### Javascript errors shown in your browser console/inspector

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by spacegaier**
## Proposed change

Try to determine the "most correct" domain that should therefore be used to display the brands icon.

Both domain and integration names are used, since the manufacturer name does not necessarily match directly the domain, but it might the more user friendly name.

On the device page, we do not yet have the integration names available, although I could of course add a look-up here as well, so we have exactly the same logic int he device dashboard and the device info page.

## Type of change

- [ ] Dependency upgrade
- [X] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes #14620
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [X] The code change is tested and works locally.
- [X] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

**Comment by steverep** [comment]
FYI, there is a long relevant discussion about these icons in https://github.com/home-assistant/frontend/pull/14184#discussion_r1004933061.

The issue author wrote that the expectation would be that the brand icon be that of the device manufacturer, which I agree with.  Does this change accomplish that?

**Comment by spacegaier** [comment]
> FYI, there is a long relevant discussion about these icons in [#14184 (comment)](https://github.com/home-assistant/frontend/pull/14184#discussion_r1004933061).
> 
> The issue author wrote that the expectation would be that the brand icon be that of the device manufacturer, which I agree with. Does this change accomplish that?

Haven't seen this discussion yet and it seems to be a long one...

Yes, this PR would make sure that if a device is covered by multiple integrations, the one matching the manufacturer is chosen for the icon.

Currently, that is not the case, e.g. I have some Shelly plugs that are of course part of the Shelly integration but the same devices are also linked to the AVM Fritz!Box integration which comes from my router which also detected those plugs in the network and tracks them. So one device covered by two integrations and currently it is more or less random which icon is shown. As the manufacturer is Shelly all should show Shelly, but for some the AVM icon is shown since for some that integration is randomly sorted in the first place (I think it depends on the GUIDs assigned to the configuration entries).

So with this PR we should (at least most of the time) show the correct brand icon matching the manufacturer.

**Comment by steverep** [comment]
If I'm reading the code correctly, this is only able to pick the manufacturer's icon if the device happens to also be included by a manufacturer-aligned integration.  But that would leave out several common situations.

For example, I have several Zooz devices integrated via Z-Wave JS that will still show the Z-Wave icon instead of Zooz.  Or I have a Honeywell thermostat integrated via Homekit controller that will still show the Homekit icon.

**Comment by bramkragten** [comment]
I don't like this, I think integrations should give us some info about what kind of integration it is, so we can prioritize better.

**Comment by spacegaier** [comment]
There is now a new arch discussion about enhancing the backend to provide that reliable information: https://github.com/home-assistant/architecture/discussions/936

**Pull request closed without merging**
