### PR TITLE
Add title to backups config page

### PR DESCRIPTION
**Pull request by spacegaier**
## Proposed change

So far the `hass-tabs-subpage-data-table` only added a header slot in narrow mode, which meant that in non-narrow the new config backup page had no proper header shown.

## Type of change

- [ ] Dependency upgrade
- [X] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes #
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [X] The code change is tested and works locally.
- [X] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

**Comment by zsarnett** [comment]
The tabs are the header, right?

**Comment by bramkragten** [comment]
> The tabs are the header, right?

Yes, and it is now made so that if there is only one tab, that will be used as header, and no tabs are shown

**Comment by bramkragten** [comment]
And by adding a single tab, it will now render a title:
https://github.com/home-assistant/frontend/pull/12444

**Comment by bramkragten** [comment]
We would need a `hass-subpage-data-table` instead of `hass-tabs-subpage-data-table`

**Comment by spacegaier** [comment]
Doesn't work probably due to https://github.com/home-assistant/frontend/pull/12439

**Comment by spacegaier** [comment]
Chatted with Bram and the behavior is as expected. For a single tab subpage, no header is to be shown if there is a search bar on top. I adjusted the search label for clarity.

**Review by bramkragten — APPROVED** [review]

**Pull request merged**
