### PR TITLE
Add title option to picture card

### PR DESCRIPTION
**Pull request by spacegaier**
## Proposed change
With the new image entity, I tested adding the Wifi QR code into a dashboard, but having a picture card without any context/title is weird. Hence I added the support for an optional title.

One thing to note is that in the light theme it might looks slightly off, as there seems to be a lot of empty space, but in my case that is actually due to the image, see screenshot from dark mode.

image

image

If we agree on that addition, I will create the doc PR.

## Type of change

- [ ] Dependency upgrade
- [ ] Bugfix (non-breaking change which fixes an issue)
- [X] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes #
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [X] The code change is tested and works locally.
- [X] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

**Comment by bramkragten** [comment]
Not sure... the picture entity card can already do this, but has a pretty different styling for than this:

CleanShot 2023-06-29 at 09 52 29@2x

**Comment by spacegaier** [comment]
Yes, I saw that card as well and my barcode scanner actually was able to parse despite the half transparent overlay at the bottom, but it looks wrong (different styling and overlaying the image itself). The title approach I proposed would visually match other cards such as Entities, Alarm Panel, Shopping List, ... everything that has a card header.

**Comment by bramkragten** [comment]
I think we should not add a different type of title to this card, in fact, I think we should remove this card and merge it with the picture entity card, because it can do exactly the same. If we want to make changes to the title it should be done for all image cards, so it stays consistent.

**Comment by maxistviews** [comment]
Can picture cards be used in the entities card? Because that would help with titling how OP wishes.

**Comment by maxistviews** [comment]
This is still something that should be considered.

**Comment by jlpouffier** [comment]
Hello 👋 

We reviewed this PR internally and it started a fruitful conversation that I will try to summarize here.

The unfortunate `TL;DR` is that we will reject and close this PR.

The gist of our conversation was:

**We have too many cards used to represent an image.**
- The `picture` card that has almost no functionality (expect a tap/hold action)
- The `picture entity` card that contains 100% of the functionality of the picture card but adds a few more _(Including a title)_
- The `picture elements` card _(that is the most complex one)_
- The `picture glance` card _(That can be used to quickly display the states of a few entities at once)_
  
**We do not know yet where we want to go with titles on picture cards.**
The current title on the `picture entity` card is definitely not perfect, as it covers part of the image, which is sub-optimal for a QR Code for example, but this is what we currently have, and we cannot create a new design pattern on a card so similar.
For sure, we want only one way to display an image with a title, if possible with only one card 😊 

Because of the 2 above reasons, we are actually thinking about dropping the `picture` card (We just need to figure out how to smoothly migrate installation using it)
And because we want to drop this card, we do not want to add any functionality on it at that point.

**Pull request closed without merging**
