### PR TITLE
Force reconnect when triggered from external bus

### PR DESCRIPTION
**Pull request by balloob**
## Proposed change

When the socket gets unresponse on iOS 15, it also won't respond to `close()`. This changes the external reconnect command to use the new force reconnect feature in HAWS which doesn't wait for old socket to trigger close.

~~Also renames the external command to `reconnect` instead of `restart` as that makes more sense.~~ Not renaming because it's already available in iOS 2021.12.

Requires https://github.com/home-assistant/home-assistant-js-websocket/pull/224

FYI @zacwest

## Type of change

- [x] Dependency upgrade
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes #
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [ ] The code change is tested and works locally.
- [ ] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

**Comment by balloob** [comment]
Let's not merge this until Zac has verified it works. If it works, we should include it with a frontend hot fix because it fixes the annoying websocket lost errors in iOS 15.

**Comment by zacwest** [comment]
I believe this resolves the issue where the close wasn't working (since it was trying to close gracefully) -- backgrounding the app and issuing this command causes the WebSocket to immediately reconnect when I believe it would otherwise have been stuck before.

**Comment by zacwest** [comment]
Darn, not fully. At least one case of it failing to work. Let me make sure I'm not holding it wrong.

**Comment by zacwest** [comment]
OK, I'm reasonably confident that this helps the connection status in a positive way. I'm seeing the connect/reconnect cycle a lot tighter.

I believe when the reconnect happens, the WebView errors (possibly only if more info is showing, this has been my test case) and removes all visual content, with something like:

```
2021-12-20 00:30:52.185 [Verbose] [main] [WebViewController.swift:832] userContentController(_:didReceive:) > message {     colno = 49;     filename = "\"undefined\"";     lineno = 210;     message = "\"TypeError: null is not an object (evaluating 'notifications.length')\""; }
2021-12-20 00:30:52.185 [Error] [main] [WebViewController.swift:892] userContentController(_:didReceive:) > WebView error: ["lineno": 210, "colno": 49, "filename": "undefined", "message": "TypeError: null is not an object (evaluating 'notifications.length')"]
2021-12-20 00:30:52.186 [Verbose] [main] [WebViewController.swift:832] userContentController(_:didReceive:) > message {     colno = 49;     filename = "\"undefined\"";     lineno = 210;     message = "\"TypeError: null is not an object (evaluating 'notifications.length')\""; }
2021-12-20 00:30:52.186 [Error] [main] [WebViewController.swift:892] userContentController(_:didReceive:) > WebView error: ["lineno": 210, "colno": 49, "filename": "undefined", "message": "TypeError: null is not an object (evaluating 'notifications.length')"]
2021-12-20 00:30:52.187 [Verbose] [main] [WebViewController.swift:832] userContentController(_:didReceive:) > message {     colno = 49;     filename = "\"undefined\"";     lineno = 210;     message = "\"TypeError: null is not an object (evaluating 'notifications.length')\""; }
2021-12-20 00:30:52.187 [Error] [main] [WebViewController.swift:892] userContentController(_:didReceive:) > WebView error: ["lineno": 210, "colno": 49, "filename": "undefined", "message": "TypeError: null is not an object (evaluating 'notifications.length')"]
2021-12-20 00:30:52.187 [Verbose] [main] [WebViewController.swift:832] userContentController(_:didReceive:) > message {     colno = 49;     filename = "\"undefined\"";     lineno = 210;     message = "\"TypeError: null is not an object (evaluating 'notifications.length')\""; }
2021-12-20 00:30:52.187 [Error] [main] [WebViewController.swift:892] userContentController(_:didReceive:) > WebView error: ["lineno": 210, "colno": 49, "filename": "undefined", "message": "TypeError: null is not an object (evaluating 'notifications.length')"]
2021-12-20 00:30:52.187 [Verbose] [main] [WebViewController.swift:832] userContentController(_:didReceive:) > message {     colno = 49;     filename = "\"undefined\"";     lineno = 210;     message = "\"TypeError: null is not an object (evaluating 'notifications.length')\""; }
2021-12-20 00:30:52.187 [Error] [main] [WebViewController.swift:892] userContentController(_:didReceive:) > WebView error: ["lineno": 210, "colno": 49, "filename": "undefined", "message": "TypeError: null is not an object (evaluating 'notifications.length')"]
```

Seems to require a full refresh to get out of showing all blank when this happens.

It's possible I'm logging the filename incorrectly in JS to the WebView, sorry about the confusingness of that part.

**Review by bramkragten — APPROVED** [review]

**Comment by bramkragten** [comment]
> notifications.length

I'll fix this in another PR

**Comment by zacwest** [comment]
OK I'm not seeing the `notifications.length` error log anymore, but I am seeing the WebView blank itself out when the restart command resolves an otherwise-dead WebSocket connection; it doesn't appear to cause an issue when the connection wasn't dead, oddly enough.

**Comment by zacwest** [comment]
Oh no I'm still seeing the notifications.length when it reproduces, I think, e.g.:

2021-12-20 17:16:35.368 [Verbose] [main] [WebViewController.swift:832] userContentController(_:didReceive:) > message {     colno = 295032;     filename = "\"http://10.0.2.2:8123/frontend_latest/app.2b82fe2c.js\"";     lineno = 887;     message = "\"TypeError: null is not an object (evaluating 'e.length')\""; }
2021-12-20 17:16:35.368 [Error] [main] [WebViewController.swift:892] userContentController(_:didReceive:) > WebView error: ["lineno": 887, "message": "TypeError: null is not an object (evaluating 'e.length')", "colno": 295032, "filename": "http://10.0.2.2:8123/frontend_latest/app.2b82fe2c.js"]

**Pull request merged**
