### PR TITLE
Fix zwave js handling multiple config entries

### LINKED ISSUE #12136: Z-Wave options do not appear if Switch as X is first in Integration list
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When I have a Z-Wave device setup with Switch as X, if it is listed first in the integrations the additional Z-Wave options do not show up in the device page. If Z-Wave JS shows up first I do get the proper config options.

image

### Describe the behavior you expected

Z-Wave configuration options should always be available:

image
image

### Steps to reproduce the issue

Configure multiple Z-Wave switch entities with "Switch as X" and view device page.

### What version of Home Assistant Core has the issue?

dev

### What was the last working version of Home Assistant Core?

_No response_

### In which browser are you experiencing the issue with?

all

### Which operating system are you using to run this browser?

Windows 11, iOS

### State of relevant entities

_No response_

### Problem-relevant frontend configuration

_No response_

### Javascript errors shown in your browser console/inspector

_No response_

### Additional information

_No response_

### LINKED ISSUE #12641: Switch as X integration disables zwave_js configuration
### The problem

I 'converted' nearly all of my Zwave switches to either lights or fans using the 'Switch as X' integration.  However, doing so means that I cannot write a new automation via the UI that triggers on state change of the device (e.g. it being turned on or off, or a zwave value changing).  Also once the switch is converted, you cannot view the zwave configuration for it anymore.

e.g. config of switch before - note the zwave config options

image

after:  zwave info not available

image

Trigger not available when switch as light

image

### What version of Home Assistant Core has the issue?

core-2022.5.1

### What was the last working version of Home Assistant Core?

_No response_

### What type of installation are you running?

Home Assistant OS

### Integration causing the issue

Switch as X

### Link to integration documentation on our website

https://www.home-assistant.io/integrations/switch_as_x

### Diagnostics information

_No response_

### Example YAML snippet

_No response_

### Anything in the logs that might be useful for us?

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by bramkragten**
## Proposed change

Fixes https://github.com/home-assistant/frontend/issues/12641
Fixes https://github.com/home-assistant/frontend/issues/12136

## Type of change

- [ ] Dependency upgrade
- [X] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes #
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [ ] The code change is tested and works locally.
- [ ] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

**Comment by raman325** [comment]
out of curiosity, instead of doing all of this in the frontend, should we just update the core to accept a device_id instead of node_id and entry_id and do all of this logic there? We already have to preprocess this information to get the node in the core, so maybe we just take the complexity there?

**Comment by bramkragten** [comment]
Yeah, that would work too

**Comment by raman325** [comment]
@MartinHjelmare any thoughts on this? While it's a bigger change, I think moving this complexity to the core is the right way to handle this.

**Comment by MartinHjelmare** [comment]
Sounds good!

**Pull request closed without merging**
