### PR TITLE
Rework plant card

### PR DESCRIPTION
**Pull request by c727**
Initially I was checking the code cause the card needs some seconds to show values after a restart but this is backend related..

- restructured the code a bit
- hide non-existend sensors
- minor design changes
current:
old
PR:
plant

### CODE REVIEW

**Comment by raccettura** [comment]
It would be super nice if missing sensors were hidden and it made the card smaller. 

Here's my use case: Right now I've got several of them one below the other in landscape mode. Requires scrolling and lots of dead space. If the card was narrower it could fit multiple on the screen and make much more economical use of the space.

In my case I've got a group with all the battery usage of random devices, so battery is just duplication on mine. I'd gladly trade that duplication for less scrolling on these really spaced out cards.

**Comment by c727** [comment]
@raccettura screenshot please, can't follow you

**Comment by c727** [comment]
...that is not related to this PR, there is already an issue for this

**Review by balloob — APPROVED** [review]

**Comment by PeteBa** [comment]
@c727, like the code clean-up! Can you double check case when battery=100 as I'm getting "mdi:battery-100" (doesn't exist) rather than "mdi:battery"

**Comment by c727** [comment]
hups, thank you

**Pull request merged**
