### PR TITLE
Add "paste list" option to shopping list card

### PR DESCRIPTION
**Pull request by jenseo**
## Proposed change

I found the following proposal of a new feature for the shopping list integration/card, making it possible to paste a list of items, instead of adding them one by one:

[https://github.com/home-assistant/frontend/issues/6224](https://github.com/home-assistant/frontend/issues/6224)

This PR implements this by letting the user switch between "single input mode" or "multi line input mode" in a textarea. Each new line (identified by line breaks) will be considered a new item.

Small demo of current state of the proposed change, showing: 

- A paste of the list 
- A manual input of multiple items at once 
- The functionality to trim unneeded spaces around the item and exclusion of empty items.

screen-capture

## Type of change

The user can now decide if he/she wants to input each item one by one, or paste a whole list (maybe someone sent it by SMS, not an uncommon scenario in our family at least) at once. The user can also write a multiline list in the textarea introduced in this PR. Once he/she hits the add button, each row on in the text box are converted into list items. 

I have also introduced trim() on each string, to make sure no empty spaces or such are added to the list by mistake.

Some new strings has been introduced that I guess need to be translated. Not sure exactly what the process are on these?

Apart from this, I removed some legacy stylings that were no longer having an effect on the svg icons, which seems to have changed since this component was built. I also tried to align it slightly better in terms of margin/padding so that it looks and behaves more like the other cards generated from scratch in the dev environment container.

I didn't find the location of the tests, so I wasn't able to add any. But will of course update the PR once you give me directions on how to find the tests :)

- [ ] Dependency upgrade
- [ ] Bugfix (non-breaking change which fixes an issue)
- [ X ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ X ] Code quality improvements to existing code or addition of tests

## Example configuration

No configuration needed more than activating the shoppingList integration and trying out the shopping list card and of course the pasting list option in particular.

## Additional information

- This PR implements the following feature request:
[https://github.com/home-assistant/frontend/issues/6224](https://github.com/home-assistant/frontend/issues/6224)

## Checklist

- [ X ] The code change is tested and works locally.
- [ X ] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

I didn't find the location of the tests, so I wasn't able to add any. But will of course update the PR once you give me directions on how to find the tests :)

### CODE REVIEW

**Comment by homeassistant** [comment]
Hi @jenseo, 

It seems you haven't yet signed a CLA. Please do so [here](https://home-assistant.io/developers/cla_sign_start/?pr=home-assistant&#x2F;frontend#9971).

Once you do that we will be able to review and accept this pull request.

Thanks!

**Comment by bramkragten** [comment]
How about we always allow multi-line input, but still add it when pressing enter? So you can paste a multi-line list.

The buttons for the modes are not really clear, and I don't think a user will understand how to use them without some documentation.

**Comment by jenseo** [comment]
@bramkragten You mean only having one text field for both cases? Yes, I thought about it but thought maybe it would then be a bit hidden for existing users. 

Also needs some logic for when to get the event clipboard content and when to get it from the text field (value in text field won't be available when the paste event fires I believe)

So if you rather have one field, I can definitely do that. :)

**Comment by jenseo** [comment]
Or did you mean not using the paste event at all? That's perfectly fine as well of course

**Comment by bramkragten** [comment]
> Or did you mean not using the paste event at all? That's perfectly fine as well of course

Why do we use the paste event data? The content of the clipboard will be in the text area at that point right?

**Comment by jenseo** [comment]
@bramkragten I noticed it wasn't, perhaps due to render cycles or perhaps due to developer overlooking something 😁

Can investigate some more, but maybe we should decide first on what the end result should be so to say?

**Comment by bramkragten** [comment]
> @bramkragten I noticed it wasn't, perhaps due to render cycles or perhaps due to developer overlooking something 😁

Probably timing.

> Can investigate some more, but maybe we should decide first on what the end result should be so to say?

Yes, agree, @matthiasdebaat our UX designer, can probably help us with that when is back from his vacation.

**Comment by jenseo** [comment]
@bramkragten Sounds like a plan. Will add the screenshots, no problem

**Comment by jenseo** [comment]
@bramkragten @matthiasdebaat Screen capture added :)

**Comment by matthiasdebaat** [comment]
To summarize and check if I understand correctly. There are three use cases for creating the shopping list:
1. Hit `enter` and there's a new checkbox.
2. Type multiple lines that results in multiple checkboxes. 
3. Paste multiple lines that results in multiple checkboxes. 

I like your idea for adding a different editing mode when you want a multi-line input. LinkedIn got `Press enter to send` checkbox option in it's chat (now days in an overflow menu). We could introduce a same pattern? I like this more then two buttons.

When pasting multiple lines, can we automatically switch to the multi-line input mode?

**Comment by jenseo** [comment]
@matthiasdebaat Yes, you understand it correctly :)

1. Existing functionality.
2. In my solution, as of now, this is when the user has switched input mode to "paste mode/multi line input". 

Will need to check out the Linkedin chat, but sounds doable. 

A paste will automatically create the multilines and I guess this could switch the input mode as well, but maybe it's not clear for the user if it's not displayed somehow?

Not sure if I interpret your idea of input mode correct though, it might be that I'm still stuck in the solution I have done up to this point :)

**Comment by jenseo** [comment]
Ah, now I understand the Linkedin part, yeah, a checkbox would work of course!

**Comment by jenseo** [comment]
@matthiasdebaat Love it! Yes, shift + enter could probably work for multiline input if needed. And a paste would automatically create multiple items if multiple rows.

**Comment by jenseo** [comment]
So, what should we go with? One mode, shift makes it possible to add multiple lines at once and paste of multiple lines instantly creates items?

**Comment by matthiasdebaat** [comment]
> So, what should we go with? One mode, shift makes it possible to add multiple lines at once and paste of multiple lines instantly creates items?

Yeah, lets go with that!  I've updated the design in Figma, including:
- Overlay menu with the current two options `Show drag tool` and `Clear checked item`.
- Checkbox icon in front of the input instead of the plus icon.

This all makes it more consistent en cleaner.
https://www.figma.com/file/TgFCEL62MNhYGhygW7qthI/Shopping-list-multiple-lines?node-id=0%3A1

**Comment by jenseo** [comment]
> - Overlay menu with the current two options `Show drag tool` and `Clear checked item`.

Great, just one question:

The current behavior of the checked items is that they jump from the list to a "new list" of checked items so to say.

Then the "clear checked items" button becomes more of an action than a setting so to say.

Do you mean that the checkbox would instead remove all items at once if checked, and skip the separate list part.

And is it is not checked, should the "clear checked items" action button still appear?

**Comment by matthiasdebaat** [comment]
Just made this small prototype, in the hope it makes things clear: https://www.figma.com/file/TgFCEL62MNhYGhygW7qthI/Shopping-list-multiple-lines?node-id=0%3A1

You can interact with the `Burger` checkbox and the overflow menu

**Comment by jenseo** [comment]
@matthiasdebaat Yes, I understood how you meant, but to make sure we're discussing the same thing and to clarify what I meant with my question:

In the original shopping list card, this is how it behaves when you check an item (see screen capture below):

1. You check an item and it jumps to a new list of checked items
2. Once you click the "clear checked items" _button_, an action is fired clearing them all.

Here's a screen capture of what I mean:

screen-capture

So, my question is if your Figma sketch/prototype...:

- ...intend to replace this functionality
-  ...mean that the user can switch between the traditional separate checked items list and a new mode making all checked items to be removed instantly.

Maybe @bramkragten also have some input on the subject? 

I don't want to implement anything based on us not having communicated properly of course 😄 

Thanks guys, hopefully we can sort this so that we can actually get this improvement included soon 🙂

**Comment by matthiasdebaat** [comment]
> In the original shopping list card, this is how it behaves when you check an item (see screen capture below):
> 
> 1. You check an item and it jumps to a new list of checked items
> 2. Once you click the "clear checked items" _button_, an action is fired clearing them all.
> 
> 
> So, my question is if your Figma sketch/prototype...:
> 
> * ...intend to replace this functionality
> * ...mean that the user can switch between the traditional separate checked items list and a new mode making all checked items to be removed instantly.

Good for asking!! The interaction design is actual the same, only the visual design changed. So it's still the same as your screen capture, only the `Checked items` title and margin is removed. This makes the checked items the last items on the list. 

I agree, communicating via text isn't the best. If you like we could do a video call?

**Comment by bramkragten** [comment]
Sounds good to me, only thing is that your are hiding the options a little more in the overflow menu, but I think that's fine...

**Comment by jenseo** [comment]
Thanks, now it's all crystal clear, so no call necessary at this time 😊 Will reach out if any questions arise, but for now all is covered. 

Hopefully I will get some free time soon to be able to implement.

**Comment by jenseo** [comment]
I agree that a checkbox icon feels a bit odd, since you can't distinguish it from the actual checkboxes.

The idea with having the sorting function "always on" is really interesting in my opinion and would be beneficial when you quickly want to order a list based on store sections when shopping for instance. And might be unnecessary to "hide it" behind a menu so to say.

Need to look into that part of the code to see if anything hinders it.

My spontaneous best case scenario would probably be to keep the plus icon as is, with functionality the same. We could move it to the right of the input though if that makes more sense.

If it's possible to keep the reordering always on, I don't really see the menu that important anymore. Instead we could make sure the "remove checked items button" appear as soon as you check something. We might need to rethink its location though, based on the new, compact design without a separate checked items section.

The menu feels a bit like an unnecessary click, I agree on that.

**Comment by matthiasdebaat** [comment]
> Why do we hide the drag and drop in the overflow menu? We should just make that always draggable no?
> (I know that is a change from now as you have to toggle it)
> We seem to be adding to much to the top of the check list when not needed.

I like the idea to make it always draggable, but I don't want to show al the extra icons. Can we make the row draggable? 

One thing I wanted with this design is to make it simpler. You can see that it's checked so there's no need for a title above the checked items. An `add` button in front of an input is strange. If we make it always draggable we could place the `+` after the input, so that's nice. Only need to find a spot for the `Clear checked item` button. 


> Google put it on the left, personally, makes sense to me.

I couldn't find the Google example, can you share a screenshot with us?

**Comment by bramkragten** [comment]
Didn't mean we should implement that, was just context.

**Comment by jenseo** [comment]
> Didn't mean we should implement that, was just context.

Phew 😄

**Comment by jenseo** [comment]
Ok, so I have implemented what we have discussed above. Since the fields needs to editable also after they are added to the list, I decided to keep the draggable indicator on each unchecked item, to make things a bit more understandable for the user. Let me know if you think otherwise.

Here's a small screen capture of what we've got now:

screen-capture

**Comment by matthiasdebaat** [comment]
> Ok, so I have implemented what we have discussed above. Since the fields needs to editable also after they are added to the list, I decided to keep the draggable indicator on each unchecked item, to make things a bit more understandable for the user. Let me know if you think otherwise.
> 
> Here's a small screen capture of what we've got now:
> 
> screen-capture

Really really nice! [Nielson Norman Group](https://www.nngroup.com/articles/drag-drop/) also advice to show handle icons, so good choice. It looks less pretty, but it's more usable.

> Also realized now when I saw the screen captures that we probably want the icon before the add item input field to stay aligned at the top of the field at all times, also when adding multiple lines. So, I'll fix that tomorrow. Now off to bed!

Yeah, I agree.

**Comment by matthiasdebaat** [comment]
Could we change te cursor to the closed hand when you start to drag?
image

**Comment by jenseo** [comment]
> Could we change te cursor to the closed hand when you start to drag? image

Actually I tried to do that, but there seems to be a bug in the sorting package that is implemented that makes it hard to get it to work properly. I gave it one and a half hour before giving up. I could give it another go, but most solutions in their git repo seems to be kind of hacky getting it to work. A bit afraid it would introduce side effects since HA is such a huge application.

**Comment by bramkragten** [comment]
You will have to login to your instance in every browser, the token is stored in the browser.

**Comment by zsarnett** [comment]
@jenseo Would you be open to splitting this PR into smaller PRs that build on one another?

**Comment by jenseo** [comment]
@zsarnett Apologies for the late reply and that this PR has been abandoned, we have some tough times in the family so I haven't had the time nor the energy to work on this. Can definitely be split up, I agree with @bramkragten that it has grown a bit too much, it's hard to have an overview atm. 

Not sure I will be able to finish this for the time being, maybe someone wants to pick it up where I left it a while ago?

**Comment by dennykorsukewitz** [comment]
Noooo 😢

**Pull request closed without merging**
