### PR TITLE
Fix displayed month when opening date range picker

### LINKED ISSUE #15800: Extended history graph does not offer actual month in data select
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Hello,

if I click in history graph to the month field, the system offered me by default February instead of March which is the current month.

Why?

### Describe the behavior you expected

I expected that the system offer actual month in the date select field.

### Steps to reproduce the issue

1. click to some entity
2. on History graph click show more
3. click to file for date select
4. there is showed February insted of March
...

### What version of Home Assistant Core has the issue?

2023.3.3

### What was the last working version of Home Assistant Core?

_No response_

### In which browser are you experiencing the issue with?

_No response_

### Which operating system are you using to run this browser?

_No response_

### State of relevant entities

_No response_

### Problem-relevant frontend configuration

_No response_

### Javascript errors shown in your browser console/inspector

_No response_

### Additional information

_No response_

### LINKED ISSUE #15802: Calendar in history is stuck in February
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

The calendar for selecting date ranges is stuck displaying February. As we roll over into a new week, I always have to advanced the month to March so I can select current date ranges. 

2A05208E-04B1-4711-81B7-933BFEA2FB77

### Describe the behavior you expected

I would expect that it would align itself to either the start date or end date of the currently selected date.

### Steps to reproduce the issue

1. In history, select a date. 

### What version of Home Assistant Core has the issue?

Supervised

### What was the last working version of Home Assistant Core?

Believed to be 2023.2 since it was the correct month

### In which browser are you experiencing the issue with?

Firefox. Companion app (iOS) 

### Which operating system are you using to run this browser?

Windows 10; Debian 11; iOS 16.3.1

### State of relevant entities

_No response_

### Problem-relevant frontend configuration

_No response_

### Javascript errors shown in your browser console/inspector

_No response_

### Additional information

I believe this to be related to 2023.3 updates, but because it got stuck in February, it may have been an issue since 2023.2. 

I help manage other instances, and all seem to exhibit this behaviour. All are running 2023.3 or newer.

### PR DESCRIPTION
**Pull request by piitaya**
## Type of change

- [ ] Dependency upgrade
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes #15800, fixes #15802
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [ ] The code change is tested and works locally.
- [ ] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

**Comment by karwosts** [comment]
I think with this change we lose the second time picker, that seems bad? I don't see any way to adjust the end time. 

image

**Comment by bramkragten** [comment]
This happens because we hide the second calendar table, and the march is in the right column...

https://github.com/home-assistant/frontend/blob/dev/src/components/date-range-picker.ts#L214-L216

**Comment by piitaya** [comment]
Oh I see... I didn't see that css override and I didn't understand why it didn't work.

CleanShot 2023-03-13 at 17 35 13

Should the range option display 2 time-pickers and one calendar ? Looks like a bug in the dependency.

**Comment by piitaya** [comment]
I used another approach to fix the issue

**Review by bramkragten — APPROVED** [review]

**Comment by bramkragten** [comment]
> I used another approach to fix the issue

Nice!

**Comment by oziee** [comment]
does this also fix the same problem within the Logbook UI for selecting the dates ?

**Pull request merged**
