### PR TITLE
Add precipitation to weather card

### PR DESCRIPTION
**Pull request by escoand**
I've added the precipitation into the forecast chart.

Pull-request for OpenWeatherMap component: https://github.com/home-assistant/home-assistant/pull/13971

### CODE REVIEW

**Comment by c727** [comment]
stupid question: no weather component has data for this in its forecast. so where do you get the data from?

**Comment by c727** [comment]
please test your stuff before you create a PR

**Comment by escoand** [comment]
Which came first, chicken or egg? In this case both: https://github.com/home-assistant/home-assistant/pull/13971

**Comment by c727** [comment]
Link the PR in the description please and add screenshots

**Comment by escoand** [comment]
Thanks for reopening. I've referenced the other way around and this is visible on the website. But you're right, it's not visible ie in the OctoDroid Android App.

**Review by c727 — APPROVED** [review]

**Comment by escoand** [comment]
Currently there is no unit for the values, but this is a problem for the temperatures as well. The openweathermap precipitation is in mm. Should we at this to the HTML?

**Comment by c727** [comment]
we have units defined here hass.config.core.unit_system -> length. for metric we use [mm]

**Comment by c727** [comment]
... and imperial uses inch/in.
the conversion (if required) should be done by the backend part

**Comment by escoand** [comment]
Ok, thanks I'll look into it. But I meant if the unit should be visible.

**Comment by escoand** [comment]
Backend PR was merged. Maybe we do the unit thing in a second PR.

**Comment by c727** [comment]
```javascript
getUnit(measure) {
  if (measure === 'precipitation') {
    return this.getUnit('length') === 'km' ? 'mm' : 'in';
  }
  return this.hass.config.core.unit_system[measure] || '';
}
```
what about the more-info-card? https://github.com/home-assistant/home-assistant-polymer/blob/master/src/dialogs/more-info/controls/more-info-weather.html

**Comment by escoand** [comment]
Don't know if every weather provider gives this value as mm/inch or if we get rain probability and therefore should pass the unit together with the data.

**Comment by c727** [comment]
Then you should check this

**Comment by c727** [comment]
I solved the merge conflicts in #1221, If we get problems with incorrect units that should be fixed in main repo components

**Pull request closed without merging**
