### PR TITLE
Give media image in media bar some space

### PR DESCRIPTION
**Pull request by spacegaier**
## Proposed change

Currently the media image is glued to the sidebar. Now it can breathe :)

I don't really care about the specific pixel value, so feel free to propose better suiting ones.

**Before:**
image

**After:**
image

## Type of change

- [ ] Dependency upgrade
- [X] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes #
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [X] The code change is tested and works locally.
- [X] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

**Comment by bramkragten** [comment]
I think there have been discussions about this? @matthiasdebaat @zsarnett ?

**Comment by matthiasdebaat** [comment]
Great fix @spacegaier! In my design I had the same spacing on the left as top and bottom. Like your proposal, if an image isn't square we should constrain proportions and move the text to the right.

**Comment by zsarnett** [comment]
We shouldn't add space to the left. This cuts down on readable text and isn't needed. We should be giving as much real estate to the image as possible.

**Comment by bramkragten** [comment]
Note that the space on the top is only there because the image is not square, for a square image there is no spacing on the top.

**Comment by balloob** [comment]
Bram is correct. All media is either square or portrait mode, which doesn't have this issue.

**Comment by spacegaier** [comment]
> Bram is correct. All media is either square or portrait mode, which doesn't have this issue.

Well obviously, that is not always the case, since that image is in landscape mode 😉. It is from the new Radio Browser (station "UKNova" from Antarctica).

And I feel we should be able to handle that.

**Comment by zsarnett** [comment]
We should just catch if the image doesn't load. We wont be able to catch all cases for images being weird width/heights

**Comment by zsarnett** [comment]
We could just use `background-size: cover` but that would hide part of your image

**Comment by balloob** [comment]
We can listen to the `load` event and detect if `width > height` and do something.

**Comment by balloob** [comment]
Radio station logos are not traditional media covers like we know for movies/music

**Comment by spacegaier** [comment]
How do we proceed here with the landscape formats?

**Comment by balloob** [comment]
Maybe listen to the `load` event on the image, check ratio and set a class?

**Comment by spacegaier** [comment]
Set a class that is then cutting off the landscape image to enforce a square render?

**Comment by zsarnett** [comment]
I think giving the image extra spacing takes away from the image in most cases. We can put together a new PR to catch the image and analyze it. If you want to do that in this PR you can and re open

**Pull request closed without merging**
