### PR TITLE
Prevent selecting a non-existant entity in history page

### LINKED ISSUE #15665: History page: let's prevent selecting a non-existing entity
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Currently it is possible to select a non-existing entity:

image

Recently there was a glitch when selecting such an entity caused a hang; this seems to be fixed.
But still it is possible to select it.
Proposal: allow only selecting a listed element.

### Describe the behavior you expected

as above

### Steps to reproduce the issue

as above

### What version of Home Assistant Core has the issue?

2023.3.0

### What was the last working version of Home Assistant Core?

_No response_

### In which browser are you experiencing the issue with?

Chrome 110.0.5481.178 

### Which operating system are you using to run this browser?

Win10x64

### State of relevant entities

_No response_

### Problem-relevant frontend configuration

_No response_

### Javascript errors shown in your browser console/inspector

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by silamon**
## Proposed change

I've went back in history and the allow custom entity was added 6 years ago upon introduction. I don't think it's needed anymore. Its the only picker that allow selecting a custom entity. 

## Type of change

- [ ] Dependency upgrade
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes #15665
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [x] The code change is tested and works locally.
- [x] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

**Comment by bramkragten** [comment]
I think it is (should be?) possible to select an entity that is removed from the state machine but still has history?

**Comment by ildar170975** [comment]
Currently it is possible to select even non-existing entity like “sensor.xyzxyzxyz”, this should be prevented imho.

**Comment by silamon** [comment]
> I think it is (should be?) possible to select an entity that is removed from the state machine but still has history?
I've tested it and it is indeed possible. Still only for the history, not for the logbook.

**Comment by silamon** [comment]
> I think it is (should be?) possible to select an entity that is removed from the state machine but still has history?

Given this, it's not possible to remove the allow-custom-entity at this time.

**Pull request closed without merging**
