### PR TITLE
Add automation editor

### PR DESCRIPTION
**Pull request by balloob**
Ultra experimental raw beta, ok?

 - Uses Preact to do the rendering.
 - Edit any automation in `automations.yaml` in config dir
 - Supported triggers: event, numeric_state, state (no for)
 - Supported action: call_service
 - Supported browser: Chrome (will reevaluate when Polymer 2 lands)

screen shot 2017-05-08 at 20 40 10

### CODE REVIEW

**Comment by maddox** [comment]
😍

**Comment by pvizeli** [comment]
I like it

**Comment by MartinHjelmare** [comment]
I like the "journey" metaphor. We could make that metaphor for all the parts of the automation.

"Like a journey, every automation starts with a single step... "

"Before you can travel, make sure you have packed your bags. Define conditions that are checked before letting the automation continue."

"Where do you want to travel today? What should the automation do?"

**Comment by balloob** [comment]
lol, that was more a placeholder to make sure that I add real text, which I didn't end up doing 😝

**Comment by balloob** [comment]
This also adds yet another panel to do configuration. This will all be merged into the config panel in the future.

**Comment by maddox** [comment]
*nitpic*: maybe `from` should come before `to` on the trigger panel to more exhibit the `->` transition

**Comment by balloob** [comment]
@maddox fixed, merging it now and pushing out a dev build. I bet that there will be a lot to nitpic 👍

**Comment by aequitas** [comment]
Great to see automations being brought to the UI. +1 for keeping the UI configuration in sync with config files. IMHO one of the big benefits of HA is the ability to keep everything in source control due to the use of human editable configuration files over a database.

**Pull request merged**
