### PR TITLE
Improve person/alarm/lock state

### PR DESCRIPTION
**Pull request by piitaya**
## Proposed change

Add variables for alarm disarmed, person away and lock unlocked. 

**Lock**
CleanShot 2022-12-09 at 17 55 39

**Alarm**
CleanShot 2022-12-09 at 17 58 47

**Person**
CleanShot 2022-12-09 at 18 00 10

## Type of change

- [ ] Dependency upgrade
- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes #
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [ ] The code change is tested and works locally.
- [ ] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

**Comment by lymanepp** [comment]
IMO, unlocked should be red and locked should be green (or default color).

**Comment by piitaya** [comment]
> IMO, unlocked should be red and locked should be green (or default color).

And for the alarm?

**Comment by lymanepp** [comment]
> And for the alarm?

IMO, exceptional cases should get colors and the "normal" cases should use the default color. So the alarm being disarmed is probably the "normal" case and would be the default color.

**Comment by piitaya** [comment]
For a lock, normal case is unlocked (when your alarm is disarmed). 

Here's implemented logic. 

You enter the house:
Lock unlocked (default)
Alarm disarmed (default)
You leave the house: 
Lock locked (colored)
Alarm armed (colored)

Same logic for devices that serve the same purpose : protect the house 😅

**Comment by lymanepp** [comment]
> For a lock, normal case is unlocked (when your alarm is disarmed).

That's a logic change from 2022.11 and previous. I prefer the old way as it no longer stands out to me when I have a door unlocked.

I check my HA dashboard at night to see if the house is in the proper state before bedtime. Anything highlighted needs to be addressed. Well, that's how it used to be. Now ,it appears that the locks are in an exception state.

image

**Comment by zhimsel** [comment]
I'll agree with @lymanepp that the logic (to me) seems backwards. Green should be the "safe" state. Specifically, armed and locked. When things are "unsafe" (disarmed, unlocked), the house is "vulnerable". This is the "exception" state.

I can see how the opposite viewpoint could be held, though, so this is purely a point of opinion. Given that it's configurable via themes, I'm okay with the default being whatever. What I'm most interested in is that the `disarmed` and `unlocked` states be given back a named color/css class (which this PR does).

**Comment by piitaya** [comment]
Yes the two logics are right, we should just have the same for both entities : lock and alarm.

I just used the alarm logic that was implemented for years in HA.

As there is a variable, this will be configurable in themes.

**Comment by Mincka** [comment]
> Yes the two logics are right, we should just have the same for both entities : lock and alarm.
> 
> I just used the alarm logic that was implemented for years in HA.
> 
> As there is a variable, this will be configurable in themes.

Why use the same logic as for the alarm? It's not the same type of device at all. In my point of view, the lock can be considered as an opening, when the lock is open, it is not in its default state, it should be a point of attention as explained here above.  

Even worse when we think about the jammed lock state. It's critical because the door failed to arm and **the color is the same as a lock fully locked**. That's why I also think that this logic of having a red/orange lock when locked is wrong. 

If the logic needed to be reversed at some point (and aligned with the alarm for some reason), I would have change the colors of the alarm itself but not the lock. It would easier to explain that an alarm that is not activated is red.

**Comment by piitaya** [comment]
I updated the description and pushed the fix : 
- Secure state to green
- Unsecure state for lock to red
- Disarmed state for alarm to inactive because it shouldn't be as alarming as the unlocking state.

**Comment by zhimsel** [comment]
@piitaya thanks for changing your mind (or at least agreeing with the request here) and your quick turnaround! This change is in line with my intuition on how alarms and locks should be indicated.

But again, the most important change here is returning the _configurability_ of those colors (by re-including the `disarmed` and `unlocked` state colors). Thanks for doing that!

Looking forward to seeing this released.

**Comment by lymanepp** [comment]
@piitaya thank you for making these changes!!

**Review by balloob — APPROVED** [review]

**Pull request merged**
