### PR TITLE
Add service descriptions in zwave panel

### PR DESCRIPTION
**Pull request by andrey-git**
* Add support for service descriptions in call buttons. Use it in Zwave panel.
* Don't capitalize attribute keys and values. For some data case might be important.
* Sort nodes by name and not by ID (might be different order if name customization is used)

zwave

### CODE REVIEW

**Comment by andrey-git** [comment]
@turbokongen

**Comment by turbokongen** [comment]
Is it possible to have the descriptions as mouseover descriptions? I think it looks a bit crowded.

**Comment by andrey-git** [comment]
Mouseover doesn't exist on mobile :)

I think the descriptions are important.

When I added my last zwave node  I decided to try out you panel. It worked. Then I added another node via dev-state service calls and set association so one will control the other. After a long time trying to understand why they don't talk to each other I noticed that the first device was included as *secure*.

I'll look into adding a question mark button to toggle the descriptions on/off

**Comment by turbokongen** [comment]
Question marks are a great idea. Have a look at the node information card.  That has a toggle button to hide view text.

**Comment by andrey-git** [comment]
@turbokongen Please take another look, I added some more changes to the PR.

**Comment by turbokongen** [comment]
I'm unable to test this, because I'm out traveling for work. Just a few questions:
1. The sorting, before, it sorted alfabetically by the zwave node entity_id how does it sort now ?
2. The help text, is that show for all buttons in the card?

**Comment by andrey-git** [comment]
Now it is sorted by name.

The help text appears for all service calls.

**Review by turbokongen — APPROVED** [review]

**Pull request merged**
