### PR TITLE
Update developer-tools-state.js: widen "Set state" controls

### PR DESCRIPTION
**Pull request by ildar170975**
Please check this: https://github.com/home-assistant/frontend/discussions/17488

image

## Type of change

- [ ] Dependency upgrade
- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes #
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [ ] The code change is tested and works locally.
- [ ] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

**Comment by ildar170975** [comment]
Can anyone hint me why "CI / Lint and check format (pull_request)" is failed? ))))

**Comment by karwosts** [comment]
If you click the details, you can see this:

```
Run yarn run lint:prettier
Checking formatting...
[warn] src/panels/developer-tools/state/developer-tools-state.js
[warn] Code style issues found in the above file. Run Prettier to fix.
Error: Process completed with exit code 1.
```

This check is saying it doesn't like the way the code is formatted. The check is _very_ strict, not a single whitespace can be out of place. 

Typically if you have a real dev environment setup the `prettier` tool runs automatically as part of submit and formats your code in exactly the way it expects, so this would rarely hit anyone who was pushing from command line. If you try to make edits in the github UI I can see this happening. 

My guess is that it wants you to remove the blank line 64.

**Comment by ildar170975** [comment]
@karwosts 
Thanks a lot!
Removed the empty line.
Seems very logical - myself never leave an empty line before a closing bracket, a code looks untidy )).

**Comment by bramkragten** [comment]
I think this should still have a max width, I agree 400px is too small, but maybe change it to 800px?

**Comment by ildar170975** [comment]
> I think this should still have a max width, I agree 400px is too small, but maybe change it to 800px?

Tested with a 1920x1200 desktop, iPhone 5s portrait, iPad Air portrait and desktop (Chrome only); seemed to work fine w/o specifying max-width. 
Maybe another browser does need this attribute?

**Comment by ildar170975** [comment]
> I just don't think this is useful or good UX:

1. I do not see “last changed” and “last updated” data panel in your screenshot. 
Compare with my screenshot from the 1st post. 

2. If you think that max-width is needed to be set - ok, let us set it to 800px as you suggested.

**Comment by bramkragten** [comment]
> I do not see “last changed” and “last updated” data panel in your screenshot.
Compare with my screenshot from the 1st post.

Yeah, but this is what you will get in the UI with your code

**Comment by ildar170975** [comment]
> Yeah, but this is what you will get in the UI with your code

Sorry, I missed the point:
-- in your screenshot - there is no entity selected; so no "last_changed/last updated" displayed - and the "entity" selector, "state" field & "attributes" field takes a whole width;
-- in my screenshot - some entity is selected, so the "last_changed/last updated" is displayed on the right side.

**Comment by bramkragten** [comment]
Sorry, I don't understand your point here? Both are valid states of the UI, and so both should look ok?

I thought we agreed on a max width of 800px?

**Comment by ildar170975** [comment]
> Both are valid states of the UI, and so both should look ok?

For me, your screenshot w/o selected entity_id looks OK as well.
But I agree to revert to using `max-width` (800px) - anyway it is better than using 400px.

**Review by bramkragten — APPROVED** [review]

**Pull request merged**
