### PR TITLE
Add a "Fix all" button to statistics tab on developer tools

### PR DESCRIPTION
**Pull request by mukaschultze**
## Proposed change

Home Assistant instances that have been set up for a long time or that had past integrations that added a lot of entities might end up with lots of broken entities in the statistics tab of the developer tools dashboard. Currently, there's no way of bulk-cleaning these broken statistics from the UI.

This PR adds a "Fix all" button to the dashboard that allows the user to bulk remove entities that have no state or that have an unsupported state class.

### Screenshots
image
image
image

## Type of change

- [ ] Dependency upgrade
- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

No configuration required.

## Additional information

- This PR fixes or closes issue: fixes #
- This PR is related to issue or discussion: #12644
- Link to documentation pull request:

## Checklist

- [x] The code change is tested and works locally.
- [x] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

**Comment by karwosts** [comment]
I will point out that there are valid reasons to not want to fix some statistics issues, for example if you have old energy data from an entity that has been removed, and you want to preserve that data in your energy dashboard.

So someone in that situation would not be able to use a "fix all" button without erasing data they wanted to keep.

Is it might be nice if we had a multi-select option on the table, and then an option to bulk "fix selected", in case someone wants to select all, and then exempt a few entities from fixing. But I know that's more of an enhancement beyond the PR that's proposed here.

**Comment by bramkragten** [comment]
I like the multi select proposal!

**Comment by mukaschultze** [comment]
Yes, makes sense to use something more similar to how the latest automation page handles changing categories, multi-select, and such. Back when I started working on this my HASS didn't have the updated automation list and I didn't know it was possible with the current UI components.

I'll try to update this PR to have a better user experience using these components when I have time

**Comment by mathieucarbou** [comment]
Plese... Merge....  You sure don't want to see my screenshots of all my endless pages of sensors to fix 😈

**Pull request closed without merging**
