### PR TITLE
Update zwave_js WS API commands

### PR DESCRIPTION
**Pull request by raman325**
## Proposed change
Names changed here so we are changing the corresponding commands in the frontend: https://github.com/home-assistant/core/pull/75797

## Type of change

- [ ] Dependency upgrade
- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [x] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- Link to core pull request: https://github.com/home-assistant/core/pull/75797

## Checklist

- [ ] The code change is tested and works locally.
- [ ] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

**Review by bramkragten — APPROVED** [review]

**Comment by MartinHjelmare** [comment]
Backend PR is merged.

**Comment by zsarnett** [comment]
@MartinHjelmare will this go into 2022.8?

**Comment by MartinHjelmare** [comment]
No, we haven't planned to include it, right @raman325?

**Comment by raman325** [comment]
correct. Not included. This will go into 2022.9

**Comment by kpine** [comment]
Is this OK to merge this now?

```text
2022-08-05 09:09:48.988 INFO (MainThread) [homeassistant.components.websocket_api.http.connection] [140530596592128] Received unknown command: zwave_js/get_any_firmware_update_progress
2022-08-05 09:09:49.002 INFO (MainThread) [homeassistant.components.websocket_api.http.connection] [140530596592128] Received unknown command: zwave_js/get_firmware_update_progress
```
(from core `dev`)

**Review by zsarnett — APPROVED** [review]

**Pull request merged**
