### PR TITLE
Add context data option to template tab

### PR DESCRIPTION
**Pull request by mdegat01**
## Proposed change

Adds a way to provide context data to set initial variables for templates in Developer Tools -> Template. The primary purpose of this change is to allow you copythe data in `changed variables` from a trace like this:

Screen Shot 2022-02-20 at 4 51 33 PM

And paste it in to the new context data field. Then you can iterate on and debug the template that isn't working correctly in your automation with exactly the same context info it would have when actually run in that automation. And paste it back in to the automation afterwards when you're done fixing it.

It also helps in any other use cases when you are debugging a template that normally has passed in variables when actually run by HA. Like templates used in template switch, light, vacuum, select, etc. entities. Instead of having to change your template by adding lines at the top like this:

```j2
{% set brightness = 100 %}
{% set color_temp = 100 %}
{% set white_value = 100 %}
...
```

Just set all that info as context data using YAML and keep it out of your template like you would in the config.

Note here is what the UI of this tab looks like after this change. I put the context data field below the template because it can get quite long when you copy and paste from a trace and I didn't want it to take over the screen and push the template way down as that's the focus.

Screen Shot 2022-02-20 at 5 35 09 PM

## Type of change

- [ ] Dependency upgrade
- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

Not config but you can paste this below yaml into context data and the below template in to try it out:

```j2
{{ trigger.platform == "homeassistant" and trigger.event == "start" }}
```

```yaml
this:
  entity_id: automation.auto_dismiss_ha_update_alerts
  state: 'on'
  attributes:
    last_triggered: '2022-02-20T07:45:27.409825+00:00'
    mode: single
    current: 0
    id: '1610853218162'
    friendly_name: Start up tasks
  last_changed: '2022-02-20T07:50:47.833188+00:00'
  last_updated: '2022-02-20T07:50:47.833188+00:00'
  context:
    id: 8a409a59fda11b42416765c67d040d50
    parent_id: null
    user_id: null
trigger:
  id: '0'
  idx: '0'
  platform: homeassistant
  event: start
  description: Home Assistant starting
```

## Additional information

- This PR fixes or closes issue: fixes #
- This PR is related to issue or discussion:
- Link to documentation pull request: https://github.com/home-assistant/home-assistant.io/pull/21725

## Checklist

- [ ] The code change is tested and works locally.
- [x] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [x] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

**Comment by mdegat01** [comment]
So to be clear, my example in the PR is not working right now and I'm at a loss as to why. If you change the template to this:

```j2
{{ this }}
```

Then you see this as the output:
Screen Shot 2022-02-20 at 5 27 38 PM

Which looks correct except you also get this in the log:

```
2022-02-20 22:23:57 WARNING (Thread-90) [homeassistant.helpers.template] Template variable warning: 'this' is undefined when rendering '{{ this }}'
```

Which makes no sense because the result is showing and clearly is defined. But something is clearly wrong because if you try and reference a field of that object with a template like `{{ this.state }}` then it just blows up like this:

Screen Shot 2022-02-20 at 5 29 51 PM

Clearly I'm doing something wrong here I'm just pretty confused as to what it is. I figured I'd throw it up as a draft PR in case other wiser folks knew what was up. If not I'll continue poking at it tomorrow.

**Comment by bramkragten** [comment]
I guess your issue is related to core, and not to the frontend code...

**Comment by mdegat01** [comment]
@bramkragten Looking around the frontend, I only found one other place where we call `subscribeRenderTemplate` and pass in a value for `variables`. Looks like we pass in an object called `config` and the name of the user as `user` in [markdown cards](https://github.com/home-assistant/frontend/blob/dev/src/panels/lovelace/cards/hui-markdown-card.ts#L126-L139). But there I don't see this issue, here's me testing the same situation on my main HA running the latest stable version:

Screen Shot 2022-02-21 at 9 40 18 AM

Maybe its something to do with the type of object `js-yaml.parse` returns?

**Comment by bramkragten** [comment]
Mmmm that makes it even weirder... `js-yaml.load` just returns a normal object, nothing special about that...

**Comment by mdegat01** [comment]
🎉 🎉 

Screen Shot 2022-02-21 at 1 28 27 PM

**Comment by balloob** [comment]
So there are a few concerns:
- This should be called "Variables" as that's what you're defining here
- The rendered variables in a trace are stringified. `last_changed` and `last_updated` are actually `datetime` objects and `this` is a State object. `context` is a Context object etc.

**Comment by mdegat01** [comment]
@balloob well changing the label is easy (and makes sense). As for the other part, it makes sense but not sure what can be done. I can certainly note that in the docs (especially the `last_changed`/`last_updated` thing, forgot about that).

I still think this is a QOL improvement even if there is still room to improve it more. Like a future enchancement here could be a way to select a trace to provide context for a template or re-run a template from within the a screen in a trace in that context, that way we could reconsitute the variables in their actual form for users and not the stringified versions.

**Comment by mdegat01** [comment]
Also even outside the trace debugging use case, I think this is just helpful for templating. I know I personally pop open this tab all the time just to test out snippets of Jinja to figure out what works. It's a lot easier to set up test data in these scenarios with YAML then it is to type out things like:
```j2
{% set my_test_string = "test" %}
{% set my_test_object = {"string":"string", "object":{"a":"a", "b"}, "array":["a", "b", "c"]} %}
...
```

**Comment by balloob** [comment]
Sure, I can see how it is an improvement.

In it's current iteration it is most likely to confuse more users than that users will benefit from it. It's too easy to think that this text area is for the template, for example and then be frustrated that the template tool doesn't work.

Maybe we can do something like we do for the description in automations:

https://user-images.githubusercontent.com/1444314/155260915-c1abdd30-c9ed-470e-8cf0-fe439d98f486.mp4

If it has been filled in before, the variables can automatically be opened.

If it's opened for the first time, it should contain some data or else it would not be clear how it can be used.

The demo template can be updated to remove the variable setting.

**Comment by zsarnett** [comment]
Are you able to make the changes requested?

**Pull request closed without merging**
