### PR TITLE
Update simple-tooltip to 8.0.2 with RTL fix (remove patch)

### PR DESCRIPTION
**Pull request by yosilevy**
## Proposed change

Update simple-tooltip to 8.0.2 with RTL fix (remove patch)

## Type of change

- [X] Dependency upgrade
- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes #
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [X] The code change is tested and works locally.
- [X] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

**Comment by yosilevy** [comment]
This is my first package update so please review carefully... I've removed the patch I created since they fixed it in the repo and notified me.

**Comment by silamon** [comment]
You should also delete the patch itself from the [yarn patch folder](https://github.com/home-assistant/frontend/blob/cea402ebf89ee5ce719adeec7282cb3fc7556972/.yarn/patches/%40lrnwebcomponents-simple-tooltip-npm-8.0.0-77591f2e0c.patch).

**Review by steverep — CHANGES_REQUESTED** [review]
Could you delete the patch as well?

**Comment by yosilevy** [comment]
Done. Sorry for the delay.

**Review by steverep — APPROVED** [review]

**Pull request merged**
