### PR TITLE
Fix glance card with header if parent does not set block

### PR DESCRIPTION
**Pull request by balloob**
## Proposed change

The glance card with a header in a context that did not set `display: block` on the card was breaking the layout of the glance card. This was noticeable in the gallery.

Before:

image

After:

image

## Type of change

- [ ] Dependency upgrade
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes #
- This PR is related to issue:
- Link to documentation pull request:

## Checklist

- [ ] The code change is tested and works locally.
- [ ] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

**Review by zsarnett — COMMENTED** [review]
We should not remove this. This will break in a stack, no? It should take the height of the tallest card in a horizontal stack

**Comment by bramkragten** [comment]
> We should not remove this. This will break in a stack, no? It should take the height of the tallest card in a horizontal stack

The card should, the entities not?

**Comment by zsarnett** [comment]
Idk. Just want to make sure this doesn't break it

**Comment by balloob** [comment]
Then add it as a demo to the gallery! 😄

**Review by bramkragten — APPROVED** [review]

**Comment by balloob** [comment]
No need to put it in the milestone. It's not fixed in Lovelace itself, because we have `.column > * { display: block; }`

**Comment by bramkragten** [comment]
> No need to put it in the milestone. It's not broken in Lovelace itself, because we have `.column > * { display: block; }`

Was thinking about stacks etc

**Comment by balloob** [comment]
Ah yes. I thought it only impacted the gallery.

**Pull request merged**
