### PR TITLE
Redefine browser requirements for legacy (ES5) builds

### PR DESCRIPTION
**Pull request by steverep**
## Breaking change

Browser requirements for legacy (ES5) builds of the frontend have been updated to create a sunset policy. Support will sunset for browsers more than 7 years old and when global utilization falls below a conservative threshold of 0.05%.  This will not affect the vast majority of users.

## Proposed change

This builds on the `browserslist` implementation from #16267 by proposing a more practical set of requirements for legacy builds based on time and utilization instead of just features.  Without such a sunset policy, the builds will just keep growing with more transforms and polyfills likely without any benefit to real working devices in the wild.

I covered an explanation of the requirements I came up with in the comments of the config, so please read that first... ⏳ .

~~I tried to be pretty conservative - very old stuff will certainly be supported.  I used 10 years as the cutoff because, as of today, that's when browsers start losing support for those minimum feature requirements.  Beyond about 12 years, support drops off very quickly.  I picked 0.1% utilization just looking at the data.~~

_Numbers revised per discussion below.  Minimum browsers reported below have been adjusted._

In terms of polyfills and transforms that are dropped compared to `dev`, this only loses the 3 oldest Babel transforms and only ~~3~~ 11 of 413 possible Core JS polyfills.  So not much change to the actual build today, just trying to put it on a tractable path.

New requirements would be at least:
- Android ~~4.4~~ 4.4.3
- Chrome ~~28~~ 51
- Edge ~~12~~ 14
- Firefox ~~22~~ 47
- IE 11
- iOS ~~7~~ 9.3
- Opera ~~15~~ 37
- Safari ~~6.1~~ 10
- Samsung 4

## Type of change

- [ ] Dependency upgrade
- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (thank you!)
- [x] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes #
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [x] The code change is tested and works locally.
- [x] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

**Comment by bramkragten** [comment]
I think we can drop a lot more, or we should do a lot more on actually supporting these versions.
Below iOS 10 HA doesn't work currently for example, and that is probably also the case for other older versions...

**Comment by steverep** [comment]
Fair enough.  A little of each might be best.  Why does it not work below iOS 10 for example?  Is it JS-related or CSS issues?

**Comment by bramkragten** [comment]
> Fair enough. A little of each might be best. Why does it not work below iOS 10 for example? Is it JS-related or CSS issues?

Both, I could get it working on an iOS 8 device (with luck) by changing some JS (for example, our proxy polyfill doesn't have support for `has` which we use in `custom_icons`, we should fix that) and issues with `globalThis`, but then it looks like shit, really unusable...

**Comment by bramkragten** [comment]
I think it would be really nice if we could support up to iOS 9, as then we support almost all iPads (except for the first one)

But I'm not sure if that is doable, but we can try :-)

**Comment by steverep** [comment]
Yeah, I should have specified I also chose 10 years because that's also when CSS flex box support will likely get really intractable as most browsers will be based on an older spec, not to mention probably many other issues.

I would expect most, if not all, JS issues should be fixable.  CSS on the other hand needs a tool like [`autoprefixer`](https://github.com/postcss/autoprefixer) in the preprocessing pipeline.  My plan would be to fork the Babel plugin for minifying and tweak it to run `postcss` on all the CSS template literals.

**Comment by bramkragten** [comment]
> My plan would be to fork the Babel plugin for minifying and tweak it to run postcss on all the CSS template literals.

Cool! Maybe you can contribute it to the original project?

**Comment by steverep** [comment]
Yeah I'll try but it looks abandoned at the moment.

**Comment by steverep** [comment]
> I think it would be really nice if we could support up to iOS 9, as then we support almost all iPads (except for the first one)
> 
> iOS 9 also has full support for flexbox :-)

Seems reasonable to adjust the requirements to fully support flex box at the current spec.  That translates to either:
1. Going from 10 years to 8 years to bring Safari/iOS up to v9.  That also brings Firefox/Chrome/Opera well above where they'd need to be.  (Note that also would drop IE 11 and android 4.4, but they'd be saved by their utilization > 0.1%).
2. Just adding manual requirements for each browser, i.e. with the intention to fall into 10 year support in the future.

Thinking about it a little more, 10 years is probably excessive.  If you figure a new iPhone/iPad gets about 6-8 years worth of updates, that's trying to support 16+ year old devices, which I would guess are dead by now.  Something more than 5 and less than 10 seems like a better choice.

The utilization numbers are a better indication of actual devices out there though.  For example, take a look at the [browsers > 0.05%](https://browsersl.ist/#q=>+0.05%25).  Having HA analytics data would be even better though. 😉 



> `toggleAttribute` is something iOS 11 complains about, but it does work otherwise


Yeah not much you can do to polyfill HTML except building it into the code or just waiting for good support from browsers.  I think just relying on the forgiving nature of HTML and having a warning that legacy builds  may not support certain features is the way to go there.

**Comment by steverep** [comment]
So after staring at the utilization data and looking at compatibility tables and maximum OS versions for various mobile devices, I've revised to 7 years or 0.05%.  I updated the OP above with the new minimum versions.

In terms of Apple devices, this equates to:
- on the brink of dropping support for iOS 9.3 at 0.06% (iPhone 4S, iPad 2/Gen 3/mini Gen 1)
- supporting iOS 10 a little longer at 0.07% (iPad Gen 4, iPhone 5/5C)
- definitely need to support iOS 12 for a while (0.4% (iPhone 5S/6/6+, iPad Air Gen 1/mini 2)

7 years lines up with 9.3 (released just over 7 years ago) and also ensures that Chrome and Firefox work on the same devices based on their compatibility.

Refs:
- [iOS version by device](https://iosref.com/ios)
- [Chrome release compatibility](https://en.wikipedia.org/wiki/Template:Google_Chrome_release_compatibility)
- [Firefox for Android compatibility](https://en.wikipedia.org/wiki/Template:Firefox_for_Android_release_compatibility)

**Review by bramkragten — APPROVED** [review]

**Pull request merged**
