### PR TITLE
add show_state option for picture-glance entities

### LINKED ISSUE #3901: Ability to show the temperature/humidity state value in a picture-glance footer
```yaml
      - type: picture-glance
        title: Living Room
        camera_image: camera.livingroom
        entities:
          - sensor.living_room_temperature
          - sensor.living_room_humidity
```

The temperature/humidity entities will show as their icons (🌡 %) but I actually need to click on them to see the current temperature and humidity values. It would be nice if I could just see the values at a glance right in the footer overlay and click on those numbers if I want to see the overlay card. I would also be fine with showing the numbers (with units) beside the icons to it's clear what the percentage is for when there are multiple percentages.

I'm willing to make pull requests if there is agreement that this is more useful than just the icons.

### PR DESCRIPTION
**Pull request by iantrich**
Continues the great work by @isabellaalstrom in https://github.com/home-assistant/home-assistant-polymer/pull/3321

Closes #3901

Docs: https://github.com/home-assistant/home-assistant.io/pull/10916

### CODE REVIEW

**Comment by bramkragten** [comment]
On `glance` we have this option on the card, and here we do it on the entity?

**Comment by iantrich** [comment]
I didn't personally like the look of a state under an icon that already relays the information; e.g. a light, but having it under the sensor did look good. So I agreed with @isabellaalstrom that it should be at the entity level

**Comment by bramkragten** [comment]
Isn't that the same on `glance`?

**Comment by iantrich** [comment]
I could introduce the option at the entity-level for glance as well if that's what you're getting at. Would leave the card-level option to avoid a breaking change and let the entity-level option override it. Could add the same to picture-glance.

**Comment by bramkragten** [comment]
I would prefer that if we want it on entity level

**Comment by iantrich** [comment]
@bramkragten you see anything else on this one? Thanks.

**Review by bramkragten — APPROVED** [review]

**Pull request merged**
