### PR TITLE
Upgrade app-datepicker to drop old MWC

### PR DESCRIPTION
**Pull request by steverep**
## Proposed change

Version 5 has been deprecated (even though 6.x is not officially released... 😕).  The main reason to upgrade is that v6 is based on MWC 0.27 and newer lit, so this drops several duplicate MWC components.  I forgot to do this after bumping Material and lit a while ago.  This also cleans up a manual resolution dropped in #15865 for `reactive-element`.

Functionality seems basically the same with better, but still awful, keyboard and a11y support.  Please check the styling.

## Type of change

- [x] Dependency upgrade
- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes #
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [x] The code change is tested and works locally.
- [x] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

**Comment by bramkragten** [comment]
Version 5 to version 6 is a pretty massive one, I tried it but didn't really like it...
Updated the code to make it work, look ok-ish though...

It seems to have some bugs too, the wrong year is shown as selected etc..

**Comment by bramkragten** [comment]
> Yeah I don't really like it either. I just tested the demo because the HA implementation is somehow more inaccessible. This PR was purely to fix the bundle issue for me.

With your code the element didn't show at all, since the name of the element was changed ;-)

> What do you think about switching to [`vaadin-date-picker`](https://vaadin.com/docs/latest/components/date-picker)? There is also a ["light" version](https://cdn.vaadin.com/vaadin-web-components/24.0.0/#/elements/vaadin-date-picker-light) similar to the combo-box. It's very accessible and obviously under active development.

Hehehe, we actually used that before switching to this one.
I would actually be ok with switching back... considering the route of `app-date-picker`

**Comment by steverep** [comment]
Ha... I didn't realize that.  Why was the switch made?

**Comment by bramkragten** [comment]
Mainly because this one used Lit, and was closer to material.

**Comment by steverep** [comment]
Can the old code be revived easily or worth starting over?

Closing this since the duplicates were fixed in #15865

**Comment by steverep** [comment]
Theming looks to have changed in v24 too (not merged yet).  Hopefully that's even better.  Thanks! 👍🏻

**Pull request closed without merging**
