### PR TITLE
Allow commas in state of history download

### LINKED ISSUE #19895: History CSV Export does not support Text Sensors containing commas
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [x] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

When exporting the History of a Text Sensor that contains commas (specifically, an ESPHome ble_scanner text sensor), the CSV file splits columns in the middle of the text sensor value.

### Describe the behavior you expected

I expect the commas within the text sensor value to be escaped

### Steps to reproduce the issue

1. Create an ESPHome device with a ble_scanner text sensor
2. Export the sensor history to CSV
3. Observe the column mistmatch
...

### What version of Home Assistant Core has the issue?

2024.2.4

### What was the last working version of Home Assistant Core?

_No response_

### In which browser are you experiencing the issue with?

_No response_

### Which operating system are you using to run this browser?

_No response_

### State of relevant entities

_No response_

### Problem-relevant frontend configuration

_No response_

### Javascript errors shown in your browser console/inspector

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by potelux**
## Proposed change

When exporting history data to a CSV, surround the state value in quotes so that any internal commas do not create new columns in the output file.  Additionally, escape any quotes in the state value.

## Type of change

- [ ] Dependency upgrade
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Additional information

- This PR fixes or closes issue: fixes #19895
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [x] The code change is tested and works locally.
- [x] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

**Comment by piitaya** [comment]
Should we only escape when it's needed? In most case, it will be string without comma or number and we will have quotes for each state even it's not needed.

**Comment by potelux** [comment]
> Should we only escape when it's needed? In most case, it will be string without comma or number and we will have quotes for each state even it's not needed.

Checking to see if the escape is needed will require more overhead than just replacing.  You would have to iterate over every string to search for commas, then iterate over the string that contain commas to replace any internal quotes.  

Also, the state (TimelineState.state) will always be a string, so we don't need to check if it is of a different type.  Plus, this could help to prevent any edge-cases we haven't considered.

**Comment by potelux** [comment]
This change would bring us into compliance with points 7 and 8 of https://csv-spec.org/

**Comment by potelux** [comment]
> This change would bring us into compliance with points 7 and 8 of https://csv-spec.org/

Point 10 does suggest only using quotes when required, but permits the usage even if it is not required.

**Comment by piitaya** [comment]
We can do something like this. WDYT?

```ts
const safeState = s.state.includes(",") ? `"${s.state.replaceAll('"', '""')}"` : s.state;
csv.push(`${entityId},${safeState},${formatDate(s.last_changed)}\n`);
 ```

**Comment by potelux** [comment]
> This change would bring us into compliance with points 7 and 8 of https://csv-spec.org/

Point 10 does suggest only using quotes when required, but permits the usage even if it is not required.

> We can do something like this. WDYT?
> 
> ```ts
> const safeState = s.state.includes(",") ? `"${s.state.replaceAll('"', '""')}"` : s.state;
> csv.push(`${entityId},${safeState},${formatDate(s.last_changed)}\n`);
> ```

That would likely be better since it is the recommendation of Point 10 in the CSV standard.

We should extract the "," as a const as well.  Maybe, `CSV_DELIMETER = ","`.  This delimeter is used each time data is added to the CSV, but technically it could be ",", ";", or "\t".

**Comment by potelux** [comment]
> > We can do something like this. WDYT?
> > ```ts
> > const safeState = s.state.includes(",") ? `"${s.state.replaceAll('"', '""')}"` : s.state;
> > csv.push(`${entityId},${safeState},${formatDate(s.last_changed)}\n`);
> > ```
> 
> That would be better since it is the recommendation of Point 10 in the CSV standard.
> 
> We should extract the "," as a const as well. Maybe, `CSV_DELIMETER = ","`. This delimeter is used each time data is added to the CSV, but technically it could be ",", ";", or "\t". We only need to check if the string contains a comma if the comma is the current delimeter. If a semicolon is the delimeter, then that is what we need to check the string for.

Where would be the best place for that const?  Would it make sense in `src/data/history.ts`

**Comment by piitaya** [comment]
I don't think we need a delimiter const for now. If we want to extend the csv export in the future, I think we should rely on library that do it properly to avoid recoding the wheel.
For now, I think we should keep it simple 🙂

**Review by balloob — APPROVED** [review]
Thank you ❤️

**Pull request merged**
