### PR TITLE
Update RGBW and RGBWW white control to new UI slider, take 2

### PR DESCRIPTION
**Pull request by PaoloTK**
## Proposed change
The UI for light control has recently been updated for brightness and white temperature controls, but not for the white component of RGBW and RGBWW lights. I've done so with the goal of better UX, especially on mobile.

chrome_SYmvctxeyt
chrome_c0cHOyY0wX

## Type of change

- [ ] Dependency upgrade
- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information
The old style white brightness control sliders under the RGB color picker for RGBW and RGBWW lights have been updated to the new style control sliders.
The new sliders don't support a label or icon. I think having sliders that are self explanatory is helpful, but it's definitely worth considering adding that information somewhere. Although the old W icons didn't make much sense to me, considering the letter only makes sense for English.
I'm not sure about the styling on the color brightness slider. In the current PR I implemented a rainbow gradient, but I've also experimented with using the current RGB color.
It's my understanding that a color temperature cannot be specified for the white channel(s) of RGBW and RGBWW lights. Because of this I had to pick arbitrary colors for the new sliders.
For the RGBW white brightness slider color I chose the amber-color variable. I experimented with trying to use a neutral white color but found contrast to be an issue on the light theme.
For the RGBWW white brightness sliders, I used the colors the CCT gradient is built with.

## Checklist

- [x] The code change is tested and works locally.
- [x] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

**Comment by bramkragten** [comment]
@matthiasdebaat

**Comment by bramkragten** [comment]
For comparison current:
CleanShot 2023-05-08 at 11 36 21

**Comment by bramkragten** [comment]
What I miss here are labels mostly I think, it might not be clear enough from just the sliders what they control?

**Comment by matthiasdebaat** [comment]
I agree we should add labels.

Should the sliders be more like what design software does? Correct me if I'm wrong.
CleanShot 2023-05-08 at 12 09 25@2x

**Comment by PaoloTK** [comment]
Thank you for the feedback. @bramkragten I do agree labels are needed, but they're not available in the control slider. Do you think it makes more sense to add a label property to the control slider or to add labels separately for this dialog alone?

> I agree we should add labels.
> 
> Should the sliders be more like what design software does? Correct me if I'm wrong. CleanShot 2023-05-08 at 12 09 25@2x

Are you talking about the opacity slider colors or the styling on the sliders in general? I think having a consistent style is to be preferred. The control sliders I implemented match with the tile sliders and the other light properties sliders (brightness, color temperature).

**Comment by PaoloTK** [comment]
I added labels and the current value for each slider:

image

**Comment by matthiasdebaat** [comment]
Labels looks great!

> Are you talking about the opacity slider colors or the styling on the sliders in general? I think having a consistent style is to be preferred. The control sliders I implemented match with the tile sliders and the other light properties sliders (brightness, color temperature).

I was thinking about something like this:
- Color brightness got the same color as the picker
- Cold and warm white got the same slider as brightness.

Not sure if this is correct representation though.

change color

**Comment by PaoloTK** [comment]
> 

My first iteration had the color brightness slider match the color picker, but sometimes the picker doesn't match the current color so I found that confusing, but that was before I added labels.
Good shout on making every slider have a picker. This solves the problem with these sliders being able to go down to 0% unlike the others (e.g. brightness), which has some glitchy behavior.
With this style slider it might be worth exploring using a neutral white color again on the RGBW slider, since contrast should be less of a problem with the gradient to black.

**Comment by PaoloTK** [comment]
@piitaya any feedback/tips?

**Comment by PaoloTK** [comment]
> Labels looks great!
> 
> > Are you talking about the opacity slider colors or the styling on the sliders in general? I think having a consistent style is to be preferred. The control sliders I implemented match with the tile sliders and the other light properties sliders (brightness, color temperature).
> 
> I was thinking about something like this:
> 
> * Color brightness got the same color as the picker
> * Cold and warm white got the same slider as brightness.
> 
> Not sure if this is correct representation though.
> 
> change color

I have implemented the requested fixes and squashed some bugs with the color brightness slider color. I chose to default the color brightness slider color to full white rather than full black, so if the value is undefined we still get a gradient rather than a full black slider. I guess an alternative could be to set the whole slider to the disabled color.
The white temperature vertical slider has a label property I haven't implemented for the the RGBW(W) sliders. Is it something that needs to be added?

chrome_Ayuoh6QmzO
chrome_zb7gWg6U8i

**Comment by PaoloTK** [comment]
@bramkragten @matthiasdebaat Any chance you had the time to look at the latest revision? Thank you.

**Comment by bramkragten** [comment]
Personally I'm not a big fan of the gradient, but 🤷‍♂️

**Comment by PaoloTK** [comment]
> Personally I'm not a big fan of the gradient, but 🤷‍♂️

I don't disagree that this looks better:

chrome_Q1nfANElXI

My problem with this approach is that it becomes hard to set the value to 1%. These control sliders seem to be designed to allow a minimum value of 1%. Setting minimum value to 0% results in glitchy behavior (that I'm sure can be fixed) but more importantly seems to go against the UX goals of the slider? Please correct me if I'm wrong.

**Comment by PaoloTK** [comment]
With the latest beta the color picker now updates dynamically based the color brightness and white value(s) for RGBW and RGBWW lights. This makes my implementation of the color brightness slider problematic, because it now won't match the color picker and could be confusing. Any idea on a solution?
As for using the control sliders with no picker, a possible solution would be to add toggles like this:
239997292-3bd9061e-139e-481c-ac58-046766ec67e4
This would let us set the minimum value to 1% like the other control sliders, and as a bonus the user can quickly toggle the color and white channel(s).

**Comment by matthiasdebaat** [comment]
We need to update the slider to be less bold, more like the Material 3 sliders. Because of this dependency I'm closing this PR for now.

**Pull request closed without merging**
