### PR TITLE
Remove minification from translations to reduce build time by 1.5mins 

### PR DESCRIPTION
**Pull request by rob-mccann**
## Proposed change

I noticed it took a little while in the `build-flattened-translations` gulp task. I profiled the task via `node --inspect` and saw time spent in minification. Given the translations are already pure json files on a single line, I wondered if the minification was having any impact. I ran an MD5 hash over the `build-translations` directory before and after commenting the line out and it gave the same hashes.

Removing the line took this task down from 1.2 minutes to a couple of seconds on my Macbook pro 15. I removed the `build-translations` directory between runs.

Before:
image

After:
image

## Type of change

- [ ] Dependency upgrade
- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [x] Code quality improvements to existing code or addition of tests

## Checklist

- [x] The code change is tested and works locally.
- [x] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

**Review by bramkragten — COMMENTED** [review]
This is cool! That's way faster!

You should also remove the `gulp-jsonminify` dependency

**Comment by rob-mccann** [comment]
@bramkragten done

**Comment by zsarnett** [comment]
Thank you! 🎉

**Review by bramkragten — APPROVED** [review]
Thanks!

**Comment by donkawechico** [comment]
THANK YOU @rob-mccann!!! This is one of those "unsung hero" improvements that never make it to the blog but quietly lead to more features because of how much it improves development flow.

Great job.

**Pull request merged**
