### PR TITLE
Add a few missing dynamic `font-family` CSS var()

### LINKED ISSUE #10542: Body element - hardcoded font family
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

The `body` has the font family hardcoded. An easy to find example is the sidebar title (Home Assistant).
image
image

### Describe the behavior you expected

I would have said that instead of hardcoding that value, it should be using a variable like `paper-font-body1_-_font-family` ?

### Steps to reproduce the issue

No particular steps. Inspect element on the sidebar Home Assistant text and look for the `body` rule.

### What version of Home Assistant Core has the issue?

core-2021.11.0

### What was the last working version of Home Assistant Core?

_No response_

### In which browser are you experiencing the issue with?

Any

### Which operating system are you using to run this browser?

Ubuntu 20.04

### State of relevant entities

_No response_

### Problem-relevant frontend configuration

_No response_

### Javascript errors shown in your browser console/inspector

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by spacegaier**
## Proposed change

Add a few missing theme vars for `font-family`.

## Type of change

- [ ] Dependency upgrade
- [X] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes #10542
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [X] The code change is tested and works locally.
- [X] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

**Comment by bramkragten** [comment]
https://github.com/home-assistant/frontend/pull/9226#issuecomment-847339034

**Comment by spacegaier** [comment]
Man o man, the bot is really persistent 😆

**Comment by bramkragten** [comment]
> Man o man, the bot is really persistent 😆

You have to remove the stale label

**Comment by robertalexa** [comment]
I guess the real question is why is this not merged after more than half a year :)

**Comment by spacegaier** [comment]
> I guess the real question is why is this not merged after more than half a year :)
> 
> @spacegaier i think you need to change this from a draft to ready

Because I finally need to address the comments from Bram (hence the draft status 😄). It's on my todo list.

**Comment by robertalexa** [comment]
Oh I didn't notice the second PR. My bad :)

**Pull request closed without merging**
