### PR TITLE
Added hold and double tap actions for tile card

### PR DESCRIPTION
**Pull request by dsypniewski**
## Proposed change

Added hold and double tap actions for the Tile card
My personal use case is that I want both the tap and icon_tap actions to be toggle for a light but that leaves me without a quick access to more-info dialog, this solves that.
Based on the linked feature request it seems that I'm not the only one with similar problem.

## Type of change

- [ ] Dependency upgrade
- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml
type: tile
tap_action:
  action: toggle
hold_action:
  action: more-info
double_tap_action:
  action: more-info
icon_tap_action:
  action: toggle
entity: light.kitchen
```

## Additional information

- This PR fixes or closes issue: fixes #
- This PR is related to issue or discussion: https://community.home-assistant.io/t/hold-action-for-tile-card/481666
- Link to documentation pull request: https://github.com/home-assistant/home-assistant.io/pull/29481

## Checklist

- [x] The code change is tested and works locally.
- [x] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [x] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

**Comment by dsypniewski** [comment]
@bramkragten Is there something I can do to help push this forward?

**Comment by piitaya** [comment]
Hello 👋
We discussed with UX team and we don't want to encourage users to use hold and double tap action because it can be difficult to perform on some device. However, we're not opposed to bring this feature as a YAML only feature for now. Could you take the editor part out of the PR?

**Comment by dsypniewski** [comment]
@piitaya Done

**Review by piitaya — APPROVED** [review]
Thanks !

**Comment by martindybal** [comment]
@dsypniewski @piitaya Thnak you for your effort. I use hold_action a lot in my dashboards. But there is one thing I don't like, when I long hold an icon, it doesn't become hold_action but icon_tap_action. Which is unexpected behavior for me. What if I add both icon_hold_action and icon_double_tap_action. I understand that this is a very complicated configuration, but I would not like to change the behavior that users may already be used to.

**Pull request merged**
