### PR TITLE
Add config panel to recorder

### PR DESCRIPTION
**Pull request by sanyatuning**
## Proposed change

Add configuration screen to recorder integration.
core PR: https://github.com/home-assistant/core/pull/62604

## Type of change

- [ ] Dependency upgrade
- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes #
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [x] The code change is tested and works locally.
- [ ] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

**Comment by spacegaier** [comment]
Just wondering whether a panel is the correct approach here or whether this should be a config flow from the backend for the recorder integration?

**Comment by sanyatuning** [comment]
> Just wondering whether a panel is the correct approach here or whether this should be a config flow from the backend for the recorder integration?

Is it possible to show an "entities picker" in the config/options flow?

**Comment by spacegaier** [comment]
> > Just wondering whether a panel is the correct approach here or whether this should be a config flow from the backend for the recorder integration?
> 
> Is it possible to show an "entities picker" in the config/options flow?

Can't remember having ever seen that, but that doesn't mean it's not possible :) . But just with a quick glance at the coding, I cannot see a `ha-form-entity-picker.ts` or similar.

**Comment by matthiasdebaat** [comment]
Like that recorder settings can be changed in the UI. Don't want to scope creep, but should this be an entity setting in the dialog instead of a big recorder setting?

**Comment by sanyatuning** [comment]
@matthiasdebaat 
That will be a great addition but requires changing the core entity classes (I tried it), and in the first step, I would like to introduce something much simpler but useful.

**Comment by zsarnett** [comment]
Core PR still WIP

**Comment by dougiteixeira** [comment]
> Like that recorder settings can be changed in the UI. Don't want to scope creep, but should this be an entity setting in the dialog instead of a big recorder setting?

Just one point: it really seems ideal that the configuration was carried out in the settings of each entity.  But there should be a way to change this in bulk, maybe some services like "include all entities in recorder", "exclude all entities in recorder", "include entities listed in recorder", "exclude entities listed in recorder", maybe with domains too… this would avoid the user having to manipulate the configuration of each entity of the instance (which sometimes are many) to configure the recorder.  The same goes for a panel, it would be nice to have an option to select the entities and include or exclude them in the bulk recorder.

**Pull request closed without merging**
