### PR TITLE
HAWS 6.1

### PR DESCRIPTION
**Pull request by balloob**
## Proposed change

Update Home Assistant JS WebSocket to 6.1 to leverage new compressed `subscribe_entities`

https://github.com/home-assistant/home-assistant-js-websocket/releases/tag/6.1.0

backend PR is already merged: https://github.com/home-assistant/core/pull/67891

## Type of change

- [x] Dependency upgrade
- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes #
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [ ] The code change is tested and works locally.
- [ ] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

**Review by bdraco — APPROVED** [review]
LGTM 👍

**Comment by bdraco** [comment]
I put this on a production install and did some basic testing

```
{"id":2,"type":"event","event":{"c":{"camera.generic_f563ad44240ee8e19e7bca1e729c5adb":{"+":{"lu":1647074469.155974,"c":"ce7a2b3ff1ad7036e53bdb66d27e72a3","a":{"access_token":"78038216b953c19a916cc7758f535e079ab559d74b436a6eb51865f433257537","entity_picture":"/api/camera_proxy/camera.generic_f563ad44240ee8e19e7bca1e729c5adb?token=78038216b953c19a916cc7758f535e079ab559d74b436a6eb51865f433257537"}}}}}}
```

**Comment by bdraco** [comment]
Screen Shot 2022-03-11 at 23 15 49
All the power sensor updates now fit on the screen in the network dev console :)

**Comment by bdraco** [comment]
Found a bug

`{"id":2,"type":"event","event":{"c":{"light.table_light_cct_49d272":{"+":{"s":"off","lc":1647078469.501077,"c":"a940b8a0ff0bf237613101b7f9dfcd28","a":{"ip_address":"192.168.106.198"}},"-":{"a":["restored"]}}}}}`

The `restored` key isn't being dropped

**Review by bdraco — CHANGES_REQUESTED** [review]
Bugfix https://github.com/home-assistant/home-assistant-js-websocket/pull/251

**Comment by bdraco** [comment]
Other than the remove bug testing looks great 👍

**Comment by balloob** [comment]
Pushed 6.1.1

**Comment by bdraco** [comment]
Retesting now

**Review by bdraco — APPROVED** [review]
Testing passed 👍  Took a while since I wanted to try it on a few production systems.

Everything working as expected.  I verified attributes are now being removed.

**Pull request merged**
