### PR TITLE
Change layout of Zwave JS device config page

### PR DESCRIPTION
**Pull request by bramkragten**
## Proposed change

Makes settings screen wider, align inputs

CleanShot 2022-12-14 at 19 37 47

## Type of change

- [ ] Dependency upgrade
- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [X] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes #
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [ ] The code change is tested and works locally.
- [ ] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

**Comment by karwosts** [comment]
While you're opening this up, do you have any ideas to solve this issue where the select box is cutoff and you can't see the full value of what's being selected?

image

Can leave this for a later PR if you want, just wanted to raise this to your attention. I saw a few issues open about this. 

Maybe either show the full value as a tooltip, or do some kind of marquee thing in the field that rolls through the entire string?

This should be much better than it was before, but I don't know if some fields could still overflow.

**Comment by bramkragten** [comment]
Yes, you can set natural width on the select so the options take the space they need

**Review by piitaya — COMMENTED** [review]
How does it look on mobile ? Input below text ?

**Comment by bramkragten** [comment]
yes
CleanShot 2022-12-15 at 15 22 30

**Review by piitaya — APPROVED** [review]

**Pull request merged**
