### PR TITLE
Prevent deletion of the owner user

### PR DESCRIPTION
**Pull request by ludeeus**
## Type of change

- [ ] Dependency upgrade
- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes #
- This PR is related to issue:
- Link to documentation pull request:

## Checklist

- [ ] The code change is tested and works locally.
- [ ] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

**Review by zsarnett — APPROVED** [review]

**Comment by penright** [comment]
To add a thought. Most of the time that the "owner" user was deleted, was because they forgot the password. There needs to be a way to recover the password for the owner. Also, what happens if a person is already in the "owner-less" situation. It may not be worth the trouble either way, just wanted to throw those thoughts out there.

**Comment by ludeeus** [comment]
While I do agree, that is out of the scope of this PR.
Feel free to open a Feature Request

**Comment by KTibow** [comment]
Wouldn't a warning be better?

**Comment by ludeeus** [comment]
Not really, you should not delete the owner account, if you lost its password and that is the reason you are deleting it (like the docs tell you to do), there is a CLI tool for that.
Other than that I see no reason why deleting the owner should be possible.

**Pull request merged**
