### PR TITLE
Allow blueprint updates if there is a source URL

### PR DESCRIPTION
**Pull request by ludeeus**
## Proposed change

Allow updating blueprints if a source URL is defined.

image

## Type of change

- [ ] Dependency upgrade
- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes #
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [x] The code change is tested and works locally.
- [ ] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

**Comment by frenck** [comment]
What is the blueprint is no longer compatible with existing instances of the blueprint?
E.g., an input was added/removed?

**Comment by ludeeus** [comment]
We can never update then 👍

**Comment by frenck** [comment]
Well, we can, but we need to check compatibility. If it's not a match... dunno?

**Comment by bramkragten** [comment]
We should create a backend function that checks if a blueprint can be saved, we should use that for update and when saving a blueprint automation.

And we should display a warning ofc in the update dialog, the author of the blueprint is responsible for not breaking in the end of the day...

**Comment by ludeeus** [comment]
If it's a match, there is no need to update.
If it's not a match, its behaviour/expectations changes and we can't do anything.
So we can only really update if _only_ the name/description changes.
So we should not have it at all.

**Comment by frenck** [comment]
> If it's a match, there is no need to update.

Why? The whole blueprint logic could have changed, while keeping the signature of the inputs exactly the same.

**Comment by ludeeus** [comment]
> The whole blueprint logic could have changed,

> its behaviour/expectations changes and we can't do anything.

**Comment by bramkragten** [comment]
It could also be a bug fix? Or new features?

**Comment by ludeeus** [comment]
Both will change behavior.

**Comment by bramkragten** [comment]
Not necessarily? And the description could/should show if it does.

**Comment by ludeeus** [comment]
And the creator can classify "bugfix" any whey they want (not that it matter since we don't have any context of what type of change it is)
The point is, if it changes, we don't know what or how that impacts the user.

**Comment by bramkragten** [comment]
Sure, what that is not our responsibility 🤷🏻‍♂️.

We check if it won't throw errors and the author of the blueprint should make sure functionality will not break.

We should show the description and that could show warnings, or we should add a changelog field or something... Not that the user will know what version he is on...

**Pull request closed without merging**
