### PR TITLE
RFC: Add icon effects to ha-icon

### PR DESCRIPTION
**Pull request by thomasloven**
## Proposed change

Materialdesignicons has some "effects" that can be applied to icons - see bottom of [this page](https://cdn.materialdesignicons.com/4.9.95/).

This allows those to be added to icons in Home Assistant too by means of a icon name suffix - see configuration example.

## Type of change

- [ ] Dependency upgrade
- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml
  type: entities
  entities:
      - entity: light.bed_light
        icon: mdi:arrow-up
        name: mdi:arrow-up
      - entity: light.bed_light
        icon: mdi:arrow-up:rotate-45
        name: mdi:arrow-up:rotate-45
      - entity: light.bed_light
        icon: mdi:arrow-up:rotate-90
        name: mdi:arrow-up:rotate-90
      - entity: light.bed_light
        icon: mdi:arrow-up:rotate-135
        name: mdi:arrow-up:rotate-135
      - entity: light.bed_light
        icon: mdi:arrow-up:rotate-180
        name: mdi:arrow-up:rotate-180
      - entity: light.bed_light
        icon: mdi:arrow-up:rotate-225
        name: mdi:arrow-up:rotate-225
      - entity: light.bed_light
        icon: mdi:arrow-up:rotate-270
        name: mdi:arrow-up:rotate-270
      - entity: light.bed_light
        icon: mdi:arrow-up:rotate-315
        name: mdi:arrow-up:rotate-315
      - entity: light.bed_light
        icon: mdi:arrow-up:flip-v
        name: mdi:arrow-up:flip-v
      - entity: light.bed_light
        icon: mdi:arrow-up:flip-h
        name: mdi:arrow-up:flip-h
      - entity: light.bed_light
        icon: mdi:arrow-up:spin
        name: mdi:arrow-up:spin
```
1oxixXVXid

## Additional information

- This PR fixes or closes issue: fixes #
- This PR is related to issue: 
- Link to documentation pull request: 

## Checklist

- [x] The code change is tested and works locally.
- [x] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

**Comment by Mariusthvdb** [comment]
great! been a long time request, hope you can make it!
https://community.home-assistant.io/t/uses-mdi-helper-css-classes-in-homeassistant/64334/5

**Comment by SeanPM5** [comment]
Spin effect would be pretty cool as the on state for fan entities.  

`icon: mdi:fan:spin`

**Comment by balloob** [comment]
So what is the use case that you can't do with a custom image ? There has been a single request for this feature and it can be achieved with images (including gifs for animations). I don't think that warrants shipping extra code to every Home Assistant user ever.

**Comment by Mariusthvdb** [comment]
Using custom images is way more complicated than using these mdi effects on the beautiful mdi icons . Being able to vertically flip mdi:desk-light eg would make it a snap of a finger turning these into a right and left light. As many other graphic icons could benefit from getting a more explicit visual meaning.

Sure we can rotate icons in Lovelace cards with styling using card-mod. Wouldn’t be necessary if core Ha were to support these improvements which are layed out for us by Mdi just like that.

Please don’t oppose this frontend improvement option.  Cant be much of a burden to the core code. Or system performance for that matter?

Hope you will allow for this fervently. Thanks if you do!

**Comment by arsaboo** [comment]
Also, not all built-in LL cards can use gifs or animations. Colors and motion are great visual cues that we should definitely encourage. Not everyone can use card-mod. I have been using HA for a while and even I feel intimidated by card-mod; not to mention it requires dependence on custom cards.

**Comment by TheZoker** [comment]
Also +1 for adding these effects for the mdi. Gifs and custom images are one way to go, but just applying an effect on an mdi makes this so much easier and faster (I don't have to create gifs or stuff like that)

**Comment by iantrich** [comment]
Nice addition, Thomas! 🎉

**Comment by Mariusthvdb** [comment]
any update on this? This can't be added too soon to core HA ;-)

**Comment by thomasloven** [comment]
I think it won't be merged. @balloob raises some good points in that there's already other ways to achieve the same thing, and it's a rather big addition (in compiled code size) that benefit few users.

It *will* be in the next version of card-mod, though...

**Comment by Mariusthvdb** [comment]
Thank you. And I appreciate it coming to Card-mod!

I do think the suspected 'few users' might be surprisingly many in real life, once this option would be opened to the public.
And, up to now there are no other ways to achieve the same thing, with the possible exception of the spin in a button card. Unless I am really missing the obvious here.

Way complex techniques might be available in card-mod styles (which I thankfully use here and there) while your addition of core icon-effects would make it all so very simple.
Not to mention open it up for use in global customizations, hence cutting even more config code.

think this would need a Poll in the community

**Comment by zsarnett** [comment]
I agree with both. I really only see it necessary for the Spin effect but I think this would be a beneficial change. Ability to more easily see motion and state changes at a glance is very helpful

**Comment by Mariusthvdb** [comment]
so there's 26 thumbs up, and 2 down, and this is closed without any further discussion....?

**Comment by bramkragten** [comment]
I count 11, but the main reason I closed this is that the code is no longer relevant as this component is completely rewritten.

**Comment by Mariusthvdb** [comment]
Ha, you're a selective counter ;-) the first post got 11, but there was some followup.

back to the important stuff though:

> no longer relevant as this component is completely rewritten.

could it be then these icon effects are part of that complete rewrite? and this PR is 'merged'...

**Pull request closed without merging**
