### PR TITLE
Lovelace - Weather Card: Adjust margins and move text

### PR DESCRIPTION
**Pull request by timmo001**
## Desctiption

Adjusts margins as to seperate out sections better.

### Before

image

### After

image

### CODE REVIEW

**Review by zsarnett — APPROVED** [review]

**Comment by balloob** [comment]
I don't like it. "Rainy" seems way too much glued to the forecast now. It's actually pretty misplaced there to begin with, it feels kinda randomply placed. I wonder if we should make the header something like `Rainy <small>Dark Sky</small>`

**Comment by timmo001** [comment]
Also reduced some other margins that were wasting space:

image

**Review by balloob — APPROVED** [review]

**Comment by zsarnett** [comment]
ah changing the base screws everything up... Will try to fix

**Comment by balloob** [comment]
Nah, doesn't screw it up, just shows that not all commits from master are in dev (because cherry-picked, they get slightly different commit sha's). Merging master -> dev and now it's all good.

**Pull request merged**
