### PR TITLE
Update translationMetadata.json - Added Irish language code

### PR DESCRIPTION
**Pull request by aindriu80**
## Proposed change

Add Irish language support to Home Assistant.  

As per  https://developers.home-assistant.io/docs/translations/#maintainer-steps-to-add-a-new-language instructions I have completed the first two steps:

1. Retrieve Irish/Gaeilge language code from IANA subtag registry https://www.iana.org/assignments/language-subtag-registry/language-subtag-registry
2. Add 'ga' language code to src/translations/translationMetadata.json

 

## Type of change

- [ ] Dependency upgrade
- [ ] Bugfix (non-breaking change which fixes an issue)
- [X] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Additional information

This pull request is in relation to https://github.com/home-assistant/frontend/discussions/21807 

Details about the language:-

English Name: Irish
Native Name: Gaeilge
Type: language
Subtag: ga
Description: Irish
Added: 2005-10-16
Suppress-Script: Latn

My Lokalise account: aindriu80@gmail.com

## Checklist

- [ ] The code change is tested and works locally.
- [X] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

## Summary by CodeRabbit

- **New Features**
	- Added support for the Irish language (Gaeilge) to enhance localization and accessibility for Irish-speaking users.

### CODE REVIEW

**Review by bramkragten — APPROVED** [review]

**Comment by bramkragten** [comment]
What is your email on Localise, so I can give you access to translate the newly added language?

**Comment by aindriu80** [comment]
> What is your email on Localise, so I can give you access to translate the newly added language?

My lokalise email is  aindriu80@gmail.com

Thanks!

**Comment by aindriu80** [comment]
> What is your email on Localise, so I can give you access to translate the newly added language?

Do you think everything here is ok for a merge? I don't know if I am missing something

**Review by bramkragten — APPROVED** [review]

**Comment by silamon** [comment]
It also needs a core PR right similar to this one: https://github.com/home-assistant/core/pull/122768?

**Comment by bramkragten** [comment]
> It also needs a core PR right similar to this one: [home-assistant/core#122768](https://github.com/home-assistant/core/pull/122768)?

Oh right yeah, true, we should update the docs

**Review by bramkragten — APPROVED** [review]

**Comment by silamon** [comment]
No need to keep the pull requests updated with the latest dev. It will be merged quite soon, when people from Home Assistant are able to set up the things in Lokalise.

**Comment by aindriu80** [comment]
> No need to keep the pull requests updated with the latest dev. It will be merged quite soon, when people from Home Assistant are able to set up the things in Lokalise.

Oh I see, thank you very much ! it was a bit confusing >< !

**Pull request merged**
