### PR TITLE
[WIP] Add precipitation forecast graph to weather card

### PR DESCRIPTION
**Pull request by Tommatheussen**
## Proposed change

This PR adds a graph to the weather forecast card, this graph shows precipitation data for the coming forecast entries.
image

## Type of change

- [ ] Dependency upgrade
- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes #
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [ ] The code change is tested and works locally.
- [ ] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

**Comment by bramkragten** [comment]
Hi @Tommatheussen!

Thank you for your PR, it has been in draft status for a month now without any changes.
Do you want us to look at the code, or discuss the function? Or will you finish this PR soon?

**Comment by silamon** [comment]
It was discussed on the devs_ux channel in Discord around the same time. 

tmatheussen — 03/25/2024 5:49 PM
Hi Guys, I've been working on adding a precipitation forecast graph to the weather card, I got a draft PR up here:
https://github.com/home-assistant/frontend/pull/20130
I also asked in the ⁠devs_frontend channel, but I'm looking for some feedback/pointer in the UI side of things. Is there any design mockup for precipitation forecast graphs?

karwosts — 03/25/2024 7:16 PM
I'm doubtful there's any mockup but I'll throw in my 2c:
* I would have expected a rough alignment between the forecast icons and the rainfall, i.e. a 5 day forecast would have 5 precipitation bars, with vertical alignment between them.
* not really a fan of autoscaling the vertical axis, as you can't really tell anything at a glance without checking the axis scaling in its tiny font, and it makes at a glance a single drop of rain visually equivalent to a huge downpour. I know a fixed scale can have its own issues too, I'm not sure what's the right answer for that exactly.
* I do wonder if a graph is really the most appropriate way to display this, versus maybe just like adding a little raindrop mdi icon under the temperature and just a simple label like "💧 4mm". Graph takes a lot of space for that same information.
 
Madelena — 03/25/2024 11:06 PM
I concur with karwosts on point 1 and 3. For point 2, I think autoscaling to fit is fine, but there also should be a minimum y axis scale to avoid small units being magnified too much. 
I also wonder if there should be this much information on one single card. And what kind of graphs there would be
This is my own weather dashboard for reference.
image
My recommendation would be to build a Weather Dashboard Blueprint (Strategy) to house the graphs and icons in a coherent reusable manner, similar to how to build the Energy Dashboard
Thanks for the PR tmatheussen! Always nice to see more development on weather 😄
We engage in Open Design, so if there are any great developments, our designers in our team are happy to help with a mockup or give advices 😄

tmatheussen — 03/26/2024 9:08 AM
Thanks for the pointers! Indeed the axis and scaling is something I had in mind already, but wanted to get some early feedback 🙂
With the precipitation forecast graph there might indeed be too much information in 1 card (even it's it's toggleable), a separate graph might be better. The reason for going for a graph, to me it seems more intuitive to quickly see if rain is expected (especially for the hourly forecast), rather than having to look at the numbers 😅
I'll see if I can make a separate graph card for this forecast

Madelena — 03/26/2024 10:25 AM
I'd recommend looking into building a dashboard blueprint (AKA strategy) instead of a card: https://developers.home-assistant.io/docs/frontend/custom-ui/custom-strategy

**Comment by Tommatheussen** [comment]
As mentioned above, I indeed got some feedback on the UX channel already, I've actually started on getting some standalone graphs going, but so far did not push any code for it. 
I'm happy to close this PR and open a new one later down the line once I have something properly working?

**Comment by bramkragten** [comment]
Yeah that might be better, especially if it will differ a lot

**Pull request closed without merging**
