### PR TITLE
Fixed state card of number entity

### PR DESCRIPTION
**Pull request by kukulich**
## Proposed change

The number entity does not have any `mode` attribute currently. The PR is not merged yet: https://github.com/home-assistant/core/pull/43867

The code that is copied from `input_number` expects the `mode` attribute so it's not possible to set the value in "more info" window now.

Before
---
before2

After
---
after2

## Type of change

- [ ] Dependency upgrade
- [X] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml
demo:
```

## Additional information

- This PR fixes or closes issue: fixes #
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [X] The code change is tested and works locally.
- [X] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

**Comment by spacegaier** [comment]
The input field seems rather big / wide. Reducing that might make sense?

**Comment by kukulich** [comment]
@spacegaier I tried to not modify anything in the design - I only try to remove the useless parts and fix the bug.
Yes, it may be narrower but the `input_number` entity has the same wide input.

**Comment by bramkragten** [comment]
Actually, it is not:
image

**Comment by kukulich** [comment]
@bramkragten 

Ok, it looks there's difference between Firefox and Chrome:

Firefox
---

firefox


Chrome
---

chrome

**Comment by kukulich** [comment]
@bramkragten 

Screenshot of the fixed number state card in Chrome:

number

**Comment by bramkragten** [comment]
Ah ok 😄  we should fix that in FF in a different PR

**Review by bramkragten — APPROVED** [review]

**Pull request merged**
