### PR TITLE
Fix multi select ha-form

### LINKED ISSUE #10567: "User Input Malformed" error when re-configuring integrations in the front end GUI
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

On a few Integrations for me:
- adaptive-lighting: https://github.com/basnijholt/adaptive-lighting/issues/213#issuecomment-962667659
- programmable_thermostat: https://github.com/custom-components/climate.programmable_thermostat/issues/42

and for others:

- Homekit: https://community.home-assistant.io/t/homekit-error-user-input-malformed/353390/9

They allow to re-configure via the front end due to a GUI bug I think, there is some sort of non-front-end-existing field in the list being tracked that I can't edit, so I can't save the changes.
image

Rolling back and the inputs look slightly different too? 

### Describe the behavior you expected

I expected to be able to edit the fields in the pop up when configuring an integration, and so long as these fields are valid and complete, then to be able to save the changes.

### Steps to reproduce the issue

1. Install programmable thermostat, confirm it works fine.
2. Try and update the integration configuration, by clicking configure in the front end
3. Change any value in that form
4. click submit
...

### What version of Home Assistant Core has the issue?

2011.11

### What was the last working version of Home Assistant Core?

2011.10

### In which browser are you experiencing the issue with?

_No response_

### Which operating system are you using to run this browser?

Home Assistant OS

### State of relevant entities

_No response_

### Problem-relevant frontend configuration

_No response_

### Javascript errors shown in your browser console/inspector

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by bramkragten**
## Proposed change

Fixes https://github.com/home-assistant/frontend/issues/10567

## Type of change

- [ ] Dependency upgrade
- [X] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes #
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [ ] The code change is tested and works locally.
- [ ] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

**Review by zsarnett — APPROVED** [review]

**Review by basnijholt — APPROVED** [review]

**Comment by seekingwittyid** [comment]
Still seeing this error in HASS Bridge after updating to .11.2. Switching the configuration from Bridge to Accessory and back fixed the issue.

**Comment by bramkragten** [comment]
This is not part of 11.2

**Comment by seekingwittyid** [comment]
> This is not part of 11.2

Ah, I must have misread the merge then. Either way, until the fix is released the steps I provided above should work as a workaround for anyone having similar issues with the HASS Bridge plugin at least.

**Comment by poelzi** [comment]
This is bad. This fix solves problems with lots of plugins, to be honest 2021.11 is quite broken because of that. When is 11.3 scheduled ?

**Pull request merged**
