### PR TITLE
Show entity_picture in logbook

### LINKED ISSUE #7734: Logbook card does not grant customized icon
## Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

## The problem
Logbook card does not grant customized icon

## Expected behavior
Logbook card should show customized icons, if there is one defined.

Custom home-feed card grants the customized icons (see attached homefeed.png) while the logbook card for the same set of entities it does not (see attached logbook.png).
The entity in the example is a device_tracker of type ping.

homefeed
logbook

## Steps to reproduce
1. Create a device_tracker entity with customized icon in $CONF/customize.conf to a local picture
2. Display that entity in the logbook card.

```
(ha_venv3_8) pi@raspberrypi:~/homeassistant_conf $grep akos customize.yaml
device_tracker.akos_phone:
  entity_picture: /local/mdi-akos.png
(ha_venv3_8) pi@raspberrypi:~/homeassistant_conf $
```

## Environment

- Home Assistant release with the issue: 0.118.0
- Last working Home Assistant release (if known): n/a
- Browser and browser version: Chrome 86.0.4240.193, MS Edge 44.17763.831.0
- Operating system: windows 10

## State of relevant entities

```yaml
source_type: router
friendly_name: Ákos
entity_picture: /local/mdi-akos.png
```
Its state is : home

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

None.

```txt

```

### PR DESCRIPTION
**Pull request by spacegaier**
## Proposed change

Switched out the `<ha-icon>` against a `<state-badge>`. For it work I adjusted the state-badge a bit so it can work without a `stateObj` since some logbook entries do not have an actual object (e.g. HA stop and start).

grafik

## Type of change

- [ ] Dependency upgrade
- [ ] Bugfix (non-breaking change which fixes an issue)
- [X] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes https://github.com/home-assistant/frontend/issues/7734
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [X] The code change is tested and works locally.
- [X] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

**Comment by bramkragten** [comment]
I don't think this makes sense in all cases, for a media player for example it will now show the current playing media art?

**Comment by spacegaier** [comment]
> 
> 
> I don't think this makes sense in all cases, for a media player for example it will now show the current playing media art?

That's a good point. Just to check: You are fine with showing the entity picture in general, if we filter out the entity types where it does not make sense (currently only the media players)? If yes, I will implement this filter.

**Comment by bramkragten** [comment]
Not just media players I think, every dynamic entity picture, also cameras and I don't know if there are more (templates...).

**Comment by spacegaier** [comment]
> 
> 
> Not just media players I think, every dynamic entity picture, also cameras and I don't know if there are more (templates...).

I now added logic so we can filter those domains out. For now I added camera and media_player.

**Review by bramkragten — APPROVED** [review]

**Pull request merged**
