### PR TITLE
[logbook] fix scrolling on iOS

### LINKED ISSUE #4791: logbook scrolling issue on mobile browsers Safari and Chrome & iOS Home Assistant app
## Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

## The problem
When scrolling on the logbook, it stops recognizing the scroll after 1 line. (as if you were to remove your finger from the screen after scrolling 1 line of logbook)  

## Expected behavior

You should be able to scroll multiple lines of the logbook at a time with out it stopping.

## Steps to reproduce
1. Go to the logbook on an iOS mobile device and try and scroll more than 1 line at a time

## Environment
- Home Assistant release with the issue: Home Assistant 0.105.0
- Last working Home Assistant release (if known): Home Assistant 0.104.3
- UI Type (States or Lovelace): Lovelace
- Browser and browser version: Safari , Chrome v80.0.3987.88, iOS Home Assistant App v2019.1
- Operating system: iOS v13.3.1
- Frontend version: 20200130.1 - latest
- Device: iPhone Xs

## Problem-relevant configuration

```
  include:
    entities:
      - cover.garage
  exclude:
    domains:
      - automation
      - media_player
      - sensor
    entities:
      - light.kitchen_lights
      - group.main
      - binary_sensor.garagelighttimer
      - binary_sensor.mud_timer
      - binary_sensor.d1_motion
```

### LINKED ISSUE #4814: Logger screen scrolling problem on iOS
## Checklist

- [ X] I have updated to the latest available Home Assistant version.
- [ x] I have cleared the cache of my browser.
- [ x] I have tried a different browser to see if it is related to my browser.

## The problem

  iOS 12.4.1 browser chrome or safari. Logger window scrolling only goes one line at a time. Not able to smooth scroll with finger swipe like on other versions.  Not a show stopper but Very annoying. 

## Expected behavior

  Drag a finger on the window and the page should scroll like in other versions up to this point. 

## Steps to reproduce
    1. Log in. 
    2. Navigate to Lovelace
    3. Click logger
    4. Try to scroll the page

## Environment
- Home Assistant release with the issue: 0.105.2
- Last working Home Assistant release (if known): .102 (I think, but any prior version)
- UI Type (Lovelace): 
- Browser and browser version: iOS iPad, or iPhone. 
- Operating system: iOS 12.4.1
- safari or chrome. Both exhibit the same problem. 
## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

### PR DESCRIPTION
**Pull request by KapJI**
## Proposed change

Fix issue when you can scroll only one item at time on iOS/ipadOS. 

My theory is that when you try to append element to shadow root the current scroll action is reset and new events are not fired before you start scrolling again. This doesn't happen when you append to normal element inside shadow root.

And this is what this change does. `lit-virtualizer` creates shadow root when `scroll()` doesn't. And to function properly we need to manually set styles which were added to shadow root before.

## Type of change

- [ ] Dependency upgrade
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes #4791, fixes #4814 
- This PR is related to issue: 
- Link to documentation pull request: 

## Checklist

- [x] The code change is tested and works locally.
- [x] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

**Review by bramkragten — APPROVED** [review]
Great!

**Comment by KapJI** [comment]
@bramkragten do you mind merging this one as well?

**Comment by WilldabeastHA** [comment]
Thanks for fixing this! What’s the best way to update this fix on my Home Assistant Core?

**Comment by KapJI** [comment]
@WilldabeastHA If you want it today then follow these instructions to use development version: https://developers.home-assistant.io/docs/frontend_development/
Or just wait before the next version is released.

**Pull request merged**
