### PR TITLE
Add ingress session validation

### LINKED ISSUE #2185: Seeing a lot of "No valid ingress session" errors with 0.117.0b6, sometimes resulting in a popup with "Unable to load the panel source: /api/hassio/app/entrypoint.js."
**Home Assistant release with the issue:**

0.117.0b6, HassOS 4.15, Supervisor 2020.10.0

**Operating environment (HassOS/Generic):**

HassOS in a KVM

**Supervisor logs:**

```text
20-10-28 16:34:33 WARNING (MainThread) [supervisor.api.ingress] No valid ingress session a33a198fc8d5a8c8051ab4a75c5ad59ba26a1445b45c2c1214b32b0f55bab79b849a90af6c41792abc2d63da36cd987b075d699fb5d7b8856e562c8a756f6aea
20-10-28 16:35:15 WARNING (MainThread) [supervisor.api.ingress] No valid ingress session a33a198fc8d5a8c8051ab4a75c5ad59ba26a1445b45c2c1214b32b0f55bab79b849a90af6c41792abc2d63da36cd987b075d699fb5d7b8856e562c8a756f6aea
20-10-28 16:35:57 WARNING (MainThread) [supervisor.api.ingress] No valid ingress session a33a198fc8d5a8c8051ab4a75c5ad59ba26a1445b45c2c1214b32b0f55bab79b849a90af6c41792abc2d63da36cd987b075d699fb5d7b8856e562c8a756f6aea
20-10-28 16:36:39 WARNING (MainThread) [supervisor.api.ingress] No valid ingress session a33a198fc8d5a8c8051ab4a75c5ad59ba26a1445b45c2c1214b32b0f55bab79b849a90af6c41792abc2d63da36cd987b075d699fb5d7b8856e562c8a756f6aea
20-10-28 16:37:21 WARNING (MainThread) [supervisor.api.ingress] No valid ingress session a33a198fc8d5a8c8051ab4a75c5ad59ba26a1445b45c2c1214b32b0f55bab79b849a90af6c41792abc2d63da36cd987b075d699fb5d7b8856e562c8a756f6aea
20-10-28 16:38:03 WARNING (MainThread) [supervisor.api.ingress] No valid ingress session a33a198fc8d5a8c8051ab4a75c5ad59ba26a1445b45c2c1214b32b0f55bab79b849a90af6c41792abc2d63da36cd987b075d699fb5d7b8856e562c8a756f6aea
20-10-28 16:38:45 WARNING (MainThread) [supervisor.api.ingress] No valid ingress session a33a198fc8d5a8c8051ab4a75c5ad59ba26a1445b45c2c1214b32b0f55bab79b849a90af6c41792abc2d63da36cd987b075d699fb5d7b8856e562c8a756f6aea
20-10-28 16:38:58 WARNING (MainThread) [supervisor.api.ingress] No valid ingress session a33a198fc8d5a8c8051ab4a75c5ad59ba26a1445b45c2c1214b32b0f55bab79b849a90af6c41792abc2d63da36cd987b075d699fb5d7b8856e562c8a756f6aea
20-10-28 16:39:27 WARNING (MainThread) [supervisor.api.ingress] No valid ingress session a33a198fc8d5a8c8051ab4a75c5ad59ba26a1445b45c2c1214b32b0f55bab79b849a90af6c41792abc2d63da36cd987b075d699fb5d7b8856e562c8a756f6aea
20-10-28 16:39:40 WARNING (MainThread) [supervisor.api.ingress] No valid ingress session a33a198fc8d5a8c8051ab4a75c5ad59ba26a1445b45c2c1214b32b0f55bab79b849a90af6c41792abc2d63da36cd987b075d699fb5d7b8856e562c8a756f6aea
20-10-28 16:40:09 WARNING (MainThread) [supervisor.api.ingress] No valid ingress session a33a198fc8d5a8c8051ab4a75c5ad59ba26a1445b45c2c1214b32b0f55bab79b849a90af6c41792abc2d63da36cd987b075d699fb5d7b8856e562c8a756f6aea
20-10-28 16:40:22 WARNING (MainThread) [supervisor.api.ingress] No valid ingress session a33a198fc8d5a8c8051ab4a75c5ad59ba26a1445b45c2c1214b32b0f55bab79b849a90af6c41792abc2d63da36cd987b075d699fb5d7b8856e562c8a756f6aea
20-10-28 16:40:51 WARNING (MainThread) [supervisor.api.ingress] No valid ingress session a33a198fc8d5a8c8051ab4a75c5ad59ba26a1445b45c2c1214b32b0f55bab79b849a90af6c41792abc2d63da36cd987b075d699fb5d7b8856e562c8a756f6aea
20-10-28 16:41:03 WARNING (MainThread) [supervisor.api.ingress] No valid ingress session a33a198fc8d5a8c8051ab4a75c5ad59ba26a1445b45c2c1214b32b0f55bab79b849a90af6c41792abc2d63da36cd987b075d699fb5d7b8856e562c8a756f6aea
20-10-28 16:41:27 INFO (MainThread) [supervisor.api.security] /supervisor/logs access from a0d7b954_ssh
```

This bit is from the latest occurrence:

```text
20-10-28 16:54:51 WARNING (MainThread) [supervisor.api.ingress] No valid ingress session a33a198fc8d5a8c8051ab4a75c5ad59ba26a1445b45c2c1214b32b0f55bab79b849a90af6c41792abc2d63da36cd987b075d699fb5d7b8856e562c8a756f6aea
20-10-28 16:55:25 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token
20-10-28 16:55:33 WARNING (MainThread) [supervisor.api.ingress] No valid ingress session a33a198fc8d5a8c8051ab4a75c5ad59ba26a1445b45c2c1214b32b0f55bab79b849a90af6c41792abc2d63da36cd987b075d699fb5d7b8856e562c8a756f6aea
20-10-28 16:55:59 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API connection is closed
20-10-28 16:56:01 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request initialize
20-10-28 16:56:01 INFO (MainThread) [supervisor.api.proxy] WebSocket access from a0d7b954_vscode
20-10-28 16:56:01 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request running
```

I also periodically see these in the HA log:

```text
2020-10-28 09:40:55 ERROR (MainThread) [homeassistant.components.hassio.http] Client error on api supervisor/info request 
2020-10-28 09:42:19 ERROR (MainThread) [homeassistant.components.hassio.http] Client error on api app/entrypoint.js request 
```

**Description of problem:**

Somewhere in the 0.117 beta cycle accessing the Supervisor page has become flaky and unreliable.  Sometimes clicking on the Supervisor sidebar icon results in several seconds of delay before the Dashboard comes up, and often it never comes up (just a black screen).  Refreshing the page sometimes makes the Dashboard appear, sometimes I get an "Unable to load the panel source: /api/hassio/app/entrypoint.js." popup, and sometimes it just stays at a black screen.  Going back to the "Overview" Lovelace page and back into Supervisor may or may not allow me to get to the Supervisor page (same failure possibilities as before).  When it fails, I always get a "No valid ingress session" in the logs, as shown above.  It happens on both mobile and desktop, and both with and without going through my reverse proxy - I can reproduce it just going straight to http://192.168.1.169:8123/hassio/dashboard, for instance.

Restarting HA or restarting the KVM doesn't appear to have an effect on the problem.  Neither does clearing the cache or logging out of HA and logging back in.  The problem persists throughout.

I realize that HassOS, Supervisor, and HA have different release timelines, so I don't know exactly where the problem showed up.  It was certainly more reliable a few weeks ago.

### PR DESCRIPTION
**Pull request by balloob**
## Proposed change

When an ingress panel is open, check every minute if the session is still valid and extend validation. Without this, a web app that has not been used for 10 minutes will stop working.

Requires https://github.com/home-assistant/supervisor/pull/2223

Untested as I don't currently have a supervisor dev env.

Fixes https://github.com/home-assistant/supervisor/issues/2185
## Type of change

- [ ] Dependency upgrade
- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes #
- This PR is related to issue:
- Link to documentation pull request:

## Checklist

- [ ] The code change is tested and works locally.
- [ ] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

**Review by ludeeus — APPROVED** [review]

**Comment by ludeeus** [comment]
Just need to update the path in the test and it should be good to go :+1:  (yeah, we actually test this :exploding_head:  )

**Comment by balloob** [comment]
amazing.

**Comment by balloob** [comment]
Have you been able to test this against the latest supervisor instance ?

**Comment by ludeeus** [comment]
Not more than I saw the expected status and response when it was called.

**Comment by ludeeus** [comment]
Added some extra logs to SU, verified that it bumps the time on session validation calls, also verified that the browser stops checking if you ~~navigate~~ browse away from ingress :+1: 

```
20-11-06 21:58:02 DEBUG (MainThread) [supervisor.api.security] /ingress/validate_session access from Home Assistant
20-11-06 21:58:02 DEBUG (MainThread) [supervisor.ingress] 1604704321.825337
20-11-06 21:59:02 DEBUG (MainThread) [supervisor.api.security] /ingress/validate_session access from Home Assistant
20-11-06 21:59:02 DEBUG (MainThread) [supervisor.ingress] 1604705221.825337
```

**Pull request merged**
