### PR TITLE
Change icon for Heat off

### PR DESCRIPTION
**Pull request by Mariusthvdb**
from `thermometer` (which has other meanings in HA frontend) to `fire-off` which is exactly what we are looking for, the flame is off in the heater

## Type of change

- [ ] Dependency upgrade
- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes #
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [ ] The code change is tested and works locally.
- [ ] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

**Comment by spacegaier** [comment]
Can you please add a screenshot to show the before and after?

**Comment by Mariusthvdb** [comment]
> Can you please add a screenshot to show the before and after?

before is what's in [the docs](https://www.home-assistant.io/integrations/binary_sensor/#device-class)

Scherm­afbeelding 2022-12-08 om 13 37 25

changing that to

Scherm­afbeelding 2022-12-08 om 13 38 17

now see the current state Normal should also change to Off (uit) probably.

**Review by piitaya — APPROVED** [review]

**Comment by Mariusthvdb** [comment]
Paul, are you sure?
I expressed my doubts, and I feel that should be checked....

I was looking for a `device_class: heating` for the actual heaters to be on/off.
I think I mistakenly found this `device_class: heat` which really is a temperature class, just like `device_class: cold` is.

**Comment by piitaya** [comment]
The current `device_class` is not `heater` but `heat` : https://www.home-assistant.io/integrations/binary_sensor/
For moisture we have ` mdi:water-off` and `mdi-water` so for me it make sense to have similar rules for `heat`.

Adding `heater` can be discussed in core and then we can have differents icons for `heat` and `heater` 🙂

**Comment by Mariusthvdb** [comment]
exactly, glad you picked up my error/doubt.
Ive asked for addition of a new device_class in the devs_core, maybe you could jump in there too to confirm?

**Pull request closed without merging**
