### PR TITLE
Make scenes toggleable

### LINKED ISSUE #5610: Add "Activate Scene" to default tap and hold actions in card editors
## The request

A user on Discord was stuck for a bit making a button card to activate a scene. This is probably a very common use case, but it's a little overly difficult / confusing at the moment. 

Right now you have to use call service and then toggle to the code editor to input service data. Many people aren't going to know what service data to enter or might be doing something just slightly off (using `entity:` instead of `entity_id:` for example). 

With Device Automations in the automation/script editors this is super simple and foolproof. Extending this same idea to the Lovelace card editors would be nice if possible.

image

### PR DESCRIPTION
**Pull request by mfschumann**
## Proposed change
This PR adds the state "scening" to the list of entity states that are considered an "off" state. Like that, scenes (that are always in the "scening" state), will always be turned on when they are toggled. This simplifies the configuration of button cards, entity buttons, and header/footer buttons that are supposed to turn on scenes: The user only has to select the entity id when configuring the button in the UI editor, there is no need anymore to change the tap action to call-service and configure service data in the code view.

## Type of change
- [ ] Dependency upgrade
- [ ] Bugfix (non-breaking change which fixes an issue)
- [X] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

Before this PR:
```yaml
type: button
tap_action:
  action: call-service
  service: scene.turn_on
  service_data:
    entity_id: scene.fancy_scene_that_shall_be_turned_on
```
After this PR:
```yaml
type: button
entity: scene.fancy_scene_that_shall_be_turned_on
```

## Additional information

- This PR fixes or closes issue: closes #5610
- This PR is related to issue or discussion: [#8147](https://github.com/home-assistant/frontend/discussions/8147), [forum discussion](https://community.home-assistant.io/t/turn-on-scene-with-button-in-lovelace-card-header-footer/267355)
- Link to documentation pull request:

## Checklist
- [x] The code change is tested and works locally.
- [x] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

**Comment by homeassistant** [comment]
Hi @mfschumann, 

It seems you haven't yet signed a CLA. Please do so [here](https://home-assistant.io/developers/cla_sign_start/?pr=home-assistant&#x2F;frontend#8168).

Once you do that we will be able to review and accept this pull request.

Thanks!

**Comment by bramkragten** [comment]
This change does more than you describe in your description, it will also render scene entities with a toggle now.

We should not abuse this, a scene can not be toggled, just activated.

**Comment by mfschumann** [comment]
Thanks for the feedback. I am not sure if I understand it completely. When I tested the change, scene entities showed exactly as before in entity, entities, and button cards, e.g. for the "Arbeitszimmer Licht an" scene: 

image

Behavior is different, though. As the default action is toggle now, clicking the button or the entry in the entities card activate the scene instead of showing the more-info dialog.

**Comment by bramkragten** [comment]
Yes, in this case, because scene has its own entity row etc. But it is still abusing the system. A scene is not toggleable, so adding it to the toggle domains is not correct.

**Comment by mfschumann** [comment]
I see. Would it instead be acceptable to define a new "turn on" action that then becomes the default action for scenes? I think that would be a cleaner solution and still ease configuration of scene activation buttons in lovelace.

**Comment by bramkragten** [comment]
Yes, I think that would be an option

**Comment by mfschumann** [comment]
Ok, I will try to implement that idea and will open a new PR once I am done.

**Pull request closed without merging**
