### PR TITLE
Fix onboarding error message

### PR DESCRIPTION
**Pull request by joostlek**
## Proposed change

Currently when setting up a new HASS interface and you did not fill in language or country, the user is greeted by a python error saying that language and country is empty. I want to fix this and made a proposal. I want to start to know more how HASS works, so if someone has a better alternative, please let me know.

## Type of change

- [ ] Dependency upgrade
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Checklist

- [x] The code change is tested and works locally.
- [x] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

**Comment by joostlek** [comment]
Oh and I changed a snake case into a camel case, since I saw camel casing everywhere and found this strange.

**Review by steverep — CHANGES_REQUESTED** [review]
HA handles form errors in a much different way, and all user-facing text needs to be translated.  I'll leave it up to you whether you want to close this and start over or update this PR.

The basic procedure would be to set properties on the input field components to define the validity, then use the `ha-alert` component to display the error message at the top of the form.  There are many examples throughout the code, but take a look at `src/panels/config/areas/dialog-area-registry-detail.ts` for a simple one.

**Comment by joostlek** [comment]
Thanks for your reply @steverep. I was wondering, can the messages be translated at this point, since the user hasn't saved their language yet, since this is the form where they should?

I want to update the PR as I want to get more involved :). Thanks for the example

**Comment by steverep** [comment]
Certainly.  It can follow the browser/OS.

Procedure for adding any strings is to add keys to `src/translations/en.json` and use the `hass.localize` function as you'll see all over the code.

**Comment by joostlek** [comment]
@steverep I looked at the component you pointed at and copied the form logic. Could you maybe review it again if it now looks better? I would also like to add a validation on the currency, country and language inputs, since they can now be filled with a non existing value, also creating an exception in the backend. Is there another component which could be an example?

I also think the form would look better if all the fields had the same validations (since now only country and language has them, and the rest (timezone, elevation and currency) don't have any validation and they are defaulted to UTC, 0 and EUR respectively.

**Review by steverep — COMMENTED** [review]
You're right that all the fields should be validated, but now that I'm looking at the form more, we can do much better.  In fact, the whole form should mirror what is in `ha-config-section-general`.  For instance, there we use dropdowns for the country, language, and time zone, which obviously makes much more sense.

@bramkragten is there some reason the onboarding version of this form is just text fields?

**Comment by joostlek** [comment]
I'd be happy to give that a shot :)

**Comment by bramkragten** [comment]
> @bramkragten is there some reason the onboarding version of this form is just text fields?

They don't use just text fields, there are lists added to the textfields so you get a dropdown too, but a more native one.
I'm not sure why this was chosen here, we should probably align them at some point.

**Comment by joostlek** [comment]
@bramkragten Which one of the two would be the desired solution then?

**Comment by steverep** [comment]
The general settings page - the onboarding form is an outlier.

**Pull request closed without merging**
