### PR TITLE
Lovelace Custom ui fallback

### PR DESCRIPTION
**Pull request by cdce8p**
This PR hides an error that occurs if the lovelace UI is loaded before all custom elements are. For a short moment the UI will display an error that the `custom element doesn't exist` before reloading the page correctly.

I think that in most cases it would be ok and less intrusive to just display the `default element` instead. The error `custom element doesn't exist` normally only happens during development and testing, so it would be quite easy to notice IMO even without the flashy warning.

See also: https://community.home-assistant.io/t/lovelace-custom-ui/65026

### CODE REVIEW

**Comment by balloob** [comment]
The problem is that it also happens when a user has misconfigured their custom card imports. Having a big warning instead of "Your card doesn't work" is a good indication that something is wrong.

**Comment by andrey-git** [comment]
Maybe use an element even if it is not defined and replace that with an error after timeout? This way a rebuild is not needed in the most common flow.

**Comment by balloob** [comment]
We can't swap out elements as elements are created and then passed to the caller of the function. We could add a timeout to the error element to not show until 2 seconds in?

**Comment by andrey-git** [comment]
I'm looking for a way to avoid the rebuild which is not needed in the usual usecase.

**Comment by cdce8p** [comment]
@balloob I've added the timeout you asks for. Until we avoid rebuilding, this might be the best way.

**Comment by balloob** [comment]
I think that this is a good solution.

**Pull request merged**
