### PR TITLE
Justify Around Button Base

### LINKED ISSUE #10800: Entities Card Buttons Row: Buttons no longer centered in card row or automatically resized to fill card row
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

After updating to core-2021.12.0b0, the buttons in a multiple-buttons row in an entities card are no longer automatically resized based on the number of buttons, and are left-aligned rather than centered horizontally within the row (see screenshot below).

### Describe the behavior you expected

Prior to core-2021.12.0b0, the buttons automatically resized based on the number of buttons, and were centered horizontally within the row.

### Steps to reproduce the issue

1.
2.
3.
...

### What version of Home Assistant Core has the issue?

core-2021.12.0b0

### What was the last working version of Home Assistant Core?

core-2021.11.5

### In which browser are you experiencing the issue with?

Google Chrome 97.0.4692.36; Home Assistant iOS Companion App 2021.11.1

### Which operating system are you using to run this browser?

Various

### State of relevant entities

_No response_

### Problem-relevant frontend configuration

```yaml
type: entities
entities:
  - type: buttons
    entities:
      - entity: script.good_morning
        tap_action:
          action: call-service
          service: script.turn_on
          service_data:
            entity_id: script.good_morning
      - entity: script.good_night
        tap_action:
          action: call-service
          service: script.turn_on
          service_data:
            entity_id: script.good_night
      - entity: script.goodbye
        tap_action:
          action: call-service
          service: script.turn_on
          service_data:
            entity_id: script.goodbye
      - entity: script.i_m_back
        tap_action:
          action: call-service
          service: script.turn_on
          service_data:
            entity_id: script.i_m_back
      - entity: script.nursery_gentle_wake_up
        tap_action:
          action: call-service
          service: script.turn_on
          service_data:
            entity_id: script.nursery_gentle_wake_up
      - entity: script.nursery_lullaby_radio
        tap_action:
          action: call-service
          service: script.turn_on
          service_data:
            entity_id: script.nursery_lullaby_radio
```

### Javascript errors shown in your browser console/inspector

_No response_

### Additional information

Screenshot 2021-12-05 8 49 29 AM

### PR DESCRIPTION
**Pull request by zsarnett**
## Proposed change
Before:
image

After:
image

## Type of change

- [ ] Dependency upgrade
- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [x] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes #10800
- This PR is related to issue or discussion: #11639 #10892
- Link to documentation pull request:

## Checklist

- [ ] The code change is tested and works locally.
- [ ] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

**Comment by balloob** [comment]
I'm not a fan. I also don't think that's material?

image

https://material.io/components/chips#choice-chips

**Comment by balloob** [comment]
Material 3 chips also don't mention them. https://m3.material.io/components/chips/overview (but I think our style could use an update)

**Comment by zsarnett** [comment]
I think that Justifying evenly / around for our use case is much better visually than left aligning buttons. I would say most cases have 2-3 buttons and left aligning just doesn't look great.. plus you have more room for error when clicking them the closer they are

**Comment by zsarnett** [comment]
The material examples look great because they only show partial parts of the cards..

A lot of wasted space in our implementation

**Comment by spacegaier** [comment]
I agree with Zack. For our use case the justified layout looks much better plus is easier to use especially on touch screen devices.

**Comment by balloob** [comment]
If touch target is an issue, we should just add a margin around our chips. Otherwise it's still an issue if there are more chips. 

I also think that outlining the chips will make it less "invasive" compared to the grey background color. 

I still don't see justifying being better.

**Comment by matthiasdebaat** [comment]
> If touch target is an issue, we should just add a margin around our chips. Otherwise it's still an issue if there are more chips.
> 
> I also think that outlining the chips will make it less "invasive" compared to the grey background color.
> 
> I still don't see justifying being better.

I agree, if touch is the issue we should fix that. Personally I think it is better aligned left (right at RTL)

**Comment by spacegaier** [comment]
To me it just looks off, since everything else is justified. 

Entity rows: Name of the left, state on the right => justified
Glance card: Entities are justified
Weather forecast: Justified
Buttons card: ...
...

**Pull request closed without merging**
