### PR TITLE
Improve Style of stopped Addons

### PR DESCRIPTION
**Pull request by lambnoah99**
## Proposed change

Currently, stopped addons have black&white Icons. Some addons (like ESPHome) already have black&white icons which makes it impossible to see which state they're in. This PR changes the stopped icons to half brightness and a little bit less color.
## Type of change

- [ ] Dependency upgrade
- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes #
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [ ] The code change is tested and works locally.
- [ ] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

**Comment by homeassistant** [comment]
Hi lambnoah99

It seems you haven't yet signed a CLA. Please do so [here](https://home-assistant.io/developers/cla_sign_start/?pr=home-assistant/frontend#13946).

Once you do that we will be able to review and accept this pull request.

Thanks!

**Comment by Misiu** [comment]
@lambnoah99 please add a screenshot showing the before and after. This way we can visually see the difference.

**Comment by piitaya** [comment]
We should add another indicator to show started/stopped addon. Only transforming the icon color is not color blindness friendly.

**Comment by frenck** [comment]
> We should add another indicator to show started/stopped addon. 

We originally had that, which was removed because of "reasons" (I don't know, probably baloob or ludeeus know more).

**Comment by bramkragten** [comment]
> Maybe via the Topbar like this Unbenannt Green would mean running. Nothing would mean stopped

Thats what we use in the addon store (and we had on the addons before too I think?)

**Comment by lambnoah99** [comment]
In the addon-store, the installed addons have a blue (primary-color) bar. Therefore green (success-color) wouldn't interfere with that.

**Comment by bramkragten** [comment]
> In the addon-store, the installed addons have a blue (primary-color) bar. Therefore green (success-color) wouldn't interfere with that.

Yeah, I like it, just not sure why it was removed at some point

**Comment by bramkragten** [comment]
Let's also add a text with the status for a11y, like:
image

**Comment by lambnoah99** [comment]
> > In the addon-store, the installed addons have a blue (primary-color) bar. Therefore green (success-color) wouldn't interfere with that.
> 
> Yeah, I like it, just not sure why it was removed at some point

I'll try to implement this (the Screenshot was just done with the Browser devtools)

**Pull request closed without merging**
