### PR TITLE
Add select prev boots in error-log-card

### PR DESCRIPTION
**Pull request by wendevlin**
## Proposed change
- Add boot selector for logs, to show logs of previous boots
- Add boot information to download all logs

image

## Type of change
- [ ] Dependency upgrade
- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR is related to core PR: https://github.com/home-assistant/core/pull/129151

## Checklist

- [x] The code change is tested and works locally.
- [x] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

**Review by piitaya — COMMENTED** [review]
Can we use the same button as the one we use in the data table?

CleanShot 2024-10-25 at 16 39 54

**Comment by wendevlin** [comment]
> Can we use the same button as the one we use in the data table?
> 

Which one do you mean? I took the dropdown from data table 🤔

**Comment by piitaya** [comment]
Looks like some style are missing : 
```css
--md-assist-chip-trailing-space: 8px;
--ha-assist-chip-container-shape: 10px;
```

**Comment by wendevlin** [comment]
@piitaya thanks, I fixed it.

**Review by piitaya — APPROVED** [review]

**Pull request merged**
