### PR TITLE
Correct updating input_datetime when the state includes timezone

### PR DESCRIPTION
**Pull request by jbouwh**
# Proposed change
Needed to get PR: https://github.com/home-assistant/core/pull/61698 to work.
This is a bugfix to allow the `input_datetime` entity state to support timezones.
The frontend though splits the state in two parts (date and time). The time part also contains timezone info, that causes invalid service calls to happen.

This PR strips the timezone part from the state (if a timezone part exists).

## Type of change

- [ ] Dependency upgrade
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes #
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [ ] The code change is tested and works locally.
- [x] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

**Comment by jbouwh** [comment]
Finally I was able to test this update. This fix strips any timezone info to make sure a valid service call is made.

**Comment by spacegaier** [comment]
TBH I haven't really delved into this PR (esp. the reasoning behind it), but just a quick thought: What is with timestamps that have a "Z" for "UTC" at the end instead of a plus or minus offset?

**Comment by jbouwh** [comment]
> TBH I haven't really delved into this PR (esp. the reasoning behind it), but just a quick thought: What is with timestamps that have a "Z" for "UTC" at the end instead of a plus or minus offset?

This part is only used for the `input_datetime` entity. The state will be a `datetime` object with time zone info that is casted to a string. The refered PR in core will realize that because the way dates and times are processed in templates has changed.

The frontend uses the entity state an cast this to a string. (str(`datetime`)).

E.g.
```python
from datetime import datetime, tzinfo
a=datetime(2011, 8, 15, 8, 15, 12, tzinfo=pytz.UTC)
print(str(a))
```
Will output '2011-08-15 08:15:12+00:00'

The current code uses a `split(' ')` to obtain date and time. But the time part has still an offset that needs to be stripped to ensure a valid service call is performed.

**Comment by spacegaier** [comment]
But wouldn't `2011-08-15 08:15:12Z` also be a valid datetime string in Python that therefore the frontend could encounter? It is at least a valid ISO 8601 value.

**Comment by jbouwh** [comment]
> But wouldn't `2011-08-15 08:15:12Z` also be a valid datetime string in Python that therefore the frontend could encounter? It is at least a valid ISO 8601 value.
Sure but the service call only accepts a separate date, a separate time, or both, without timezone info.
I do not want to change that, what we want to do here is to assure the timezone part is stripped off here. In de backend the date and time are combined as local date and time.

**Comment by bramkragten** [comment]
We should not do this, we can't just ignore the timezone information if there is any, we should then use that information to parse it. But it would make it a lot more complex and breaking.

This is not the solution, closing it.

**Pull request closed without merging**
