### PR TITLE
Use the calendar color for state icon in event details

### PR DESCRIPTION
**Pull request by spacegaier**
## Proposed change

Calendars both in the panel and in a dashboard card get assigned colors so you can differentiate which events belong to which source. But if you then click on an event the shown popup with the event details does not use the same color, but instead always the generic one. 

This PR makes the state icon use the same color for a consistent visual approach. 

In all places where calendars have no color (e.g. logbook) nothing changed.

image

## Type of change

- [ ] Dependency upgrade
- [ ] Bugfix (non-breaking change which fixes an issue)
- [X] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes #
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [X] The code change is tested and works locally.
- [X] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

**Review by bramkragten — DISMISSED** [review]

**Review by bramkragten — APPROVED** [review]

**Comment by bramkragten** [comment]
Can we also add this color and icon to the add event dialog?

**Comment by bramkragten** [comment]
In the picker, like we also show the entity icon in the entity picker (why don't we just use the entity picker there btw?)

**Comment by bramkragten** [comment]
#14772

**Comment by spacegaier** [comment]
> In the picker, like we also show the entity icon in the entity picker (why don't we just use the entity picker there btw?)

I think in the picker we do not yet have a color for the calendar. Those colors are not static but depend on how many calendars are there in the panel or selected for a calendar card. Once we show the event details in the popup we know which colors a calendar has and can use that, but in the picker we don't.

**Pull request merged**
