### PR TITLE
Add Y axis limits options for historical charts

### PR DESCRIPTION
**Pull request by AnMakc**
## Proposed change

This PR adds options to control displayed values range for historical graph cards. Either lower, upper or both limits could be set. There is an option to automatically extend range to fit the data.

This is useful to keep graphs visually representative if the data range for the displayed period is too narrow or data contains outliers.

This is not implemented for statistic graph intentionally, see https://github.com/home-assistant/frontend/pull/19297#issuecomment-1879425065

**Default behavior**
Screenshot 2024-01-05 at 12 22 42

**Limits set (min: 10, max: 28), limits extension not allowed**
Screenshot 2024-01-05 at 12 22 29

**Limits set (min: 10, max: 28), limits extension allowed**
Screenshot 2024-01-05 at 12 22 14

**Visual editor section**
Screenshot 2024-01-05 at 12 22 04

## Type of change

- [ ] Dependency upgrade
- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml
type: history-graph
entities:
  - entity: <SENSOR_NAME>
min_y_axis: 10
max_y_axis: 30
fit_y_data: true
```

## Additional information

- This PR fixes or closes issue: fixes #
- This PR is related to issue or discussion: [1](https://community.home-assistant.io/t/optional-fixed-limits-for-history-graphs/142551), [2](https://community.home-assistant.io/t/set-graph-axis-range-on-history-graph/213031), [3](https://community.home-assistant.io/t/is-it-possible-to-limit-the-y-axis-of-the-history-graph-card/71389), [4](https://community.home-assistant.io/t/set-min-max-value-of-y-axis-on-graphs/499968), [5](https://community.home-assistant.io/t/history-graph-with-min-and-max-horizontal-lines/119677)
- Link to documentation pull request: https://github.com/home-assistant/home-assistant.io/pull/30665

## Checklist

- [x] The code change is tested and works locally.
- [x] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

**Comment by AnMakc** [comment]
There is one corner case.
If the user specifies negative minimum value for statistic graph with bars, bars are still drawn starting from zero.

Screenshot 2024-01-05 at 13 01 57

Let me know if this should be covered and you have any ideas.

**Comment by AnMakc** [comment]
Actually there are more non-obvious things with statistic bar charts.

1. Lower boundary is extended to zero (bottom of the bars) if the data fitting is allowed.
2. If the upper boundary is lower than the bar top, this bar is omitted.

The latter is definitely a problem, will look into it.

**Comment by pooh22** [comment]
I got notified of this PR, probably because of Discussion #18258, which I can't find anymore. I appreciate someone implementing this kind of feature. I do want to point out that my original idea was to have a fixed vertical range, which moves along with a steadily growing measurement (never getting less). It makes sense when you have an expected amount of e.g. gas usage and you want to see if in the shown period less or more than expected is used. Currently the graph can only show the range that fits the min/max values in the period shown. I'd like to be able to set the max range to be the value at T-0 in the graph plus the (T-end minus T-0)*growrate. So the growrate should be configurable...

Anyway, please keep up the good work!

**Comment by AnMakc** [comment]
It seems there is a bug in chart.js
Minimal reproduction is [here](https://stackblitz.com/edit/line-chart-5yxrkz?file=app%2Fapp.component.ts) (see lines 67-77).

When `time` scale is used for X-axis and no boundaries are provided, automatic boundaries do not respect data which is out of Y-axis boundaries.

I will revert statistics graph changes for now as it is only affected and reach out to chart.js team.

Historical graph is fine though, so please proceed with the review.

**Comment by karwosts** [comment]
Do you know why the bug affects statistics line chart, but not history line chart? I would have thought they were fairly similar. 

Had two minor UI suggestions: 
 - You could put min/max inside a grid element to make them fit on one line, they don't really need to both be full width. 
 - If I'm understanding correctly, if user does not specify a min/max, than the "extend y axis" toggle does nothing. Might be nice to conditionally hide that toggle in that case, otherwise I think it could be a little bit confusing.

**Comment by AnMakc** [comment]
> Do you know why the bug affects statistics line chart, but not history line chart? I would have thought they were fairly similar.

History line chart specifies X-axis range via `suggestedMin` and `suggestedMax` which is checked to fix this behaviour. This could also be done for statistics graph chart, but this will definitely be a workaround I want to avoid.

**Comment by AnMakc** [comment]
> If I'm understanding correctly, if user does not specify a min/max, than the "extend y axis" toggle does nothing. Might be nice to conditionally hide that toggle in that case, otherwise I think it could be a little bit confusing.

Agree, will do. Could you please point me to some form with conditionally displayed field as an example?

**Comment by karwosts** [comment]
> > If I'm understanding correctly, if user does not specify a min/max, than the "extend y axis" toggle does nothing. Might be nice to conditionally hide that toggle in that case, otherwise I think it could be a little bit confusing.
> 
> Agree, will do. Could you please point me to some form with conditionally displayed field as an example?

You can look at gauge card for an example, it hides some fields behind `showSeverity`. Feel free to ask if you run into trouble.

**Comment by AnMakc** [comment]
> You can look at gauge card for an example

Thanks, that's helped. 

Now the fit option switch is only shown if either min or max limit is set.

**Comment by Jojo-A** [comment]
Hi @AnMakc ,
I wished for this feature since the very beginning. So thank you a lot for your efforts in implementing this! 
I'd really look forward to see this feature getting merged asap!
I am not familiar with the merging system of Home Assistant in detail. But if seems to me as if everything looks good so far and the only thing missing is an official review. Is there anything we can do to push this a little bit forward or do we just have to wait?

Thanks again and greetings!

**Review by bramkragten — APPROVED** [review]

**Comment by Jojo-A** [comment]
@AnMakc 
this is perfect, thank you! Directly applied to all my history graphs right after update.
:+1:

**Pull request merged**
