### PR TITLE
Remove aria-label and blur from list items

### PR DESCRIPTION
**Pull request by steverep**
## Proposed change

I'm preparing to improve a11y for standalone instances of `mwc-list` and button menus which contain links.  This is some starter cleanup work:

- Removes remaining `aria-label` attributes from list items (again the contents provide the accessible name)
- Removes any `label` properties on list items as well (not a valid property)
- Removes calls to `blur()` for instances of `ha-clickable-list-item` (it's very unclear to me why these exist, but in general calls to `blur` are ticking off keyboard users 99% of the time)

## Type of change

- [ ] Dependency upgrade
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes #
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [x] The code change is tested and works locally.
- [x] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

**Review by piitaya — COMMENTED** [review]
I'm ok with the changes. I also don't understand why we have the `blur()` call. May be @bramkragten will have an answer.

**Comment by bramkragten** [comment]
Without the blur, the item clicked will not lose focus when the link opens a new window, probably because the ripple event handlers from mwc dont get triggered correctly.

It is not a deal breaker however imho.

**Comment by steverep** [comment]
Right, but why is that desirable?  From a keyboard user's perspective, a blur moves the focus back to the beginning of the page usually (depends on browser), and then you have to re-navigate to where you were.

**Comment by bramkragten** [comment]
yeah agree, lets remove the blur

**Review by bramkragten — APPROVED** [review]

**Pull request merged**
