### PR TITLE
Migrate mailbox to LitElement

### PR DESCRIPTION
**Pull request by silamon**
## Proposed change
Migrate mailbox to LitElement. 
There was a little refactoring (header, mp3 play) but the functionality and design remained the same.  

(After this PR, you can clean up some Polymer classes and packages since this is the last usage of ha-app-layout.)

## Type of change
- [ ] Dependency upgrade
- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [x] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes #
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [x] The code change is tested and works locally.
- [x] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

**Comment by steverep** [comment]
> (After this PR, you can clean up some Polymer classes and packages since this is the last usage of ha-app-layout.)

We should delete `ha-app-layout.js` here - no need to leave it around.  Looks like `@polymer/app-layout` can be removed as direct dependency only after a couple uses in the demo content is converted.

**Comment by silamon** [comment]
> > (After this PR, you can clean up some Polymer classes and packages since this is the last usage of ha-app-layout.)
> 
> We should delete `ha-app-layout.js` here - no need to leave it around. Looks like `@polymer/app-layout` can be removed as direct dependency only after a couple uses in the demo content is converted.

I will open a PR after this one is merged in. As far as I'm aware, there's no usage anymore in the demo content?

**Comment by steverep** [comment]
`ha-app-layout.js` should be removed in this PR since it's dead code now.

And I meant the gallery, not the demo; `app-toolbar` is still used in:

- https://github.com/home-assistant/frontend/blob/e6efb5da83e18457ac3dd6cf4144982f4cc97f8f/gallery/src/components/demo-more-infos.js#L36
- https://github.com/home-assistant/frontend/blob/e6efb5da83e18457ac3dd6cf4144982f4cc97f8f/gallery/src/components/demo-cards.ts#L23

Converting those can be another PR to remove `@polymer/app-layout`.

**Review by piitaya — APPROVED** [review]

**Comment by silamon** [comment]
> My review comment was ignored here - `ha-app-layout.js` should be deleted.

I didn't ignore your comment, as promised there's now a PR to clean it up: #17739. 
Side information: the gallery usages of app-toolbar have been removed in the meantime as well in a different PR.

**Comment by piitaya** [comment]
Sorry @steverep, I misunderstood your comment. I thought you suggested to remove both `ha-app-layout` and `@polymer/app-layout` in another PR.
BTW, it's fixed with https://github.com/home-assistant/frontend/pull/17739.

**Comment by steverep** [comment]
> I didn't ignore your comment, as promised there's now a PR to clean it up: #17739.

My comment was to remove it in **this** PR.  Separate PRs to clean up other commits is bad practice.  It just results in a longer commit history that's more difficult to follow, blame, revert, etc.

And if it was removed here, the error now fixed in #17739, where `ha-app-layout` was still being imported, would have been caught.



> Side information: the gallery usages of app-toolbar have been removed in the meantime as well in a different PR.

Same comment applies there too.  The `@polymer/app-layout` package was dead as of #17667, so it should have been removed there for completeness.

**Pull request merged**
