### PR TITLE
Use new light HS API for the color picker

### PR DESCRIPTION
**Pull request by emlove**
## Description
Frontend PR for https://github.com/home-assistant/home-assistant/pull/11288

This PR updates the frontend to use the new hue/sat API for the light color picker.

### CODE REVIEW

**Comment by NovapaX** [comment]
Awesome, what a cleanup 👍 
I have mixed feelings about removing the 'value' from the color picker element. It's currently not used in de our context of the lights. But removing it reduces the reusability of the element (for example to pick interface colors). But whatever, it's easy to put back in :)

**Comment by armills** [comment]
Well right now at least it didn't have any way to actually select a value, it was just hard-coded to 100%. We'd need a new UI element to properly select a value if we wanted to use it for that. That would definitely make it more reusable though.

Also certainly not opposed to adding RGB back to this component if we want to use it, but I'd rather not ship unused code since anything included here contributes to the size of the frontend build clients need to download.

**Comment by NovapaX** [comment]
Agree on your points.
We'll just add it back in if needed. (long live version control)

**Review by balloob — APPROVED** [review]

**Comment by armills** [comment]
Didn't realize we ran into merge conflicts here. I'll get this branch up-to-date tonight.

**Pull request merged**
