### PR TITLE
Add Afrikaans and Basque languages support

### LINKED ISSUE #217: add basque language
*@asieriko commented on Dec 15, 2018, 7:53 PM UTC:*

As per [https://developers.home-assistant.io/docs/en/internationalization_translation.html#adding-a-new-language](https://developers.home-assistant.io/docs/en/internationalization_translation.html#adding-a-new-language)
English Name: Basque
Native Name: Euskara
Language Code: eu,eu_ES,eu_FR

Thank you

*This issue was moved by [iantrich](https://github.com/iantrich) from [home-assistant/home-assistant-polymer#2332](https://github.com/home-assistant/home-assistant-polymer/issues/2332).*

### LINKED ISSUE #257: Language request - Basque
*@blizarazu commented on Jan 26, 2019, 4:24 PM UTC:*

English Name: Basque
Native Name: Euskara
Language Code : eu

*This issue was moved by [iantrich](https://github.com/iantrich) from [home-assistant/home-assistant-polymer#2569](https://github.com/home-assistant/home-assistant-polymer/issues/2569).*

### LINKED ISSUE #259: Adding a new language
*@shark711 commented on Sep 8, 2018, 1:01 AM UTC:*

As per [https://developers.home-assistant.io/docs/en/internationalization_translation.html#adding-a-new-language](https://developers.home-assistant.io/docs/en/internationalization_translation.html#adding-a-new-language)
English Name: Afrikaans
Native Name: Afrikaans
Language Code: af, af-ZA

*This issue was moved by [iantrich](https://github.com/iantrich) from [home-assistant/home-assistant-polymer#1645](https://github.com/home-assistant/home-assistant-polymer/issues/1645).*

### PR DESCRIPTION
**Pull request by awarecan**
Fixes home-assistant/ui-schema#259
Fixes home-assistant/ui-schema#257
Fixes home-assistant/ui-schema#217

Afrikaans and Basque languages have been added to both frontend and backend lokalise projects.

@shark711, @blizarazu, @asieriko you can start translate now.  

I translated small part of them to make sure the new language worked. Feel free to review and change them. Blame Google if you found any silly translation.

### CODE REVIEW

**Comment by blizarazu** [comment]
How can we start translating? I can't find the Basque language in Lokalise.

Thanks.

**Comment by awarecan** [comment]
@blizarazu 

image

Or try this link: https://lokalise.co/project/3420425759f6d6d241f598.13594006/?view=single&reference_lang_id=640&single_lang_id=911

**Comment by blizarazu** [comment]
Sorry but I can't see Basque language in the list of available languages. That link brings me to https://lokalise.co/project/3420425759f6d6d241f598.13594006/?view=multi and Basque is not in the list. Am I missing any step?

**Comment by awarecan** [comment]
I can find Basque following your link. It is the fourth place, after Arabic. It displays as Spain flag on the top, the 4th place as well.

**Comment by blizarazu** [comment]
This is what I see when I click the link
image


And these are the available languages I can see
image

**Comment by awarecan** [comment]
Interesting, all three new languages I recently added are not showed up. I will look into it.

**Comment by awarecan** [comment]
@blizarazu I assigned new languages to you, let me know if you still have problem.

**Comment by blizarazu** [comment]
Now I can see it. Thank you!

**Comment by shark711** [comment]
I still can't see it though, do I have the correct project?
https://lokalise.co/project/3420425759f6d6d241f598.13594006
https://lokalise.co/project/130246255a974bd3b5e8a1.51616605

**Comment by awarecan** [comment]
@shark711 you should have access now.

There are some issues in lokalise.co side, I have to add the new languages to each translator and we have 1300+ translator in our team.

I am talking with their support now, see if they can help me batch update, or fix their issue.

Right now, I have to manual update individual contributor's settings.

**Comment by shark711** [comment]
I can access it thanks!
Can you change the flag to the South African flag?

**Comment by blizarazu** [comment]
Basque language should be just Basque without variation (eu instead of eu-ES) and the flag should be this one:

imagen

**Comment by awarecan** [comment]
@blizarazu please ignore the flag displayed in lokalize.co, it is not end-user facing. I customized the language tag, so it indeed is `eu`, not `eu-ES`. But I don't have a way to change the flag.

We don't have any flag displayed in our frontend.

**Comment by awarecan** [comment]
@shark711 similar response to your request, I have no control over the flag displayed in lokalize.co. And it won't displayed in our frontend anyway.

**Comment by blizarazu** [comment]
@awarecan Thank you!

**Pull request merged**
