### PR TITLE
The gauge card doesn't render correctly on iOS 15.2 / macOS 12.1 in the companion apps

### LINKED ISSUE #11041: The gauge card doesn't render correctly on iOS 15.2 / macOS 12.1 in the companion apps
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

This is the same issue as #10766 for which a partial fix was submitted via #10992. A potential fix was suggested in [this comment](https://github.com/home-assistant/frontend/pull/10992#issuecomment-1002134042).

### Describe the behavior you expected

The gauge card should correctly render also in the Home Assistant companion apps on both iOS/macOS.

### Steps to reproduce the issue

Have a gauge card configured like:
```
- type: gauge
   entity: sensor.temperature
   min: 0
   max: 100
   severity:
     green: 20
     yellow: 22
     red: 25
   name: ' '
```

### What version of Home Assistant Core has the issue?

core-2021.12.6 (and earlier)

### What was the last working version of Home Assistant Core?

_No response_

### In which browser are you experiencing the issue with?

Safari 15.2 +

### Which operating system are you using to run this browser?

macOS 12.1, iOS 15.2

### State of relevant entities

_No response_

### Problem-relevant frontend configuration

_No response_

### Javascript errors shown in your browser console/inspector

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by raducotescu**
## Proposed change

1. enhanced the Safari test from #10766
2. added special handling for the HA Companion App on macOS/iOS - fixes #11041 

## Type of change
- [ ] Dependency upgrade
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [x] Code quality improvements to existing code or addition of tests

## Additional information
- This PR fixes or closes issue: fixes #11041
- This PR is related to issue or discussion: #10766
- Link to documentation pull request:

## Checklist
- [x] The code change is tested and works locally.
- [x] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

**Comment by raducotescu** [comment]
@balloob, could you please run the workflows for this PR? Who else should review it? I've tested it by running a new HA instance in Docker, to which I mounted the `frontend` in a volume. Everything worked as expected. Both Safari and the companion apps running on iOS/macOS render the gauge card correctly now.

**Comment by raducotescu** [comment]
All the linked issues mentioned above should be fixed by this PR.

**Comment by raducotescu** [comment]
Neither the fix from #10766 nor this will address other browsers than Safari on iPhone / iPad, where the apps are forced to use the WebKit version provided by Apple. This is because the user agents are different for each browser:

1. Chrome on iOS: `Mozilla/5.0 (iPhone; CPU iPhone OS 15_2 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) CriOS/96.0.4664.116 Mobile/15E148 Safari/604.1`
2. Firefox on iOS: `Mozilla/5.0 (iPhone; CPU iPhone OS 15_2 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) FxiOS/40.2 Mobile/15E148 Safari/605.1.15`

I guess we could _also_ parse the `iPhone OS 15_2 like Mac OS X` part, but I don't have an iPad that could run the latest iPadOS so that I could verify the fix. The same actually applies to the companion app on iPad - I'd need somebody to provide me with a user agent from the companion app, to check if the fix from this PR works correctly.

**Comment by raducotescu** [comment]
According to [1] and [2] the user agent used by both Firefox and Chrome on an iPad will be equivalent to the Safari desktop user-agent. However, it seems that the `Version` is not reported correctly, so any kind of detection based on the user agent for these two browsers will fail.

In the end, I think we will have to accept this PR in its current state, which at least makes Safari on iOS >= 15.2 and macOS >= 12.1 plus the companion app to render the gauge cards correctly.

[1] - https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/User-Agent/Firefox
[2] - https://developer.chrome.com/docs/multidevice/user-agent/#chrome-for-ios

**Comment by zsarnett** [comment]
Ill take a look at this later today or tomorrow. Thanks!

**Comment by bramkragten** [comment]
I suggest we remove all animation from the gauge in Safari. This is getting way too messy.

**Comment by balloob** [comment]
If this workaround is only for animations, then I agree.

**Comment by raducotescu** [comment]
> I suggest we remove all animation from the gauge in Safari. This is getting way too messy.
How would you then render the gauge card on Safari?

> If this workaround is only for animations, then I agree.
The "workaround" is not for the animation itself, but rather for the way the gauge "fill" area is rendered.

**Comment by raducotescu** [comment]
Can we have a decision here, please? Whatever the decision will be, it’s better than not doing anything. I really want to use gauge cards for my climate dashboard and all of my devices are Apple ones.

If you decide to merge the PR that’s great, if not I can obviously fork the gauge card and create a custom one for my instance, but this limbo state doesn’t help anyone.

**Comment by bramkragten** [comment]
From what I can remember, the issues with Safari where with the way we animate the gauge, so you are saying the issues are still there if you remove all animations?

**Comment by raducotescu** [comment]
@bramkragten, the issue is not caused by `ha-card > ha-gauge > svg > animatetransform`, but rather by how the `transform` is applied to `ha-card > ha-gauge > svg > path`.

Now that I pay more attention to it, there isn't any initial animation in Safari 15.2 and above, the way you defined in #6492.

**Comment by bramkragten** [comment]
This is the solution probably to not have to check for Safari anymore (this is just for the none needle gauge):

```diff
diff --git a/src/components/ha-gauge.ts b/src/components/ha-gauge.ts
index 9ce125966..64852ac68 100644
--- a/src/components/ha-gauge.ts
+++ b/src/components/ha-gauge.ts
@@ -65,12 +65,12 @@ export class Gauge extends LitElement {
 
   protected render() {
     return svg`
-      <svg viewBox="0 0 100 50" class="gauge">
+      <svg viewBox="-50 -50 100 50" class="gauge">
         ${
           !this.needle || !this.levels
             ? svg`<path
           class="dial"
-          d="M 10 50 A 40 40 0 0 1 90 50"
+          d="M -40 0 A 40 40 0 0 1 40 0"
         ></path>`
             : ""
         }
@@ -87,9 +87,9 @@ export class Gauge extends LitElement {
                         stroke="var(--info-color)"
                         class="level"
                         d="M
-                          ${50 - 40 * Math.cos((angle * Math.PI) / 180)}
-                          ${50 - 40 * Math.sin((angle * Math.PI) / 180)}
-                         A 40 40 0 0 1 90 50
+                          ${0 - 40 * Math.cos((angle * Math.PI) / 180)}
+                          ${-50 - 40 * Math.sin((angle * Math.PI) / 180)}
+                         A 40 40 0 0 1 40 25
                         "
                       ></path>`;
                   }
@@ -125,17 +125,8 @@ export class Gauge extends LitElement {
               `
             : svg`<path
                 class="value"
-                d="M 90 50.001 A 40 40 0 0 1 10 50"
-                style=${ifDefined(
-                  !isSafari
-                    ? styleMap({ transform: `rotate(${this._angle}deg)` })
-                    : undefined
-                )}
-                transform=${ifDefined(
-                  isSafari
-                    ? `rotate(${this._angle}${isSafari152 ? "" : " 50 50"})`
-                    : undefined
-                )}
+                d="M -40 0 A 40 40 0 1 0 40 0"
+                style=${styleMap({ transform: `rotate(${this._angle}deg)` })}
               >`
         }
         ${
@@ -187,7 +178,6 @@ export class Gauge extends LitElement {
         fill: none;
         stroke-width: 15;
         stroke: var(--gauge-color);
-        transform-origin: 50% 100%;
         transition: all 1s ease 0s;
       }
       .needle {
```

**Comment by raducotescu** [comment]
Let me test it on my setup and see if works correctly in all the browsers/apps that can run on my Mac. It would be cool if we could get rid of the Safari-specific code, but we should also make sure that people who haven't updated to the latest Safari don't experience any issues.

**Comment by bramkragten** [comment]
It _should_ work on all browsers, it shifts everything so the rotation origin is in the 0,0 of the viewport. That was the issue in Safari in the first place.

**Comment by raducotescu** [comment]
It seems to render correctly on all Safari versions I have access to: 15.1, 15.2, 15.3. The needle code will have to be adapted though and that's where I'm stuck. :D

**Comment by bramkragten** [comment]
You should change all x and y coordinates to 50 less

**Comment by raducotescu** [comment]
Thanks for the hint, @bramkragten! I have a slightly different patch based on what you started and it seems to work correctly on Safari >= 15.1 (it doesn't affect the Safari 15.1 rendering and also works correctly on Safari 15.2 and above). I want to test it on iOS 14 as well and, if successful, will open a new PR.

**Comment by raducotescu** [comment]
Let's close this PR in favour of #11363, which is way cleaner.

**Pull request closed without merging**
