### PR TITLE
Fix hassio log overflow issue

### LINKED ISSUE #1350: Scrolling on hassio logs not working as expected
**Home Assistant release with the issue:**

0.72.1

**Browser and Operating System:**

Chrome

**Description of problem:**

Scrolling on the log card can overflow the page and is not scrolling correctly (especially on mobile devices)

### PR DESCRIPTION
**Pull request by timmo001**
## Description

Fixes issue with logs overflowing when logs are larger than the current screen

## Related issue this fixes

#1350 

## Screenshots

image

image

image

image

### CODE REVIEW

**Comment by c727** [comment]
is this tested?

**Comment by timmo001** [comment]
I'm just testing this on my instance now

**Comment by timmo001** [comment]
I'm unable to test this on my hassio setup but I did test it using the dev tools (see screenshots) so I know this should fix the issue. If someone knows how to run these changes in hassio it would be great. I did read the docs but they seem way too much of a pain to get set up. https://developers.home-assistant.io/docs/en/hassio_hass.html

I also have no access to a working card reader so I cant add my ssh key to connect to the host system of hassio

**Comment by c727** [comment]
I asked because this doesn't fix anything...

We don't accept drive-by-PRs

**Pull request closed without merging**
