### PR TITLE
Add icons for new sensor device classes

### PR DESCRIPTION
**Pull request by fabiocastagnino**
## Proposed change
I want to add 4 new device_classs, to handle the electrical measurement, related to PR:
https://github.com/home-assistant/core/pull/36800

## Type of change

- [ ] Dependency upgrade
- [ ] Bugfix (non-breaking change which fixes an issue)
- [X] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Additional information

- This PR fixes or closes issue: fixes #
- This PR is related to issue:
- Link to documentation pull request: 

## Checklist

- [x] The code change is tested and works locally.
- [x] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

**Comment by bramkragten** [comment]
Can you add a screenshot of the icons with the device class?

**Review by bramkragten — APPROVED** [review]

**Comment by fabiocastagnino** [comment]
off course:
https://user-images.githubusercontent.com/9453234/85062718-4301c400-b1a9-11ea-9a01-e8a034bc8aeb.png

**Comment by spacegaier** [comment]
There are also dedicated MDI icons for current, but they differentiate between AC and DC, so they are probably not usable here in a generic setting.
image

**Comment by dgomes** [comment]
I support @spacegaier since the voltage icon used is also for AC, we should use mdi-current-ac

**Comment by MartinHjelmare** [comment]
Core PR is merged.

**Review by elupus — COMMENTED** [review]
Isn't something like mdi:guage and counter better here than flash. The flash symbol is overused in HA already.

Also voltage seem odd too since there is nothing saying it's AC. But maybe okey.

**Comment by ludeeus** [comment]
why is an icon for current used for voltage, wouldn't `hass:flash` fit better?

**Comment by frenck** [comment]
Honestly, I think `hass:flash` is overused, there is no difference in a switch, power, energy, current, power factor, and possibly: voltage.

**Comment by ludeeus** [comment]
I agree!
Just thought it was weird that an icon for current was used for voltage, and the flash icon for current, feels those should be switched at least :shrug:

**Comment by fabiocastagnino** [comment]
Tecnically both current and voltage have sinusine form, it's only the name in the icon set that are misleading.
I agree with @frenck `hass:flash` is overused. 
Any suggestion to better icon?
`axis` or `angle-acute` for power_factor
`sine-wave` for voltage
`flash` for current, energy and power, but I can't find better
?

**Comment by elupus** [comment]
Guage, counter?

**Comment by ludeeus** [comment]
There are icons for current, why not use any of them for current?

**Comment by bramkragten** [comment]
So we should change:

- `sine-wave` for voltage
- `hass:current-ac` for current

And power-factor? 🤷‍♂️

**Comment by dgomes** [comment]
I would go with @fabiocastagnino suggestion: mdi:angle-acute

**Pull request merged**
