### PR TITLE
Change "persons" to "people"

### PR DESCRIPTION
**Pull request by sampl**
## Proposed change

"Persons" is an old, formal word. "People" is much more common and natural-sounding.

[Cambridge Dictionary](https://dictionary.cambridge.org/us/grammar/british-grammar/person-persons-or-people):

> Persons (plural) is a very formal word. We only use it in rather legalistic contexts. To refer to groups of human beings or humans in general, we use people.

[Merriam Webster](https://www.merriam-webster.com/words-at-play/people-vs-persons):

> For references to groups of a specific or general number, either people or persons may be used, but modern style guides tend to prefer people

[Grammarly](https://www.grammarly.com/blog/persons-people-peoples):

> Most of the time, people is the correct word to choose as a plural for person. Persons is archaic, and it is safe to avoid using it, except in legal writing, which has its own traditional language

## Type of change

- [ ] Dependency upgrade
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes #
- This PR is related to issue:
- Link to documentation pull request:

## Checklist

- [ ] The code change is tested and works locally.
- [x] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

**Comment by homeassistant** [comment]
Hi @sampl, 

It seems you haven't yet signed a CLA. Please do so [here](https://home-assistant.io/developers/cla_sign_start/?pr=home-assistant&#x2F;frontend#7037).

Once you do that we will be able to review and accept this pull request.

Thanks!

**Review by bramkragten — APPROVED** [review]

**Review by KTibow — APPROVED** [review]

**Comment by CM000n** [comment]
Isn't that a question of context? In the German context of software solutions and products in general one would never speak of "Leute" (German word for "people"). Instead, the term "Personen" (German for "Persons") is still more common here. 
Of course, I can't speak for the English-speaking world, but at least in the German language, a corresponding change of the designation in the frontend and the translation that comes with it could look strange.

I don't know if that even matters here. But it came to my mind spontaneously when I saw the PR.

**Comment by zsarnett** [comment]
That can be changed in Lokalize for those languages

**Comment by sampl** [comment]
It makes sense that it’s different in German and elsewhere, languages are
wild!

Hopefully it’s clear that this is for the English version only, lmk if I
need to edit to make that true.

**Pull request merged**
