### PR TITLE
Add Core to supervisor/system

### PR DESCRIPTION
**Pull request by ludeeus**
## Proposed change

Add a Core card to supervisor/system.
With both core and supervisor using calver, the confusion continues, hopefully, this will make things clearer.
Action buttons have also been prefixed, like "Supervisor restart"

The metrics card is removed and the metrics are inserted at the bottom of their respective cards.

## Type of change

- [ ] Dependency upgrade
- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes #
- This PR is related to issue or discussion: 
	- https://community.home-assistant.io/t/2021-1-happy-new-year/264975/38
	- https://community.home-assistant.io/t/2021-1-happy-new-year/264975/39
	- https://community.home-assistant.io/t/2021-1-happy-new-year/264975/63
	- https://community.home-assistant.io/t/2021-1-happy-new-year/264975/65
	- https://community.home-assistant.io/t/2021-1-happy-new-year/264975/71
	- https://community.home-assistant.io/t/2021-1-happy-new-year/264975/72
	- https://community.home-assistant.io/t/2021-1-happy-new-year/264975/76
	- I can probably find other examples in other threads, but you get the point.
- Link to documentation pull request:

image

## Checklist

- [x] The code change is tested and works locally.
- [x] There is no commented out code in this PR.
- [:joy:] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

**Comment by bramkragten** [comment]
Shouldnt core be the first card?

**Comment by ludeeus** [comment]
It's the Supervisor panel, IMO all other "sections" are secondary information

**Comment by frenck** [comment]
I agree with Bram. It feels more logical to have Core -> Supervisor -> Host (or Host -> Supervisor -> Core) in order of the way they are stacked.

**Review by bramkragten — APPROVED** [review]

**Comment by ludeeus** [comment]
Core - SU - host
image

Host - SU - Core
image

**Comment by frenck** [comment]
For me, personally, either works. The last one (host first) feels more focused on the Supervisor panel maybe, so that might be better.

**Comment by bramkragten** [comment]
Personally, I would still prefer core first, but I can also live with this.

**Comment by frenck** [comment]
@bramkragten Haha that is actually a valid concern 😓

**Comment by ludeeus** [comment]
reordered, and added confirmation dialogs to core/su restart

**Comment by bramkragten** [comment]
One last nitpicks, can we change the wording on the buttons?

`Core Restart` -> `Restart Core`
`Host Reboot` -> `Reboot Host`

etc

**Pull request merged**
