### PR TITLE
Migrate to Marked.js + js-xss for Markdown parsing

### PR DESCRIPTION
**Pull request by korylprince**
As discussed on the Discord #devs_frontend, this replaces [pagedown](https://github.com/StackExchange/pagedown) with [Marked](https://github.com/markedjs/marked) and [js-xss](https://github.com/leizongmin/js-xss) (both MIT-licensed).

The main reason for doing so is to support [Github Flavored Markdown](https://github.github.com/gfm/) which includes useful extensions to Markdown like tables and task lists.

Since most Hassio add-ons are hosted on GitHub, this will result in a better user experience for developers and users alike (i.e. the README will look the same in both places.)

Marked's built in sanitizer strips all HTML tags (normally tags can be used in Markdown), so instead of using it, js-xss is used on Marked's output. I've tested every HTML and Markdown XSS vector I could find on the Internet and could not find a successful case through this combination.

`markdown-js.html` was minified with `uglifyjs --compress --mangle` to cut down on size.

This was tested using the `persistent_notification.create` service.

### CODE REVIEW

**Comment by homeassistant** [comment]
Hi @korylprince, 

It seems you haven't yet signed a CLA. Please do so [here](https://home-assistant.io/developers/cla_sign_start/?pr=home-assistant&#x2F;home-assistant-polymer#1026).

Once you do that we will be able to review and accept this pull request.

Thanks!

**Comment by balloob** [comment]
xss is really really big. All of a sudden we're jumping from 10K to 35K! There must be a better way. Can marked be configured? Can tables be added to pagedown? Can we strip the sanitization code from marked if we're not using it?

**Comment by korylprince** [comment]
Yes, the size is quite a bit more (relatively), but when gzipped, the comparison is 4KB to 10.9KB which isn't quite as extreme. We're also talking about a static file that will be cached by the browser. I get where you're coming from, not wanting to take on extra bloat, but we're talking about a 7KB increase on a 2.7MB uncached first page load (in Chrome on a brand new instance.) That's a 0.25% size increase.

I did do due diligence in searching for a solution. Here's what I've tried/researched:

#### Use just Marked

We can use the sanitze feature of Marked, but it removes all HTML, which many people may use in their Markdown. I see this as trading new features for old ones which isn't a great option.

#### Strip unused code (from xss-js or Marked)

I've tried compiling these two smaller from source using Webpack, uglify, and closure compiler, but couldn't make any sort of dent. The sanitize code in Marked is pretty small, and tightly coupled with the library.

#### Use another (smaller) Markdown library

I can't find another library that has the desired features and is smaller than Marked (adding an XSS library if required.)

#### Use another (smaller) XSS library

I really can't find another well supported XSS library at all. Yahoo has xss-filters, but that's mainly for use in templating and doesn't support just passing a chunk of HTML.

#### Add tables to Pagedown

Pagedown itself [doesn't seem interested in adding tables](https://github.com/StackExchange/pagedown/issues/22). There is an unmaintained(?) [extension for Pagedown](https://github.com/jmcmanus/pagedown-extra) to add tables and a few other features. This comes in at 22KB (7.4KB gzipped)

This is an option if you really want to save 3.5KB gzipped. However I think the features and userbase of xss-js and marked plus my points at the start of this post outweigh this option by far.

**Comment by balloob** [comment]
> 2.7MB uncached first page load

Where does this number come from? The critical assets on first page load are `frontend.html` (185KB) and `core.js` (2.9KB). Even if you add icons (210KB), language (2KB) and fonts (max 240KB), you don't get even close to 2.7MB

I guess the increase is acceptable as all alternatives are worse.

**Comment by balloob** [comment]
I've updated the JS with minified source from NPM to make sure that it has not been altered.

**Comment by korylprince** [comment]
Sorry, this was me not knowing exactly how home assistant serves assets. The 2.7MB comes from running with `development_frontend`. Running hass normally results in 666KB on first page load.

This just comes from Chrome's network tab and doing "Empty Cache and Hard Reload."

I've written a build script in PR #1038 to automate the building of `markdown-js.html`. Sorry I didn't submit it in this PR; I just now wrote it :blush:

**Pull request merged**
