### PR TITLE
WIP: Lovelace: Glance Card - Show more info dialog on long click/press

### PR DESCRIPTION
**Pull request by timmo001**
## Description

Makes the more info dialog show when a glance

Currently, users can use either a more info when clicked, a toggle, or call-service. The problem is, the more info dialog is required for lights, history etc. meaning that two clicks are required to toggle a light if the user needs to set brightness etc.

This removes that need and allows the click action to still work, but if the card is pressed for more than a second, the more info dialog will show instead of triggering the action.

## Checklist

- [ ] Change is tested and works on my device(s)

### CODE REVIEW

**Comment by timmo001** [comment]
Great! This was a feature I and a few others were really looking forward to.

I've looked at your code, and it seems you know what you are doing more than I do :smile: 

Before reading your comment, I did get it to work (however not as elegantly as your mixin)

If you want to go your own way or extend upon this PR, go ahead! :+1: If I get the chance tomorrow I might try switching this to the mixin.

But since it's 12:30 my time I'm going to bed. :zzz:

**Comment by zsarnett** [comment]
If this going to be accepted it will need to be using the mixin, if possible, to keeps things consistent and not reinvent the wheel.

**Comment by balloob** [comment]
We need to make it a lit-html directive, not a mixin. That way we can attach it to any DOM.

**Comment by balloob** [comment]
Going to close in favor of #1848

**Pull request closed without merging**
