### PR TITLE
fix action default

### PR DESCRIPTION
**Pull request by zsarnett**
## Type of change

- [ ] Dependency upgrade
- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes #
- This PR is related to issue:
- Link to documentation pull request:

## Checklist

- [ ] The code change is tested and works locally.
- [ ] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

**Comment by zsarnett** [comment]
wait this doesnt work

**Comment by zsarnett** [comment]
For some reason, its not rendering the changes in `this._action`

I confirmed the action was changed but if you update the listbox the new value doesn't show unless I click code editor and then back

**Comment by zsarnett** [comment]
Looks like we need to update the button card editor and other editors as well to handle a default of no config for the action

**Comment by bramkragten** [comment]
<https://github.com/home-assistant/frontend/compare/action-editor-default> ?

**Pull request closed without merging**
