### PR TITLE
Move light brightness below icon

### LINKED ISSUE #3606: Move brightness percentage on Light card
**Description of problem:**
The brightness percentage can sometimes be hard to read, because it is displaying on top of the light icon. I think this pic demonstrates the legibility problem:

brightness

Being up there is also a problem for mobile, because your finger will be covering that area most of the time during interaction. Especially when you get between 25% to 75% brightness range. 

There appears to be an empty "safe area" where the brightness percentage can be placed (see my red box/text) just above the friendly name.

### PR DESCRIPTION
**Pull request by iantrich**
Closes https://github.com/home-assistant/home-assistant-polymer/issues/3606

### CODE REVIEW

**Comment by SeanPM5** [comment]
Damn you are fast, went back to edit the issue a few mins after posting and noticed it was fixed already 😆

**Comment by iantrich** [comment]
Well I nodded my head while reading it and seemed super easy, so :man_shrugging:  :rofl:

**Comment by balloob** [comment]
Let's make the text black instead of white with black border

**Comment by iantrich** [comment]
@balloob black text with black border?

**Comment by balloob** [comment]
no, we can drop the black border too

**Pull request merged**
