### PR TITLE
Add schema validating Lovelace config

### PR DESCRIPTION
**Pull request by andrey-git**
Currently the Lovelace config is not validated.
If we want Lovelace to be frontend-only we can't use backend `voluptuous` schemas, so this PR adds frontend JSON schema.

This PR only adds a basic schema.

This PR increased Lovelace panel JS by 4k (2k compressed)

Also in this PR:
 - Add a test that will validate that the schema itself is valid

TODO in future PRs:
 - Extend the schema to everything in home-assistant/ui-schema/schema.md
 - Add JSON example(s) of Lovelace config and add tests that will validate them.
 - Auto-generate `schema.md` based on the schema.

### CODE REVIEW

**Comment by andrey-git** [comment]
Added a test that the schema is valid.

**Comment by balloob** [comment]
So one thing we have been doing is that each card is doing their own config validation. Config is validated during `setConfig` and then an exception is raised if it's invalid. That also makes it possible for us to show invalid config cards like this:

image

This also makes it possible for us to support custom cards with config validation.

So I don't think that we need a single config validation function. I prefer what we have now, each layer does their own config validation.

**Comment by andrey-git** [comment]
The reason I started this is I made a config without views, and then with views as empty array and in both cases it failed with a JS error in dev console.

It is easy to forget to validate some corner case when validation is written manually.

Maybe somewhat different approach then: Each element, including custom ones that are called from non-custom elements will have a schema attribute that will autovalidate?

**Comment by andrey-git** [comment]
Advantage to a central schema is that it will allow to generate documentation that will always be up to date. Custom elements can still have their own schema.

**Comment by balloob** [comment]
I want to prevent with Lovelace is that a single misconfigured card prevents the whole system from starting up. I agree that we can do better with the initial config. 

My vision is that in the future we will allow card config to be edited one card at a time. Via the UI. A card can specify a `static get config_tag() { }` to specify a custom element for configuration, or we will show a YAML editor for just that block. (we'll need to switch to [`ruamel.yaml`](https://yaml.readthedocs.io/en/latest/overview.html)). A bit [like this](https://home-assistant-lovelace-gallery.netlify.com/#demo-hui-entities-card) with the "Show config" toggle checked.

If we want to add something like `static get validation_schema() { }` to our API for cards, it will only be possible to define normal objects as validators. We don't want to expose a package to the window object as part of the API as that is instant tech debt. We will have to load it forever and before loading _any_ resources.

I think that the config at https://www.home-assistant.io/lovelace is pretty extensive and manually curated config, although harder to maintain, is easier to make human readable with examples etc.

**Comment by andrey-git** [comment]
OK, so one centralized schema is out.

I still think it is valuable to have per-card Schemas.

If we export Ajv itself we can provide validation support to custom cards too.
If you don't want to add that API we can use ajv-pack (like the current state of this PR) to create a validating module per built-in-card schema.

What this will also allow in the future is card config editor based on the schema. Like this one (didn't look into details through): https://github.com/json-editor/json-editor

**Comment by balloob** [comment]
I've tried automatic form generation in other projects, and it never works great. It works great… until it doesn't. This usually happens when you need to load things on demand or need more advanced controls (like an entity picker filtered by domain).

That's why I mentioned `static get config_tag() { }` above. A card will either be able to specify another custom element that can edit the config for that card, or the default is a textarea with just that card config.

**Pull request closed without merging**
