### PR TITLE
disabled state for buttons was reversed

### PR DESCRIPTION
**Pull request by Bart274**
This solves issue https://github.com/home-assistant/home-assistant/issues/1941

### CODE REVIEW

**Comment by balloob** [comment]
A position of 0 is fully closed. That means that when a rollershutter is fully closed (position = 0) we should disable the up arrow. The current behavior is thus correct.

**Comment by n8henrie** [comment]
I was about to submit an identical pull request after spending a few couple days of free time trying to debug this unexpected behavior, glad to see I'm not the only one that found it confusing.

@balloob -- I see [your more detailed explanation](https://github.com/home-assistant/home-assistant/issues/1941#issuecomment-215403077) but respectfully disagree -- to me, not only does calling a rolled up rollershutter "closed" seem backwards and contrary to common language for garage doors / blinds, but additionally a state of `0` would seem to represent a rollershutter at its *lowest* point, and `100` the highest, no? I suppose some people could have rollershutters that go the other direction, but this [seems pretty standard](https://duckduckgo.com/?q=rollershutter&iax=1&ia=images).

That said, if you feel firmly about this or it isn't open for discussion, I'll be happy to at least see if I can clarify in the documentation to save others a little time and confusion in the future.

**Comment by balloob** [comment]
I don't feel strong at all, open for change. Was thinking of merging
rollershutter and garage door into a new component called cover which will
do it all right. Not sure when I have time for this so PRs welcome

**Comment by n8henrie** [comment]
Good to hear. It's disconcerting when I'm away from home and check my garage door status and see that it's been "100 / fully open" all day -- and have to remind myself that means it's actually closed and all is well:

screen shot 2016-04-30 at 10 41 25 am

I think a combined component makes the most sense. I'd think that just combining them under the generic term "rollershutter" would be okay (rather than having to make an all new component) except that it's such a long word, leading to some [disagreements and inconsistencies on spelling](https://github.com/home-assistant/home-assistant/commit/91731c72344c5c2b7cc785109199b27eb8addc88). "Cover" isn't terribly descriptive, but it is short and easy to spell, and the docs could just explain what kind of devices it's best suited to.

I've not a very experienced Pythonista (or programmer for that matter), but I've been itching for a bigger Python 3 project I could start contributing to. I'll make an issue over at the main hass repo and start working on it.

**Comment by rrubin0** [comment]
Is it not possible to allow users to modify the icons? It seems that would be the easy fix; include the states of the rollers/garage as a ```flip_state: true``` customize option. Not sure how difficult that would be but it certainly solves both issues, IMO

**Pull request closed without merging**
