### PR TITLE
Update battery_color.ts

### PR DESCRIPTION
**Pull request by ildar170975**
## Proposed change
Updated thresholds to more standard:
70 -> 67
30 -> 34

## Type of change
- [ ] Dependency upgrade
- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [x ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes #
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [ ] The code change is tested and works locally.
- [ ] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

**Comment by piitaya** [comment]
The threshold values are multiple of ten because icons already use multiple of ten.

https://github.com/home-assistant/frontend/blob/dev/src/common/entity/battery_icon.ts#L30-L41
```ts
const BATTERY_ICONS = {
  10: mdiBattery10,
  20: mdiBattery20,
  30: mdiBattery30,
  40: mdiBattery40,
  50: mdiBattery50,
  60: mdiBattery60,
  70: mdiBattery70,
  80: mdiBattery80,
  90: mdiBattery90,
  100: mdiBattery,
};
```

**Comment by ildar170975** [comment]
The proposed changes are for COLOR. 
What you are talking is about an ICON.

**Comment by piitaya** [comment]
I explain you why we use multiple of ten for color : because we use multiple of ten for icons too.

**Comment by ildar170975** [comment]
Using “multiple of ten” cannot prevent using a different way for colors. There are 10 possible icons - then use multiple of ten. There are 3 possible colors - use corresponding values then, what is a problem?

**Comment by piitaya** [comment]
We chose to align color thresholds on multiple of ten. I explained why we did that choice. We will keep theses values for now because we can not change the rules every time somebody suggest a new rules. If we have many bad feedbacks about these, we can reconsider it in the future.

**Pull request closed without merging**
