### PR TITLE
Polyfill ElementInternals for material-web components. Fix #18600

### LINKED ISSUE #18600: A slider lacks the slider part on iOS
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

I've been using this slider for a while on the web frontend for a while. It worked just fine on iOS. I noticed recently that the slider isn't a slider anymore on iOS. It's just a widget which displays a fixed value.

I thought that I've made some mistake or that this was cause by the grid card. That wasn't the case. The slider works properly on the web frontend and on Android, both from the grid card and as a card added directly to the dashboard.

This issue can be reproduced with two entities exposed by a xiaomi air purifier, the favorite level and its speaker volume level. I haven't tried to reproduce this with other entities. These were the only sliders in my setup.

image
image

### Describe the behavior you expected

I expected the slider to be usable as a slider. It is a slider on the web frontend. It's a slider on Android. It's not a slider on iOS.

### Steps to reproduce the issue

1. Install the latest Home Assistant & the latest app on iOS
2. Find a number entity which has a slider
3. Add that entity to a dashboard
4. Open the dashboard on the web frontend
5. Open the dashboard on iOS
6. Check if the slider is shown on iOS and on the web frontend, iOS will probably not show the slider properly
...

### What version of Home Assistant Core has the issue?

2023.11.1

### What was the last working version of Home Assistant Core?

_No response_

### In which browser are you experiencing the issue with?

Home Assistant Companion 2023.7 for iOS

### Which operating system are you using to run this browser?

_No response_

### State of relevant entities

_No response_

### Problem-relevant frontend configuration

_No response_

### Javascript errors shown in your browser console/inspector

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by thomasloven**
## Proposed change

Add elementInternals polyfil to improve compatibility with older safari versions (particularly mobile).

~~I put this on ha-slider because that's where I have found the problem, but it may be necessary at other places too since many material-web components seem to rely on `attachInternals`.
I tried `/src/resources/compatibility.ts`, but that caused issues with scoped-custom-elements-registry for some reason.~~

## Type of change

- [ ] Dependency upgrade
- [X] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes #
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [X] The code change is tested and works locally.
- [X] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

**Comment by steverep** [comment]
> I tried /src/resources/compatibility.ts, but that caused issues with scoped-custom-elements-registry for some reason.

That wouldn't be the correct spot anyway since it would only go into the legacy build, and the modern build still needs it.  For now, I think including it wherever `@material/web` is imported is best, and it needs to be before it in import order.  I'm working on a smarter way to handle these types of polyfills using a custom Babel plugin.

What were the errors with scoped registry?

Unrelated, but you mentioned many other errors on your old iPad.  Can you open some issues for them?  I've been trying to better define and improve browser support, so that would certainly help.  Feel free to ping me.

**Comment by thomasloven** [comment]
The many other errors were actually on the Material Web demo page, which is utterly broken on old safari. https://material-web.dev/components/slider/

**Comment by ildar170975** [comment]
@steverep 
Steve, on that
https://github.com/home-assistant/frontend/issues/18600#issuecomment-1807148540
comment I posted a screenshot from a page
https://material-web.dev/components/slider/
which was open on Safari in iOS 15.x.
On this screenshot sliders are not displayed.

**Comment by steverep** [comment]
Ah, okay.  Errors on old browsers would be expected there since they only support the latest 2 versions of browsers.  You'd think it'd be in their best interest to at least add polyfills to the demo page though. 🤷🏻‍♂️

**Review by bramkragten — APPROVED** [review]

**Comment by thomasloven** [comment]
Damn! It's been nearly one and a half years!

**Pull request merged**
