### PR TITLE
Remove tap highlight on mobile Safari

### PR DESCRIPTION
**Pull request by NovapaX**
This removes the tap highlight (transparent grey) over the complete interface or big sections thereof.

The tap highlight behaviour doesn't work nice with the app-experience and full screen touch-listening overlays (like paper-drawer). The items where a tap-highlight would work (clickable state cards for example) don't get the highlight anyway (for some reason).

UX improvement for another PR: `:active` highlights on actually clickable/tappable elements (e.g. state-card)

### CODE REVIEW

**Comment by NovapaX** [comment]
Changed the event listener on state-card to 'click' as indicated in Polymer documentation: https://www.polymer-project.org/2.0/docs/devguide/gesture-events

This has the added benefit of enabling the tap-highlight for these state-cards. This provides some interaction-feedback upon tapping a state-card.

**Comment by balloob** [comment]
I wonder if this issue still persists if we migrate from `paper-drawer-panel` to `app-layout`. `paper-drawer-panel` has been deprecated in favor of `app-layout` for a while now.

**Comment by NovapaX** [comment]
I guess the issue will still be there... it's related to an element having a touch listener on it. And the drag-gesture on the layout to open the drawer will remain right?

But this little fix at least should make it look a lot less quirky for now. (on iOS)
I there already an issue to move to app-layout? 
(So I can keep track of this and test if it is still needed then.)

**Comment by balloob** [comment]
Can you test on this demo of app-layout? http://polymerelements.github.io/app-layout/templates/shrine/#feature

Added issue: #925

**Comment by balloob** [comment]
#929 fixes #925 and introduced app-layout. Let's get that one merged and then let's see if this fix is still needed

**Comment by balloob** [comment]
Can you see if this PR is still necessary now that we're using app-layout?

**Comment by NovapaX** [comment]
Just tested it, and the tap highlights on the full-screen touch-targets are still here.
So yes, this is still needed imo.

**Comment by balloob** [comment]
Ok, can you add a comment to the CSS and then I'm 👍 to merge it.

**Pull request merged**
