### PR TITLE
Don't check zwave_js node firmware update capabilities

### LINKED ISSUE #13052: Configure Device not available on many Z-Wave devices
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

even when there are (many) configurable params available for the device.

This is all the more blocking core functionality since  the menu items in the Overflow menu of that Configure Device aren't available either..

I noticed this when looking for the device link in the Z-Wave JS device DB, which because of this issue isnt available either.

example of a device not showing:

Schermafbeelding 2022-06-30 om 20 21 26

and check the options for that device in the DB:

https://devices.zwave-js.io/?jumpTo=0x010f:0x0602:0x1003:3.2

### Describe the behavior you expected

- Always show the overflow options of the Configure Device
  we should always be able to Re-interview the device, and use the overflow menu items, even if no configurable params are     available. That's, the overflow menu should always be available too

- Move the device device database link so it is always available, even if there are no configurable params on the device, and  because of that, no Configure device is displayed.

### Steps to reproduce the issue

1. select a device in the device list
2.
3.
...

### What version of Home Assistant Core has the issue?

2022.8.0.dev20220630

### What was the last working version of Home Assistant Core?

_No response_

### In which browser are you experiencing the issue with?

any

### Which operating system are you using to run this browser?

macOS 12.4

### State of relevant entities

_No response_

### Problem-relevant frontend configuration

_No response_

### Javascript errors shown in your browser console/inspector

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by raman325**
## Proposed change
It was previously assumed that we could check the firmware update capabilities of a node always and so we used that information to generate the appropriate device actions list as well as to improve the user experience of picking a target chip for the upgrade. In the beta we learned that is not the case - sleeping nodes will not respond with this information which means the device actions won't load until the device is woken up.

There's probably a way to fix this in a way that doesn't remove this feature entirely, but after talking to @AlCalzone it appears we may introduce a way in the future to check the firmware update capabilities without having to communicate with the node which would allow us to reintroduce this feature in a much simpler way.

CC - @AlCalzone @kpine @Mariusthvdb @balloob @MartinHjelmare 

## Type of change

- [ ] Dependency upgrade
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes https://github.com/home-assistant/frontend/issues/13052
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [ ] The code change is tested and works locally.
- [ ] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

**Comment by kpine** [comment]
Can't comment on the code, but this fixes the issue for me; the button and overflow menu are back. But, there are a few issues with the upload dialog box I thought I'd mention.

image

1. There's no checkbox to uncheck
2. Is `firmware_target` supposed to be localized as [`Firmware Target (chip)`](https://github.com/home-assistant/frontend/blob/07332bf155997fae782a45ffc5ef8e95d6872295/src/translations/en.json#L3333)?
3. Is the `valueMin` change working as intended? I can still set a negative target, I would expect it to stop at 0. I didn't go further than this dialog, so I'm not sure if it's validated later. You could also set the max value to 255, that's the maximum target value that is possible (8-bit value).

**Comment by kpine** [comment]
I have to retract part of my previous comment. If you refresh the Device page (e.g. F5 in Firefox), most of the time the buttons and overflow menu labels are invisible. Rarely they will render correctly.

**Review by balloob — APPROVED** [review]

**Comment by Mariusthvdb** [comment]
just as a fyi because it might have been gone unnoticed: 
this is also happening on non sleeping devices:

Schermafbeelding 2022-07-04 om 00 02 46

so if you focussed on that, is want the sole reason for the issue.

**Comment by AlCalzone** [comment]
I'm a bit late to the party, but is there any way to ask the user to wake up a sleeping device, then query the info and then show the dialog?

The main idea of querying them before the update is to know what to ask the user and to not ask them unnecessary stuff. E.g. don't show the target if there is only 1.
And querying that info instead of relying on the cache was to make sure we're not operating on stale information.

Its probably less critical here, since ultimately the user needs to provide that info and they should know it from the manufacturer. But the WIP semi-automatic update process will need to communicate with a device before even checking for available updates.

**Comment by AlCalzone** [comment]
https://github.com/zwave-js/node-zwave-js/pull/4779 will cache the capabilities during the interview and add a method to retrieve the information from cache

**Pull request merged**
