### PR TITLE
Add source selection to media control card

### PR DESCRIPTION
**Pull request by kleest**
## Proposed change

This adds the option to select a source to the media control card without the need to open the more-info menu. 

## Type of change

- [ ] Dependency upgrade
- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

None

## Additional information

This also adds a previously missing radio list item component similar to check list item component.

## Checklist

- [x] The code change is tested and works locally.
- [x] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

**Comment by matthiasdebaat** [comment]
Can you add a screenshot?

**Comment by kleest** [comment]
Correct. That's not how I intended it would look like. I did not consider the small cards since I developed it for the panel-type dashboard that only displays one card:
image

Furthermore, the source selection button is misplaced if there is no browse media button.

Two questions:
1. How should the "small" and "big" cards be handled? I guess it makes sense to display the source selection button only for bigger cards otherwise there is not enough space for the source selection (some kind of media query?).
2. Currently, the browse media button is placed with `position: absolute` and a `right:` offset. For the source selection button I did the same. I need to change this since browse media is optional. While it is entirely clear to me how to this for the general CSS case, I would like to know how to do this properly in HA frontend with the existing code style and building blocks.

**Comment by frenck** [comment]
> That's not how I intended it would look like. I did not consider the small cards since I developed it for the panel-type dashboard that only displays one card:

That is not how we can approach this. The recorder I've shown above is the default dashboard Home Assistant will generate. Meaning this approach now is unusable by default 😉

**Comment by bramkragten** [comment]
> How should the "small" and "big" cards be handled? I guess it makes sense to display the source selection button only for bigger cards otherwise there is not enough space for the source selection (some kind of media query?).

I think we should discuss if we want this functionality in the media control card first, and if so, how (button, in the overflow, etc) UX @matthiasdebaat should be able to help with that probably.

> Currently, the browse media button is placed with position: absolute and a right: offset. For the source selection button I did the same. I need to change this since browse media is optional. While it is entirely clear to me how to this for the general CSS case, I would like to know how to do this properly in HA frontend with the existing code style and building blocks.

Wrap them in a div, and position that div the way the browse media button is now

**Comment by kleest** [comment]
Fixed placing of the buttons. Both buttons are now correctly placed even if the "select source" or "browse media" features are not supported.

**Comment by matthiasdebaat** [comment]
> I think we should discuss if we want this functionality in the media control card first, and if so, how (button, in the overflow, etc) UX @matthiasdebaat should be able to help with that probably.

I understand that you want more media control when using this card in full screen. However, this card is not designed for full screen, but for the format Frenck has shown above. The more-info dialog is for more control. In this case, we shouldn't move the controls out of this dialog to the card. For example, we also have `Sound mode`.

If you want a media control dashboard, I recommend creating one with ours, for example with our [strategies](https://developers.home-assistant.io/docs/frontend/custom-ui/custom-strategy/).

**Pull request closed without merging**
