### PR TITLE
Change service_data to just data

### PR DESCRIPTION
**Pull request by thomasloven**
## Proposed change

In the spirit of streamlining and designing away the most common user errors.

Does anyone even remember why it's `service_data` in the frontend, if there ever was a reason?

> Edit: For future reference; It's probably because `tap_action` used to just be a string `"call-service"` and then `service` and `service_data` were parameters on the element itself rather than everything being neatly tucked into a `tap_action` object as it is now. In that case `data` would be a terribly broad keyword to reserve.

Should be backwards compatible.

Todo:
- [ ] ~~Architecture discussion??~~
- [X] Actually run this and see if it works
- [X] Documentation
- [X] Update gallery
- [X] Automatically convert/merge `service_data` into `data` in GUI editors.

## Type of change

- [ ] Dependency upgrade
- [ ] Bugfix (non-breaking change which fixes an issue)
- [X] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [X] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes #
- This PR is related to issue or discussion:
- Link to documentation pull request: home-assistant/home-assistant.io#22840

## Checklist

- [ ] The code change is tested and works locally.
- [ ] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

**Comment by bramkragten** [comment]
Yes, yes, yes!

**Review by spacegaier — COMMENTED** [review]
To prevent confusion 😄. There are a few more places where such a comment might make sense.

**Comment by spacegaier** [comment]
Is that something where similarly to the way we handle core integrations we want to deprecate that in half a year or so and force users to switch to `data` so we do not have to carry the coding "mixture" forever?

**Comment by frenck** [comment]
> Is that something where similarly to the way we handle core integrations we want to deprecate that in half a year or so and

In core we had `data` and `data_template`; we still carry them around and have been removed over 2 years ago. Up until this day, I still see new examples, issues, forum, and Discord messages using the old `data_template`.

I guess this is similar; which probably should stick for a long long time.

**Comment by thomasloven** [comment]
I'm thinking maybe `service_data` should be kept for the [service call button element](https://www.home-assistant.io/dashboards/picture-elements/#service-call-button) since that doesn't have a `tap_action`.
At least until it is deprecated in favor of a more generic `button` element.

Thoughts?

**Comment by zsarnett** [comment]
Agreed. Can leave for now and then deprecate

**Review by bramkragten — APPROVED** [review]

**Pull request merged**
