### PR TITLE
Optimized for theming

### PR DESCRIPTION
**Pull request by bramkragten**
Reduced the variables so themes are easier to make. A few color are adjusted minimally...

### CODE REVIEW

**Comment by balloob** [comment]
Can you clean up your branch, there are a lot of commits that are not yours in there.

**Comment by bramkragten** [comment]
OK now hero with git... didn't manage but restarted: https://github.com/home-assistant/home-assistant-polymer/pull/380

**Comment by balloob** [comment]
https://xkcd.com/1597/ 😉

**Comment by bramkragten** [comment]
Exactly that.

**Pull request closed without merging**
