### PR TITLE
Fix scrolling region

### PR DESCRIPTION
**Pull request by timmo001**
Moves the scrollbar so it is no longer hidden by the header

### CODE REVIEW

**Review by c727 — DISMISSED** [review]
Can't see any drawbacks moving this

**Comment by c727** [comment]
hmz I think we should just remove it. iron-pages doesnt has this property all in all

**Comment by balloob** [comment]
You can't just move some attribute around, it shows that you haven't read the docs of the elements.

Here are the docs for the app-header-layout, which is what ha-app-layout extends from:
https://www.webcomponents.org/element/PolymerElements/app-layout/elements/app-header-layout#property-hasScrollingRegion

We have a setup with a collapsing header, which only works if we have a scrolling region.

**Comment by c727** [comment]
It also works without the property and shows the correct scrollbar

**Comment by balloob** [comment]
Interesting, maybe it was left from when we had our own collapsible header logic.

**Comment by balloob** [comment]
This branch got conflicts so I just committed it directly to master.

**Comment by balloob** [comment]
Ugh, and so this broke the height of `ha-app-layout`, so that it has a white block below the cards. Fixed it in 7f93317314a5e51bcf38f2a1e4ee2dd8dc0332ba but it will be broken for the whole 0.71 release 😭 

image

**Pull request closed without merging**
