### PR TITLE
Upgrade MDI icons to 4.5.95

### PR DESCRIPTION
**Pull request by bonanitech**
Changelog: https://dev.materialdesignicons.com/changelog#version-4.5.95

Screenshot 2019-10-09 19 41 50

### CODE REVIEW

**Review by iantrich — APPROVED** [review]

**Comment by bramkragten** [comment]
@iantrich no need for a 0.101 milestone yet, everything will make it before the beta cut 😄

**Comment by iantrich** [comment]
We already cut beta? I thought standard practice was to only include bug fixes after the first beta cut so we don't get bit by a breaking feature change

**Comment by bramkragten** [comment]
yeah we do, but all new stuff will go to 0.101 when the next beta is cut. Only after a beta cut you need to put a milestone on them so they can be cherry picked.

**Comment by iantrich** [comment]
👍

**Pull request merged**
