### PR TITLE
Add support for safe area insets

### LINKED ISSUE #6148: iOS app tweaks needed for FABs and tab bars
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

The iOS app had a change in this PR https://github.com/home-assistant/iOS/pull/606 where it removed a safeAreaInsets setting. That was a good change since there were a number of issues before (the iOS "gesture bar" overlapping the tab bar for example, and the notch covering the content in certain cases). This change is present in the iOS 2020.1 app, which is not yet live in the store but will be very soon.

This requires a few adjustments on the frontend side, mainly for the FABs. They need to be placed a little higher on iOS. Provided some screenshots below to demonstrate how it looks.

The other thing I notice is that underneath the tab bars it appears to be showing the primary-background-color variable (`#fafafa` on the default theme) rather than extending the tab bar background color all the way down. Dunno if I explained that well enough, but here's an image of the Phone app on iOS for how it's supposed to look: 

image

You can see that it's all one color from top to bottom, this is the desired behavior. When you look at the HA screenshots below you'll see it's two colors (white for the tab bars, gray for the gesture bar).

And here's some screenshots of how the FABs look:

**Automations / Scenes / Scripts / Helpers tab bar**:

image

**Lovelace Dashboards tab bar**: 

image

**Persons / Zones / Users tab bar**: 

image

Those are all the same placement, but the Integrations seems to have different behavior. Unlike all of the others, this one seems to be partially cut off and displays _underneath_ the tab bar.

image

There might be some more stuff but haven't played with this build long enough and going to bed now, just wanted to report this quickly.

One last thing to note, is that it probably displays different on an older iPhone (with home button). The tab bars are probably docked to the very bottom of the screen instead of being pushed up slightly? So if you make the FAB higher, it might be TOO high on those phones, I don't know. Don't have one of those older phones to test on, only have the iPhone 11 Pro. 

## Expected behavior

* Make the FABs display a little higher on iOS
* Make the tab bars look like the Phone app screenshot I posted above, it's supposed to be one color and not two.

## Environment

- Home Assistant release with the issue: 0.111.1
- Last working Home Assistant release (if known): n/a
- Browser and browser version: iOS App 2020.1
- Operating system: iOS 13.5.1

## State of relevant entities

```yaml

```

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

### PR DESCRIPTION
**Pull request by bramkragten**
## Proposed change

Mainly checked on iPhone now, might need some further tweaks.

Closes https://github.com/home-assistant/frontend/issues/6148

## Type of change

- [ ] Dependency upgrade
- [ ] Bugfix (non-breaking change which fixes an issue)
- [X] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [X] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes #
- This PR is related to issue:
- Link to documentation pull request:

## Checklist

- [ ] The code change is tested and works locally.
- [ ] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

**Comment by zacwest** [comment]
This is a _huge_ improvement, thank you so much!

Here are a few things I've noticed playing with it, grouped by theme. Overall feels really good though.

- [ ] [Confirmation on integration settings](https://user-images.githubusercontent.com/74188/88615821-80c6f780-d047-11ea-9d76-d157041fbdf6.png): the 'update' button is underneath the safe area, but also clipped off the screen. This also happens for the editing of e.g. device or entity settings.
- [ ] [Card configuration](https://user-images.githubusercontent.com/74188/88616938-46128e80-d04a-11ea-89e6-4daacece642f.png) is similar, the action buttons are underneath the home indicator. This is also the case when adding a new card, editing a scene.
- [ ] [Delete confirmation](https://user-images.githubusercontent.com/74188/88617013-79edb400-d04a-11ea-9758-0cc6d7bcad7e.png) and editing e.g. the name of an integration like Shopping List, logout confirmation.
- [ ] [TOTP Setup]:(https://user-images.githubusercontent.com/74188/88617090-9db0fa00-d04a-11ea-84dc-b2ff6e6b63fa.png): not sure if there is one, but it also seems like the cancel button may be hidden somewhere, too.
- [ ] [Page bottoms in Dashboards, Profile](https://user-images.githubusercontent.com/74188/88617149-bf11e600-d04a-11ea-9f0c-e1c950b066ee.png): feels like the bottom of the container could use some padding, since the 'create token' button is outside the safe area, and the dashboard contents are also bleeding out of the safe area.
- [ ] [Profile button in hamburger menu](https://user-images.githubusercontent.com/74188/88617279-0e581680-d04b-11ea-81d1-61f15ac20ce3.png): could this be bumped up at all? It's 'dangerously'-feeling close to the bottom of the menu.

**Comment by bramkragten** [comment]
Think I addressed it all, did you just check portrait or also landscape?

**Comment by zacwest** [comment]
I did--couldn't find anything landscape-exclusive, it feels a lot better now that the bars are extending to the full-bleed edges. Ran the latest, a couple more things, but largely perfect!

- [ ] [Renaming my device](https://user-images.githubusercontent.com/74188/88694988-29ac3b80-d0b6-11ea-896b-c27d87309275.png) has the offset 'update' button, similar to the integration edit.
- [ ] [Dashboard bottoms](https://user-images.githubusercontent.com/74188/88695060-39c41b00-d0b6-11ea-89a8-30fe829705e1.png) could use a bit of padding like the profile.

**Comment by bramkragten** [comment]
Done!

**Review by balloob — APPROVED** [review]

**Review by balloob — APPROVED** [review]

**Pull request merged**
