### PR TITLE
Make input_boolean icon state dependent

### PR DESCRIPTION
**Pull request by Mariusthvdb**
## Type of change

- [ ] Dependency upgrade
- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes #
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [ ] The code change is tested and works locally.
- [ ] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

**Comment by thomasloven** [comment]
I don't think the difference is obvious enough.

Nothing about `toggle-switch-outline` or `toggle-switch-off-outline` stands out as either ON or OFF to me. They're just mirrored.

Maybe consider using `toggle-switch` for `on` and `toggle-switch-off-outline` for `off`?

**Comment by Mariusthvdb** [comment]
thx. 
was explicitly _Not_ trying to use the same icons as used for switch, which uses the non-outline version... I wanted to respect the difference between switch and boolean doing so.
It is a fine difference, yet, if you get used to is, the toggle is quite immediate for its visual feedback?

Schermafbeelding 2021-11-05 om 15 15 25

Schermafbeelding 2021-11-05 om 15 15 35

also syncs nicely with the toggle itself.

btw comp with switches using the solid toggle:

Schermafbeelding 2021-11-05 om 15 17 25

what do you think?

**Comment by Mariusthvdb** [comment]
please have another look here? Dont know how else to change this, remaining subtle and in style with the rest of HA Frontend, and yet be distinctive as can be. 

works beautifully for the switch domain now (2021.11.2) and believe this will do just the same for input.boolean

hope you agree

**Comment by bramkragten** [comment]
Make use checkboxes for input boolean?

**Comment by Mariusthvdb** [comment]
thats a great suggestion yes! wouldn't that interfere with the other UX in HA where checkboxes are used?
circle-outline and check-circle-outline maybe ?

```
    case "input_boolean":
       return compareState === "on"
         ? mdiCheckCircleOutline
         : mdiCircleOutline;
```

there are so many....

**Comment by Mariusthvdb** [comment]
couldn't import the `mdi:minus-box-outline` so using `checkbox-blank-outline` now

**Comment by thomasloven** [comment]
The minus box is used by several UI languages to indicate a partial check:

image

**Comment by bramkragten** [comment]
I would go for `checkbox-blank-circle-outline` and `checkbox-marked-circle-outline`, to not confuse with the normal UI

**Comment by Mariusthvdb** [comment]
int this too close too what is used for binaries? I rather liked the square, which are not used yet in HA?

**Comment by bramkragten** [comment]
Oh... yeah... but the squares might look like actual inputs?

**Comment by Mariusthvdb** [comment]
well, they are input_booleans ... ;-)

**Comment by Mariusthvdb** [comment]
toggle:
Schermafbeelding 2021-11-11 om 09 48 14

square checkbox:
Schermafbeelding 2021-11-11 om 09 45 39

circle checkbox:
Schermafbeelding 2021-11-11 om 09 50 58

**Comment by matthiasdebaat** [comment]
An icon should not be confusing and shouldn't be reused for other interaction. A description of a boolean is `true` or `false`. A toggle icon is in itself a good choice, only it is confusing with a switch next to it. Think we could use a better icon. I don't think we should go for the square checbox, that looks the same as the component. 

The check on the circle checkbox makes it look `true`. That's nice. I would like to suggest to use `check-circle-outline` and `close-circle-outline`. When switching between states, the icon doen't move that way.

**Comment by Mariusthvdb** [comment]
Schermafbeelding 2021-11-11 om 16 39 57

thank you Matthias

**Comment by ludeeus** [comment]
Should these even have a default icon?
The action (toggle) is indicator enough of its state?

**Comment by Mariusthvdb** [comment]
you're right. otoh, current default is mdiToggleSwitchOutline. Concept of this PR in he first place was that a fixed icon like that is confusing.

Changing it like Matthias suggests takes away that confusion, and spices the FR up bit, making it more 'telling' at that.

**Review by zsarnett — DISMISSED** [review]

**Review by zsarnett — APPROVED** [review]

**Pull request merged**
