### PR TITLE
Use mwc-button instead of paper-button

### PR DESCRIPTION
**Pull request by balloob**
It's such a more beautiful material button. And Lit/TS 👍 

image

### CODE REVIEW

**Comment by iantrich** [comment]
that's a lot of buttons...

**Comment by balloob** [comment]
Haha yes. `<mwc-button>` is a drop in replacement that does some default styling from the get go.

Since the other styling was all part of `ha-style.ts`, it was easy to go through it.

**Comment by balloob** [comment]
image

image

**Comment by iantrich** [comment]
Partial for https://github.com/home-assistant/home-assistant-polymer/issues/2607

**Comment by iantrich** [comment]
Fixes 
https://github.com/home-assistant/home-assistant-polymer/issues/2407

**Pull request merged**
