### PR TITLE
Inform user that subscription is needed for cloud services

### PR DESCRIPTION
**Pull request by piitaya**
## Proposed change

CleanShot 2023-04-26 at 12 58 58

## Type of change

- [ ] Dependency upgrade
- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes #
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [ ] The code change is tested and works locally.
- [ ] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

**Comment by bramkragten** [comment]
I guess it now happens after you logout and have not restarted, should be fixed ones cloud moves to config entry (hopefully next release)

**Comment by bramkragten** [comment]
Let's also update the init data: <https://github.com/home-assistant/frontend/pull/16318/files#diff-65b8eac676f35d649ae8d8a664623df0c8146ad9b2f9e47b6dc3debd77207756R51-R52>

```ts
stt_engine: this._cloudActive ? "cloud" : undefined;
tts_engine: this._cloudActive ? "cloud" : undefined;
```

**Comment by piitaya** [comment]
If you're logged and the subscription is not active. Should cloud service be enabled?

**Comment by bramkragten** [comment]
> If you're logged and the subscription is not active. Should cloud service be enabled?
No

**Comment by piitaya** [comment]
Ok, then we can remove the alert when cloud will be a config entry.

**Review by bramkragten — APPROVED** [review]

**Pull request merged**
