### PR TITLE
Allow adding card from history panel

### PR DESCRIPTION
**Pull request by balloob**
## Proposed change

Allow adding the current selection on the history panel as a card to a dashboard. Re-uses current suggest card logic used on device info page.

image

Screenshots of how existing logic deals with it:

CleanShot 2024-01-30 at 22 28 32

CleanShot 2024-01-30 at 22 28 49

Error when no data selected

CleanShot 2024-01-30 at 22 50 16

## Type of change

- [ ] Dependency upgrade
- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes #
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [ ] The code change is tested and works locally.
- [ ] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

**Comment by matthiasdebaat** [comment]
Based on our [guidelines](https://design.home-assistant.io/#components/ha-dialogs) some feedback.

> Screenshots of how existing logic deals with it:
> 
> CleanShot 2024-01-30 at 22 28 32

Can you group the `Cancel` and `Next` buttons to the right? 
And move the `X`-icon to the left?

> CleanShot 2024-01-30 at 22 28 49

Is there an option to avoid three buttons in one dialog?
Can you add a `X`-icon to the top left?

> Error when no data selected
> 
> CleanShot 2024-01-30 at 22 50 16

What will happen when you click `OK`? Will you get the option to select data? Or does it abort the flow?

**Comment by bramkragten** [comment]
@matthiasdebaat these are not new dialogs added in this PR, but already existing dialogs (that should be updated)

**Review by piitaya — COMMENTED** [review]
I like the idea but the history panel displays statistics and history while the graph card only displays history. Should we add the same behavior between graph card and history panel?

**Comment by balloob** [comment]
@piitaya yeah, that would be a nice addition. Right now we have the statistics card as alternative, but that doesn't work for all entities.

**Review by silamon — APPROVED** [review]

**Pull request merged**
