### PR TITLE
Separate outline color

### PR DESCRIPTION
**Pull request by KTibow**
## Proposed change

Sometimes a theme wants to hide dividers (I've wanted to do that many times throughout using HA). However, this makes some buttons and expanders look weird. This PR separates outlines from dividers, into their own color `--outline-color` (defaulting to the same color as `--divider-color`, for now).

## Type of change

- [ ] Dependency upgrade
- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

N/A

## Additional information

- This PR fixes or closes issue: N/A
- This PR is related to issue or discussion: N/A
- Link to documentation pull request: N/A

## Checklist

- [x] The code change is tested and works locally.
- [x] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

### CODE REVIEW

**Comment by piitaya** [comment]
I'm ok to split outline and divider into different variables fo easy theming. 

However, it should not change the default theme. All the default color should be the same as before.
With this PR, border color are not consistent anymore across the different page.

CleanShot 2023-10-04 at 10 50 03

CleanShot 2023-10-04 at 10 50 29

**Comment by KTibow** [comment]
Good point, that does look bad. However, while I could make outline color default to the divider color, I think it makes more sense to be a _bit_ more prominent than it is now - this does mean changing the default theme, but I think it's an improvement:
Before:
image
After:
image

**Comment by bramkragten** [comment]
> Good point, that does look bad. However, while I could make outline color default to the divider color, I think it makes more sense to be a _bit_ more prominent than it is now - this does mean changing the default theme, but I think it's an improvement

Not sure I agree that it is an improvement, can you also share a screenshot in light mode?

**Comment by KTibow** [comment]
> can you also share a screenshot in light mode?

Before:
image
After:
image

> And of a dashboard with a lot of cards?

It doesn't affect cards at all, since they already have their own variable.

**Comment by bramkragten** [comment]
> It doesn't affect cards at all, since they already have their own variable.

`ha-card-border-color` is derived from `divider-color`, so should be changed to outline color too, and will change then.

Let's not mix changing the colors (style) with the code changes. Let's do the code changes first, and then you can create a new PR for updating the style if you want.

**Comment by KTibow** [comment]
In cards, the border is more a stylistic thing. There's a background that separates it already. This change is supposed to target places where the outline is the only way to tell the element apart.

**Review by bramkragten — APPROVED** [review]

**Pull request merged**
