### PR TITLE
Fix for missing 'Disarm' button

### PR DESCRIPTION
**Pull request by gwww**
Disarm button does not show when in `arming` and `disarming` state.

### CODE REVIEW

**Comment by homeassistant** [comment]
Hi @gwww, 

It seems you haven't yet signed a CLA. Please do so [here](https://home-assistant.io/developers/cla_sign_start/?pr=home-assistant&#x2F;home-assistant-polymer#1549).

Once you do that we will be able to review and accept this pull request.

Thanks!

**Comment by BioSehnsucht** [comment]
Relates to home-assistant/home-assistant-polymer/issues/1415

**Comment by balloob** [comment]
Why would it need to show in disarming state ? It's already disarming so one cannot disarm again?

**Comment by BioSehnsucht** [comment]
What state should be used for entry timers running (alarm will go to triggered state if not disarmed before entry timer expires) ? It's armed and going to alarm (maybe), but the siren isn't sounding so yet setting `STATE_ALARM_TRIGGERED` doesn't seem right. Should it be `STATE_ALARM_ARMING` for exit timer and `STATE_ALARM_PENDING` for entry timer? If so, what's the intended use of `STATE_ALARM_DISARMING` ?

**Comment by gwww** [comment]
Further to @BioSehnsucht comment, some alarm panels use `pending` when arming/disarming. The panel that we are working on (ElkM1), we chose to use `arming` and `disarming` states when arming/disarming. That seems more appropriate.

**Comment by balloob** [comment]
Well, this is not the place for a discussion about the available states of alarm panels. That would be in the [architecture repo](https://github.com/home-assistant/architecture/issues).

**Pull request merged**
