### PR TITLE
Fix entity config page rendering for disabled entities

### PR DESCRIPTION
**Pull request by spacegaier**
## Proposed change

Fix for PR https://github.com/home-assistant/frontend/pull/11078. 

It assumed that we always have a state, but that is not the case for disabled entities. This PR ensures that the page can still render (the icon title will then be "undefined").

grafik

## Type of change

- [ ] Dependency upgrade
- [X] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes #
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [X] The code change is tested and works locally.
- [X] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

**Review by ludeeus — DISMISSED** [review]

**Comment by bramkragten** [comment]
Please also update typing to prevent this same error in the future

**Comment by spacegaier** [comment]
> Please also update typing to prevent this same error in the future

I'm afraid I need an additional hint to what you mean.

**Comment by thomasloven** [comment]
I think it means change `any` in 
```js
template: (_, entry: any) => html`
```
to something more specific that has an optional `entity` property.

**Comment by spacegaier** [comment]
> I think it means change `any` in
> 
> ```js
> template: (_, entry: any) => html`
> ```
> 
> to something more specific that has an optional `entity` property.

I already assumed something along those lines, but originally did not see which type to use. I think I figured it out now...

**Review by bramkragten — APPROVED** [review]

**Comment by thomasloven** [comment]
Github won't let me comment so far outside the changes, but line 79 needs a change too then, right?
`entity: HassEntity;` -> `entity?: HassEntity;`

**Comment by bramkragten** [comment]
> Github won't let me comment so far outside the changes, but line 79 needs a change too then, right? `entity: HassEntity;` -> `entity?: HassEntity;`

TOOOOOO LATE! 😛

**Comment by spacegaier** [comment]
> Github won't let me comment so far outside the changes, but line 79 needs a change too then, right? `entity: HassEntity;` -> `entity?: HassEntity;`

Already did that a few seconds ago 😄👍

**Pull request merged**
