### PR TITLE
Fix scanning of small QR codes with JS

### PR DESCRIPTION
**Pull request by MindFreeze**
## Proposed change

Based on https://github.com/zwave-js/zwave-js-ui/pull/3946 by @AlCalzone 

https://github.com/nimiq/qr-scanner uses the native [BarcodeDetector](https://developer.chrome.com/docs/capabilities/shape-detection#barcodedetector) if available in browsers (essentially only Chrome), otherwise defaults to a JS port of ZXing. That port seems to be suboptimal, since it really struggles with the small Z-Wave QR codes.

https://www.npmjs.com/package/barcode-detector is a polyfill based on the WASM version of ZXing, which works much, much better.

The wasm file is added to `static/js` on build.

## Type of change

- [ ] Dependency upgrade
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes #
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [x] The code change is tested and works locally.
- [x] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

**Comment by AlCalzone** [comment]
I'll give this a shot later

**Review by bramkragten — DISMISSED** [review]

**Comment by AlCalzone** [comment]
I can see that the wasm file gets loaded, but I'm not sure this is actually working better than before.

I'll try to make a comparison tomorrow with Z-Wave JS UI and the HA frontend.

**Comment by MindFreeze** [comment]
> Ok, there seems to be no meaningful difference between Z-UI and HA anymore in terms of scanning, so that's good.
> 
> Only I'm getting this alert all the time, but I'm not sure why

Turns out the wasm version gives a slightly different error msg. Fixed.

Also added a fix for the "add device" button. It was stuck on disabled after a canceled inclusion.

**Comment by MindFreeze** [comment]
Realized that originally the PR was not zwave specific and the zwave fix should have been in a separate PR. But they are related so pls don't make me separate it 🥺

**Review by bramkragten — APPROVED** [review]

**Pull request merged**
