### PR TITLE
Add translations for ZHA alarm control panel configuration

### PR DESCRIPTION
**Pull request by dmulcahey**
## Proposed change

This PR adds translations for ZHA alarm control panel configs. In the next release I may move the config translations to the back end to keep them all together so that only the backend PR will need to be opened instead of needing a backend and frontend PR each time the options are expanded. 

## Type of change

- [ ] Dependency upgrade
- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes #
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [ ] The code change is tested and works locally.
- [ ] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

**Comment by balloob** [comment]
If you intend to copy them to the backend, we shouldn't merge this now. Otherwise these translation keys are created, people are translating them, and then we throw them out?

**Comment by bramkragten** [comment]
You are just adding keys? Where are these keys used?

**Comment by dmulcahey** [comment]
@balloob what would you prefer... I happened to notice in something you were working on recently that we can load translations from the backend. I didn't know we could do that. I built the new configuration options for ZHA around ha-form and vol schemas. Currently you need to add schema to the backend and a translations PR to the front end to translate the labels. I was going to refactor that later to move the translations to the backend so that only 1 PR needs to be opened to add more config options... does this make sense? 

@bramkragten these are for the alarm control panel configurations for ZHA.

**Comment by bramkragten** [comment]
Yes, I think translations on the backend make sense, lets close this.

**Pull request closed without merging**
