### PR TITLE
[WIP] Allow inclusion and exclusion on entity-filter cards

### PR DESCRIPTION
**Pull request by ciotlosm**
Work in progress to support filter entities. Fixes https://github.com/home-assistant/ui-schema/issues/41

```yaml
      - type: entity-filter
        filter:
          include: [{}]
          exclude:
            - domain: cover
            - domain: switch
            - domain: group
```

- [ ] Proper config validation in setConfig
- [ ] Update documentation

### CODE REVIEW

**Comment by c727** [comment]
As mentioned on discord yesterday I think we should move the filter to a static entities list:
- the result of domain/entity_id filters will always be the same
- user doesn't have to think about complex exclude/include strategies
- we can use the same syntax as for other entities cards including
```yaml
entities:
  - entity: light.kitchen
    name: test
```

So the result will be
```yaml
type: filter-entities
state_filter:
  - on
  - home
entities: []
```

**Comment by balloob** [comment]
I like the idea by @c727 a lot. It removes the exact pain point that is causing so many people trying to use it incorrectly.

If people want an all powerful filter card, they can write their own.

**Comment by ciotlosm** [comment]
@balloob @c727 I have to agree with you. Just a bit upset when losing some power in the entity. I understand the reasons behind going this route but man... includes + excludes would have allowed some really creative setups. 

I will close this PR as it no longer makes sense.

**Comment by c727** [comment]
You can still release this as custom card for lazy power users :P

**Pull request closed without merging**
