### PR TITLE
Subscribe to zwave_js node status updates in device panel

### PR DESCRIPTION
**Pull request by raman325**
## Proposed change
Right now there are two properties that we show in device info that only load on refresh, but they can change while looking at the panel. This change subscribes to updates so we can update the state appropriately.

Dependent on https://github.com/home-assistant/core/pull/73249

## Type of change

- [ ] Dependency upgrade
- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes #
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [ ] The code change is tested and works locally.
- [ ] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

**Review by zsarnett — DISMISSED** [review]

**Comment by zsarnett** [comment]
This PR Subscribes to the Status but doesn't do anything with it right?

**Comment by raman325** [comment]
It updates the device info panel. Before we only queried the status at load but now it will change live

**Review by zsarnett — APPROVED** [review]

**Comment by zsarnett** [comment]
Can be merged once the core is merged

**Comment by raman325** [comment]
> Can be merged once the core is merged

merged!

**Pull request merged**
