### PR TITLE
Don't use `base64url` for filename hash

### PR DESCRIPTION
**Pull request by bramkragten**
## Proposed change

Using 'base64' for filenames is problematic since it has the character / in its alphabet

ref: https://github.com/home-assistant/frontend/pull/15991

## Type of change

- [ ] Dependency upgrade
- [X] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes #
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [ ] The code change is tested and works locally.
- [ ] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

**Review by steverep — COMMENTED** [review]
Yes, base64 uses `+` and `/`, but base64url uses `-` and `_` instead (and also does not pad with `=` like base64).  The latter is the URL and filename safe variant.

https://datatracker.ietf.org/doc/html/rfc4648#section-5

**Comment by bramkragten** [comment]
Dev build doesnt work with current settings... With this change it does

**Comment by steverep** [comment]
Dev builds are working fine for me (Firefox and Chrome on Windows).  What's your symptom?

I'm confused because you're changes here aren't doing anything for production (still using base64url) and just making the digest undefined in development (which is not hashing anything anyway)...

**Comment by steverep** [comment]
Just confirmed with a sanity check on back to back builds with and without this change:

```
diff -rq hass_frontend hass_frontend_old
```

No differences output.

**Comment by bramkragten** [comment]
Webpack is giving me errors:
```
[17:57:08] 'webpack-watch-app' errored after 16 s
[17:57:08] TypeError [ERR_UNKNOWN_ENCODING]: Unknown encoding: base64url
    at Buffer.toString (buffer.js:802:11)
    at WasmHash.digest (/Users/bram/Documents/projects/home-assistant/frontend/node_modules/webpack/lib/util/hash/wasm-hash.js:143:34)
    at BatchedHash.digest (/Users/bram/Documents/projects/home-assistant/frontend/node_modules/webpack/lib/util/hash/BatchedHash.js:64:20)
    at Compilation.createHash (/Users/bram/Documents/projects/home-assistant/frontend/node_modules/webpack/lib/Compilation.js:4194:47)
    at /Users/bram/Documents/projects/home-assistant/frontend/node_modules/webpack/lib/Compilation.js:3033:39
    at /Users/bram/Documents/projects/home-assistant/frontend/node_modules/webpack/lib/Compilation.js:3277:6
    at /Users/bram/Documents/projects/home-assistant/frontend/node_modules/neo-async/async.js:2818:7
    at done (/Users/bram/Documents/projects/home-assistant/frontend/node_modules/neo-async/async.js:3522:9)
    at /Users/bram/Documents/projects/home-assistant/frontend/node_modules/webpack/lib/Compilation.js:3240:8
    at /Users/bram/Documents/projects/home-assistant/frontend/node_modules/webpack/lib/Compilation.js:3349:32
[17:57:08] 'develop-app' errored after 20 s
```

**Comment by steverep** [comment]
That's coming directly from node's buffer library which should take any of [these encodings](https://nodejs.org/api/buffer.html#buffers-and-character-encodings).  I don't understand why that error would occur unless your node version is old (`base64url` was added in minor releases of v14 and v15).

Looks like this isn't a devContainer.  What's your node version?  Any special mods?

**Comment by steverep** [comment]
FYI this is just coming from the "compilation" hash which is just a unique identifier for the build that can be used with the `[fullhash]` placeholder.  I would also expect you would get the same error building for production locally.

**Comment by bramkragten** [comment]
Meh, it was using node 14 instead of 16 :-/ my bad...

**Comment by steverep** [comment]
No sweat

**Pull request closed without merging**
