### PR TITLE
Add icon particles to onboarding

### PR DESCRIPTION
**Pull request by milanmeu**
## Proposed change
Add icon particles to onboarding.
Inspired by the 2021.4 release party (45:35): https://youtu.be/9V9DHB5nsNQ?t=2735

Icon particles are displayed on every onboarding page.
The icons list is based on the usage from analytics. Icons that are difficult to distinguish on a blue background are excluded.
The integration page is different, here the shown icons depend on the found and configured integrations.

Video: https://user-images.githubusercontent.com/15276289/114410649-d4647b80-9bab-11eb-834b-a01f94c4ab7a.mp4

## Type of change

- [ ] Dependency upgrade
- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Additional information

- This PR fixes or closes issue: fixes #
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [x] The code change is tested and works locally.
- [x] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

**Comment by spacegaier** [comment]
TBH: Looks cluttered and weird to me, almost like a rendering bug. Screenshot 3 is better (since less cluttered), but the graph lines behind the icons interfere with the logos that carry text in them since the logons are half translucent.

If we do something like that, then I think it needs to be a lower number of particles. A GIF would also help to better gauge the feel of it.

**Comment by milanmeu** [comment]
I replaced the screenshots with a video.

**Comment by milanmeu** [comment]
> but the graph lines behind the icons interfere with the logos that carry text in them since the logons are half translucent

I changed it in https://github.com/home-assistant/frontend/pull/8902/commits/f3791b54759ff2854c6f21925f76ef68d2a63f00. There is still a line through the Synology logo. I don't think it affects readability much.
This change is not in the video so here's a screenshot:
onboarding

**Comment by balloob** [comment]
Hahahaha nice one! 

So we should make sure that the particles in the background (or logos) don't attract too much attention. It should be decorative, but not annoying. So can we make it gray scale, maybe partially transparent ? 

Thinking if an an ideal world, it would be that we have a bunch of logos and we make the ones the user has twice as big. That way it looks a bit more random. 

So before you spend more time, if we don't think that we can get it be almost not distracting, we shouldn't move forward. So I guess the grayscaling/making the logos just white-ish should be a good firsst try.

**Comment by SeanPM5** [comment]
It's a neat idea conceptually, but IMO too distracting.  My eyes immediately get drawn to all the floating logos in the background and trying to see how many brands I can recognize, when instead my focus should be on completing the actual onboarding steps. 

I also feel it kinda gives a wrong / creepy vibe when you're inputting sensitive information like username, password, and home location while having tons of different company logos flying around your face. For the Analytics step in particular, I think it might cause users to misinterpret things and it will harm the opt-in rate.

Where I could see these floating icons maybe working is on a new "Welcome to Home Assistant" intro screen that appears before the create user account step. It could have some intro text (`"Are you ready to awaken your home, reclaim your privacy and join a worldwide community of tinkerers?"`) along with a continue button and that's it. And then once you leave that first screen it'd switch back to the current particles for the rest of the steps.

**Comment by balloob** [comment]
Thanks for your contribution. After thinking about it, I think it's better we don't do it right now.

**Pull request closed without merging**
