### PR TITLE
Fix missing seconds on datetime and time fields

### LINKED ISSUE #10278: input datetime: seconds set to zero without input
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When an input field for an input datetime entity is shown in the UI, the seconds of the datetime value is set to zero, without editing the value explicitly. Maybe one reason is, that with the default input field for time values seconds cannot be set at all.

### Describe the behavior you expected

The value of the input datetime entity should not be set to another value, when just showing the UI. Only when editing the value it should change.

### Steps to reproduce the issue

1. take any input_datetime entity with only time input
2. use service dev tools and call service input_datetime.set_datetime for that entity with time: '00:00:30'
3. check with states dev tools the state of the entity, it is '00:00:30'
4. Go to a lovelace dashboard and just view a control for this entity (for example the generated dashboard with all entities). Alternatively view the more info dialog, which shows the value of the entity from configuration -> entities.
5. go to states dev tools and check the state of the entity again, it is '00:00:00'

### What version of Home Assistant Core has the issue?

core-2021.10.4

### What was the last working version of Home Assistant Core?

_No response_

### In which browser are you experiencing the issue with?

Chromium to 94.0.4606.81, Firefox 93.0

### Which operating system are you using to run this browser?

Win10

### State of relevant entities

```txt
After service call:

editable: true
has_date: false
has_time: true
hour: 0
minute: 0
second: 30
timestamp: 85
friendly_name: some time

After showing:

editable: true
has_date: false
has_time: true
hour: 0
minute: 0
second: 0
timestamp: 0
friendly_name: some time
```

### Problem-relevant frontend configuration

_No response_

### Javascript errors shown in your browser console/inspector

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by chriss158**
## Proposed change

Currently, an input_datetime is display without seconds, which causes following issue: #10278.
With this PR the input_datetime with the more info dialog will display also seconds, which fixes the issue.
Additionally, on some other places like on automation the condition time and trigger time also displays time without seconds. This PR also adds the second's field there.

image,
image

## Type of change

- [ ] Dependency upgrade
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes #10278
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [x] The code change is tested and works locally.
- [x] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

**Review by spacegaier — DISMISSED** [review]

**Comment by bramkragten** [comment]
I don't think we should just display seconds everywhere, we should fix the seconds being updated when shown in the UI.

In some places showing seconds might make sense, but in most cases it won't.

**Comment by zsarnett** [comment]
@chriss158 Can you fix the merge conflicts?

**Comment by chriss158** [comment]
> I don't think we should just display seconds everywhere, we should fix the seconds being updated when shown in the UI.
> 
> In some places showing seconds might make sense, but in most cases it won't.

Ok, we could just show the seconds in the more info dialog to fix the issue. In the automations we could remove the seconds. I just thought that it would be reasonable to show the seconds everywhere.

> @chriss158 Can you fix the merge conflicts?
Doing right now 👍

**Comment by chriss158** [comment]
Done 👍

**Comment by zsarnett** [comment]
Can we remove the seconds in the automation editor? Adn then this looks good. Thanks

**Comment by chriss158** [comment]
> Can we remove the seconds in the automation editor? Adn then this looks good. Thanks
Removed and fixed merge conflicts :+1:

**Review by spacegaier — APPROVED** [review]
LGTM

**Comment by bramkragten** [comment]
This doesn't solve the problem I think, the issue is that `paper-time-input` removes seconds when it is not enabled, while it should just not render the seconds input and return the current value of seconds.

**Comment by zsarnett** [comment]
Is this still an issue with the MWC Components?

**Pull request closed without merging**
