### PR TITLE
Migrate chips to Material 3 chips.

### PR DESCRIPTION
**Pull request by piitaya**
## Proposed change

Use new Material 3 chips. Most chips has been replaced by M3 chips.  Demo has been updated too.

Some chips are used as label or tags (in quick-bar, automation list, user dialog). They are migrated to a new component `ha-label` that doesn't have click action and hover state.

Old Material chip dependency is not removed because it's needed for target picker. We have to figure out how to move this one to M3 (in another PR).

## Type of change

- [ ] Dependency upgrade
- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes #
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [ ] The code change is tested and works locally.
- [ ] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

**Comment by silamon** [comment]
For what it is worth, there is also a material chip implementation in the target picker. Aside from the chip possibilities, this one has multiple icon buttons and a very custom css.

**Comment by piitaya** [comment]
@silamon I checked to convert those chips to M3. M3 chips doesn't support 2 trainling actions (only remove action is possible). I will be for another PR because it's to much work for this one (e.g. we have to develop our own chips using M3 internals if we want this one)

**Comment by silamon** [comment]
> @silamon I checked to convert those chips to M3. M3 chips doesn't support 2 trainling actions (only remove action is possible). I will be for another PR because it's to much work for this one (e.g. we have to develop our own chips using M3 internals if we want this one)

Yeah I agree, eventually it may fit better as a regular component not really tied to a m3 chip.

**Comment by JosephAbbey** [comment]
The preview deployment does not seem to be working for this PR

**Comment by piitaya** [comment]
@JosephAbbey Here's the link : https://deploy-preview-18513--home-assistant-gallery.netlify.app/#components/ha-chips

**Review by bramkragten — APPROVED** [review]

**Pull request merged**
