### PR TITLE
Fix compression of hassio builds

### PR DESCRIPTION
**Pull request by ludeeus**
## Proposed change

- There is no service worker for the hassio frontend so there is nothing to compress with be there.
- brotli compression was included in aiohttp 3.10 (and then Home Assistant 2024.8.0, meaning that we can not full use that, because of older core with newer supervisor, for that reason we need to compress with both.

## Type of change

- [ ] Dependency upgrade
- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes #
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [ ] The code change is tested and works locally.
- [ ] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

## Summary by CodeRabbit

- **New Features**
	- Enhanced file compression functionality with new parameters for including service workers and modern files.
	- Improved flexibility in selecting files for compression based on user-defined options.

### CODE REVIEW

**Comment by bramkragten** [comment]
Is it an option to keep supervisor just on Zopfli for now instead of including both?

**Comment by ludeeus** [comment]
That would be an option, but the reason it was added is that it is faster.
As the frontend of hassio is bundled in the published container so the overhead should be minimal right?

**Comment by bramkragten** [comment]
Yeah, only thing is that the container will be bigger, but might not be a big deal.

**Review by bramkragten — APPROVED** [review]

**Comment by steverep** [comment]
> There is no service worker for the hassio frontend so there is nothing to compress with be there.

But gulp will just ignore that part of the glob for supervisor, so I don't think that change was necessary?


> brotli compression was included in aiohttp 3.10 (and then Home Assistant 2024.8.0, meaning that we can not full use that, because of older core with newer supervisor, for that reason we need to compress with both.

Is there not a mechanism in place to enforce what core versions each supervisor version supports?  Core would just ignore the `*.br` files and serve the uncompressed versions, so no fix would be technically needed unless we remove those as in #19838.

I don't think compressing with both indefinitely is a good approach to sustain given how expensive of an operation it is, especially with Zopfli.  We should have a deprecation plan here.

**Comment by ludeeus** [comment]
It would not just ignore it, the build failed, which is why it was changed.

Other than merging more and more of the old supervisor UI into the core UI, there is (AFAIK) no deprecation plan for older systems.
There is a reason we want compression; leaving that out because that 1 build a year might take 4 minutes extra is not a good option, IMO.

**Pull request merged**
