### PR TITLE
Check if external app by object

### LINKED ISSUE #4271: reloading frontend from new version toast removes external auth
**Checklist:**

- [ ] I updated to the latest version available
- [ ] I cleared the cache of my browser

**Home Assistant release with the issue:**
0.102

**Last working Home Assistant release (if known):**

**UI (States or Lovelace UI?):**
When a new version of the frontend is available, a toast shows up. When I click reload on this toast while the frontend is loaded with external auth, it will reload without external auth. (external_auth=1). This gives a bad experience in Android and iOS app.

**Browser and Operating System:**

**Description of problem:**

**Javascript errors shown in the web inspector (if applicable):**

```

```

**Additional information:**

### PR DESCRIPTION
**Pull request by bramkragten**
Fixes https://github.com/home-assistant/home-assistant-polymer/issues/4271

### CODE REVIEW

**Review by balloob — APPROVED** [review]

**Comment by bramkragten** [comment]
Can use optional chaining here :tada:

**Comment by balloob** [comment]
Did you test this with the Android app? Easiest way to test it is to remove the external_auth in query check and see if Android app can still use external auth. 

We should also update the dev docs

**Review by balloob — APPROVED** [review]
niiiice

**Comment by bramkragten** [comment]
Yeah tested with the android app.

**Pull request merged**
