### PR TITLE
Fix visibility save in dashboard edit

### LINKED ISSUE #20010: [2024.3.0] Editing visibility of a dashboard does not work anymore
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

When trying to edit the visibility of an existing dashboard page. It is not possible to save my changes.
The slider just jumps back after some seconds.
 -> Changing visibility is not possible at all

### Describe the behavior you expected

I can change the visibility for all users and can save my changes

### Steps to reproduce the issue

1. Create new dashboard page with any visibility settings
2.  Try to edit them after saving it the first time (looks like initial save is ok)

### What version of Home Assistant Core has the issue?

2024.3.0

### What was the last working version of Home Assistant Core?

2024.5.4

### In which browser are you experiencing the issue with?

Google Chrome 122.0.6261.111

### Which operating system are you using to run this browser?

Windows 11

### State of relevant entities

```txt
no relevant enitites
```

### Problem-relevant frontend configuration

```yaml
I created a experimental sections card. May the bug is related to this.
```

### Javascript errors shown in your browser console/inspector

```txt
hui-dialog-edit-view.ts:475 Uncaught TypeError: Cannot assign to read only property 'visible' of object '#<Object>'
    at F.value (hui-dialog-edit-view.ts:475:20)
    at F.handleEvent (lit-html.ts:2018:29)
    at r (fire_event.ts:76:8)
    at t.value (hui-view-visibility-editor.ts:136:5)
    at F.handleEvent (lit-html.ts:2018:29)
    at HTMLDivElement.<anonymous> (mwc-switch-base.ts:121:14)
```

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by silamon**
## Proposed change
Fix #20010

## Type of change

- [ ] Dependency upgrade
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes #20010
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [x] The code change is tested and works locally.
- [x] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

**Review by piitaya — APPROVED** [review]
Thank you 👍

**Comment by giovanni247000** [comment]
it still doesn't work after the latest update

**Comment by ildar170975** [comment]
@giovanni247000
imho the latest update is 2024.3.0 where the issue was observed first time.

**Comment by giovanni247000** [comment]
still has to come out the update that solves the problem I understand correctly, sorry but I don't go away from it much but I just wanted to understand if I'm the one who'm doing something wrong or it's correct that for the moment it still doesn't work

**Pull request merged**
