### PR TITLE
Align entities card section header styling

### PR DESCRIPTION
**Pull request by spacegaier**
## Proposed change

Currently the section header is using the primary color that we normally reserve for links, buttons, other interactive elements. This is quite misleading.

grafik

I tried several alternatives. In all I reduced the margin at the bottom to the next element a bit since it was quite far away.

1. Primary text color:
grafik

2. Primary text color + font weight:
grafik

3. Secondary text color + font weight:
grafik

4. Use exact style from entity / gauge card (when https://github.com/home-assistant/frontend/pull/8081 merged) = secondary text color + font weight + font size 16px
grafik

=> I personally like the "sleek" look in number 3 esp. when combined with other cards such as entity or gauge. It feels lighter and provides better separation between regular rows and the section header.
The font size increase in number 4 makes it more consistent with the other cards, but is not really required, since the text color already provides enough visual separation.

## Type of change

- [ ] Dependency upgrade
- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [X] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes #
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [X] The code change is tested and works locally.
- [X] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

**Comment by bramkragten** [comment]
Can you add a screenshot of your preferred one in the light theme too?

**Comment by spacegaier** [comment]
grafik

**Comment by bramkragten** [comment]
I don't think a header should have a secondary color, I think we should just follow material rules?
<https://material.io/design/typography/the-type-system.html#type-scale>

**Comment by spacegaier** [comment]
All my examples that used white text color should say "Primary Text Color". The target was to have the same color as the card title, not specifically the secondary color. I will update that.

Reg. MD rules: So it should be "Subtitle 1" = same size and weight as the regular primary body text in the card or what level do we assign to the section header?

**Comment by bramkragten** [comment]
I think I prefer number 2

**Pull request merged**
