### PR TITLE
Allow pressing enter to pick item at the top  of the list

### PR DESCRIPTION
**Pull request by balloob**
## Proposed change

Allow pressing enter in the "add integration" dialog to pick entry at top of the list.

image

Pressing enter would pick Unifi Network.

## Type of change

- [ ] Dependency upgrade
- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes #
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [ ] The code change is tested and works locally.
- [ ] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

**Comment by spacegaier** [comment]
That behavior feels a bit weird to me and is not really clear to the user from a UX POV. I think it would be more consistent if you could navigate the result list with the arrow keys so that arrow down highlights the first search result and then the enter press picks it. So the same as e.g. the quick bar does.

**Comment by balloob** [comment]
I agree that that is an improvement, but I consider this also an improvement. I don't have time to do a refactor of the handler picker.

**Comment by balloob** [comment]
Pinging @matthiasdebaat to let him decide 👍

**Review by zsarnett — APPROVED** [review]

**Comment by matthiasdebaat** [comment]
Think this is a good first step. The suggestions @spacegaier is a better next iteration. Sound like it's a bit more work, so let's keep it small for now.

**Pull request merged**
