### PR TITLE
Refactor Intl polyfills and remove from ES5 entrypoints

### LINKED ISSUE #15956: Supervisor entrypoints are too big ?
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Entrypoint.something.js has grown beyond 1.4MB and is being truncated by default reverse proxy settings in nginx

Took me a while to fix and another while to unregister the service workers that cache this file.

Now it's working for me but I'm guessing many a reverse proxy user will struggle.

Maybe something can be done to compress the file or split it up or refactor and maybe nothing can be done, just wanted to report here this will probably cause some headaches...

Using HAOS and all updated to the latest stable version.

### Describe the behavior you expected

No file above 1MB should be needed for the UI?

### Steps to reproduce the issue

Load the UI over a nginx reverse proxy 
Observe entrypoint.xxxxx.js is truncated 

### What version of Home Assistant Core has the issue?

2023.3.6

### What was the last working version of Home Assistant Core?

2023.3.4 or 5

### In which browser are you experiencing the issue with?

all, not a browser issue but nginx default max body size

### Which operating system are you using to run this browser?

all

### State of relevant entities

_No response_

### Problem-relevant frontend configuration

_No response_

### Javascript errors shown in your browser console/inspector

```txt
Depends where the file gets truncated, can vary a bit
```

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by steverep**
## Proposed change

This change drastically reduces the entrypoint sizes for the ES5 build by removing the _FormatJS_ `Intl` polyfills and loading them with the same timing logic as the latest build.  It also greatly simplifies use of `Intl` where desired by only requiring a single import.  Steps are roughly:

1. Split the dynamic import and top level await version for the latest build into its own module.  Also split out the locale data polyfill function so there's no circular dependency.
2. Move the TLA to the new `intl-polyfill` module, and just write code to import it before using `Intl`.
3. Split the static import version for the ES5 build as well.  Code is written for latest build, but Webpack makes the swap for the ES5 build.

And here's the result on the ES5 build:

| ES5 Entrypoint | Old | New |
|:--- |:---:|:---:|
| app | 582K | 596K |
| core | 2.1M | 345K |
| custom-panel | 2.0M | 317K |
| authorize | 2.5M | 859K |
| onboarding | 2.7M | 1.1M |
| _Total Bundle_ | _36M_ | _32M_ |

And as a happy accident, the latest build entries go down a little too.  This is because the connection mixin is no longer importing the `localize` module early:

| Latest Entrypoint | Old | New |
|:--- |:---:|:---:|
| app | 315K | 293K |
| core | 19K | 19K |
| custom-panel | 35K | 35K |
| authorize | 388K | 367K |
| onboarding | 417K | 395K |
| _Total Bundle_ | _26M_ | _26M_ |

I mean... I knew that was going to happen. 🦊 

This may actually fix the Webpack upgrade issue as well because that's reportedly related to conditional TLAs, which are eliminated here.  I'll have to check that out.

## Type of change

- [ ] Dependency upgrade
- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [x] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes #
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [x] The code change is tested and works locally.
- [x] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

**Comment by steverep** [comment]
I'm adding 2 corrections here:

1. Dynamic imports should use the `polyfill-force` options so as not to repeat the `shouldPolyfill` checks.
2. English locale data must be imported after the corresponding polyfill.

There are other corrections/improvements that I noticed could be made, but I'll save those for a follow up and list in an issue before I forget.

Also, these polyfills are still plaguing the supervisor entrypoints (see #15956).  Some extra savvy is needed to fix that.

**Review by bramkragten — APPROVED** [review]

**Comment by steverep** [comment]
Did you want to wait on 2023.6 for this one?

**Comment by bramkragten** [comment]
> Did you want to wait on 2023.6 for this one?

yeah, I'll merge it on thursday if that doesn't stop your from continuing something else?

**Comment by steverep** [comment]
There's more that requires this, but also plenty to do that doesn't.  No big deal to wait or just work with a stash. 👍🏻

**Comment by steverep** [comment]
FYI, this does indeed fix the ability to upgrade Webpack (ref: https://github.com/webpack/webpack/issues/16097).

**Pull request merged**
