### PR TITLE
Prettier 💎

### LINKED ISSUE #672: Prettier
How do we feel about switching to [Prettier](https://prettier.io/) for formatting the code? We would focus it on JS only. Once we convert Polymer to JS, it will become part of it too.

ESLint will be limited to 1 style check: was this code prettified. (it would still check for bugs, unused args etc)

### PR DESCRIPTION
**Pull request by balloob**
This adds prettier to the code base.

Closes #672 

Includes:
 - Prettier pre-commit hook for staged files
 - ESLint preset that disables things that conflict with prettier
 - ESLint plugin to enforce prettier was run

### CODE REVIEW

**Comment by thomasloven** [comment]
I like that this breaks long lines, but it seems this removes trailing commas in objects?
You get prettier git diffs in the future if they are allowed.

For example, adding a new key-value pair to the following object:
```js
let mything = {
  key1: 'value1',
  key2: 'value2',
}
```
would mark two lines as changed if you also had to add the separating comma.

**Comment by balloob** [comment]
Trailing comma's is an option. I think that's a good option to enable https://prettier.io/docs/en/options.html

**Comment by balloob** [comment]
Added trailing comma to the options. First commit contains config changes, 2nd commit is Prettier applied.

**Comment by armills** [comment]
Could we keep the default quotes at single-quotes, at least for the initial PR to make it easier to see the other changes? https://prettier.io/docs/en/options.html#quotes No real preference if we want to switch it later though.

Also worth noting that after this is merged we should be careful to make sure open PR branches get rebased before merging to save ourselves some headaches.

**Comment by balloob** [comment]
I prefer to have one massive PR than to have to do another quote related one later. 

Yeah for open PRs it might be a little pain. There are not any really big PRs open that couldn't be easily ported.

**Pull request merged**
