### PR TITLE
Add missing 1px to prevent slider pin cutoff

### PR DESCRIPTION
**Pull request by spacegaier**
## Proposed change

Follow-up to PR https://github.com/home-assistant/frontend/pull/7651. @ludeeus was <s>right</s> wrong and it needs to be 5px 😆.

**Before:**
image

## Type of change

- [ ] Dependency upgrade
- [X] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes #
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [X] The code change is tested and works locally.
- [X] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

**Comment by ludeeus** [comment]
That means I was wrong ;)

**Comment by spacegaier** [comment]
> 
> 
> That means I was wrong ;)

Ahm...yeah...typo 😉 . Fixed.

**Comment by ludeeus** [comment]
5 is so strange...
I'm more in favor of 6 in that case, @bramkragten ?

**Comment by bramkragten** [comment]
I think 5 is fine in this case... Ideally, we should not have to do this at all...

**Review by bramkragten — APPROVED** [review]

**Pull request merged**
