### PR TITLE
Added a bunch of tile features

### PR DESCRIPTION
**Pull request by josephabbey**
## Proposed change
I have implemented a bunch of features for the tile card, including:
- Generic toggles (lights, switches, automations, and input_boolean)
- Generic buttons (buttons, scripts, automations, and input_button)
image
- Update (skip and install)
image
- Media controls (on, off, pause, play, repeat, shuffle, next, previous)
- Media volume (buttons or slider)
image
- Buttons option for select-options feature
image
- Number Input (buttons or slider)
image
- Text Input
image
- Datetime Input
image
- *Entity* (Show a row with an entity icon, name, and state, with most of the options for the tile card also available, including icon actions and state content)
image

## Type of change

- [ ] Dependency upgrade
- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml
title: Home
views:
  - path: default_view
    title: Home
    cards:
      - features:
          - type: entity
            entity: media_player.bedroom
            state_content:
              - state
              - app_name
          - type: entity
            entity: light.ceiling_lights
            icon_tap_action:
              action: toggle
          - type: entity
            entity: blah.blah
        type: tile
        entity: update.demo_add_on
        hide_state: true
        icon_tap_action:
          action: call-service
          service: homeassistant.reload_config_entry
          target:
            entity_id: update.demo_add_on
        color: grey
      - type: tile
        entity: input_boolean.test
        features:
          - type: toggle
      - type: tile
        entity: light.bed_light
        features:
          - type: toggle
      - type: tile
        entity: button.push
        features:
          - type: button
      - type: tile
        entity: automation.new_automation
        features:
          - type: toggle
          - type: button
      - type: tile
        entity: media_player.bedroom
        features:
          - type: media-controls
            use_extended_controls: true
          - style: buttons
            type: media-volume
          - type: media-volume
            style: slider
      - type: tile
        entity: update.demo_add_on
        features:
          - type: update
```

## Additional information

- Link to documentation pull request: https://github.com/home-assistant/home-assistant.io/pull/29642

## Checklist

- [x] The code change is tested and works locally.
- [x] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works. (not usually done for tile features from what I can see)

If user exposed functionality or configuration variables are added/changed:

- [x] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

**Comment by bramkragten** [comment]
We should split this PR to make reviewing and merging easier.

We also need a review from UX @matthiasdebaat

**Comment by JosephAbbey** [comment]
Feel free to choose a selection of these features to accept, I had lots of ideas.

I have also now added documentation.

**Comment by JosephAbbey** [comment]
Ok, I have fixed those linting issues, sorry about that

**Comment by JosephAbbey** [comment]
@bramkragten 
> We should split this PR to make reviewing and merging easier.

Should I split it into individual tile features with 1 PR each?

**Comment by piitaya** [comment]
Hello 👋 Thanks for the proposal 🙂

I have some feedbacks about the changes. We already thought about most of these features but we didn't implement them due to the usability or blocking points.
In general, we don't use texts in features but icons because the tile card can be used in a grid card so I can be small. There is an exception for dropdown (climate and preset) because the text takes the full width of the card. 
Then, we don't use material design input on tile features because there are designed for form, not for widget. For example, the dropdown in tile feature (which is the same as more info) is not the same as the one in our form. Texts can be very long depending on the language and we do not want to penalize certain languages in terms of the accessibility of features.

**Buttons**:  The icon action is here for these action so I don't think it can it can be really useful. 
**Toggle** : Same as buttons. However, I can see a benefit for this feature : Having the same height for every light with tile card (e.g. If you have a grid of tile card, you can put brightness feature for light that supports brightness and switch feature for others to keep the same height for every card)
**Select buttons** : Adding icons to select option is work in progress in the back-end. We can release this once it's ready but with icons instead of text. 
**Update** : Looks like something similar than Mushroom update card. We thought about importing similar UX to tile features but we didn't put this one as a feature because update entity are a "technical entity" and in general should not appear in a dashboard (because new updates appears in the config screen.
**Media player** : More info redesign for media player is on the roadmap so this tile features will be designed according to the new more info. Having something like a mini media player dedicated control can be cool instead of reusing button and sliders.
**Input number** : Our current slider doesn't have live preview so It's not precise to select the right value. However, the plus and minus button works well!
**Input date and text** : Material design input should not be used.
**Entity** : That not something we have to bring to tile feature. The tile card is designed for a single entity.

I would suggest to open a first PR for input number feature 🙂 
I let @matthiasdebaat to complete my feedback for the design point of view.

**Comment by JosephAbbey** [comment]
Hi @piitaya, thanks for the review, I have a few problems that I was trying to solve with these features but given your feedback, I am not sure how they could be solved:

- For scripts it doesn't seem obvious that a click on the card or the icon would run it because neither are obviously buttons (although I have seen the possibility of a tap and hold gesture that may solve this).
- For automations it doesn't make sense that a click on the card would enable/disable it and a click on the icon would run it, it would make more sense to have a witch and a button.
- An example for the entity card: I have some zigbee temperature sensors, it would be nice to show the temperature in a tile with the humidity and battery shown underneath but in the same tile.
- Another example: I have one climate entity for my house that controls the central heating, I would like to include the controls for the fans inside of the same card.
- Final example (less useful): I have some zigbee smart 4-plugs, I would like to have a tile card that is headed with a switch group and then has underneath each individual plug switch (basically all on or off and each on or off)

These are the problems that I wanted to solve, you may have better solutions or better ways to implement my solutions. 

Thanks Joseph.

**Comment by KTibow** [comment]
The screeenshot shows a non-Roboto font in the buttons, probably from using `<button>` which needs a CSS reset.

**Comment by piitaya** [comment]
For multiple entities, an [entities card](https://www.home-assistant.io/dashboards/entities/) seems to be a better alternative. But we are actively discussing about extending the tile card with the design team so I don't have a solution for now. Tile card is focused on single entity. A kind of "device tile card" or "area tile card" could be a solution for multiple entities purpose. I keep you updated 🙂

**Comment by piitaya** [comment]
@JosephAbbey Do you like to open a PR for the number feature so we can move forward on this one?

**Comment by piitaya** [comment]
I had a branch/PR for update feature few month ago. Do you want me to open a PR for update feature or should I restore mine?
Also, It can be cool to have icon instead of text inside buttons (like the Mushroom card one).
image

And I totally agree with you, entities card should be updated/enhanced to fit the tile card design. That's what we did for thermostat card in the december release. But we should take care to handle all the possible cases to avoid regression for users. (e.g. many special row are supported https://www.home-assistant.io/dashboards/entities/#special-row-elements)

**Comment by JosephAbbey** [comment]
The update feature should definitely use icons. So we should use your implementation.

When it comes to the entities card, I would be happy with basically a bunch of tile cards stacked as one card (I currently use the stack in card custom card for this). My wants would be:
- the state content feature
- having tile features for multiple entities
- different colours for each entity
- individual icon tap actions
- either one tap action or individual tap actions but it must be clear where you click, for example ripples and hover

My last thought is that it is nice to show a "master" tile in a list (with indentation or size), in my final image it is clear that the top entity is the main entity.

**Comment by Hedda** [comment]
> we are actively discussing about extending the tile card with the design team so I don't have a solution for now. Tile card is focused on single entity. A kind of "device tile card" or "area tile card" could be a solution for multiple entities purpose. I keep you updated 🙂

Any updates on those "device tile card" and/or "area tile card" ideas for showing multiple entities? That is also requested here:

* https://community.home-assistant.io/t/enhanced-tile-card-display-multiple-device-sensors-and-attributes/757601

**Comment by jaimevisser** [comment]
Yes! A Device tile card is exactly what I'm looking for!

**Comment by Madelena** [comment]
> Any updates on those "device tile card" and/or "area tile card" ideas for showing multiple entities? That is also requested here:
> 
> * https://community.home-assistant.io/t/enhanced-tile-card-display-multiple-device-sensors-and-attributes/757601

Definitely looking into it, and thanks for the link.

**Comment by Hedda** [comment]
@Madelena Thanks! FYI, there is also a similar request here > https://github.com/home-assistant/frontend/discussions/20159

**Pull request closed without merging**
