### PR TITLE
Add more contrast to map

### PR DESCRIPTION
**Pull request by KTibow**
## Proposed change

Add a filter to make the map easier to see with more contrast.
Before:
image
After:
image
Here I only applied the filter to one tile:
image

## Type of change

- [ ] Dependency upgrade
- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

[Open your Home Assistant instance and show your zones.](https://my.home-assistant.io/redirect/zones/)

## Additional information

- This PR fixes or closes issue:
- This PR is related to issue or discussion: #12392
- Link to documentation pull request:

## Checklist

- [ ] The code change is tested and works locally.
- [x] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

**Comment by noxhirsch** [comment]
IMHO that's way too much contrast / too bright in dark mode. It doesn't look nearly as good as before and makes the overlays (marker / zones / path of the last hours) hard to see.

**Comment by ildar170975** [comment]
> too much contrast / too bright in dark mode

Then probably using special theme variables may be better.

**Comment by matthiasdebaat** [comment]
As [commented](https://github.com/home-assistant/frontend/discussions/12932#discussioncomment-3169843) in the discussion. I would like to use a more vibrant map style with more contrast that users are familiar with, for example from Google Maps. For the CARTO basemap, that would be the [Voyager style](https://d.basemaps.cartocdn.com/#13/40.7062/-74.0045). We're only adding zones and people to our map, so I think this would work perfectly with a more detailed map.

Downside is that there isn't a dark mode version of Voyager. In that case we could invert the colors or apply a hue rotate effect, [described in this blog post](https://www.esri.com/arcgis-blog/products/arcgis-online/mapping/create-a-light-or-dark-version-of-any-map-in-two-seconds/).

CleanShot 2022-07-18 at 11 16 28@2x
CleanShot 2022-07-18 at 11 17 35@2x

**Comment by matthiasdebaat** [comment]
Thanks for getting this ball rolling @KTibow!

**Comment by KTibow** [comment]
Closing in favor of #13227

**Pull request closed without merging**
