### PR TITLE
Adjust gitignore: Only exclude "translations" folder + children

### PR DESCRIPTION
**Pull request by spacegaier**
## Proposed change

We want to track changes to `src/translations/en.json` and `src/common/translations/*` which currently are ignored. Now we only ignore the `translations/` folder itself.

Not sure if there are other paths we need to list as well?

## Type of change

- [ ] Dependency upgrade
- [X] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes #
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [ ] The code change is tested and works locally.
- [ ] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

**Comment by bramkragten** [comment]
the current rule does not match `src/translations` or `src/common/translations` ?

**Comment by spacegaier** [comment]
> the current rule does not match `src/translations` or `src/common/translations` ?

It does for me in VS Code on Windows. I always get an error when changing `en.json` or when I added the new util files in `src/common/translations` for the other PR a few minutes ago. I had to manually use `git add src/common/translations/date_names.ts -f` (so with the force option) to have git ignore the `gitignore` here.

**Comment by bramkragten** [comment]
Stupid windows

**Comment by steverep** [comment]
That's my bad I guess.  If I'm reading the [gitignore doc](https://git-scm.com/docs/gitignore) correctly, the whole `# Build` sections should be changed to:

```
# build
build/
/hass_frontend/
dist/
/translations/
```

And the trailing "`*`" should be removed from `.yarn/*`, `node_modules/*`, and `.vscode/*`.  Rationale:

- Leading "/" makes it not apply in sub-directories
- Trailing "/" says only match directories (e.g. doesn't apply to a file called "`build`")
- The middle "/" in "`translations/*`" does make it not apply to sub-directories, but the single asterisk makes it not apply to grandchildren (e.g. "translations/frontend/en.json").  I think "`/translations/`" and "`translations/**`" are effectively the same (although maybe the latter doesn't ignore the directory itself?).

**Comment by spacegaier** [comment]
Closing in favour of the more comprehensive https://github.com/home-assistant/frontend/pull/14567

**Pull request closed without merging**
