### PR TITLE
Add a docs icon to the config flow dialog

### PR DESCRIPTION
**Pull request by balloob**
## Proposed change
Add link to the documentation to the config flow dialog

image

Marking as draft because I am not 100% satisfied with looks yet.

## Type of change

- [ ] Dependency upgrade
- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes #
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [ ] The code change is tested and works locally.
- [ ] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

**Review by zsarnett — DISMISSED** [review]

**Comment by zsarnett** [comment]
Looks the same as lovelace right?

**Comment by ludeeus** [comment]
Almost, in lovelace we use `mdiHelpCircle` instead of `mdiHelpCircleOutline`

**Comment by balloob** [comment]
I agree consistency is better, but maybe we should update it everywhere. That icon is intense.

image

**Comment by ludeeus** [comment]
Personally, I like the slimmer variant used here better (`mdiHelpCircleOutline`)

**Comment by balloob** [comment]
Same.

**Review by zsarnett — DISMISSED** [review]

**Review by zsarnett — APPROVED** [review]

**Pull request merged**
