### PR TITLE
Change English/default naming of Configure UI to Edit Dashboard

### LINKED ISSUE #6506: Change wording of Configure UI to Edit Dashboard
## The request

image

## The alternatives

Not changing it?

### PR DESCRIPTION
**Pull request by zsarnett**
## Type of change

- [ ] Dependency upgrade
- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [x] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes #6506
- This PR is related to issue:
- Link to documentation pull request: https://github.com/home-assistant/home-assistant.io/pull/14186

## Checklist

- [ ] The code change is tested and works locally.
- [ ] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

**Review by ludeeus — DISMISSED** [review]
This needs a documentation change as well <https://www.home-assistant.io/lovelace/>

**Comment by zsarnett** [comment]
@ludeeus 😄 
image

**Comment by ludeeus** [comment]
Now since we have multiple dashboards it makes sense to change this from "UI" to "dashboard".
But the change from "configure" to "edit", I'm not sure about, do we have, or should we have a standard here?
For integrations, we mostly have "configure", on the other hand, we have "edit" for view and card in lovelace :man_shrugging:

**Comment by zsarnett** [comment]
In my mind, configure sounds much more technical and daunting than edit. And I don't believe that taking control of your Lovelace dashboard should be a daunting experience. That's why I believe we are going to take out the daunting warning when editing a dashboard

**Comment by SeanPM5** [comment]
I agree with @zsarnett that the word "configure" sounds a little too technical and perhaps scary to newer users. I think it's a good idea to make it sound more simple and welcoming.

Another idea would be "Customize Dashboard" but that might be a tad long? 

I like "Edit Dashboard" though. And for what it's worth, iOS uses "Edit Home Screen" and "Edit" on their widgets screen. So billions of users are already familiar with that terminology.

**Review by ludeeus — APPROVED** [review]
I'm fine either way as long as we are consistent :)

**Pull request merged**
