### PR TITLE
Add pointer cursor to ha-formfield in update card

### PR DESCRIPTION
**Pull request by ludeeus**
## Proposed change

Make the entire element "clickable"

## Type of change

- [ ] Dependency upgrade
- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes #
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [ ] The code change is tested and works locally.
- [ ] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

**Comment by bramkragten** [comment]
A label for an input element normally doesnt have a pointer cursor

**Comment by ludeeus** [comment]
That's why it's added here.

**Comment by bramkragten** [comment]
Haha, but why?

**Comment by ludeeus** [comment]
So it’s clear
I know you can click the text, you know it. But I doubt everyone does.

**Comment by bramkragten** [comment]
Yeah, but we should not go and change default behavior of the browser, and definitely not just in 1 place, we use this in a lot of places.

**Pull request closed without merging**
