### PR TITLE
Fix drag and drop with sortablejs

### PR DESCRIPTION
**Pull request by piitaya**
## Proposed change

Sortable was broken because it's trying to access to `Polymer.dom`. I cleaned one missing polymer reference. 

image

[Sortable source](https://github.com/SortableJS/Sortable/blob/babf6ab85fdfc5e13be1027827cecfbba2fb0d1e/src/utils.js#L492)

## Type of change

- [ ] Dependency upgrade
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes #
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [ ] The code change is tested and works locally.
- [ ] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

**Comment by bramkragten** [comment]
This means we no longer set these settings for the elements that do use Polymer...

**Comment by piitaya** [comment]
We have `dom: "shadow"` but I don't know why? It should be a function not a string.

**Comment by piitaya** [comment]
> This means we no longer set these settings for the elements that do use Polymer...
> 
> Not sure how much that is needed

Why would we keep Polymer in the window now it's deprecated?

**Comment by bramkragten** [comment]
> > This means we no longer set these settings for the elements that do use Polymer...
> 
> > 
> 
> > Not sure how much that is needed
> 
> 
> 
> Why would we keep Polymer in the window now it's deprecated?

Because we still use Polymer elements

**Comment by bramkragten** [comment]
But yeah, seems this is for Polymer 2 👍🏼

**Review by bramkragten — APPROVED** [review]

**Pull request merged**
