### PR TITLE
Hide group header in case of empty name

### PR DESCRIPTION
**Pull request by andrey-git**
Hide group header in case of empty name

https://community.home-assistant.io/t/optional-group-titles/10176

### CODE REVIEW

**Comment by balloob** [comment]
The idea from the group component is that it never has an empty name, hence the line `service.data.get(ATTR_NAME, object_id)`. I think that we should fix that bug instead?

**Comment by andrey-git** [comment]
Then we could drop the `trim()` part. The other code is still needed to avoid the extra padding that comes with the title.

**Comment by andrey-git** [comment]
Actually that is incorrect. `service.data.get(ATTR_NAME, object_id)` is allowing an empty name (a missing name defaults to objectid, which is fine). 

The problem is with `computeStateName` which falls back to objectID if friendly_name is defined but is an empty string. Should I fix this one?

**Comment by balloob** [comment]
Sorry, my message was not clear. I think that it's totally a good idea to fall back to object id if the name is non-existing. We should always have a name.

**Comment by andrey-git** [comment]
I agree with the fallback.

But what about the case where the user explicitly specified an empty name?

Might not make much sense for a state card, but reasonable for a group or a badge.

It could still be weird in config pickers, but having no group header sounds like reasonable request.

**Comment by balloob** [comment]
Although it's easy to support here, I wonder at what other places it is going to bite us. The config picker should not be _too_ weird as we are currently showing the entity id underneath the name. But I can see that changing in the future.

**Comment by andrey-git** [comment]
This change as-is affects the group header presentation only.
Changing `computeStateName` will have wider effects.

**Comment by balloob** [comment]
I understand it's the presentation only but the issue is that once we support it here, we "officially" support it. So if there is any place where we render group names (now or in the future), we now will always need to do some if-check to make sure that we handle this case.

**Comment by andrey-git** [comment]
The user already can use a group name " " (single space) to *mostly* remove the header except for some leftover margin.

As-is this PR only handles that case without affecting how the group will look like as state card.

Though the the state card would still look weird because of that space-only name.

We could add a config variable 'hide_name' similar to control:hidden, but I dislike adding visual configs to groups.

**Pull request merged**
