### PR TITLE
Sync selected icon with selected value in new select component

### PR DESCRIPTION
**Pull request by piitaya**
## Type of change

- [ ] Dependency upgrade
- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes #
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [ ] The code change is tested and works locally.
- [ ] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

**Comment by bramkragten** [comment]
Not sure I understand what the difference is with the old code?

**Comment by piitaya** [comment]
> Not sure I understand what the difference is with the old code?

The old code set the icon using entity state value while now it's using the value of the select (this value can be changed using the property or when choosing select option).

This caused issue like this :
CleanShot_2023-08-14_at_14 29 42

**Comment by bramkragten** [comment]
So it is like an optimistic update, but with the first state update it will be overridden right? Should we also handle it failing to update in time?

**Comment by piitaya** [comment]
Yes, the select behavior isn't changed. It was always optimistic. This PR only sync between the label and the icon.
I need to check if it's not possible to get the icon from the selected ha-list-item instead of recomputing it.

**Comment by piitaya** [comment]
I updated the code to get the icon from the selected item 🙂

**Review by bramkragten — APPROVED** [review]

**Pull request merged**
