### PR TITLE
add preload stream to exoplayer

### PR DESCRIPTION
**Pull request by uvjustin**
## Proposed change

When Exoplayer is used to play HLS on Android, the preload_stream checkbox is drawn over by exoplayer. One solution is to add a native android checkbox on top of the Exoplayer view and send/receive the checkbox data to the frontend. This PR adds an interface to the frontend to send/receive preload_stream information from the Android client when Exoplayer is active.
I'm pretty sure this is NOT how we want to implement this, particularly on the android -> frontend side. I couldn't find any external messaging scaffolding that supported a mobile app -> frontend message, so I used a hack which sets a listener via the ExternalMessaging.commands object. @balloob I would appreciate some input as to how to do this properly (maybe extend external_messaging)?
BTW this was working for me but I haven't had a chance to rebuild and test it after a quick refactor to move the code from ha-camera-stream.ts to ha-hls-player.ts. I made corresponding changes on the Android app side and can create a PR there too if needed, but I think looking at this gives the idea of how it's supposed to work (sending the preload_stream field back and forth).

## Type of change

- [ ] Dependency upgrade
- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes #
- This PR is related to issue:
- Link to documentation pull request:

## Checklist

- [ ] The code change is tested and works locally.
- [ ] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

**Comment by balloob** [comment]
This is why we can't have nice things :) 

We should avoid drawing this checkbox over the video in Android, as it means we are coupling Android and HA releases for UI elements which is a bad idea. 

I suggest we move preload stream to the toolbar or entity settings. What do you think @bramkragten ?

**Comment by bramkragten** [comment]
I never liked that button there anyway 😄 

I would say the toolbar is a nice place, we just don't have an API to do that right now

**Comment by uvjustin** [comment]
Sounds good guys, I'll shelve this then. Sorry for causing all this trouble. I'm just worried about people complaining when 0.115 drops and the Android exoplayer folks start complaining about the missing button

**Comment by Debugga-nb** [comment]
Is this still shelved?

**Pull request closed without merging**
