### PR TITLE
Fix support for alternate-audio and subtitles for hls

### LINKED ISSUE #16972: Media Browser: HLS stream does not support alternate-audio
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When trying to render a m3u8 file via the Home Assistant media browser, the browser properly extracts and play the video part of the HLS stream, but not the audio part nor the subtitles when they are not part of the same stream than the video but proposed as alternate-audio as described in HLS RFC: https://datatracker.ietf.org/doc/html/rfc8216#section-4.3.4.2

### Describe the behavior you expected

The audio part and the subtiltles are available when playing the stream.

### Steps to reproduce the issue

The streaming is issued from a local TV box (Freebox) so it cannot be accessed from outside, so it will be hard to reproduce from somewhere else than on my LAN.

Still, the m3u8 is the following:

> #EXTM3U
#EXT-X-VERSION:4
#EXT-X-MEDIA:TYPE=SUBTITLES,GROUP-ID="subs",LANGUAGE="fra",NAME="Fran\xc3\xa7ais malentendant",URI="/stream/76/sub_2184.m3u8",AUTOSELECT=YES
#EXT-X-MEDIA:TYPE=SUBTITLES,GROUP-ID="subs",LANGUAGE="fra",NAME="Fran\xc3\xa7ais",URI="/stream/76/sub_2185.m3u8",AUTOSELECT=YES
#EXT-X-MEDIA:TYPE=AUDIO,GROUP-ID="audio",LANGUAGE="fra",NAME="Fran\xc3\xa7ais",URI="/stream/76/es_230.m3u8",AUTOSELECT=YES,DEFAULT=YES
#EXT-X-MEDIA:TYPE=AUDIO,GROUP-ID="audio",LANGUAGE="qad",NAME="Audio Description",URI="/stream/76/es_231.m3u8",AUTOSELECT=YES
#EXT-X-MEDIA:TYPE=AUDIO,GROUP-ID="audio",LANGUAGE="qaa",NAME="Version Originale",URI="/stream/76/es_232.m3u8",AUTOSELECT=YES
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=6500000,AUDIO="audio",SUBTITLES="subs"
/stream/76/es_220.m3u8

### What version of Home Assistant Core has the issue?

2023.7.0.dev20230617

### What was the last working version of Home Assistant Core?

never

### In which browser are you experiencing the issue with?

Firefox 114

### Which operating system are you using to run this browser?

Windows 10

### State of relevant entities

_No response_

### Problem-relevant frontend configuration

_No response_

### Javascript errors shown in your browser console/inspector

```txt
There are no errors, the audio and subtitles are simply fully discarded
```

### Additional information

The problem is due to the partial use of hls.js in class ha-hls-player.ts, in 2 different places:

1. use of 'light' hls.js:
https://github.com/home-assistant/frontend/blob/7c15a65bba8a9dc1c9406a2026cd466a8a03a1ee/src/components/ha-hls-player.ts#L112
The use of the 'light' version simply disable the support of alternate-audio as per hls.js documentation:
[**NOTE:** `hls.light.*.js` dist files do not include alternate-audio, subtitles, CMCD, EME (DRM), or Variable Substitution support. In addition, the following types are not available in the light build:](https://github.com/video-dev/hls.js/blob/35cf55a8748aa9cfc062803cf9ecbdfbc5d65904/README.md?plain=1#L195)
This should be replaced by  `const Hls: typeof HlsType = (await import("hls.js/dist/hls.mjs"))`

2. Manual playlist extraction from master playlist:
A manual extraction of the video playlist from the master playlist is done here:
https://github.com/home-assistant/frontend/blob/7c15a65bba8a9dc1c9406a2026cd466a8a03a1ee/src/components/ha-hls-player.ts#L141
This extracted stream playlist 'playlist_url' contains only the video in such case, and it is the stream given to hls here:
https://github.com/home-assistant/frontend/blob/7c15a65bba8a9dc1c9406a2026cd466a8a03a1ee/src/components/ha-hls-player.ts#L162
This should be replaced by the full master playlist, that is to say `this.url`, so that hls could properly extract everything.

Please note I validated those changes as working locally for my case, and that it did not break my camera stream that is using m3u8 generated by the stream component, but I do not know why those choices (that looks like optimizations to avoid double call) were done initially. A way to keep old behavior would be to check for existence of alternate media tags '#EXT-X-MEDIA' and go for full hls and master playlist url only in such case.

### PR DESCRIPTION
**Pull request by NicoIIT**
## Proposed change

Fix the HLS wrapping implementation in order to support the HLS standard 'alternate-audio' and subtitles feature.
There is currently an optimization in the software that prevent this feature to work:

- The 'light' version of hls.js is used and this one does not support 'alternate-audio' as per [documentation](https://github.com/video-dev/hls.js/blob/35cf55a8748aa9cfc062803cf9ecbdfbc5d65904/README.md?plain=1#L195)
- The optimization consisting in reading the master playlist only once in case it contains only a basic playlist needs to be corrected to also consider the case of 'alternate-audio' (tag #EXT-X-MEDIA used).

## Type of change

- [ ] Dependency upgrade
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes #16972

## Checklist

- [x] The code change is tested and works locally.
- [x] There is no commented out code in this PR.
- [x] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

**Comment by bramkragten** [comment]
What is your usecase for this? I can’t imagine cameras having subtitles or alternate audio tracks?

**Comment by bramkragten** [comment]
If this is just for the media browser, we should split this, so we don't load unneeded stuff for the main use case, displaying camera feeds.

**Comment by NicoIIT** [comment]
Indeed this is only useful for the media browser and is of no use for the camera. I can see 3 ways to avoid impacting camera feeds performances:

1. Move the pre processing of the master playlist before the import of the Hls module, and then import the relevant one based on the result. The preprocessing could be isolated in a function that would compute private attributes '_hevcCodecUsed', '_needFullHls' and '_playlist_url'. 
This will only impact the performance of the basic Error Cases which I think is acceptable. 
3. Carry an indicator as it was done [here](https://github.com/home-assistant/frontend/pull/6974) to only perform this in case of call from 'hui-dialog-web-browser-play-media.ts'. 
4. Split into 2 modules, with a base inheritance. A bit overkill maybe :)

Let me know what you think would be the best!

**Comment by bramkragten** [comment]
Option 1 sounds best to me flexibility wise, but as we will start loading HLS later (we now load the playlist and HLS in parallel, it would be in sync then) it will impact general performance.

The case of exoplayer would be improved though as it wouldn't have to import HLS? (That could already be done today I guess? Does exoplayer need HLS or HLS support checks?)

Option 2 would make sure we don't hurt performance of camera feeds at all.

@uvjustin any opinion?

**Comment by uvjustin** [comment]
> Option 1 sounds best to me flexibility wise, but as we will start loading HLS later (we now load the playlist and HLS in parallel, it would be in sync then) it will impact general performance.
> 
> The case of exoplayer would be improved though as it wouldn't have to import HLS? (That could already be done today I guess? Does exoplayer need HLS or HLS support checks?)
> 
> Option 2 would make sure we don't hurt performance of camera feeds at all.
> 
> @uvjustin any opinion?

I agree with your analysis, option 1 makes sense, but there will be a slight performance hit. (Re: exoplayer, yes, I don't believe it needs to import hls. BTW, we may be able to remove the whole exoplayer workaround as H.265 support is better now as Google seems to have changed its tune on the codec. Need to check whether the support in Chrome also extends to Webview. Also there was an issue with hls.js HEVC codec parsing that I had an upstream PR to fix...will follow up on that.)
I'm ok with option 2 too. Option 3 does seem like overkill :-)

**Pull request closed without merging**
