### PR TITLE
Fixes issues with translation strings containing < >

### PR DESCRIPTION
**Pull request by ludeeus**
## Proposed change

Fixes an issue where the translation would cause the UI to halt, and exit current config flow.
Latest example was the Owntracks integration with German language selected.

Doing that currently results in this:

> Expected "#", "'", "\n", "{", argumentElement, double apostrophes, end of input, or tagElement but "<" found.

## Type of change

- [ ] Dependency upgrade
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes #
- This PR is related to issue:
- Link to documentation pull request:

## Checklist

- [x] The code change is tested and works locally.
- [x] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

**Comment by bramkragten** [comment]
The download script only handles the frontend translations, not the backend translations. We should probably do this during build.

**Comment by ludeeus** [comment]
Right! :facepalm:

**Comment by bramkragten** [comment]
@ludeeus don't you forget about this one?

**Comment by ludeeus** [comment]
Let's close it until we have something better.

**Pull request closed without merging**
