### PR TITLE
Added state as a selectable option in the ui for the statistics graph.

### PR DESCRIPTION
**Pull request by Roeland54**
## Proposed change

Added state as a selectable option in the ui for the statistics graph.

## Type of change

- [ ] Dependency upgrade
- [ ] Bugfix (non-breaking change which fixes an issue)
- [x ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes #
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [x] The code change is tested and works locally.
- [x] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

**Comment by homeassistant** [comment]
Hi @Roeland54, 

It seems you haven't yet signed a CLA. Please do so [here](https://home-assistant.io/developers/cla_sign_start/?pr=home-assistant&#x2F;frontend#12981).

Once you do that we will be able to review and accept this pull request.

Thanks!

**Comment by bramkragten** [comment]
What is the use case for showing state?

**Comment by Roeland54** [comment]
I use this to visualize my utility meter as bar chart:
image

**Comment by Roeland54** [comment]
I agree on the fact it would introduce confusion. And the my use case is indeed more of a workaround to get the graph I want.
If you select a different time period then the period of the utility meter it does not make any sense anymore.

I think the proper way to do it would be to adjust the statistics graph card to be able to show the delta of the sum. Just like the energy-solar-card does. This would also drop the need for a utility meter helper because the statistics of the sensor itself could be used. If you would find this type of change useful I could try to take a stab at it.

**Comment by Roeland54** [comment]
Is included by https://github.com/home-assistant/frontend/pull/13837

**Pull request closed without merging**
