### PR TITLE
Use primary color for filter badge color

### LINKED ISSUE #20259: Colour of applied filters
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

In the 2024.04b1 I notice that the certain filters are applied by default (this is ok), and we can add additional filters as per our needs.

But what took me by surprise was that the applied filter counts were in orange, I immediately went to see what the problem was. Typically orange or red in HA denotes something that you need to action (ie errors, updates, etc). But then I found that these will always be showing up in orange as there is always something filtered by default.

image

### Describe the behavior you expected

As the application of filters is the normal and default state, I would assume that these should be shown in grey, white, etc. Basically a color that shows that this is normal, but ensures that you are aware that a filter is applied and how many.

### Steps to reproduce the issue

1.
2.
3.
...

### What version of Home Assistant Core has the issue?

2024.04b1

### What was the last working version of Home Assistant Core?

_No response_

### In which browser are you experiencing the issue with?

Chrome

### Which operating system are you using to run this browser?

Windows 10

### State of relevant entities

_No response_

### Problem-relevant frontend configuration

_No response_

### Javascript errors shown in your browser console/inspector

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by piitaya**
## Proposed change

CleanShot 2024-03-29 at 10 31 04

CleanShot 2024-03-29 at 10 30 59

## Type of change

- [ ] Dependency upgrade
- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes https://github.com/home-assistant/frontend/issues/20259
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [ ] The code change is tested and works locally.
- [ ] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

**Comment by frenck** [comment]
I like this a lot better, indeed, this ain't a warning :)

**Comment by matthiasdebaat** [comment]
I agree

**Review by frenck — APPROVED** [review]
Thanks, @piitaya 👍 

../Frenck

**Comment by Madelena** [comment]
Yeah, given that we only have Primary and Accent, Primary is better because it's less distracting. In M3 I'd have picked the Secondary or Tertiary color.

**Pull request merged**
