### PR TITLE
Wrap dict attributes

### LINKED ISSUE #17932: more-info: displaying "dictionary" attributes is broken
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Consider a sensor:
```
template:
  - sensor:
      - name: test_long_attr
        state: ok
        attributes:
          dict_attr: >-
            {% set LONG_VALUE_1 = "xxx" %}
            {% set LONG_VALUE_2 = "yyy" %}
            {%- set DICT = {
              'value_1': LONG_VALUE_1,
              'value_2': LONG_VALUE_2
              } -%}
            {{DICT}}
```
which has a "dictionary" attribute:
изображение

This is how it is displayed in more-info:

изображение

**So far it is OK.**

Now consider a similar sensor with a LONGER values:
```
template:
  - sensor:
      - name: test_long_attr
        state: ok
        attributes:
          dict_attr_long: >-
            {% set LONG_VALUE_1 = "Morocco lies close to the Azores–Gibraltar Transform Fault." %}
            {% set LONG_VALUE_2 = "Morocco lies close to the Azores–Gibraltar Transform Fault." %}
            {%- set DICT = {
              'value_1': LONG_VALUE_1,
              'value_2': LONG_VALUE_2
              } -%}
            {{DICT}}
```
изображение

But here more-info is corrupted:

изображение

Recently - at least in 2023.7 (or .8) it was OK.
Seems that this was broken in some of recent releases.

### Describe the behavior you expected

All info is fit in a window.

### Steps to reproduce the issue

as above

### What version of Home Assistant Core has the issue?

2023.9.2

### What was the last working version of Home Assistant Core?

_No response_

### In which browser are you experiencing the issue with?

Chrome 117.0.5938.63

### Which operating system are you using to run this browser?

Win10x64

### State of relevant entities

_No response_

### Problem-relevant frontend configuration

_No response_

### Javascript errors shown in your browser console/inspector

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by joshmcrty**
## Proposed change

This lets the `<pre>` element used for `dict_attr` wrap long text instead of breaking out of its container when viewing sensor attributes, for example, in a more info dialog. Simply wrapping the text will ensure that all of the information is visible, but it could become difficult to read for *very* large blocks of text as seen in https://github.com/home-assistant/frontend/issues/18027.

This also removes the default margins on the `<pre>` element to be consistent with how other attribute values are displayed.

A couple of other ways to fix this could be to use `text-overflow: ellipsis` and either `overflow: hidden` or `overflow-x: auto`, or even offer some kind of "view more" button that pops up a separate, larger dialog with just that text to give it more room to be viewed.

Before:
Screenshot 2023-10-19 at 12 08 22 PM

After:
Screenshot 2023-10-19 at 12 40 58 PM

With `text-overflow: ellipsis` and `overflow-x: auto`:
Screenshot 2023-10-19 at 12 41 26 PM

## Type of change

- [ ] Dependency upgrade
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

This is borrowed from the issue linked below

```yaml
template:
  - sensor:
      - name: test_long_attr
        state: ok
        attributes:
          dict_attr_long: >-
            {% set LONG_VALUE_1 = "Morocco lies close to the Azores–Gibraltar Transform Fault." %}
            {% set LONG_VALUE_2 = "Morocco lies close to the Azores–Gibraltar Transform Fault." %}
            {%- set DICT = {
              'value_1': LONG_VALUE_1,
              'value_2': LONG_VALUE_2
              } -%}
            {{DICT}}
```

## Additional information

- This PR fixes or closes issue: fixes https://github.com/home-assistant/frontend/issues/17932
- This PR is related to issue or discussion: https://github.com/home-assistant/frontend/issues/18027
- Link to documentation pull request:

## Checklist

- [x] The code change is tested and works locally.
- [x] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

### CODE REVIEW

**Review by bramkragten — APPROVED** [review]

**Comment by ildar170975** [comment]
@joshmcrty 
Thank you for the fix!
But can you fix a font too?
https://github.com/home-assistant/frontend/issues/17932#issuecomment-1801281736

**Comment by Mariusthvdb** [comment]
tbh, I am no sure whether it is the fact we have a longer attribute, or we have an attribute in a dictionary . If the former, we might need to open a dedicated issue for this font issue?

**Comment by ildar170975** [comment]
> longer attribute

For this case it does not show a monospace font.



> dedicated issue

I'll probably open a PR - if the author of the latest change will not do it himself.

**Comment by ildar170975** [comment]
@joshmcrty 
I wonder why these styles for `pre` was not used in `ha-attributes-value` ?
https://github.com/home-assistant/frontend/blob/a5e5efa5263de790f4624a581f71d6db35eefa65/src/components/ha-attributes.ts#L128
```
        pre {
          font-family: inherit;
          font-size: inherit;
          margin: 0px;
          overflow-wrap: break-word;
          white-space: pre-line;
        }
```
These attributes give both a correct font & a wrapping.

**Comment by joshmcrty** [comment]
@ildar170975 thanks for looking into this further. I'm guessing that when `ha-attributes-value` was created in https://github.com/home-assistant/frontend/pull/17249 the `pre` styles were left behind in `ha-attributes`. I created this PR while only focused on the wrapping issue. I wasn't aware that it had previously also matched the standard font. I thought the monospace font was intentional. I can create another PR that moves all of the prior styles to the correct location. I don't think the `pre` styles are needed anymore in `ha-attributes`.

**Comment by ildar170975** [comment]
> I don't think the `pre` styles are needed anymore in `ha-attributes`

I also wondered what that `pre` code is doing in `ha-attributes`...
So, shall we simply add SAME code to the `ha-attributes-value`:
```
          font-family: inherit;
          font-size: inherit;
          margin: 0px;
          overflow-wrap: break-word;
          white-space: pre-line;
```
even may be instead of the code added by you?
I made a quick test - just opened Code Inspector in Chrome & then added those styles to the `pre` element, and (as said it before) this gave both a correct font & a wrapping.

**Pull request merged**
