### PR TITLE
🔥 remove more-info-updater

### PR DESCRIPTION
**Pull request by iantrich**
binary_sensor.updater uses the default more-info dialog. This looks to not be used or I'm missing something.

### CODE REVIEW

**Comment by bramkragten** [comment]
Did this ever work? It looks at the domain but the domain is not `updater` but `binary_sensor` we could also fix this in `state_more_info_type` ?

**Comment by ludeeus** [comment]
It used to work, when it was named `updater.updater`

**Comment by iantrich** [comment]
Not sure if it is worth to "fix" this 🤷‍♂ really just adds a link instead of text for the link

**Comment by bramkragten** [comment]
> It used to work, when it was named `updater.updater`

Ah, the domain changed? That explains it...

**Comment by iantrich** [comment]
So, remove it, right?

**Pull request merged**
