### PR TITLE
Media Player Card: Add Volume Control + More

### PR DESCRIPTION
**Pull request by zsarnett**
## Proposed change

- Adds Volume Controls to Media Card - Same Logic from Media Entity Row
- Reduces the padding in the card - This aligns more with the Spotify player on Android
- Make controls always visible - This is introduced to make the card more useful when viewed on smaller screens in Horizontal Stacks
- Moves a lot of logic for Styles into CSS variables - This makes the style of the card much easier to understand and maintain
- Reorganizes the CSS to make more sense with the flow of the HTML - Easier to Maintain

image

## Type of change

- Dependency upgrade
- Bugfix (non-breaking change which fixes an issue)
- [x] New feature (thank you!)
- Breaking change (fix/feature causing existing functionality to break)
- [x] Code quality improvements to existing code or addition of tests

## Additional information

- This PR fixes or closes issue: fixes #
- This PR is related to issue: 
- Link to documentation pull request: 

## Checklist

- [x] The code change is tested and works locally.
- [x] There is no commented out code in this PR.
- [x] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

**Comment by zsarnett** [comment]
### Width 350px:
image

### Width 299px:
image

### Width 249px:
image


### Width 200px:
image

**Comment by bramkragten** [comment]
I like it, just don't like the volume slider on top of the artwork.

Crazy idea: can we do it vertically instead of horizontal? Or make it popup when you press the volume icon?

**Comment by zsarnett** [comment]
Yea I looked into that... Seemed more complicated than it was worth. I think there is a repo that take the material elements and does this like a slider or something. I was more afraid of the way it would handle on mobile and with our card being so small and not overlaying onto other cards

**Comment by zsarnett** [comment]
Also, if we do the only show when you click the volume icon it would differ from the experience you get when using in an entity row

**Comment by bramkragten** [comment]
True, but this really takes away the clean look of media player card...

**Comment by iantrich** [comment]
What about showing it when you click the volume icon and then slowly fading it back out after being used?

**Comment by zsarnett** [comment]
Thats what I was saying would be a different UX than with the entity row

Clicking the entity row icon mutes

**Comment by zsarnett** [comment]
Vertical Slider is not fun :)

https://github.com/StartPolymer/s-slider

IS the closest I can find but I don't know how to implement it and building it is very daunting.

**Comment by bramkragten** [comment]
OK, can we move it under the play control buttons?

**Comment by zsarnett** [comment]
image

Not sure if this is the design we want either

**Comment by Molodax** [comment]
Would you consider to bring back a power button on player while playing. Previously it was possible to turn off TV in one click but not now.

**Comment by zsarnett** [comment]
I want to pick this feature back up even if I just completely redo it. Vertical seems out of scope as it would be a very hacky solution unless someone wants to take a stab at it. But we use the mwc slider or at least the polymer version and wouldn't want to use a different version just for this.

Do we like the under the play/skip controls or to the right?

**Pull request closed without merging**
