### PR TITLE
Reduce circular slider sensitivity when used in card

### PR DESCRIPTION
**Pull request by piitaya**
## Proposed change

Reduce circular slider sensitivity for thermostat card and humidifier card.

## Type of change

- [ ] Dependency upgrade
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes #
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [ ] The code change is tested and works locally.
- [ ] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

**Comment by bramkragten** [comment]
Shouldnt we maybe increase the threshold of the hammer recognizer?

**Comment by piitaya** [comment]
I'm not sure because it's a circular slider so all direction are checked...

**Comment by piitaya** [comment]
One other thing we can do is it to limit the starting zone to the target circle instead of the full slider. But it will change the UX for interaction...

**Comment by bramkragten** [comment]
What would be the change in UX in that case?

**Comment by piitaya** [comment]
If we make the dot only draggable, it will be different between card and more info (and compared to other slider too)

**Review by bramkragten — APPROVED** [review]

**Pull request merged**
