### PR TITLE
codemirror height to 100%

### LINKED ISSUE #2723: CodeMirror Height does not scale to card height
**Home Assistant release with the issue:**
0.87.1

**Browser and Operating System:**
Chrome
Ubuntu 18.10 Linux

**Description of problem:**

The `.CodeMirror` class seems to always be 300px even though it should be set to `100%` 

**Additional information:**

image

image

### PR DESCRIPTION
**Pull request by iantrich**
fixes https://github.com/home-assistant/home-assistant-polymer/issues/2723

### CODE REVIEW

**Comment by bramkragten** [comment]
Does this work? In my tests it didn't work good.

**Comment by bramkragten** [comment]
Seems like it is now just as long as the code that is in it, and that messes with the dialog.

**Comment by timmo001** [comment]
I think there is a CSS `fit-content` / `max-content` which may work better. The CSS may need tweaking elsewhere to stop the dialogue from scaling beyond the bounds of the page which I'm not sure if it does or not

**Comment by bramkragten** [comment]
https://github.com/home-assistant/home-assistant-polymer/pull/2737

**Pull request closed without merging**
