### PR TITLE
Change color of state-badge icon according to rgb or brightness

### PR DESCRIPTION
**Pull request by andrey-git**
Change color of state-badge icon according to rgb or brightness.

Now icon color will respect `rgb_color` attribute regardless of domain.
In case `brightness` attribute exists it will be used as weight to select color between "off" color and "on" color. This will work correctly even if those colored has been themed to something else.

### CODE REVIEW

**Review by balloob — APPROVED** [review]

**Comment by raccettura** [comment]
Is it possible to extend this slightly to be able to change color based on state? Would be nice if for example open windows could be set to a custom color for increased visibility.

**Comment by andrey-git** [comment]
@raccettura you can do so with custom UI once this PR is released in 0.55

**Comment by raccettura** [comment]
Oh that's interesting. Some documentation would be good then. I know from searching myself this seems to be a frequently requested feature. This totally falls into the new feature category.

**Comment by andrey-git** [comment]
Using https://github.com/andrey-git/home-assistant-custom-ui#template-attributes you will be able to conditionally set `rgb_color` \ `icon` of your windows.

**Pull request merged**
