### PR TITLE
Avoid error in map-card

### PR DESCRIPTION
**Pull request by thomasloven**
## Proposed change

We shouldn't assume setConfig succeeds before the card is attached.

## Type of change

- [ ] Dependency upgrade
- [X] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes #
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [ ] The code change is tested and works locally.
- [ ] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

**Comment by bramkragten** [comment]
We need more changes here, as we only update the map after that when the config is changed, the map loaded and the old config was nog undefined. A lot of things that can go wrong.

**Comment by bramkragten** [comment]
It assumes `loadMap` handles the first update of config

**Comment by Mariusthvdb** [comment]
since I am the author of the issue Thomas refers to: thanks for having a look at this. 
not using dark mode or light mode myself, I never realized the error originated here. And I believed to to be the Map card configuration variable [dark_mode](https://www.home-assistant.io/lovelace/map/#dark_mode).

Other than this PR, can we prevent this error, by adapting anything in the themes we do use?

**Comment by thomasloven** [comment]
No. The only thing this has to do with the themes is that the variable in question happens to be about that. Otherwise it's unrelated to the underlying issue.

But the more I look at this, the less I understand how it can ever be a problem at all...

**Comment by Mariusthvdb** [comment]
ok, thanks. do remember we saw the error on `hours_to_show` also (though that hasn't been spotted for some time now) on the same Map card config.

**Review by bramkragten — APPROVED** [review]

**Comment by bramkragten** [comment]
I don't think this is still relevant right? 🤔

**Comment by Mariusthvdb** [comment]
> I don't think this is still relevant right? 🤔

haven't seen the errors for some time now. (slight disclaimer: they didnt happen all the time...)

**Pull request closed without merging**
