### PR TITLE
Add frost guard mode switch

### PR DESCRIPTION
**Pull request by cgtobi**
## Description:

This pull request contains changes to add the frost guard mode switch to the Netatmo Thermostat component.

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) with documentation (if applicable):** home-assistant/home-assistant/pull/7754

### CODE REVIEW

**Comment by justweb1** [comment]
Is there a backed PR to accompany this? If so, please link it.

**Comment by cgtobi** [comment]
Sorry, I just thought about it the moment you commented.
This is related to https://github.com/home-assistant/home-assistant/pull/7754.

**Comment by balloob** [comment]
We will not merge this as the new service and attribute are only going to be part of the netatmo platform for now. If in the future more devices have this feature we can consider generalizing it.

**Comment by cgtobi** [comment]
Could you please point me to where this has to be implement?

**Comment by justweb1** [comment]
Github.com/netatmo

**Comment by balloob** [comment]
At this point in time we should not add support to this to the Home Assistant UI. When implemented as a service you will still be able to control it from the UI using an input_boolean and a script to call the right service.

**Comment by cgtobi** [comment]
Ok, thanks for taking the time.

**Pull request closed without merging**
