### PR TITLE
WIP: New list style editor options

### PR DESCRIPTION
**Pull request by iantrich**
21A21631-AD3C-4FFE-861E-1AF0354D33B3
D99E288D-847F-47BA-A985-D9F0A73BB020

Quickly threw this together tonight, didn't really refine anything, just looking for high-level feedback on if this general style is better suited for our UI; obviously lots of cleanup/styling needed and the action editor is not quite working

image
image
image

### CODE REVIEW

**Comment by iantrich** [comment]
Add headings
image

**Comment by bramkragten** [comment]
I think tabs would work better. I would like this kind of layout for the stack editors.

**Comment by iantrich** [comment]
Tabs would only work for one level, though

**Comment by bramkragten** [comment]
Well you could have tabs in tabs (don't do that). But we should make sure all basic settings are on the first screen. Mostly that is just the entity.

For actions on the actions screen I would say something like <https://material.angular.io/components/expansion/overview>

**Comment by iantrich** [comment]
@bramkragten how would that work with things that need to be drilled down even further like stacks? you'd need to have a card editor inside your card editor which would then have its own set of tabs. And those cards can have stacks within them, and so forth. I don't think the tabs approach would scale for that, but maybe we could get around that. I'm not sure.

I also feel like the list allows to be more clear about the options within especially once you add secondary text to the item. A tab's title needs to be pretty short to look decent. The one benefit I see in tabs is as you stated, being shown the basic settings by default. Perhaps we have a middle-ground with "Basic" and "Advanced" tabs and display the options in a list within those?

**Comment by bramkragten** [comment]
Stacks won't use tabs. A single card uses tabs.
The stack editor will just allow you to select a card/create a card and load a editor for that individual card with a back button.

The advanced stuff should not be on the first page when you open the editor, it should be further back (is a tab?) and only shown in advanced mode.

**Comment by iantrich** [comment]
:+1: I agree with that approach for stacks

You should still have an indication that advanced options exist even if the user is not in advanced mode and directions on how to activate advanced mode and/or a link to enable it.

**Comment by iantrich** [comment]
What's the threshold for advanced? I'm having a hard time visualizing where that line is. Anything beyond the required fields?

**Comment by SeanPM5** [comment]
I like some aspects of this. Think it would work very well for the actions part. Would be nice for stacks as mentioned. And the experience seems like it'd be nicer on mobile since the fields aren't crammed side-by-side.

Added a bit more styling to the initial list - icons and descriptive text "previewing" what's inside. I also renamed Display Options to Appearance which I think is a bit nicer. Could probably come up with a better/more simple name for Entity Options too?
styling

But I'm a little iffy on the idea of splitting things up to such a degree. Particularly with name/card title being made more inconvenient. I think that's used the vast majority of the time, and now it would have reduced visibility and require extra clicks.

Just because something is an optional field doesn't necessarily mean it should be hidden. If your email client only showed the "Recipient" field and had Subject and Body fields moved elsewhere because they were _technically_ optional, we'd all think that was stupid and inconvenient. UI's should be optimized for how people actually use things.

**Comment by iantrich** [comment]
@SeanPM5 yeah, I'm not really on board with the idea of basic vs advanced options. It just produces hurdles for users. In the end, if a user is presented with an option in our editor that is deemed confusing, we just haven't don't a good job explaining it or presenting it to them.

**Comment by bramkragten** [comment]
Let's start with tabs like we have for views, and see from there how we can clean it up and make ik logical, and what we need.

**Comment by bramkragten** [comment]
So that would be an entity, action, display tab. In the action tab we might be able to use this.

**Comment by iantrich** [comment]
I'm not a fan of the tab proposal, mostly because you can't help regular users understand the tabs at first glance. A list with the secondary text, which @SeanPM5 did a great job showcasing, allows us to concisely explain each area of options so a user is not clicking through all of them to find the actual option they want to change. 

An additional thought I had is that required fields should be above the list or their own line item. Don't want users sifting through options to find something they missed either.

**Comment by iantrich** [comment]
> can't see the most important options when you enter the editor.

Does `important` equate to `required`?

You could have the editor open showing the required options with a back button to bring you to the full list of options

**Comment by iantrich** [comment]
Regardless, I don't see any benefit in separating things into tabs. My idea was that more context helps the users, not necessarily the actual separation. The separation was just a byproduct to more easily allow a user to get to option they were interested in rather than scrolling through a long list of individual options. I would take the long list of individual options over tab separation.

**Comment by SeanPM5** [comment]
IMO both tabs and lists would overly complicate things. I like the goal behind those ideas more than the execution. 

I think it's possible to accomplish the same goals using the existing design. Just need to make the UI a little more contextual so it's not overwhelming the user by showing _every_ single option all at once. 

As an example, there's no reason to show the name, icon, theme options before the user has even selected an Entity. So initial card editor view could be very simple, just an Entity picker (the one required field in most cards). The preview on the right could show instructions like "Select an entity to begin" rather than the error it does now (as suggested in https://github.com/home-assistant/home-assistant-polymer/issues/3642).

Sensor card shouldn't show `Graph Detail` and `Hours to Show` fields if the Graph Type was `none`.

Entities card editor doesn't need to display the `"Show Header Toggle?"` unless there's 2 or more entities. (Iffy on this one).

Picture Glance and Picture Entity cards could first ask the user whether they want to use an image or a camera entity and then hide a bunch of fields based on that. 

Just a few ideas. There might be some issues with this approach too that I haven't thought of, but I kinda prefer it to list/tabs.

**Comment by iantrich** [comment]
@SeanPM5 yeah, we can do a lot more in terms of being smarter as to what we display and when. Some sort of onboarding when creating a new card makes sense as well but is probably a later phase to tackle.

I'm going to play around with this some more this week. I'm thinking that @bramkragten's earlier idea of exploring the use of expansion panels might be a good compromise and at the very least, as a starting point, using those for the action editor as that is one of the bigger things to take up screen real estate in our editors.

**Comment by iantrich** [comment]
I'm going to continue working on this within the [boilerplate-card](https://github.com/custom-cards/boilerplate-card)

**Pull request closed without merging**
