### PR TITLE
Badges - Show timestamp the same way as timer

### PR DESCRIPTION
**Pull request by surfingbytes**
## Proposed change
Badges currently support timer, where it nicely shows timer's icon and remaining time. This change handles sensor with device_class: timestamp the same way - icon with remaining time. That allows you to display remaining time to next sunrise, or next Alexa timer from Alexa Media Player integration (which is timestamp, not timer).

Before:
image
After:
image

## Type of change

- [ ] Dependency upgrade
- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml
views:
  - path: default_view
    title: Home
    badges:
      - entity: sensor.sun_next_dawn
    cards: []
```

## Additional information

- This PR fixes or closes issue: fixes #
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [x] The code change is tested and works locally.
- [x] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

## Summary by CodeRabbit

- **New Features**
  - Enhanced badge functionality to handle sensor device classes, particularly timestamps. The badge now correctly evaluates and displays state information for timestamp sensors.

### CODE REVIEW

**Comment by surfingbytes** [comment]
@matthiasdebaat could you please check this? Are PR reviewers not automatically assigned?
The screenshot is with next sun dawn, because that's an entity that's always there so I was able to use it. However, better example would be dishwasher finish time.
Thank you

**Comment by piitaya** [comment]
Hi 👋
We are working on a redesign of the badge with the design team : https://github.com/home-assistant/frontend/pull/21401
It will be possible to customize the display state on these badge like the tile card. So I guess we can add an option to choose between absolute or relative for timestamp.

Also, I'm not sure it makes sense for all timestamps. For moon and sun, the date is always less than 1 day but for some others it can be many days.

**Comment by surfingbytes** [comment]
Hi @piitaya , thanks for the info. The new badges looks cool. However, as they look completely different from the current ones, could the current ones be renamed to, let's say, alerts? That way thy could be uses in parallel to the new ones. Tbh, with the red circle, they even look like alerts, and I'm using them as such - to show plants that need watering, batteries that needs replacing, running timers etc. It would also be great if they can be used as cards (=anywhere on dashboard, not just on top).

Anyway, whether you decide to completely replace current badges with the new ones, or have them side by side (under different names of course), it can take anywhere between 6 months to infinity :) And in that case, would it be possible to approve this PR, so we have at least something until the new badges arrive? This PR really does change it to better, looking at the before/after screenshots.

**Comment by bramkragten** [comment]
We decided not to keep the old badges around and replace them fully. We are open to adding other types of badges, but they will have to fit in the new design system.

It is also possible to create custom badges to keep using the old, or any other, style of badges.

**Pull request closed without merging**
