### PR TITLE
Add HomematicIP Cloud Config Flow picture

### PR DESCRIPTION
**Pull request by worm-ee**
This is the picture for the HomematicIP Config Flow "please press the blue button"
PR: https://github.com/home-assistant/home-assistant/pull/14861

### CODE REVIEW

**Comment by c727** [comment]
can you optimize the file size please? (not sure if we have a how-to anywhere)

**Comment by balloob** [comment]
Yeah, all the transparent stuff around it needs to be trimmed

**Comment by mxworm** [comment]
Hmm, didn't see the single pixel border, sorry.

**Comment by c727** [comment]
Ehm the 2nd version was fine?! now we have this giant file size again.

the `transparent stuff` is a "bug" in the GitHub image preview

**Comment by mxworm** [comment]
Sorry, it was the wrong file. Now it should be fine I checked it with gimp and not the standard Mac crap.

**Review by c727 — APPROVED** [review]

**Comment by balloob** [comment]
Can you add it to a new folder inside images called `config_flows`

**Pull request merged**
