### PR TITLE
Fallback to raw config entry reason if localize returns an empty string

### PR DESCRIPTION
**Pull request by bdraco**
## Proposed change

Show config entry reason if localize returns an empty string

Fixes a regression discussed in https://github.com/home-assistant/frontend/pull/19128#discussion_r1583573736

## Type of change

- [ ] Dependency upgrade
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes #
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [x] The code change is tested and works locally.
- [ ] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

**Comment by bdraco** [comment]
Screenshot 2024-04-29 at 2 14 29 PM

Confirmed working now. 

Side note: its hard for users to discover these now

**Comment by gjohansson-ST** [comment]
I made the comment already in the previous PR that these failure reasons (translated or not) are quite hidden and it's not obvious for any user to hover the icon to see it.

**Comment by bdraco** [comment]
> I made the comment already in the previous PR that these failure reasons (translated or not) are quite hidden and it's not obvious for any user to hover the icon to see it.

I spent way too much time walking a user through how to hover their mouse arrow the other day.  While there was an aha moment, and the problem got solved, it was definitely not very discoverable.

**Review by silamon — APPROVED** [review]

**Comment by silamon** [comment]
The new material lists allow to show up to the three rows in a list item and a variable height. That will give place to solve this properly. But I'm open to other suggestions if you have any.

**Comment by bdraco** [comment]
> The new material lists allow to show up to the three rows in a list item and a variable height. That will give place to solve this properly. But open to other suggestions if you have any. 
> 
> 
> 
> EDIT: I'll see if I can put that into a PR in the coming days. 

That sounds fantastic.  Thank you

**Comment by gjohansson-ST** [comment]
I think that sounds great or perhaps append on failure messages something like " click x to see more details" something something.

**Review by bramkragten — APPROVED** [review]

**Pull request merged**
