### PR TITLE
Add theme variable ha-card-backdrop-filter

### PR DESCRIPTION
**Pull request by noxhirsch**
## Proposed change
This adds the theme variable `ha-card-backdrop-filter` so you can e.g. add blur to the card background if you have a picture as Lovelace background (which many themes have):
image

## Type of change

- [ ] Dependency upgrade
- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml
themes:
  blur_theme:
    ha-card-backdrop-filter: blur(3px)
    ha-card-background: rgba(255,255,255, 0.5)
```

## Additional information

- This PR fixes or closes issue: fixes #
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [x] The code change is tested and works locally.
- [x] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

**Comment by thomasloven** [comment]
Could be worth noting that this property is not supported by default by Firefox.

**Comment by noxhirsch** [comment]
That's right, but since it can be enabled very quickly in Firefox, it would be sad to not implement this variable (although I don't use it myself). 
If there would be a theme var list in the docs, a note could be added there - but since that doesn't exist, I don't know where I should at this hint.

**Review by bramkragten — APPROVED** [review]

**Comment by bramkragten** [comment]
I'm a bit hesitant to add this, not sure what problems this could cause in the future...

**Comment by noxhirsch** [comment]
Is there anything I can (try to) do about it?

**Pull request closed without merging**
