### PR TITLE
Ask for reload on service worker change

### LINKED ISSUE #1292: Prompt user to reload when new frontend detected
On a new release, it's important that the user starts using the new frontend as soon as possible. We should prompt the user to reload when a new one is detected.

https://stackoverflow.com/a/41896649/646416

### PR DESCRIPTION
**Pull request by balloob**
Fixes #1292

### CODE REVIEW

**Review by andrey-git — APPROVED** [review]
Is the alert intended to block the reload until dismissed?

**Comment by c727** [comment]
I don't like the alert: In case a user runs the frontend on wallmounted displays he has to confirm it on every device. Maybe we remove it or use something not blocking like a toast notification

**Comment by balloob** [comment]
So yeah, the alert will have to be clicked away before we reload. I will remove it. Let me explain how the process is, and how neither option is ideal:

- user navigates to frontend of Home Assistant vX and service worker installs. Caching happens as part of the installation.
- user updates backend to Home Assistant vX+1
- user navigates to frontend, receives vX frontend from service worker. This frontend will register the service worker of vX+1, which will installs in the background. This takes **Y time**, which could be a while on mobile connections as it's roughly 1.2MB. As part of the installation of the new service worker, we clear the no longer used cache of frontend vX. We do code splitting and thus the currently loaded frontend of vX will no longer be able to load panels or other code on demand.

So we don't have to worry for long running instances, as they won't refresh the page. If you're on mobile, a sudden refresh if you're trying to turn on your lights would suck. However, navigating to a panel or noticing that parts of the frontend no longer work, would suck too…

**Comment by balloob** [comment]
Actually, I read some more. It only clears the old cache when activating the new service worker. So if we just make sure that we don't claim it, we should be good.

https://developers.google.com/web/tools/workbox/modules/workbox-precaching#how_workbox-precaching_works

**Comment by balloob** [comment]
image

**Comment by balloob** [comment]
Alright, so I went deep and this is what is going on.

Previously, we had "skipWaiting" and "clientsClaim". The problem is, when the new service worker is activated, it's at that moment in time that the old cache will be deleted. So by not doing that, the old frontend will keep working.

But now we have the problem that people need to close ALL tabs for the service worker to be updated and receive the new frontend. Although we shouldn't, we sometimes make breaking changes on the backend between 2 frontend versions. So now the user is stuck and we're going to get confusing bug reports.

So this is where the toast comes in. When a new frontend has been found and installed, but has not been loaded yet, we'll show a toast on ALL open Home Assistant windows . Clicking on reload will refresh ALL open windows. It has to impact all windows because a service worker is shared among them all.

**Pull request merged**
