### PR TITLE
Convert color picker to typescript

### PR DESCRIPTION
**Pull request by piitaya**
## Type of change

- [ ] Dependency upgrade
- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [x] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes #
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [ ] The code change is tested and works locally.
- [ ] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

**Review by steverep — COMMENTED** [review]
Is this operable via keyboard at all?  I don't see anything but mouse and touch events.

**Comment by piitaya** [comment]
I close the PR as we will migrate certainly migrate [iro.js](https://github.com/jaames/iro.js).

**Comment by piitaya** [comment]
@steverep Is there any way to make a 2 dimensional color picker accessible using arrow keys to move the cursor?

Or is it better to use the html color picker in that case or draw 2 sliders instead of a 2-dimensional picker

**Comment by steverep** [comment]
> @steverep Is there any way to make a 2 dimensional color picker accessible using arrow keys to move the cursor?

Yes, it's possible.  For example, the Windows color picker does this and gives screen readers spoken feedback as it moves.  That said, I rarely see it and not strictly necessary as long as there is another accessible way.

> Or is it better to use the html color picker in that case or draw 2 sliders instead of a 2-dimensional picker?

The pickers you get with `<input type="color">` vary wildly across browsers, and honestly are not crazy accessible as of today anyway, so I wouldn't recommend that.  Using sliders is fine, but detracts from the visual accessibility.

The one absolutely essential feature for a11y is to be able to edit the values, preferably in any format.  For example, use a live text field for hex and spinners or sliders for RGB and HSL.

The next a11y feature is to have a textual representation of the picked color.  The old school way is to separate "basic" (a grid of swatches or big combo-box with names) from "custom" (a map with RGB or hex inputs).  The other way is like the Windows picker.

Make sense?

**Comment by piitaya** [comment]
Yep it make sense ! 👍
If the native one isn't accessible, I think we need to add another accessible way (by raw value editing for example) 🙂

**Pull request closed without merging**
