### PR TITLE
Add padding when large class is added

### LINKED ISSUE #3711: Thermostat card doesn't look good when it is small (unneeded padding)
When You add multiple thermostats stacked they have padding and font size problems:
Open official demo (https://demo.home-assistant.io/#/lovelace/0)
add this card:
```
type: vertical-stack
cards:
  - cards:
      - type: thermostat
        entity: climate.upstairs
      - type: thermostat
        entity: climate.upstairs
    type: horizontal-stack
  - cards:
      - type: thermostat
        entity: climate.upstairs
      - type: thermostat
        entity: climate.upstairs
    type: horizontal-stack
```

You will get this look:
image

As you can see icons are cut on the bottom.

ha-card is getting the correct class (`small`), but there is unneeded padding-top for `modes` class. After removing this padding card look much better:
image

My proposition is to remove padding when ha-card has `small` class (or add padding when ha-card has `large` class).

Also please consider changing font size based on container size, as suggested here: https://github.com/home-assistant/ui-schema/issues/221#issuecomment-530862458, because right now `title` and `current-mode` are getting too large.

### PR DESCRIPTION
**Pull request by Misiu**
Fixes https://github.com/home-assistant/home-assistant-polymer/issues/3711

### CODE REVIEW

**Comment by homeassistant** [comment]
Hi @Misiu, 

It seems you haven't yet signed a CLA. Please do so [here](https://home-assistant.io/developers/cla_sign_start/?pr=home-assistant&#x2F;home-assistant-polymer#3729).

Once you do that we will be able to review and accept this pull request.

Thanks!

**Comment by Misiu** [comment]
Test entry:
```
type: vertical-stack
cards:
  - cards:
      - type: thermostat
        entity: climate.upstairs
      - type: thermostat
        entity: climate.upstairs
    type: horizontal-stack
  - cards:
      - type: thermostat
        entity: climate.upstairs
      - type: thermostat
        entity: climate.upstairs
    type: horizontal-stack
```

Before:
ha_before
After:
ha_after

**Comment by bramkragten** [comment]
This also means the modes will be a lot closer to the current mode and the set temperature will drop down. In your specific use case this turns out better, but not in every situation.

Before:
image

After:
image

**Comment by Misiu** [comment]
@bramkragten I agree, I tested this only with my case. What entry did You use? Can You post it here?
I can give this a second look, but I need a week or two to finish my current project (HA related).
Maybe there should be 3 types of size? small, normal and large? this way by default I can align everything in normal state and add modifiers to small and large views.

**Comment by bramkragten** [comment]
We are working on replacing the round slider, let's wait for that and see if this is still a thing.
https://github.com/home-assistant/home-assistant-polymer/pull/3734

**Comment by Misiu** [comment]
@bramkragten sure :) In a future project I'm planning to use 16 thermostats so I want to squish 4 in a single card to save space.
Before I start anything I'd like to have the UI fixed for such a scenario. Then the only thing that will remain is how the generic thermostat works - https://github.com/home-assistant/home-assistant/issues/20154, hopefully, it will be fixed till then 🙂

**Pull request closed without merging**
