### PR TITLE
ability to filter badges based on state

### PR DESCRIPTION
**Pull request by iantrich**
Closes https://github.com/home-assistant/ui-schema/issues/165

### CODE REVIEW

**Comment by iantrich** [comment]
I couldn't think of a better config option than `badges_state_filter` on the view that wouldn't be a breaking change. Open to suggestions.

**Comment by balloob** [comment]
I don't think we should do it like this. 

Can't we make a filter "badge" that wraps a normal badge config? That is how we do it for cards and it prevents us from having extra logic in odd places.

**Comment by iantrich** [comment]
That could allow us to start supporting custom badges as well which would be cool

**Comment by iantrich** [comment]
Going to close this and revisit after entity filter changes merged

**Pull request closed without merging**
