### PR TITLE
Add support for description_html

### PR DESCRIPTION
**Pull request by robbiet480**
See balloob/home-assistant#1662

### CODE REVIEW

**Comment by balloob** [comment]
Did you test this? Because afaik Polymer does not allow rendering innerHTML via attributes.

**Comment by robbiet480** [comment]
@balloob I did test this and it works perfectly. I found the method I used in [this](https://github.com/Polymer/TemplateBinding/issues/57#issuecomment-161710256) Polymer issue comment.

**Comment by balloob** [comment]
- Using the element tag is a hack and only works because of Polymer shady DOM implementation. This will _most likely_ break once Polymer moves to use native web components.
 - This is a major security vulnerability. Anyone that can set a state can now inject HTML. We should not want this.

I do see the need for rendering forms so I suggest we rewrite the configurator to fetch the form contents from the server via an API call. Since the configurator can only be called from Python, an attacker would at least also need to have access to the server it is running on.

Even better would be if we can work around this and use just attributes that hardcode render as something (image, text, button)

**Comment by balloob** [comment]
About the marked-element, we could use that one too for the dismissable notification component. Hmmmmm

**Comment by robbiet480** [comment]
Markdown is what I was also considering but came to the same conclusion as you, let's not bloat with a big MD library

**Comment by balloob** [comment]
I'm going to close this PR. This solution is not the way to go. It will bite us in the foot later.

**Pull request closed without merging**
