### PR TITLE
ADD: [media card] STOP action support

### LINKED ISSUE #4822: media player card not supporting STOP
## The request
The media player card does not support STOP if the backend supports PAUSE.
I'm wondering if it's by design or if a PR would be accepted.

### PR DESCRIPTION
**Pull request by koying**
## Proposed change
Add a "Stop" button to the media card if applicable, i.e. if the underlying integration has SUPPORT_STOP
Sample

## Type of change

- [ ] Dependency upgrade
- [ ] Bugfix (non-breaking change which fixes an issue)
- [X] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Additional information

- This PR fixes or closes issue: fixes #4822
- This PR is related to issue: #4822
- Link to documentation pull request: 

## Checklist

- [X] The code change is tested and works locally.
- [X] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

**Comment by zsarnett** [comment]
I don't know if this is something we want to add to this card. Especially not in that position with the Play Pause Icon having the circle background. I'm not sure the need if you can just Pause the player or turn it off

**Comment by koying** [comment]
As I tried to capture in #4822, what would be the reason *not* to add the "stop" action to the card, considering it's a standard media_player service.

If I take Kodi as an example, you don't shut down the box or even the program because you want to stop the current playback ;)

**Comment by zsarnett** [comment]
Not saying this for all devices but my google home for example. There is no difference between powering off the device and stoping the media.

I turned off the player using the power button. the state goes to Off

I use the notification on my phone to press the Stop Button. The state goes to Off.

Google Home UI also doesn't have a stop button in the application. I personally just don't see it necessary to clutter the Lovelace UI with another Icon. I would see it more necessary in the more info popup

**Comment by koying** [comment]
> Google Home UI also doesn't have a stop button in the application

I guess the Google Home integration should not support STOP, then, if it does.
IMHO, it's not up to the frontend to decide. If an integration says that STOP makes sense for it, than the frontend should reflect it. It's not exactly like a STOP button is exotic when it comes to media player UI....

**Comment by zsarnett** [comment]
For this PR to be merged there needs to be a new design for the card controls. Take away the background of the Play/Pause button and give a screenshot of how it looks. The issue is it **_IS_** up to Lovelace to show what functionality we want. The more info window will be the place where all functionality should live. 

I personally don't think a Stop Button is necessary but I am only one member/contributor 

Write up a good PR for this and we will see where it goes

**Comment by koying** [comment]
Rather than play "trial and error", it would be great if you could provide some mockup of a design that would be agreeable. 
Please keep in mind, when thinking about a new design, that the stop button will only be shown if the integration supports it, 
Thanks.

**Comment by zsarnett** [comment]
As I do not think the Stop is needed I will not be providing the design 😉 

The point was for you to redesign and show the new look and the Maintainers/Members will determine if it is a good change or not. You could create a PR to add the functionality to the More info dialog that I know would get merged 👍

**Comment by koying** [comment]
Ok, maybe a hint about what's bothering you with the current design?
Is it the asymmetricality? It's not like I touched the play/pause button...

**Comment by bramkragten** [comment]
Maybe try moving the stop button to the other side of the next/prev button.

We should also check what the impact is on other media players, I don't know how many reports they support stop now but don't really do something useful with it.

**Comment by zsarnett** [comment]
The new card for media control will not support this and since this is targeting the old code. This PR is no longer relevant. Most used controls will be displayed on cards and more info dialog can be opened to use other controls

**Pull request closed without merging**
