### PR TITLE
Expand calendar to full width (#7474)

### LINKED ISSUE #7474: Calendar panel not taking full width in desktop browser
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

The calendar panel is not taking up the full width of the page in desktop browsers:

It initially displays like this:
image

Then after a second or so, displays like this:
image

## Expected behavior

Calendar should take full width of page
## Steps to reproduce

Open Calendar panel

## Environment

- Home Assistant release with the issue: 0.117.0b3
- Last working Home Assistant release (if known):
- Browser and browser version: Google Chrome 86.0.4240.80
- Operating system: macOS Catalina 10.15.7 (19H2)

## State of relevant entities

```yaml

```

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

### PR DESCRIPTION
**Pull request by Kaivosukeltaja**
## Proposed change

This PR grows the calendar panel to full width as requested in #7474.

## Type of change

- [ ] Dependency upgrade
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes #7474 
- This PR is related to issue:
- Link to documentation pull request:

## Checklist

- [x] The code change is tested and works locally.
- [x] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

**Comment by homeassistant** [comment]
Hello @Kaivosukeltaja,

When attempting to inspect the commits of your pull request for CLA signature status among all authors we encountered commit(s) which were not linked to a GitHub account, thus not allowing us to determine their status(es).

The commits that are missing a linked GitHub account are the following:

- [`f6d6118557229904ba1c20bafa0b495218ea52d0`](https:&#x2F;&#x2F;github.com&#x2F;home-assistant&#x2F;frontend&#x2F;pull&#x2F;7505&#x2F;commits&#x2F;f6d6118557229904ba1c20bafa0b495218ea52d0) - This commit has something that looks like an email address (niko@salminen.me). Maybe try linking that to GitHub?.

Unfortunately, **we are unable to accept this pull request until this situation is corrected.**

Here are your options:

1. If you had an email address set for the commit that simply wasn't linked to your GitHub account you can link that email now and it will retroactively apply to your commits. The simplest way to do this is to click the link to one of the above commits and look for a blue question mark in a blue circle in the top left. Hovering over that bubble will show you what email address you used. Clicking on that button will take you to your email address settings on GitHub. Just add the email address on that page and you're all set. GitHub has more information about this option [in their help center](https://help.github.com/articles/setting-your-email-in-git/#commits-on-github-arent-linking-to-my-account).

2. If you didn't use an email address at all, it was an invalid email, or it's one you can't link to your GitHub, you will need to change the authorship information of the commit and your global Git settings so this doesn't happen again going forward. GitHub provides some great instructions on how to change your authorship information [in their help center](https://help.github.com/articles/setting-your-email-in-git/).
   * If you only made a single commit you should be able to run
      ```
      git commit --amend --author="Author Name <email@address.com>"
      ```
      (substituting Author Name and email@address.com for your actual information) to set the authorship information.
   * If you made more than one commit and the commit with the missing authorship information is not the most recent one you have two options:
       1. You can re-create all commits missing authorship information. This is going to be the easiest solution for developers that aren't extremely confident in their Git and command line skills.
       2. You can use [this script](https://help.github.com/articles/changing-author-info/) that GitHub provides to rewrite history. **Please note:** this should be used only if you are very confident in your abilities and understand its impacts.
   * Whichever method you choose, I will come by to re-check the pull request once you push the fixes to this branch.

We apologize for this inconvenience, especially since it usually bites new contributors to Home Assistant. We hope you understand the need for us to protect ourselves and the great community we all have built legally. The best thing to come out of this is that you only need to fix this once and it benefits the entire Home Assistant and GitHub community.

Thanks, I look forward to checking this PR again soon! :heart:

**Comment by homeassistant** [comment]
Hi @Kaivosukeltaja, 

It seems you haven't yet signed a CLA. Please do so [here](https://home-assistant.io/developers/cla_sign_start/?pr=home-assistant&#x2F;frontend#7505).

Once you do that we will be able to review and accept this pull request.

Thanks!

**Review by zsarnett — DISMISSED** [review]
This only does anything if the user component displays this in a flex div, no?

**Comment by Kaivosukeltaja** [comment]
@zsarnett Yes, if it not inside a `flex` element the `flex-grow` attribute will be ignored.

**Comment by zsarnett** [comment]
Then it should be up to the Parent to set this css on the child

**Comment by Kaivosukeltaja** [comment]
Ok, what would that be? The panel's shadow host was the highest up I could find. Please bear with me, it's my first shot at this project. :)

**Comment by zsarnett** [comment]
So the Full Calendar Element is the base element for the Calendar.

There are two Elements that use this element to display the calendar.

`src\panels\calendar\ha-panel-calendar.ts`

`src\panels\lovelace\cards\hui-calendar-card.ts`

**Comment by Kaivosukeltaja** [comment]
Ah okay, I see that `ha-panel-calendar.ts` already has the style `ha-full-calendar { flex-grow:1; }` - it's just that it's not getting applied to the element for some reason. Can it be because the `ha-app-layout` is adding another shadow DOM around it?

**Comment by zsarnett** [comment]
Seems to be applied in my dev environment?
image

**Comment by zsarnett** [comment]
I think the issue is that the Calendar is not updating the size in the FullCalendar library

What we should do:

in `ha-full-calendar.ts`:

```ts
public updateSize(): void {
  this.calendar?.updateSize();
}
```

in `ha-panel-calendar.ts` and `ha-calendar-card.ts` in the resize observer (for the card) or after the updateComplete() in the panel maybe. I have confirmed this works for the calendar card:

```ts
const cal = this.shadowRoot!.querySelector("ha-full-calendar");
cal?.updateSize();
```

**Comment by zsarnett** [comment]
Calendar Card without the updateSize method:
image

Calendar Card with the updateSize Method:

7ca5209c7c3a8443e9333e481635a1e2

**Comment by zsarnett** [comment]
https://github.com/fullcalendar/fullcalendar/issues/5507

**Comment by Kaivosukeltaja** [comment]
That's odd, that CSS doesn't get applied in my dev environment. I _do_ see it on my actual Home Assistant with the same calendar data which is rather interesting. 
Screenshot 2020-10-28 at 21 26 14

**Comment by zsarnett** [comment]
Are you sure you are running dev and not a branch that may have deleted the code? Either way. I think that the fix isn't CSS related. It's the way that custom element render. They can be 0 width and then full width. This make library that check the width to early get the incorrect width and result in what we see now

**Comment by Kaivosukeltaja** [comment]
Yeah, I'm on `dev` branch and pulled the latest commits from upstream just a while ago to make sure. I tried calling FullCalendar's update after the panel's `updateComplete()` but didn't see any effect - in my understanding because the calendar can't expand if the `ha-full-calendar` around it doesn't use all of its available horizontal space?

**Comment by zsarnett** [comment]
The HA full calendar element does take up the full width but it may not have when the Full-calendar element calculated the size. So we need to tell the `full-calendar` element that the rendering is finished and to resize

**Comment by Kaivosukeltaja** [comment]
I experimentally added this in the panel:
```  
  public updateSize(): void {
    setInterval(() => {
      console.log('Updating size...')
      this.calendar?.updateSize();
    }, 1000)
  }
```

So now it's updating the calendar's size once per second but it's still not doing anything for me.

Screenshot 2020-10-29 at 7 37 14

If I apply the style `ha-full-calendar { flex-grow: 1; }` everything works as it should. I think the problem in #7474 is the same one I'm currently facing and caused by styles not getting applied correctly. I made a production build but the style was missing from that as well.

**Comment by zsarnett** [comment]
Take a look at #7539  I may have fixed it there?

**Comment by Kaivosukeltaja** [comment]
Yes, can confirm that #7539 fixes this - at least in my dev environment! 👍 I'll close this one as that seems like a more solid fix. Thanks for your patience and helping me get started with HA contribution!

**Comment by zsarnett** [comment]
Thanks for the contribution. I didn't mean to take over this fix I just happened to be working on the element when I noticed that there was a ')' missing.

**Pull request closed without merging**
