### PR TITLE
Feature/badge preview

### LINKED ISSUE #3825: Preview for badges on View Configuration UI editor
**Home Assistant release with the issue:**
0.99.3

**Description of problem:**
When adding badges using the "View Configuration" UI editor, a live preview would be very helpful. Users shouldn't be expected to know what a "badge" means, or how it looks and functions.

Most people aren't going to search the documentation (which doesn't help in this particular case anyway), and I suspect that most people probably aren't going to blindly add things either. By including a preview it solves all these problems and more. No confusion.

Here is a mockup:

badge-previews

### PR DESCRIPTION
**Pull request by tomraithel**
Fixes #3825

This PR adds a preview for the **View Configuration** to getter a better visual feedback how the badges would look like.

### CODE REVIEW

**Comment by iantrich** [comment]
Don't think will play nicely with custom badges https://github.com/home-assistant/home-assistant-polymer/pull/3867

**Comment by bramkragten** [comment]
> Don't think will play nicely with custom badges #3867

No, with custom badges comes a new editor. We should take the badges out of the view editor and give it it's own edit dialog per badge just like cards.

**Comment by tomraithel** [comment]
Ok, It´s not so clear to me, what the next steps for this PR are. It reads, that it does not make a lot of sense to merge this changes in because it will be obsolete once the new editor is in place, correct?

I could revert the preview mode in entity editor but keep the refactoring for the `badge-group` and the `disabled` attribute. Does this help or should we just get rid of this PR in general?

**Comment by bramkragten** [comment]
I think we should wait for the custom badges PR to merge, we can then refactor this PR so it uses the new logic to build the badges. Would be a relative simple change I think.

**Comment by iantrich** [comment]
I'll try to get the custom badges PR cleaned up in the next couple of days

**Comment by bramkragten** [comment]
Custom badges where merged, mainly this logic is changed:
https://github.com/home-assistant/home-assistant-polymer/pull/3902/files#diff-5f4ad1f1a03a6ef3a098e3e46e029472R35-R52

See:
https://github.com/home-assistant/home-assistant-polymer/blob/dev/src/panels/lovelace/views/hui-view.ts#L279-L280

Maybe @iantrich can help you get this PR updated?

**Comment by tomraithel** [comment]
Hey. I've updated my branch to the recent changes without any conflicts. So the badge preview still works. 
What I don't understand is how I can configure a custom badge? Is that possible via the UI or only via yaml configuration?

**Comment by bramkragten** [comment]
Only yaml right now, next step is to create a editor for badges.

**Comment by tomraithel** [comment]
Is there than anything more to do for this PR? The preview seems to work correctly with the new badge build logic.

**Comment by bramkragten** [comment]
Yes, we need to add the new create badge logic. We only create `state-badges` now in the preview, but there could be other types of badges in it that we also need to render correctly.

**Comment by bramkragten** [comment]
Closing this as it has gone stale. If you would like to continue on this please open a new PR.

**Pull request closed without merging**
