### PR TITLE
Add Welsh + Indonesian to languages

### PR DESCRIPTION
**Pull request by c727**
fix: #871 
fix: #882

### CODE REVIEW

**Comment by balloob** [comment]
Should we merge this already or wait till some translations have been provided?

**Comment by c727** [comment]
I think we should wait

**Comment by balloob** [comment]
Just checked: Indonesian is 20% done, Welsh is 1%. 

Do we have a policy for cleaning up untranslated languages?

**Comment by c727** [comment]
I added some standard translations for welsh to avoid conflicts when we download/generate files. not sure when @antgwms  wants to start with translation...

we don't have a policy yet. maybe you can tweet again that we have added new strings some time ago and still need translations for some languages

**Comment by balloob** [comment]
For example, I noticed that we have 2 Serbians and neither are really up to date. Should we purge inactive languages that are < 50%?

**Comment by c727** [comment]
let's say we disable languages with <75% in 3 weeks?

**Comment by antgwms** [comment]
Thanks @c727 I noticed the addition.  I have now started the Welsh translation - 3 weeks should be fine on my side, certainly 75%+ I'm just getting my propsal finished before I complete the translations but I'll chip away at it

**Comment by antgwms** [comment]
The open & close translation entries in the polymer Welsh translation show [%key:state::cover::closed%] on hover - or should I submit and issue?

**Comment by c727** [comment]
I think we can merge this now, A possible cleanup can be done later

@antgwms you can't run a build with latest language files without an access token to lokalise

**Pull request merged**
