### PR TITLE
Make add-on sorting case insensitive

### LINKED ISSUE #10060: Add-Ons order is case sensitive
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

The add-ons on the `Dashboard` screen (Installed add-ons) are being sorted as case-sensitive.
That results in the `motionEye` add-on always be on the end of the list, instead of just before my `Mosquitto broker` add-on:
image
in

### Describe the behavior you expected

I expect all add-ons to be ordered alphabetically, being not case sensitive.

### Steps to reproduce the issue

1. Have multiple add-ons
2. Install any add-on with lowercased first letter (motionEye for example)
3. All lowercased add-ons will be on the end of the list
...

### What version of Home Assistant Core has the issue?

core-2021.9.7

### What was the last working version of Home Assistant Core?

_No response_

### In which browser are you experiencing the issue with?

Google Chrome 93.0.4577.82

### Which operating system are you using to run this browser?

Windows 10

### State of relevant entities

_No response_

### Problem-relevant frontend configuration

_No response_

### Javascript errors shown in your browser console/inspector

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by spacegaier**
## Proposed change

Make add-on sorting in dashboard sorting case insensitive.

**Note**: Untested, since I don't have a Supervisor dev isntance.

## Type of change

- [ ] Dependency upgrade
- [X] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes #10060
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [ ] The code change is tested and works locally.
- [X] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

**Comment by balloob** [comment]
You don't need a supervisor dev instance, you can connect the supervisor frontend to any existing HA OS installation https://developers.home-assistant.io/docs/supervisor/development

**Comment by spacegaier** [comment]
I will keep that in mind, but even with the API access I don't have any lower case add-ons installed and would rather not do that just for this single line PR change :) .

**Comment by ludeeus** [comment]
Is a single line enough?
How about the store listings?
How about the repository dislog?

Are all places that sort by name using this helper?

**Comment by spacegaier** [comment]
The add-on store listing has existing logic that is case insensitive even if not using the same helper:

https://github.com/home-assistant/frontend/blob/49494c572b1f235070cf43a0243ba50cdd810c28/hassio/src/addon-store/hassio-addon-repository.ts#L35

What do you mean by "repository dialog"? The dialog to add additional repositories?

**Comment by ludeeus** [comment]
That should change to be consistent.
Yes, I guess since addons can be sorted like this, that apply to that dialog as well.

**Review by bramkragten — APPROVED** [review]

**Pull request merged**
