### PR TITLE
Improve accessibility for light icons

### PR DESCRIPTION
**Pull request by bdraco**
## Proposed change

- Icons were indistinguishable for anyone with achromatopsia (and red/green color blindness for some light colors)

Testing done with https://github.com/oftheheadland/Colorblindly

Before Off with achromatopsia:
off-before-achromatopsia
Before On with achromatopsia:
on-before-achromatopsia

After Off with achromatopsia:
No Change

After On with achromatopsia:
Screen Shot 2021-09-22 at 1 11 44 PM

After Off (no filter):
No Change

After On (no filter):

Screen Shot 2021-09-22 at 1 09 58 PM

## Type of change

- [ ] Dependency upgrade
- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes #
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [x] The code change is tested and works locally.
- [x] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

**Comment by bdraco** [comment]
It would be nice to do something for Climate cards and Fans as well since they were the other two stand outs when I turned on the plugin

**Comment by spacegaier** [comment]
@matthiasdebaat Probably interesting for you.

**Comment by spacegaier** [comment]
This topic might be good independent of color blindness, to resolve those issues: https://community.home-assistant.io/t/2021-9-0-more-energy-usb-discovery-template/334830/496?u=spacegaier

https://community.home-assistant.io/t/2021-9-0-more-energy-usb-discovery-template/334830/502

**Comment by bdraco** [comment]
> This topic might be good independent of color blindness, to resolve those issues: [community.home-assistant.io/t/2021-9-0-more-energy-usb-discovery-template/334830/496?u=spacegaier](https://community.home-assistant.io/t/2021-9-0-more-energy-usb-discovery-template/334830/496?u=spacegaier)
> 
> [community.home-assistant.io/t/2021-9-0-more-energy-usb-discovery-template/334830/502](https://community.home-assistant.io/t/2021-9-0-more-energy-usb-discovery-template/334830/502)

I think it solves that issue as well (except for user's preference on theme colors... but that's outside of scope)

**Comment by bramkragten** [comment]
This will only work when there is no icon specified by the user/integration, should we also make it work for those cases?

**Comment by bdraco** [comment]
> This will only work when there is no icon specified by the user/integration, should we also make it work for those cases?

If they are overriding the icon, I think it is a case where they are hopefully making a conscious decision to do so.

Maybe an update to the developer docs with something along the lines:

When specifying custom icons, it should be easy to distinguish visually distinguish between on and off states. The front end will use color to highlight when an entity is on. Users with some form of color-blindness may have difficulty distinguishing between the on and off states by color alone. 

Example:
```python3
@property
def icon(self):
    return "mdi:lightbulb" if self.is_on else "mdi:lightbulb-icon"
```

**Comment by balloob** [comment]
I'm not a fan of the outline icons. They are not aesthetically pleasing, especially enlarged. 

I see these alternatives:
 - We drop the light card. I think adding it was a mistake. On it's own the card is too big, if you put multiple on a row the slider is not usable. I doubt the usage is high.
 - We keep avoiding using these cards in default strategies (as we do today). A person for who the card won't work shouldn't use them.
 - We allow a new config option for the card to enable "colorblind" mode. We can allow printing the state as an overlay on the icon
 - We allow a global setting (ala advanced mode) to indicate colorblindness.

**Comment by bdraco** [comment]
The light card is a big hit for households in their golden years who had trouble with the size of the entity rows on their phone.

Accommodating a household with one colorblind user and one low vision user is difficult 🙈

I can give the icons another shot and see if I can find something more visually appealing?

**Comment by bramkragten** [comment]
The you would endup with `lightbulb-on`

**Comment by balloob** [comment]
I think my last open question is: should we implement this locally at the light card, or should we do this for all places where we use a light icon?

**Comment by bdraco** [comment]
At least for new users, I think it's best to be consistent and do it everywhere so the user has continuity between UI elements and doesn't have to learn a visual cue more than once.

Existing users may have a strong reaction to a visual change which would support limiting the scope, however that's usually temporary unless it somehow breaks their workflow which seems very unlikely, but hard to tell. 

My gut feeling, without specific data, it is a rather quick cognitive adjustment so it's probably worth being consistent.

**Comment by balloob** [comment]
My issue with the lighbulb-on icon is that it's smaller than the lightbulb icon so it can contain the light rays. This gives for an odd transition:


https://user-images.githubusercontent.com/1444314/134548343-572d4b8b-84ff-482d-aed7-9429a683ac04.mp4

**Comment by spacegaier** [comment]
+1 for consistency otherwise it a) looks weird and b) results in many bug reports :) .

@balloob I get your point with the transition, but I think that is fine. I am slightly more concerned about the side-by-side look of on and off lights (so it you pause your GIF a 2 seconds), as the switched on ones are smaller, but that is counterbalanced by the coloring giving them enough visual weight I think.

**Comment by balloob** [comment]
I am less concerned about consistency. lightbulb and lightbulb-on use the same "lightbulb" part. Having the rays added on specific cards would not be weird. Just an extra accessibility touch for cards that lack other state indicators

**Pull request closed without merging**
