### PR TITLE
WIP: Make custom cards work as panel

### PR DESCRIPTION
**Pull request by ciotlosm**
Make custom cards work with views that have `panel: true`

### CODE REVIEW

**Comment by ciotlosm** [comment]
Too complex to handle

**Comment by balloob** [comment]
What was too complex? This seems like the right solution.

**Comment by balloob** [comment]
Just change `this.configChanged` inside the debounce to `() => this._selectView(this.curView)`

**Comment by ciotlosm** [comment]
For some reason with latest "dev" even without this change custom cards work as panels, no idea what changed. 

I was getting javascript errors on `this.$.view.classList.toggle('tabs-hidden', config.views.length < 2);`

**Comment by balloob** [comment]
It's just a race condition why it will work now. Change your custom card to 

```js
// Simulate a 2 second loading time
setTimeout(() => customElements.define(…), 2000);
```

And you see that it won't work.

**Comment by ciotlosm** [comment]
Ok, I will reopen and give it another go.

**Pull request closed without merging**
