### PR TITLE
Adding margin-top to sensor badges

### LINKED ISSUE #1753: Sensors don't have the correct top margin
Version: 0.79.3
Platform: Docker

Description:
Top margin isn't proprtional to the bottom and thus the layout looks a little wonky.

Issue

### PR DESCRIPTION
**Pull request by nikolaifischer**
Fixes  #1753
Sensor Badges looking less "wonky".

### CODE REVIEW

**Comment by homeassistant** [comment]
Hi @nikolaifischer, 

It seems you haven't yet signed a CLA. Please do so [here](https://home-assistant.io/developers/cla_sign_start/?pr=home-assistant&#x2F;home-assistant-polymer#1812).

Once you do that we will be able to review and accept this pull request.

Thanks!

**Comment by nikolaifischer** [comment]
Judging from the screenshot I thought it was the legacy state panel. I'm not using Lovelace and the CSS rule fixed the issue for me.

**Comment by zsarnett** [comment]
This is going to affect badges everywhere. I feel like the best way to handle this `wonky` look would be to add extra padding around the `hui-view` element (I have always felt its too close anyway) or just bottom margin to the `app-header`

**Comment by balloob** [comment]
Yeah I agree, we should never add CSS to an component because it is placed somewhere that doesn't look nice. It's the parent that is placing the badges component that is responsible for padding.

**Comment by balloob** [comment]
@nikolaifischer ?

**Comment by zsarnett** [comment]
https://github.com/home-assistant/home-assistant-polymer/pull/1863

**Pull request closed without merging**
