### PR TITLE
Use unicode ellipsis instead of 3 dots "..." in user-facing strings

### PR DESCRIPTION
**Pull request by Kisty**
## Proposed change
Replace 3-dots ellipsis with Unicode's ellipsis character.

## Type of change

- [ ] Dependency upgrade
- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes #
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [ ] The code change is tested and works locally.
- [x] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

**Comment by Misiu** [comment]
I think we're not allowed to directly modify files with translations, but instead, the translations should be updated in https://lokalise.com/, according to the docs: https://developers.home-assistant.io/docs/translations.

**Comment by bramkragten** [comment]
Yes, only `src/translations/en.json` can be changed from this repo.

**Comment by Kisty** [comment]
OK, thanks for your help guys. How can I resolve this? I could send a CL with only `en.json` changing and do the other changes in Lokalise.

Can I edit all languages in Lokalise? Would I have to say I'm a translator of all languages, I guess?

**Review by bramkragten — APPROVED** [review]

**Comment by bramkragten** [comment]
Yes, you should have access to all languages if you signup

**Comment by spacegaier** [comment]
I am not sure if we can consistently use the Unicode. I assume in the future new translations strings will popup that use regular dots plus the community translations will not be consistent neither.

**Comment by Kisty** [comment]
I've gone through the translations in Lokalise and converted most of them to the single unicode character.

@spacegaier that's fair. Some translations did in fact have the single character already. I'll finish them up soon. Wasn't quite as easy as doing a search and replace in Lokalise!

**Comment by spacegaier** [comment]
Yes, it will be consistent now, but once we add new translation keys in the future, the community translations in lokalize will most likely use three dots, as most users are not aware that there is a dedicated Unicode symbol for it. Then the inconsistencies will start again.

To remain consistent the Github action that pulls in the lokalize translations into the frontend repo would need some logic to do an automatic conversion.

**Comment by Kisty** [comment]
That would be the dream automating it through GitHub Actions. There's
possibly other characters that may be useful to auto convert to unicode
counterparts like `'`, `"` to the angled ones though those would have
complications because they have separate ones for open/closed and they're
probably not even used anyway.

**Pull request merged**
