### PR TITLE
Use Brotli compression for modern build

### PR DESCRIPTION
**Pull request by steverep**
## Proposed change

Since `aiohttp` doesn't support Brotli, this is just proof of the potential gain for now.  We either need to help them implement or write a middleware to handle it.  Looks like much of the work was done in https://github.com/aio-libs/aiohttp/pull/2945, but it was abandoned and never merged.

Since all major browsers that get served the modern build also support Brotli, this just replaces the gzip files for that bundle and keeps Zopfli for everything else (although it'd be much safer if we first merge #16506).

| Zopfli bundle | Brotli bundle | Reduction |
|:---:|:---:|:---:|
| 4.7 MB | 4.1 MB | 13% |

## Type of change

- [ ] Dependency upgrade
- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes #
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [x] The code change is tested and works locally.
- [x] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

## Summary by CodeRabbit

- **New Features**
	- Introduced Brotli compression alongside existing Zopfli compression for enhanced file handling.
	- Added new Gulp tasks to parallelize compression processes for improved efficiency.

- **Chores**
	- Updated project dependencies to include Brotli compression capabilities.

### CODE REVIEW

**Comment by steverep** [comment]
This would be unblocked after https://github.com/aio-libs/aiohttp/pull/8063

**Comment by bramkragten** [comment]
Is this unblocked now? Does the backend support Brotli now?

**Comment by steverep** [comment]
Nope… Waiting for 3.10 to be released still.

**Comment by steverep** [comment]
@bramkragten this is ready to go now.  Core is now using `aiohttp` 3.10 on the dev branch as of https://github.com/home-assistant/core/pull/122409.

cc: @bdraco

**Review by bramkragten — APPROVED** [review]

**Comment by bdraco** [comment]
Tested and working as expected with latest frontend bump

**Pull request merged**
