### PR TITLE
add more-info actions

### PR DESCRIPTION
**Pull request by iantrich**
## Proposed change
Continuation of https://github.com/home-assistant/frontend/pull/7464 as I'm awful at mocking things out but this was easy to code :)
Adds a new Actions tab to the more-info dialog if a list of actions is given
Peek 2020-11-21 23-55
Not sure on which tab it should be. Starting to think the last or first tab.
Also not sure if there should be an option to default to the actions tab or just the details tab. Right now I'm defaulting to the Actions tab if actions are defined which seems simple enough for me.

## Type of change

- [ ] Dependency upgrade
- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml
entity: light.kitchen_lights
tap_action:
  action: more-info
  actions:
    - name: Turn On Kitchen Lights
      action: call-service
      service: light.turn_on
      service_data:
        entity_id: light.kitchen_lights
    - name: Turn Off Kitchen Lights
      action: call-service
      service: light.turn_off
      service_data:
        entity_id: light.kitchen_lights
    - name: Set Kitchen Lights to 1%
      action: call-service
      service: light.turn_on
      service_data:
        entity_id: light.kitchen_lights
        brightness_pct: 1
    - name: Set Kitchen Lights to 50%
      action: call-service
      service: light.turn_on
      service_data:
        entity_id: light.kitchen_lights
        brightness_pct: 50
    - name: Set Kitchen Lights to 100%
      action: call-service
      service: light.turn_on
      service_data:
        entity_id: light.kitchen_lights
        brightness_pct: 100
show_icon: true
show_name: true
show_state: true
type: button
```

## Additional information

- This PR fixes or closes issue: fixes #https://github.com/home-assistant/frontend/discussions/7434
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [x] The code change is tested and works locally.
- [x] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

**Comment by balloob** [comment]
Lovelace configuration shouldn't influence the more info dialog like this. It would mean that if you open the more info dialog of this entity from a different integration, you can end up with different entities. It also means that if you need to adjust this entity actions, you need to adjust it in every location where it is being referenced.

**Comment by balloob** [comment]
So here is what I am thinking: aren't these just scenes ? Maybe we should find a way we can expose scenes in a better way. Maybe at the footer of more info controls?

**Comment by noxhirsch** [comment]
For lights, scenes would be sufficient for sure - but for other devices scripts/service-calls would be neccessary. A very easy and common usecase would be, to send your vacuum robot to a specific room. That's great UX: Click on the entity and you get more controls for it.
Also an auto-generated list of controls would certainly put them in a totally wrong order and even might add scenes you e.g. only need for automations.

Maybe that's something which could be added via `customize.yaml`? That way it would be the same on every more-info dialog? Or even in the dialog itself (and saved in .storage).

A new "ACTIONS" tab is also way better than in the footer of "DETAILS" because it's already very crowded there. Especially if you have these action buttons so that the user (e.g. an older person) doesn't have to mess with the many sliders etc. on "DETAILS".

**Comment by SeanPM5** [comment]
I might be in the minority on this, but personally I preferred the simplicity of the standalone dialog in https://github.com/home-assistant/frontend/pull/7464. With that implementation you were in complete control over what appeared and could be interacted with in the dialog. So you were able to make really simple foolproof UI's that your entire family could use.

By making it part of the more-info dialog like this however, you're introducing the possibility of them wandering off into another tab and performing unintended actions. There's more chance of things "going wrong" with this method.

One use case I had in mind was to let my young nephew play certain children's albums at a specific volume limit with just a tap. The standalone dialog was perfect for scenarios like this. But now he'd be able to access the "Details" tab and navigate around the Spotify media browser, play _any_ song (often explicit), change the speaker sources, blast the volume to 100% etc. Not ideal.

**Comment by noxhirsch** [comment]
@SeanPM5: I agree with you 👍 For myself I'd definitely prefer the integration into the more-info dialog. But you're right, that for many users, the standalone-dialog is easier and more "secure".

**Comment by iantrich** [comment]
@balloob let's put a pin in this till the new year as I'm sure you are plenty busy getting ready for the conference. We can then get together and brainstorm. 🧠

**Pull request closed without merging**
