### PR TITLE
Add Doorbell Lokalise key

### PR DESCRIPTION
**Pull request by wrt54g**
## Proposed change

Added a Lokalise key for Doorbell
## Type of change

- [ ] Dependency upgrade
- [X] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes #
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [ ] The code change is tested and works locally.
- [ ] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

**Comment by bramkragten** [comment]
You should also add the translation (text) to `/src/translations/en.json`

**Review by bramkragten — APPROVED** [review]

**Comment by bramkragten** [comment]
Please fix the linting (run prettier)

**Comment by wrt54g** [comment]
> Please fix the linting (run prettier)

That failed (checks)
image

**Comment by bramkragten** [comment]
Yes, because the formatting doesn't match our rules. You can run the tool `prettier` to fix this:
From the command line run:
`yarn format:prettier`

**Comment by wrt54g** [comment]
> Yes, because the formatting doesn't match our rules. You can run the tool `prettier` to fix this: From the command line run: `yarn format:prettier`

@bramkragten Where? I don't see any option for CLI in GitHub (web). Do I need to set up some action in the fork for this?

**Comment by bramkragten** [comment]
We don't accept PR's done via the web, as you have not been able to test them.

Please setup a dev env: https://developers.home-assistant.io/docs/frontend/development

**Comment by wrt54g** [comment]
> We don't accept PR's done via the web, as you are not able to test them.
> 
> Please setup a dev env: https://developers.home-assistant.io/docs/frontend/development

Then I'll close these PRs here.

**Pull request closed without merging**
