### PR TITLE
Refactor logbook data fetch logic into reusable class

### PR DESCRIPTION
**Pull request by balloob**
## Proposed change

The logbook fetch data logic was spread over 3 different places (panel, more info, card). This puts it all in 1 re-usable class.

## Type of change

- [ ] Dependency upgrade
- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes #
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [ ] The code change is tested and works locally.
- [ ] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

**Comment by bdraco** [comment]
Screen Shot 2022-05-16 at 13 40 01
Getting an error.   Also when I create 3 logbook cards its calling `config/auth/list` 3x every time I load the tab
```
ha-logbook.ts?d9f8:125 Uncaught (in promise) TypeError: Cannot use 'in' operator to search for 'recent' in undefined
    at HaLogbook.updated (ha-logbook.ts?d9f8:125:1)
    at HaLogbook._$didUpdate (reactive-element.ts?9d98:1247:1)
    at HaLogbook.performUpdate (reactive-element.ts?9d98:1230:1)
    at HaLogbook.scheduleUpdate (reactive-element.ts?9d98:1149:1)
    at HaLogbook.__enqueueUpdate (reactive-element.ts?9d98:1121:1)
```

**Comment by bdraco** [comment]
Here is the yaml I'm using for the logbook card testing

```
  - theme: Backend-selected
    title: Logbook Card Test
    path: logbook-card-test
    badges: []
    cards:
      - type: logbook
        entities:
          - light.master_hall_lights_g
          - light.kitchen_recessed_lights_g
          - light.upstairs_hall_large_lights_g
          - automation.elk_system_has_motion
      - type: logbook
        entities:
          - cover.driveway_gate_local
          - cover.large_garage_door_local
          - cover.small_garage_door_local
      - type: logbook
        entities:
          - cover.entry_front_door_shade
          - automation.front_door_doorbell
```

**Comment by bdraco** [comment]
I think the `config/auth/list` being called every time is an existing issue.  Here is what gets fired off when I load a more-info 
Screen Shot 2022-05-16 at 13 45 05

**Comment by bdraco** [comment]
console error was caused by bad testing on my part - the cache not being fully cleared.

The duplicate `config/auth/list` calls are definitely there though

**Comment by bdraco** [comment]
Scrolling the logbook generates an error
Screen Shot 2022-05-16 at 14 00 35
```
logger: "frontend.js_dev.latest.202205040"
message: "https://alexander.koston.org:8123/lovelace/logbook-card-test:0:0 ResizeObserver loop limit exceeded"
[[Prototype]]: Object
```

**Comment by bdraco** [comment]
The users being fetched every time isn't a bug, its just polling because there is no listener for to know when the users change.  We can't add one because we need to know when they are updated as well.

https://github.com/home-assistant/core/pull/71965

**Comment by bdraco** [comment]
Getting that same trace on the related logbook entries under traces.  Tried a different browser as well to make sure it wasn't a cache issue

```
Uncaught (in promise) TypeError: Cannot use 'in' operator to search for 'recent' in undefined
    at HaLogbook.updated (ha-logbook.ts?d9f8:125:1)
    at HaLogbook._$didUpdate (reactive-element.ts?9d98:1247:1)
    at HaLogbook.performUpdate (reactive-element.ts?9d98:1230:1)
    at HaLogbook.scheduleUpdate (reactive-element.ts?9d98:1149:1)
    at HaLogbook.__enqueueUpdate (reactive-element.ts?9d98:1121:1)
```

**Comment by bdraco** [comment]
The traces just needed `-renderer` https://github.com/bdraco/frontend/commit/1a6085ca135fb2d354aabc43a20ff22e2e5bbf09

**Comment by bdraco** [comment]
Selecting a single entity isn't working

**Comment by bdraco** [comment]
Refreshing isn't working.

I think it needs `this.shadowRoot?.querySelector("ha-logbook")?.refresh();` but even then its going to be throttled.  

I guess it never makes sense to allow refresh if the previous call's endRange was more than 60s after `now` at the time it was refreshed since there will never be any new results.

**Comment by bdraco** [comment]
I wonder if it would reduce the latency by any perceptible amount if the `get_events` call fired first and then `trace/contexts` and then `config/auth/list`

**Comment by balloob** [comment]
Thanks for testng. Pushed a bunch of bug fixes. I have not added caching of requests for users/contexts yet when multiple cards are visible. I did add a 60s throttle so they are only checked every 60 seconds on a per-card basis. 

I tried creating the get_events promise first before refreshing users/context, but fetching events does a bunch of extra work checking for caching so it wasn't firing it prior to the others, so reverted that change.

This is only the first pass. I think that we can spend future PRs in optimizing the fetching of data, including using https://github.com/home-assistant/frontend/blob/refactor-logbook/src/common/util/time-cache-function-promise.ts#L12

**Comment by bdraco** [comment]
Pulling and doing another test cycle

**Comment by bdraco** [comment]
May-16-2022 18-26-33


If I pop up the more info card from the main logbook page and click `Show More` on a specific entity the url changes but it doesn't refresh

**Comment by bdraco** [comment]
When clicking refresh, the spinner no longer appears, and the button doesn't grey out.   You can quickly drive the load up on the instance by clicking it multiple times thinking its not working.

Original behavior
May-16-2022 18-32-28

New behavior
May-16-2022 18-33-25

**Comment by bdraco** [comment]
Not sure how to resolve this one, but if you have hit show more and have selected a specific entity for all of recorded history, and then dismiss that entity you can end up selecting the entire events and states tables

May-16-2022 18-36-47

**Comment by bdraco** [comment]
Not sure if its just perception but the data parsing on the frontend seems snappier 👍

**Comment by bdraco** [comment]
Existing issue: the drop down will let me select entities that will never have logbook history such as sensors with UOM or entities with a state class

**Comment by bdraco** [comment]
I beat it up the best I could.  That was all I found

**Comment by balloob** [comment]
Fixed more bugs:

- ✅ Show more links from more info dialog now update logbook page
- ✅ Spinner now appears when hitting refresh. I did not grey out the refresh button as that state is currently not coupled. I did make it that the refresh button has no effect when a fetch is in progress.
- ❌ Long time span will still be loaded when entity filter removed
- ✅ Entity filter now filters out sensors with either a UoM or a state class
- ✅ Opening logbook from sidebar no longer loads auth + context twice

**Comment by bdraco** [comment]
Retesting now..

**Comment by bdraco** [comment]
> * ✅ Show more links from more info dialog now update logbook page

Confirmed

> * ✅ Spinner now appears when hitting refresh.

Confirmed

>   
>   * ⚠️ I did not grey out the refresh button as that state is currently not coupled. I did make it that the refresh button has no effect when a fetch is in progress.

Agree this is better

> * ❌ Long time span will still be loaded when entity filter removed

Still haven't come up with a good answer on what to do here

> * ✅ Entity filter now filters out sensors with either a UoM or a state class

Confirmed. So nice. 

> * ✅ Opening logbook from sidebar no longer loads auth + context twice

Confirmed

**Review by bdraco — APPROVED** [review]

**Comment by bdraco** [comment]
Did manage to get a weird error `Could not load logbook: entries.reverse is not a function` but cannot repro now

**Comment by bdraco** [comment]
http://127.0.0.1:8123/logbook?start_date=2022-05-18T04%3A00%3A00.000Z&end_date=2022-05-18T07%3A00%3A00.000Z

**Comment by bdraco** [comment]
Oh, I think its just selecting a time window in the future

**Comment by bdraco** [comment]
Yup `logbook?start_date=2022-05-30T04%3A00%3A00.000Z&end_date=2022-05-31T07%3A00%3A00.000Z` and it happens as well

**Comment by bdraco** [comment]
```

**Comment by bdraco** [comment]
> That issue is caused by a bug in the backend. Fix here [home-assistant/core#72021](https://github.com/home-assistant/core/pull/72021)

Good catch 👍

**Pull request merged**
