### PR TITLE
Button to reset chart zoom

### PR DESCRIPTION
**Pull request by MindFreeze**
## Proposed change

Button is only shown on numeric state charts. Also flipped the zoom axis on the "Individual devices total usage" graph so it properly zooms in y now

image

## Type of change

- [ ] Dependency upgrade
- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes #
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [ ] The code change is tested and works locally.
- [ ] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

**Comment by MindFreeze** [comment]
@marcinbauer85

**Comment by KNXBroker** [comment]
Just mentioned this missing feature on discord 😄 thank you for your work!! Most likely there is a reason,  why not going for double tab/click? Could be used on all type of charts.

**Comment by MindFreeze** [comment]
We may add double click in the future. It just requires more work

**Review by bramkragten — APPROVED** [review]

**Comment by ildar170975** [comment]
Should it be added to a timeline graph as well?
If there is a zoom feature for them - then probably this button needed as well.
(but have no idea where to show it....)

**Comment by MindFreeze** [comment]
no room on timeline charts. This button is redundant so not a big deal. Also we'll see if we can add double tap which will make this btn extra redundant

**Comment by karwosts** [comment]
Why do you want to zoom individual devices total on Y? Shouldn't it also be X? I'm not sure why this would be intended.

individual-zoom

**Comment by MindFreeze** [comment]
> Why do you want to zoom individual devices total on Y? Shouldn't it also be X? I'm not sure why this would be intended.

if the zooming worked properly it would change the scale of X. There is an open PR in the lib to fix this.
Zooming X here made no sense as you would only see part of the bars

**Comment by karwosts** [comment]
I know people sometimes want to zoom the X scale to see more detail on their small consumers, when the chart is dominated by one huge bar (like an electric car). Sounds like we need the "open PR in the lib" to achieve this. 

Thanks for the response.

**Pull request merged**
