### PR TITLE
Hassio rename advanced2

### PR DESCRIPTION
**Pull request by c727**
- changed advanced to system
- moved supervisor log to system
- removed Hass update info as it's already in the hassio dashboard
- some design changes
(discussed these changes with balloob and cogneato in the previous PRs)

system

fix: #914

### CODE REVIEW

**Comment by armills** [comment]
Can you describe all the changes here? It looks like there's quite a bit more than just renaming.

**Comment by pvizeli** [comment]
For me it looks good but I don't know if the polymere code is okay

**Comment by balloob** [comment]
@c727 you want to post a blog post on Home-Assistant.io talking about the changes in the UI and the goals of the re-design ?

**Comment by c727** [comment]
@balloob I haven't planned this x)

let's get everything fixed first. users reporting issues everywhere...

**Review by balloob — APPROVED** [review]

**Pull request merged**
