### PR TITLE
Add French Netatmo thermostat states

### PR DESCRIPTION
**Pull request by Twanislas**
Hi !

These are showing in English, here's the french version :)

image
image

Cheers from Belgium !

### CODE REVIEW

**Comment by bramkragten** [comment]
Hi @Twanislas thanks for this, but we do our translation management in Lokalise. Please see https://developers.home-assistant.io/docs/en/internationalization_translation.html

**Comment by Twanislas** [comment]
Oh !

Sorry for the spam then, I'll head over there ;)

Thanks !

**Comment by bramkragten** [comment]
No problem!

**Comment by Twanislas** [comment]
Sorry for the noise again but I fail to understand how to add new keys for translation in Lokalise.
Should those be added first somewhere and it will reflect in Lokalise to be available for transalation ?

Thanks !

**Pull request closed without merging**
