### PR TITLE
Treat sensor device_classes aqi, ph and power_factor as numeric

### LINKED ISSUE #18439: "AQI" & "pH" device classes: cannot specify "" uom
### The problem

Consider this template sensor:
```
template:
  - sensor:
      - name: testing_device_class_aqi
        device_class: aqi
        state: >-
          {% set INPUT_NAME = "input_number.testing_device_class_aqi" -%}
          {{ states(INPUT_NAME) }}
```
and then this history-graph:
image

If uom is added:
```
      - name: testing_device_class_aqi
        device_class: aqi
        unit_of_measurement: ""
        state: >-
          {% set INPUT_NAME = "input_number.testing_device_class_aqi" -%}
          {{ states(INPUT_NAME) }}
```
then the graph is correct:
image
But there is an error in Log:
2023-09-29 19:14:30.179 WARNING (MainThread) [homeassistant.components.sensor] Entity sensor.testing_device_class_aqi (<class 'homeassistant.components.template.sensor.SensorTemplate'>) is using native unit of measurement '' which is not a valid unit for the device class ('aqi') it is using; expected one of ['no unit of measurement']; Please update your configuration if your entity is manually configured, otherwise create a bug report at https://github.com/home-assistant/core/issues?q=is%3Aopen+is%3Aissue+label%3A%22integration%3A+template%22

The same is for the `pH` device_class.

### What version of Home Assistant Core has the issue?

2023.9.3

### What was the last working version of Home Assistant Core?

_No response_

### What type of installation are you running?

Home Assistant Container

### Integration causing the issue

_No response_

### Link to integration documentation on our website

_No response_

### Diagnostics information

_No response_

### Example YAML snippet

_No response_

### Anything in the logs that might be useful for us?

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by jbouwh**
## Proposed change

Sensor device classes `aqi`, `ph` and `power_factor` accept `None` as `unit_of_measurement`. When no `state_class` sensors of these device_classes should be treated as numerical.

## Type of change

- [ ] Dependency upgrade
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes https://github.com/home-assistant/frontend/issues/18439
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [ ] The code change is tested and works locally.
- [ ] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

**Comment by ildar170975** [comment]
> accept None as device_class

shouldn't it be `unit_of_measurement` instead?

**Comment by jbouwh** [comment]
At first I thought a backend change was needed, but maybe this is a frontend issue only

**Comment by jbouwh** [comment]
Needs some more testing. Possible there are other places to update.

**Comment by jbouwh** [comment]
Replaced with: https://github.com/home-assistant/frontend/pull/18099

**Pull request closed without merging**
