### PR TITLE
HVAC frontend.

### PR DESCRIPTION
**Pull request by balloob**
This is #53 by @turbokongen  + my clean up.

I added the state summary card back because I realized we otherwise have the temperature unit appended to the state. Sorry @turbokongen  for not realizing this in initial PR.

### CODE REVIEW

**Comment by turbokongen** [comment]
Very nice! 
I gave this a go, but it still has the same problem as I mentioned before.
The Highlighted(selected) and displayed item is not the same when navigation to a different card.
image
Also made a video to explain.
https://youtu.be/s9fq2VMm0-Y

**Comment by balloob** [comment]
I see what you mean but it does not happen locally for me (and neither should it). It seems like a bug in Chrome or Polymer.

Tried it with frontend in dev mode and compiled mode. I've tried using Chrome 51.0.2704.36 beta (64-bit), Safari and latest Firefox.

**Comment by turbokongen** [comment]
Then it is pinned to polymer. It happens in all my browsers.

**Comment by balloob** [comment]
Is there anything printed to your dev console in your browser when you open the second one ?

**Comment by turbokongen** [comment]
Nop. `Dispatch: SELECT_ENTITY`

**Comment by balloob** [comment]
I'm going to merge this as is. It's not the end of the world that the menu's are showing a different mode as long as it doesn't set it on the entity. 

You might want to `bower update` to make sure you run the latest/greatest.

**Pull request merged**
