### PR TITLE
Don't report errors while not connected

### PR DESCRIPTION
**Pull request by bramkragten**
## Proposed change

This would get in an end-less loop, the handling itself caused errors etc, etc.

## Type of change

- [ ] Dependency upgrade
- [X] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes #
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [ ] The code change is tested and works locally.
- [ ] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

**Review by steverep — APPROVED** [review]
Won't this throw away stuff we want to log?

Is the error in the handlers just because the API call fails?  If so, we should probably just start collecting errors in an array on disconnect, then log them all on reconnect as a better solution.

**Comment by silamon** [comment]
I've tested the branch and it fixes the loop upon disconnection. It should fix issue #17796 as well.

**Comment by bramkragten** [comment]
> Won't this throw away stuff we want to log?
> 
> 
> 
> Is the error in the handlers just because the API call fails?  If so, we should probably just start collecting errors in an array on disconnect, then log them all on reconnect as a better solution.

Also because the dynamic import fails

**Comment by steverep** [comment]
> Also because the dynamic import fails,

😕 Because service worker didn't cache it yet?

> and if we are disconnected, we try to connect every x seconds, this throws an error as long as the server is offline

That we should catch I think rather than let it throw?

**Comment by bramkragten** [comment]
> > Also because the dynamic import fails,
> 
> 
> 
> 😕 Because service worker didn't cache it yet?
> 
Service worker will only cache after it is used, so if you didn't have an error before, it will fail

**Comment by steverep** [comment]
SW precaches everything regardless if it gets used, so import would only fail if that didn't happen yet (or on a dev build I guess).

**Pull request merged**
