### PR TITLE
Fix typo when deleting an integration. Fixes #14135

### LINKED ISSUE #14135: Spelling error in integration menu
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When deleting an integration we are warned that "Its devices and entities will be permantly deleted."

### Describe the behavior you expected

Its devices and entities will be permanently deleted.

### Steps to reproduce the issue

1. Navigate to integrations in companion app 
2. Delete existing integration

### What version of Home Assistant Core has the issue?

2022.10.4

### What was the last working version of Home Assistant Core?

_No response_

### In which browser are you experiencing the issue with?

_No response_

### Which operating system are you using to run this browser?

_No response_

### State of relevant entities

_No response_

### Problem-relevant frontend configuration

_No response_

### Javascript errors shown in your browser console/inspector

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by krisnoble**
## Proposed change

Fix the spelling error described at https://github.com/home-assistant/frontend/issues/14135

## Type of change

- [ ] Dependency upgrade
- [X] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes #14135
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [] The code change is tested and works locally.
- [] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

**Review by bramkragten — APPROVED** [review]

**Comment by steverep** [comment]
@bramkragten this change modifies the wrong `en.json` and should be reverted.  Would have been caught by #13724! 😏

**Comment by krisnoble** [comment]
@steverep apologies, should I resubmit with the change in `src/translations/en.json` or is that generated elsewhere in the build process?

**Comment by steverep** [comment]
@krisnoble no worries - hopefully will be an impossible mistake to make soon.  Yes, just resubmit modifying `src/translations/en.json`.

**Comment by krisnoble** [comment]
@steverep done, thanks for your help!

**Pull request merged**
