### PR TITLE
more-info: make long states "multilined"

### LINKED ISSUE #16532: more-info for entities with LONG states: use word-wrapping
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Here is a sensor with a LONG state:

image

The state keeps a current address of a person.
Currently there is a limitation of 255 chars in a state; so we need a proper way to DISPLAY these long states.

**Proposal**: use a word-wrapping for these long states.

P.S. Please do not advise me to keep this particular value in an attribute instead of a state - I am displaying this value in a conventional Logbook card which only accept states.

### Describe the behavior you expected

as above

### Steps to reproduce the issue

as above

### What version of Home Assistant Core has the issue?

2023.5.0

### What was the last working version of Home Assistant Core?

_No response_

### In which browser are you experiencing the issue with?

Chrome 113.0.5672.93 

### Which operating system are you using to run this browser?

Win10x64

### State of relevant entities

_No response_

### Problem-relevant frontend configuration

_No response_

### Javascript errors shown in your browser console/inspector

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by ildar170975**
When a state is long, it does not look cool in more-info:

image

For examples, this could be an address of your car:

image

After the fix:

image

image

## Type of change

- [ ] Dependency upgrade
- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes https://github.com/home-assistant/frontend/issues/16532
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [x ] The code change is tested and works locally.
- [x ] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

**Comment by bramkragten** [comment]
I would propose something like this: <https://github.com/home-assistant/frontend/compare/alt-more-info-make-long-states-multilined->

To also take care of long entity names and the combination of long entity name and long state

**Comment by ildar170975** [comment]
> I would propose something

Thank you! Gave some my proposals: https://github.com/home-assistant/frontend/commit/0768bc3e2721ab96fe35a8783999123928312f1a#commitcomment-125115826

**Comment by bramkragten** [comment]
Will you update your PR or should I create a new one?

**Comment by ildar170975** [comment]
> Will you update your PR

I will do, you have plenty of other tasks!
The only thing is I do not have an access to a PC since this morning (only a mobile phone), will continue this work next Wednesday (30.08.23). Hope it can wait...
Thanks a lot for helping!

**Comment by ildar170975** [comment]
@bramkragten 
Can we merge the PR?
It was edited according to our discussion.

**Review by bramkragten — APPROVED** [review]

**Pull request merged**
